jenkins-x/jx

pkg/jx/cmd/cmd.go, pkg/jx/cmd/console.go, pkg/jx/cmd/open.go
=> add a `jx open` command

pkg/jx/cmd/cmd.go, pkg/jx/cmd/logs.go, pkg/jx/cmd/namespace.go, pkg/kube/env.go
=> add a `jx logs` command

pkg/auth/config.go, pkg/jenkins/utils.go, pkg/jx/cmd/import.go, pkg/jx/cmd/install.go
so that we can default the github user/pwd on repeated invocations
or just reselect an existing user/api token
=> lets make `jx install` reuse the current git auth config

pkg/jx/cmd/get_pipeline.go
require https://github.com/jenkins-x/golang-jenkins/pull/2
=> #50 display last Run number, status and duration

pkg/jx/cmd/common.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_minikube.go
also install xhyve if hyperkit can't be used and give instructions on virtualbox
=> polish the install instructions if we can't find hyperkit

README.md
=> add workaround for nip.io being down

pkg/jx/cmd/prompt.go
so that its super fast and doesn't need to talk to the k8s server
=> lets switch the prompt to show namespace + context

glide.lock, pkg/jenkins/constants.go, pkg/jenkins/import.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/import.go, vendor/github.com/jenkins-x/golang-jenkins/jenkins.go
also lets silently append a '.git' for github URLs if they are missing
=> lets allow import to have draft disabled

pkg/jx/cmd/cmd.go, pkg/jx/cmd/create_cluster_aks.go, pkg/jx/cmd/metrics.go
Current state - got as far as possible without access to create resources for aks
=> create cluster on aks; add metrics cmd

.gitignore, .updatebot.yml, README.md, jx/scripts/README.md, jx/scripts/release.sh, pkg/jx/cmd/cmd.go, pkg/jx/cmd/version.go, pkg/kube/name_test.go, pkg/kube/version.go
added back missing version command and lots of helper methods
=> added updatebot configuration and version command

pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_minikube.go, pkg/jx/cmd/install.go
add some tidy up to create GKE cluster too
=> git creds could use a http server if we are in bdd tests

pkg/jx/cmd/create_git_api_token.go, pkg/jx/cmd/create_git_user_account.go, pkg/jx/cmd/create_jenkins_user.go, pkg/jx/cmd/delete_env.go, pkg/jx/cmd/delete_git.go, pkg/jx/cmd/delete_git_token.go, pkg/jx/cmd/install.go, pkg/kube/constants.go
when adding a git token for gitea
=> lets also update the jenkins-git-credentials secrets

pkg/auth/config.go, pkg/gits/git_repo.go, pkg/helm/helm.go, pkg/jenkins/utils.go, pkg/jx/cmd/cmd.go, pkg/jx/cmd/create_git_api_token.go, pkg/jx/cmd/create_git_user_account.go, pkg/jx/cmd/create_jenkins_user.go, pkg/jx/cmd/delete_env.go, pkg/jx/cmd/install.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/upgrade.go, pkg/jx/cmd/upgrade_platform.go, pkg/jx/cmd/util/factory.go, pkg/jx/cmd/version.go
=> add jx upgrade command

README.md
=> Enable minikube ingress addon

pkg/jx/cmd/open.go
Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>
=> close #188

pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/provider.go, pkg/jx/cmd/import.go, pkg/jx/cmd/promote.go
fixes #223
now we merge the PR if its mergeable
we then wait for the SHA on master to be built and for that to succeed/fail
=> jx promote should wait for the PR to merge and be deployed

pkg/config/helm_values.go, pkg/gits/git_repo.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/provider.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_aks.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_minikube.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/get_app.go, pkg/jx/cmd/get_env.go, pkg/jx/cmd/get_url.go, pkg/jx/cmd/import.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/uninstall.go, pkg/kube/deployments.go, pkg/kube/env.go
avoids asking for domain multiple times and supports --domain CLI argument
on jx create cluster * fixes #275 fixes #278
=> polish handling of domain + init flags

pkg/config/helm_values.go, pkg/config/helm_values_test.go, pkg/config/test_exposecontroller_values.yaml, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/install.go, pkg/jx/cmd/preview.go, pkg/kube/env.go
- also includes a fix to avoid issues creating default environments that already exist in git
=> Switch to new exposecontroller config structure

README.md
Should be self explanatory. Let me know if there are questions.
=> Fix proportions of logo in README

pkg/apis/jenkins.io/v1/types.go, pkg/gits/commits.go, pkg/gits/commits_test.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/step_changelog.go
so we pass it to init and install
=> fix:(batch mode) lets preserve batch mode in create cluster

pkg/jx/cmd/util/factory.go, pkg/kube/activity.go, pkg/spring/model.go
now passing in the spring form parameters as query arguments rather than
POST form body
fixes #331
=> fix:(create spring) fix missing query parameters

pkg/jx/cmd/promote.go
this should hopefully enable the activity population
=> fix:(promote) missing activities client

Makefile, pkg/apis/jenkins.io/register.go, pkg/apis/jenkins.io/v1/register.go, pkg/apis/jenkins.io/v1/types.go, pkg/gits/commits.go, pkg/gits/commits_test.go, pkg/gits/git.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/provider.go, pkg/jenkins/constants.go, pkg/jenkins/import.go, pkg/jenkins/jobs.go, pkg/jx/cmd/cdx.go, pkg/jx/cmd/common.go, pkg/jx/cmd/create.go, pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/create_issue.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/get_env.go, pkg/jx/cmd/import.go, pkg/jx/cmd/logs.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/promote.go, pkg/kube/activity.go, pkg/kube/deployments.go, pkg/util/pickers.go
lets make it easy to create new issues from the CLI in the project of the current directory
fixes #335
=> feat:(jx create issue) lets allow issue creation via CLI

pkg/jx/cmd/init.go
clean up install script so we prompt question about getting latest draft packs using same style as other questions
=> feat(init): use jx style confirm when recreating local draft pack repos

pkg/auth/config_service.go, pkg/gits/github.go, pkg/jx/cmd/util/factory.go
lets try handle file not existing a little better so we can save it later
=> fix:(bdd) allow `jx create git token` to work with env vars

pkg/jx/cmd/import.go
so that we can generate better metadata on the Release CRD
=> fix: add more env vars

pkg/jx/cmd/common_kube_rbac.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_issue.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/kube/service_accounts.go
=> fix:(install) should also run jx init

pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/version.go
=> fix:(draft) remove draft CLI dependency

pkg/gits/bitbucket.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/provider.go, pkg/issues/git_provider.go, pkg/issues/jira.go, pkg/issues/provider.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_aws.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go
=> docs:(providers) lets show the real list of providers ;)

pkg/gits/bitbucket.go
=> More implementations of Bitbucket GitProvider methods

pkg/gits/bitbucket.go
The function export is for use in BDD tests.
=> Basic auth for BitbucketProvider, plus exporting a repo conversion func

Makefile, pkg/addon/config.go, pkg/auth/config.go, pkg/jx/cmd/get_activity.go, pkg/jx/cmd/import.go, pkg/jx/cmd/install.go, pkg/jx/cmd/status.go, pkg/kube/cluster_status.go
fix: partial for https://github.com/jenkins-x/jx/issues/299
=> feat: add vet as a Makefile target, and vetted the code - 

pkg/addon/config.go, pkg/gits/bitbucket.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/gitlab.go, pkg/gits/provider.go, pkg/issues/constants.go, pkg/issues/git_provider.go, pkg/issues/jira.go, pkg/issues/provider.go, pkg/jx/cmd/import.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/status.go, pkg/jx/cmd/step_changelog.go, pkg/kube/cluster_status.go
=> fix:(promote) better validation error if no environment specified

pkg/jenkins/import.go, pkg/jx/cmd/step_changelog.go
default to batch mode if inside pipelines
=> fix:(changelog) inside pipelines

pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/install.go, pkg/jx/cmd/util/factory.go
so that the code is more similar between the commands and minimise differences
fixes #555
=> fix:(install) make `jx install` closer to `jx create cluster`

pkg/jx/cmd/common.go, pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_anchore.go, pkg/jx/cmd/create_addon_gitea.go, pkg/jx/cmd/create_addon_kubeless.go, pkg/kube/constants.go
=> feat:(anchore) add an addon for anchore

pkg/jx/cmd/util/factory.go, pkg/spring/model.go
also improve error message if using create command in wrong namespace
=> add user agent for spring boot 

pkg/jx/cmd/step_git_credentials.go
=> fix:(jx step git credentials) we should create the parent directories

pkg/auth/config.go
ensure we properly fail if there is no chosen username
fixes #710
=> fix:(windows) avoid possible exception

pkg/gits/bitbucket.go, pkg/gits/github.go, pkg/gits/gitlab.go
=> fix:(crash) avoid core dump if there is an error querying git

pkg/jx/cmd/create_cluster_minikube.go
Added missing VM drivers list to cmd help and sorted list alphabetically.
=> Added missing VM drivers list to cmd help

pkg/helm/helm.go, pkg/jenkins/utils.go, pkg/jx/cmd/common_environments.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/delete_context.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/sync.go, pkg/kube/env.go, pkg/kube/pod.go, pkg/util/pickers.go
=> fix: jx delete app 

.gitignore, pkg/jx/cmd/logs.go
=> fix:(logs) assume verbose mode when showing the logs

pkg/jx/cmd/create_cluster_aws.go
- added missing command status check
- improved messages displayed to end users
=> Improved kops validation checking

pkg/gits/bitbucket.go
=> fix: correct bitbucket webhook url

pkg/jx/cmd/create_cluster_minikube.go
=> musty to must

pkg/config/admin_secrets.go, pkg/jx/cmd/common.go, pkg/jx/cmd/common_addon.go, pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_anchore.go, pkg/jx/cmd/create_addon_cloudbees.go, pkg/jx/cmd/create_addon_pipeline_events.go, pkg/jx/cmd/get_cve.go, pkg/jx/cmd/install.go, pkg/jx/cmd/step.go, pkg/jx/cmd/step_report.go, pkg/jx/cmd/step_report_activities.go, pkg/kube/constants.go, pkg/kube/services.go, pkg/pipeline_events/elasticsearch.go, pkg/pipeline_events/provider.go
- new pipeline events addon including Kibana and Elasticsearch
- new command `jx step report activities`
This is work in progress so not ready for prime time, still experimenting.
=> spike at sending pipeline events to elasticsearch

pkg/jx/cmd/upgrade.go, pkg/jx/cmd/upgrade_cluster.go
=> Initial draft of an upgrade cluster command

pkg/jx/cmd/upgrade_cluster.go
I've also added a check to see if the gcloud command exists, and am being more verbose when running the upgrade to give the user feedback on what is happening.
=> Prompting that feature is experimental when upgrading a cluster

pkg/jx/cmd/common_helm.go
User should be aware that `jx` is attempting to update Helm repository.
=> User should be briefly notified about helm update attempt

pkg/jx/cmd/upgrade_cli.go
=> small typo

pkg/jx/cmd/sync.go
see https://github.com/jenkins-x/jx/issues/950
simple enough cc @jstrachan
=> add ksync to the path here also

pkg/jx/cmd/common_commands.go, pkg/jx/cmd/common_helm.go, pkg/jx/cmd/create.go, pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_cloudbees.go, pkg/jx/cmd/create_addon_istio.go, pkg/jx/cmd/create_archetype.go, pkg/jx/cmd/create_camel.go, pkg/jx/cmd/create_quickstart_test.go, pkg/jx/cmd/import.go, pkg/jx/cmd/import_test.go, pkg/kube/constants.go
=> feat:(istio) create an istio addon

pkg/jx/cmd/cmd.go, pkg/jx/cmd/update.go, pkg/jx/cmd/update_cluster.go, pkg/jx/cmd/update_cluster_gke.go, pkg/jx/cmd/update_cluster_gke_terraform.go
The command re-applies the terraform plan to allow changes to be made to the cluster.
=> feat(terraform) Added a 'jx update cluster gke terraform' command

pkg/jx/cmd/create_addon_anchore.go, pkg/jx/cmd/create_addon_pipeline_events.go, pkg/jx/cmd/delete_addon.go, pkg/jx/cmd/get_cve.go, pkg/jx/cmd/step_post_build.go, pkg/jx/cmd/step_report_activities.go, pkg/jx/cmd/step_report_releases.go, pkg/kube/constants.go, pkg/kube/services.go
=> fix:(addon) cleans up the service link when an addon is deleted

pkg/jx/cmd/create_cluster_minishift.go
fix for https://github.com/jenkins-x/jx/issues/1034
=> minishift tls and permission fix

pkg/jx/cmd/common_helm.go
work around https://github.com/kubernetes/helm/issues/4230 using helm2 for now for that step
=> fix: work around helm 3 regression

pkg/jx/cmd/get.go, pkg/jx/cmd/get_issue.go, pkg/jx/cmd/get_issues.go
the command display the status of an issue and the environment where it was deployed.
=> WIP feat:(issue) add a command which displays the status of an issue

pkg/jx/cmd/get_issue.go
display also the application associated with an issue
=> feat:(issue) get the status of the issues which are not pull requests

pkg/jx/cmd/create.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/create_terraform_test.go, pkg/kube/constants.go, pkg/util/dirs.go
This command will create an organisation git repository that will be used with Terraform to create multiple clusters for multiple teams.
=> feat(terraform) `jx create terraform` command

pkg/jx/cmd/preview.go
if `DOCKER_REGISTRY` is unset, falls back to previous method of using
`docker-registry` k8s service env variables
=> Uses `DOCKER_REGISTRY` for `getImageName()`

pkg/jx/cmd/uninstall.go
=> fix:(uninstall) cleanup the namespaces even when the helm delete fails for jenkins-x platform

Jenkinsfile, myvalues.yaml.template, pkg/jx/cmd/common_team_settings.go, pkg/jx/cmd/get_applications.go, pkg/jx/cmd/install.go, pkg/jx/cmd/util/factory.go
lets try use service linking and disable features in the Jenkins X platform to minimise footprint and speed things up
=> fix: minimise the footprint of BDD tests per PR

pkg/apis/jenkins.io/v1/types.go, pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go, pkg/jx/cmd/common.go, pkg/jx/cmd/common_helm.go, pkg/jx/cmd/common_team_settings.go, pkg/jx/cmd/create.go, pkg/jx/cmd/create_cluster_aks.go, pkg/jx/cmd/create_post_preview_job.go, pkg/jx/cmd/delete.go, pkg/jx/cmd/delete_post_preview_job.go, pkg/jx/cmd/edit_helmbin.go, pkg/jx/cmd/get.go, pkg/jx/cmd/get_post_preview_job.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/util/factory.go, pkg/kube/constants.go, pkg/kube/containers.go, pkg/kube/job.go
allows folks to define jobs at a Team level to be applied to previews
fixes #1176
=> feat: allow post preview jobs to be registered on a team

Jenkinsfile, pkg/jx/cmd/common_import.go
in case we get temporary failures while the jenkins pod is down
fixes #1184
=> fix: lets add retries around jenkins create folder/project

pkg/cloud/oke/helper.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_oke.go, pkg/jx/cmd/init.go
per oracle’s product managers’ correction,  use “oke” instead of “oce”. 
once the code is merged ,we will do doc pull-request. Thanks a lot
=> update oce to oke

pkg/jx/cmd/rsh.go
=> fix:(rsh) use bash if is available in the remote container

pkg/helm/helm_cli.go
=> fix: helm version command

pkg/jx/cmd/common_install.go
=> fix:(helm) initialize helm before installing the secrets plugin

pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_ambassador.go, pkg/jx/cmd/create_addon_anchore.go, pkg/jx/cmd/create_addon_gitea.go, pkg/jx/cmd/create_addon_istio.go, pkg/jx/cmd/create_addon_kubeless.go, pkg/jx/cmd/create_addon_pipeline_events.go, pkg/jx/cmd/create_addon_prow.go
=> fix:(addon) add option for helm values

pkg/jx/cmd/create_addon_owasp.go
=> feature is really about owasp ZAP

pkg/jx/cmd/common_install.go, pkg/jx/cmd/get_preview.go
rather than the 2.9.x version
fixes #1337
=> fix: lets install a recent helm version

pkg/jx/cmd/import.go
The variable `jenknisfileBackup` should be `jenkinsfileBackup`
=> Fixing a typo in `jenknisfileBackup`

Makefile, pkg/helm/helm_cli.go, pkg/helm/helm_cli_test.go, pkg/jenkins/jobs.go, pkg/jx/cmd/promote.go
=> Fix issues with concurrent builds failing with merge conflicts and other

Makefile, pkg/builds/jenkinsfiles.go, pkg/builds/jenkinsfiles_test.go, pkg/config/project_config.go, pkg/config/project_config_test.go, pkg/helm/helm_cli.go, pkg/jx/cmd/common.go, pkg/jx/cmd/step.go, pkg/jx/cmd/step_create_build.go, pkg/jx/cmd/step_create_build_test.go, pkg/jx/cmd/test_data/step_create_build/README.md, pkg/jx/cmd/test_data/step_create_build/add_common_envvars/expected-build-release.yml, pkg/jx/cmd/test_data/step_create_build/add_common_envvars/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/expected-build-release.yml, pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/expected-build-release.yml, pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/expected-build-release.yml, pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/jenkins-x.yml, pkg/kube/containers.go, pkg/kube/crds.go, pkg/tests/files.go
using the `jenkins-x.yml` file to simplify knative build authoring
#1420
=> initial support for generating knative builds

pkg/jx/cmd/create_addon_owasp.go, pkg/jx/cmd/create_spring.go, pkg/kube/configmap.go, pkg/kube/constants.go, pkg/kube/namespaces.go
otherwise the resulting microservice will typically fail
=> fix: lets ensure the web dependency is added to spring boot apps

pkg/jx/cmd/create_cluster_eks.go
Ran into this issue https://github.com/weaveworks/eksctl/issues/118 which was fixed in this PR https://github.com/weaveworks/eksctl/pull/131
tl;dr: `eksctl` picks a random'ish availability zone, but if you run out of capacity in that availability zone, it errors.  So, you have to keep trying till it randomly'ish picks a zone that has capacity.  Solution, pass on a `--zones` option to `eksctl`.
I modeled the fix after `jx create cluster aws` but I was not aggressive about requiring zones since `eksctl` can work without the option being passed.  Let me know if it would work like the `aws` command and prompt the user for zones.
The changes here are untested too.
=> Add zones option to create cluster eks

pkg/jx/cmd/cmd.go, pkg/jx/cmd/scan.go, pkg/jx/cmd/scan_cluster.go
I recorded the command execution here:
[![asciicast](https://https://asciinema.org/a/197184.png)](https://asciinema.org/a/197184)
fixes #1489
=> feat: add a command which scans a cluster for potential security vulnerabilities

Gopkg.lock, pkg/jx/cmd/compliance_results.go, pkg/jx/cmd/compliance_status.go, vendor/github.com/heptio/sonobuoy/pkg/buildinfo/version.go, vendor/github.com/heptio/sonobuoy/pkg/discovery/queries.go, vendor/github.com/heptio/sonobuoy/pkg/plugin/driver/daemonset/daemonset.go, vendor/github.com/heptio/sonobuoy/pkg/plugin/driver/daemonset/template.go, vendor/github.com/heptio/sonobuoy/pkg/templates/manifest.go
=> fix:(compliance) update the sonobuoy client library

Gopkg.lock, vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go
=> Upgraded AWS SDK version

pkg/jx/cmd/install.go
Fix for cloud environment values not being picked up
=> Add cloud provider config files

pkg/jx/cmd/create_devpod.go
which can help us when we add IDEs to devpods or expose endpoints for debugging / testing apps etc
=> chore: add a helper method so that we can expose services for devpods

pkg/cloud/amazon/ecr_test.go, pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_ingress.go, pkg/kube/config.go, pkg/kube/configmap.go, pkg/kube/constants.go, pkg/kube/ingress.go, pkg/kube/jx_install_config.go, pkg/kube/jx_install_config_test.go, pkg/util/structs.go, pkg/util/structs_test.go
=> feat: create jx-install-config configmap during jx install. For use with

pkg/jx/cmd/controller_role.go, pkg/jx/cmd/controller_role_test.go
=> Environment role bingding for role

pkg/jx/cmd/install.go
Removed ECR workaround on behalf of #1609. I verified that it works fine.
=> Removed ECR workaround

pkg/jx/cmd/create_devpod.go, pkg/jx/cmd/delete_devpod.go, pkg/kube/services.go
=> Initial work to add theia

pkg/jx/cmd/create_devpod.go
also better logic for filtering
=> fix: reuse the username CLI argument

pkg/jx/cmd/common_team_settings.go, pkg/jx/cmd/create_devpod.go, pkg/jx/cmd/rsh.go
and pass it in from `jx create devpod`
=> fix: make username configurable on `jx rsh`

pkg/jx/cmd/create_cluster_aws.go
=> fix: better fix for finding kops state from env var

pkg/jx/cmd/create_addon_cloudbees.go
=> feat: Default DEX URL

pkg/jx/cmd/create_addon_cloudbees.go
=> fix: auto-strip trailing slash

pkg/jx/cmd/uninstall.go
It should be possible to uninstall Jenkins X without undeploying applications/environments that has been created via Jenkins pipelines. In particular it should be possible to remove Jenkins X and keep: 
- environments helm charts releases
- namespaces
Requirement to be able to remove Jenkins X from a cluster without removing production applications that are already serving production requests is a must for us :) .
=> Added `keep-environments` options to `uninstall` command

pkg/jx/cmd/create_addon_cloudbees.go, pkg/jx/cmd/login.go
=> fix:(cloudbees) set the chart flags for basic auth before installing the chart

pkg/jx/cmd/create_addon_sso.go
=> fix:(sso) return an error if the user is not member of any GitHub organization

pkg/jx/cmd/delete_aws.go
ELB service should use the same region resolving logic as EC2 service.
=> Region for ELB service should be resolved from env

Gopkg.lock, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/unmarshal.go, vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go, vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go, vendor/github.com/aws/aws-sdk-go/private/protocol/query/unmarshal.go, vendor/github.com/aws/aws-sdk-go/private/protocol/query/unmarshal_error.go, vendor/github.com/aws/aws-sdk-go/private/protocol/restxml/restxml.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go, vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go, vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go, vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go, vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go, vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go, vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go, vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go, vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
=> Upgraded AWS SDK

.updatebot.yml, Jenkinsfile, charts/jx/templates/cronjob.yaml, pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go, pkg/jx/cmd/controller_team.go, pkg/jx/cmd/delete.go, pkg/jx/cmd/delete_branch.go, pkg/jx/cmd/delete_repo.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/mocks/factory.go, pkg/prow/prow.go
also improve the CLI argument names for folks wishing to have no tiller or use a local tiller
=> fix prow and no tiller

pkg/jx/cmd/step_link_services.go
=> fix:(step service link) handle errors and reset the cluster IP

pkg/jx/cmd/common.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/controller_team.go, pkg/kube/constants.go
lets ensure there's a git user and email setup
=> fix: team controller so it can run in a pod

pkg/kube/crds.go
to avoid clashes if multiple processes try at the same time to modify CRDs
=> fix: add retries around registering CRDs

pkg/jx/cmd/import.go
=> Revert "fix: ask for organisation before replacing placeholders"

pkg/jx/cmd/cloudbees.go, pkg/jx/cmd/cloudbees_pipeline.go
=> feat: add `jx cloudbees pipeline` command

pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_sso.go, pkg/jx/cmd/create_addon_vault.go, pkg/kube/constants.go
=> feat:(addon vault opeator) add an addon for vault-operator

pkg/jx/cmd/create_cluster_eks.go
Improved debug log logic for EKS cluster create command.
=> Improved debug log logic for EKS

pkg/jx/cmd/delete.go, pkg/jx/cmd/delete_eks.go
Added `jx delete eks` command which can be used to delete EKS cluster using eksctl.
=> Added `jx delete eks` command

pkg/jx/cmd/delete_aws.go
Also added logging level option to the command.
=> 'delete aws' command should respect profile option

pkg/jx/cmd/common_import.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/import.go, pkg/util/pom_flavour.go
This pull request is related to the Dropwizard draft pack addition: https://github.com/jenkins-x/draft-packs/pull/77
It was tested with a locally built `jx` command, using the `jx edit buildpack` command to use the draft packs in https://github.com/benvandenberg/draft-packs/tree/feature/dropwizard
=> Add Dropwizard draft pack detection

pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_platform.go
=> fix:(upgrade platform) when exposecontroller config is nil

pkg/jx/cmd/create_devpod.go
Follow up to / Associated with: https://github.com/jenkins-x/jx/pull/1885
Updates `create_devpod.go` so that the user can pass in Image Pull Secrets through the `--pull-secrets` flag (implemented the above linked PR) while creating DevPods, so that they will be patched into the Edit namespace's (such as `jx-edit-john`) default service account.
Tested on both Minikube and IBM Cloud Private with private docker registries.
=> feat(devpods): Allow users to patch Image Pull Secrets when creating DevPods

pkg/builds/build_info.go, pkg/helm/helm_template.go, pkg/helm/helm_template_test.go, pkg/jx/cmd/common.go, pkg/jx/cmd/controller_build.go, pkg/jx/cmd/get_build.go, pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/get_build_pods.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_helm.go, pkg/jx/cmd/step_helm_list.go, pkg/jx/cmd/version.go, pkg/table/table.go
so that folks can list installed charts nicely without needing tiller
also fixes `jx version` so that it displays the installed platform when not
using tiller
=> feat: add `jx step helm list` for no-tiller mode

pkg/builds/build_info.go, pkg/jx/cmd/gc.go, pkg/jx/cmd/gc_pods.go, pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/get_build_pods.go
so it works more consistently with `jx get build pod` and makes it easy to filter pending builds or builds on a specific PR/branch/repo/org
=> improve `jx get build log`

.github/pull_request_template.md
Adds a template for Pull Request definition.
=> chore(github): add a template for pull request

pkg/jx/cmd/upgrade_extensions_repository.go
=> fix: need to decode the script file

pkg/jx/cmd/controller_commitstatus.go
=> fix: hack around the very broken git auth stuff

go.mod, go.sum, pkg/jx/cmd/create_vault.go, pkg/kube/vault.go, pkg/kube/vault_test.go, pkg/vault/rule.go, pkg/vault/rule_test.go
feat(vault): encode to HCL the vault path rule and add some tests
=> feat(vault): encode to HCL the vault path rule and add some tests

pkg/jx/cmd/controller_commitstatus.go
I had to hack in support for reporting gitUrl and lastCommitSha
to the pipeline activity, we should fixup the build controller and remove
this
=> fix: fix the commitstatus controller

pkg/builds/build_info_test.go, pkg/jx/cmd/controller_role.go, pkg/jx/cmd/controller_role_test.go
added unit test to show its correct behaviour as environments are created,
users added or removed from EnvironmentRoleBindings
=> fix: complete the role controller

pkg/jx/cmd/init.go
Use HA URL for chartmuseum
fixes #
=> fix: Use HA URL for chartmuseum

pkg/jx/cmd/controller_commitstatus.go
=> fix: improve message

charts/controller-backup/Makefile, charts/controller-build/Makefile, charts/controller-compliance/Makefile, charts/controller-role/Makefile, charts/controller-team/Makefile, charts/controller-workflow/Makefile, charts/gc-previews/Makefile, charts/gc-releases/Makefile, charts/jx/Makefile, charts/service-linker/Makefile, pkg/helm/helm_cli_test.go, pkg/jx/cmd/test_data/install_cloud_environments_repo/Makefile, pkg/kube/test_data/env_modify_namespace/Makefile
=> fix: removed references to depreacted chartmuseum instance

pkg/jx/cmd/common.go, pkg/jx/cmd/preview.go
When running inside pipeline, use batch mode by default. If the user specifies the --batch-mode
command line option, then always honour that.
fixes #
=> feat(preview): Default to batch mode when running in pipeline.

pkg/apis/jenkins.io/v1/types_pipeline.go
=> fix: fix the marshal name for field

pkg/jx/cmd/create_codeship.go
=> fix: adding '--skip-login' to default commands for codeship

pkg/jx/cmd/upgrade_extensions.go
=> fix: ensure releases CRD is registered

pkg/extensions/commitstatuses.go, pkg/jx/cmd/controller_commitstatus.go
=> Commitstatus8

pkg/jx/cmd/common_auth.go, pkg/jx/cmd/factory.go, pkg/jx/cmd/interface.go, pkg/jx/cmd/mocks/factory.go, pkg/jx/cmd/preview.go
Just fixes an apparent typo in #583.
=> refactor: s/IsInCDPIpeline/IsInCDPipeline/g

pkg/apis/jenkins.io/v1/types_extensions.go, pkg/jx/cmd/delete.go, pkg/jx/cmd/delete_extension.go
=> feat: add `jx delete extension`

pkg/extensions/management.go, pkg/jx/cmd/delete_extension.go
=> feat: recursively delete extension children

pkg/jx/cmd/logs.go
=> feat: make prow logging return status code 1 if build fails.

pkg/helm/helm_cli.go, pkg/helm/helm_template.go, pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_platform.go
=> feat(secrets) added secret decryption to upgrade platform

pkg/config/helm_values.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_addon_knative_build.go, pkg/jx/cmd/delete_addon_knative_build.go, pkg/jx/cmd/install.go
=> Revert "fix up knative build addon"

pkg/config/admin_secrets.go, pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_platform.go
=> feat: load jx-install-config from encrypted secrets stored in git

pkg/jx/cmd/factory.go
=> fix(preview): switch to create git provider in oder to fix the preview update into the PR

pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/import_placehoders_test.go, pkg/terraform/terraform.go, pkg/terraform/terraform_test.go
=> feat: attempting to validate terraform version before install

pkg/kube/crds.go
=> feat: export kube.RegisterCRD

pkg/jx/cmd/create_cluster_gke_terraform.go, pkg/jx/cmd/import_placehoders_test.go, pkg/spring/model.go, pkg/terraform/terraform.go, pkg/util/dirs_test.go
=> feat: handling error response from spring quickstart

pkg/kube/crds.go
=> feat: allow registering CRDs for other groups

pkg/jx/cmd/create_codeship.go
=> feat: added support for --gitops flag in codeship build

pkg/jx/cmd/step_post_install.go
=> Copy editing on help

pkg/terraform/terraform.go
=> fix: updated log message when checking terraform version

pkg/jx/cmd/create_addon_vault.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/install.go
a `vault-operator` is installed by default when using either of the following two commands:
* `jx install`
* `jx create cluster gke`
In conjunction with either of the two flags:
* `--gitops`
* `--vault` (new flag)
Please feel free to tell me if this is all wrong as I don't fully understand the codebase yet
=> Vault install

pkg/jx/cmd/init.go, pkg/jx/cmd/start_pipeline.go, pkg/kube/env.go
Spotted a `err != err` in passing and grep found a few more.
=> Fix err != err

go.mod, go.sum, pkg/gits/gerrit.go, pkg/gits/gerrit_test.go, pkg/gits/test_data/gerrit/create-project.json, pkg/gits/test_data/gerrit/list-projects.json, pkg/util/test.go
=> A few methods for Gerrit support

pkg/jx/cmd/upgrade_platform.go
=> fix: improved format of log messages on upgrade

Makefile, pkg/gits/bitbucket_cloud_test.go
=> A new test case and a make target for debugging git tests

pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/common_app.go, pkg/jx/cmd/common_environments.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/upgrade.go, pkg/jx/cmd/upgrade_apps.go, pkg/jx/cmd/upgrade_apps_test.go
* Creates a PR with any needed upgrades
* Copies addon functionality for now (will get replaced next)
fixes #
=> feat: `jx upgrade apps`

.updatebot.yml, Makefile
jenkins-x-charts/prow makes use of jx; added updatebot config & invocation to `release` make target to update that repository so that it always runs the latest version of jx.
fixes #
=> feat: ++ to updatebot to upgrade jenkins-x-charts/prow repo.

pkg/jx/cmd/create_terraform.go
=> fix: ensure gcloud is installed before login

pkg/jenkinsfile/pipeline.go, pkg/jx/cmd/common_buildpacks.go, pkg/jx/cmd/test_data/step_buildpack_apply/prow/Jenkinsfile, pkg/jx/cmd/test_data/step_buildpack_apply/prow/Jenkinsfile.tmpl, pkg/jx/cmd/test_data/step_buildpack_apply/prow/pipeline.yaml, pkg/jx/cmd/test_data/step_buildpack_apply/simple/Jenkinsfile, pkg/jx/cmd/test_data/step_buildpack_apply/simple/Jenkinsfile.tmpl, pkg/jx/cmd/test_data/step_buildpack_apply/simple/pipeline.yaml
so the new build packs work nicely on Prow
=> fix: use prow if enabled in the Jenkinfile generation

pkg/gits/gerrit_test.go
=> fix:(gerrit) Remove some unnecessary logging in tests

pkg/vault/vaultfactory.go
rather than getting a stacktrace, you now get on errors:
```
$ ./jx get vault-config
error: Error getting Vault signin token: Error making API request.
URL: PUT http://jx-vault.jx.35.187.37.181.nip.io/v1/auth/kubernetes/login
Code: 500. Errors:
* {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:jx:default\" cannot create tokenreviews.authentication.k8s.io at the cluster scope","reason":"Forbidden","details":{"group":"authentication.k8s.io","kind":"tokenreviews"},"code":403}
```
=> feat(vault): Added more error handling to vault

pkg/kube/env.go
- [x ] Change is code complete and matches issue description.
Re-order statements to avoid `nil` dereference
fixes #2364
=> Avoid panic on failed repo creation

pkg/helm/helm_cli.go
=> fix: pass the repo to fetch

pkg/jx/cmd/common_environments.go
=> Fix: don’t swallow errors on gitops

pkg/kube/crds.go
=> Fix: register the plugin CRD

pkg/helm/helm_cli.go, pkg/helm/helm_template.go, pkg/helm/interface.go, pkg/helm/mocks/helmer.go, pkg/helm/mocks/helmer_fake.go, pkg/jx/cmd/extraValues.yaml, pkg/jx/cmd/get_addon.go, pkg/jx/cmd/mocks/factory.go, pkg/jx/cmd/mocks/matchers/versioned0_interface.go, pkg/jx/cmd/mocks/matchers/versioned1_interface.go, pkg/jx/cmd/mocks/matchers/versioned_interface.go, pkg/jx/cmd/step_validate.go, pkg/jx/cmd/upgrade_addons.go, pkg/jx/cmd/upgrade_apps.go
=> feat: added the addon version to 'jx get addons'

pkg/config/admin_secrets.go
=> fix: removed <>& from the list of allowed symbols in password generation

go.mod, go.sum, pkg/jx/cmd/controller_commitstatus.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/get_applications.go, pkg/jx/cmd/import.go, pkg/prow/config/branch_protection.go, pkg/prow/config/tide.go, pkg/prow/config/types.go, pkg/prow/prow.go, pkg/prow/prow_test.go, pkg/util/git.go, pkg/util/git_test.go, pkg/util/strings.go, pkg/util/strings_test.go
Disabled the prow config and removed an application from running envirnoments when using `jx delete app`
I needed to add a new `--org` parameter to specify the github org when deleting an app as it is lost during the `import` or `create quickstart` process. My intention is that this will be stored in a new CRD in a subsequent PR
fixes #2331
=> Disabled prow configuration for jx delete app

pkg/helm/helm_helpers.go, pkg/jx/cmd/controller_commitstatus.go, pkg/jx/cmd/delete.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/get_applications.go, pkg/prow/config/branch_protection.go, pkg/prow/config/branch_protection_test.go, pkg/prow/config/tide.go, pkg/prow/prow.go, pkg/prow/prow_test.go
Follow up code quality and tests after #2446
fixes #
=> 2446-followup

pkg/jx/cmd/create_jenkins_token.go
Use only the new API to generate tokens.
Remove the old way to generate Jenkins API token since now the migration to the new version is done.
fixes #
=> fix(jenkins): use only the new API to generate tokens

pkg/jx/cmd/controller_build.go
as sometimes we missed the termination
=> fix: lets ensure we detect termination of knative builds

pkg/jx/cmd/common_install.go
=> feat: use brew if available to install helm

pkg/gits/github.go
=> fix(github archive api): prevent github archive url from redirecting

pkg/jx/cmd/create_cluster_gke.go
=> feat(gke) can now provide oauth scopes when creating gke cluster

pkg/helm/helm_cli.go, pkg/helm/helm_cli_test.go, pkg/helm/helm_helpers.go, pkg/helm/helm_template.go, pkg/helm/interface.go, pkg/helm/mocks/helmer.go, pkg/helm/mocks/helmer_fake.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/preview_test.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_helm_apply.go, pkg/jx/cmd/step_helm_install.go, pkg/jx/cmd/upgrade_addons.go, pkg/jx/cmd/upgrade_apps.go, pkg/jx/cmd/upgrade_extensions.go, pkg/jx/cmd/upgrade_platform.go
* This works for non-GitOps but won’t work for GitOps mode as that requires vault support
fixes #
=> feat: initial support for chart repo username/password

pkg/jx/cmd/controller_commitstatus.go
=> fix: more aggressively push stuff to PipelineActivity

pkg/jx/cmd/controller_commitstatus.go
=> fix: handle BUILD_ID and BUILD_NUMBER

pkg/jx/cmd/cmd.go, pkg/jx/cmd/common_plugins.go, pkg/jx/cmd/get_plugins.go
=> fix: only load managed plugins if CRD available

pkg/jenkins/utils.go, pkg/jx/cmd/common.go, pkg/jx/cmd/factory.go, pkg/jx/cmd/gc_activities.go
=> fix: jenkins client creation inside pods

pkg/binaries/binaries.go
Upgraded eksctl version to 0.1.12.
=> Upgraded eksctl version

pkg/kube/serviceaccount/serviceaccounts.go
=> fix: ensure the namespace exists when creating the vault SA

.gitignore, pkg/jx/cmd/extraValues.yaml
Just a small one to remove an extraValues.yaml that shouldn't have been checked in, and tidy up .gitignore a bit to prevent this.
fixes #
=> Remove extravalues files

pkg/prow/prow.go, pkg/prow/prow_test.go
=> feat: support for external prow plugins

pkg/gits/github.go, pkg/gits/provider.go
=> feat: add labels to PRs

pkg/jx/cmd/step_changelog.go
=> feat: ignore merge commits when creating changlogs

pkg/jx/cmd/edit.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/start.go, pkg/jx/cmd/stop.go, pkg/jx/cmd/upgrade.go
=> fix(cmd): make the suggestFor consisten with the command action and update the init command description

pkg/gits/github.go, pkg/gits/provider.go
=> feat: add updatedAt to pull request

pkg/jx/cmd/create_cluster_gke.go
=> #2573 GKE does not expect a param for this option

go.sum, pkg/jx/cmd/login.go
hardcoding a temporary directory is just madness, despite cross platform
issues like windows / Unix,  some Unixy type platforms have per user temporary
directories rather than system wide ones.
relates to #2530 but is not a fix (it is still broken for me)
=> fix(login) : do not hard code the temp directory.

pkg/jx/cmd/compliance_results.go
fixes #2587
* Requesting a pull to jenkins-x:master from ccojocar:fix-compliance-results-err
*
* Write a message for this pull request. The first block
* of text is the title and the rest is the description.
=> fix(compliance): print a user friendly message instead of a generic error message

go.sum, pkg/auth/vault_config_saver.go, pkg/cloud/gke/gcloud.go, pkg/cloud/gke/helper.go, pkg/io/config_store.go, pkg/jx/cmd/common_gke.go, pkg/jx/cmd/common_helm.go, pkg/jx/cmd/create_vault.go, pkg/jx/cmd/install.go, pkg/jx/cmd/step_helm_apply.go, pkg/jx/cmd/upgrade_ingress.go, pkg/kube/secrets.go, pkg/vault/constants.go, pkg/vault/vault_client.go, pkg/vault/vault_path.go
=> fix(gitops): get the gitops mode working in install command with vault and no-tiller

pkg/config/helm_values.go, pkg/jx/cmd/get_build_logs.go, pkg/kube/pod.go
which means on install we properly update the Staging/Production
Environment git repositories to have the proper configuration for
`exposecontroller`
=> fix: fixes the generation of Ingress with exposecontroller in staging

pkg/jx/cmd/step_link_services.go
so that it uses an external name
fixes #2037
=> fix: jx step link service

Jenkinsfile, pkg/jx/cmd/step.go, pkg/jx/cmd/step_bdd.go, pkg/jx/cmd/step_credential.go, pkg/kube/env.go, pkg/util/suggestions.go
=> fix: add a helper step for exposing secret values as env vars/files

pkg/jx/cmd/start_pipeline.go
Pass kube client down into ProwOptions again.
If only the bdd tests ran in prow mode...
fixes #2614
=> Pass kube client in ProwOptions

Makefile
There was already updatebot setup for the jenkins-x-charts/prow repo, but the regex wasn't working. Testing with my own fork of prow repo this is working ok now, so fingers crossed...
fixes #
=> chore: Correct updatebot regex for prow charts repo.

pkg/apis/jenkins.io/v1/types_environment.go, pkg/auth/auth_config.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go, pkg/kube/env.go
New environment repos. were being created under the GitHub (bot) user's personal space, rather than under the shared organisation/team.
During installation, store the selected GitHub organisation in the TeamSettings (in Dev Environment CRD): TeamSettings.envOrganisation
When creating new teams and new environments for existing teams, refer back to envOrganisation for the organisation under which to
create the environment repos. If a different organisation value is specified on the command line, this is still used in preference.
fixes #2455
=> bug(create environment): Create new environments in GitHub org.

pkg/jx/cmd/step_collect.go
`jx step collect` was using the storage git org/repo in the path where it should have been using that for the project.
fixes #
=> fix: use correct repo/org for step collect

pkg/apis/jenkins.io/v1/types_users.go
=> Custom marshaler

pkg/jx/cmd/common_helm.go
Text should be 'chart' instead of 'chat'
fixes #
=> fixed typo in common_helm.go - renamed chat to chart

pkg/jx/cmd/step_helm_release.go
and avoid core dumping if no payload body returned
fixes #
=> fix: add better error reporting

pkg/jx/cmd/import.go
=> chore: fix wrong command argument description

pkg/helm/helm_cli_test.go
yet another hard coded `/tmp` for a temp directory.
=> chore(tests) : do not hardcode the temp directory

pkg/kube/crds.go
=> bug: fix typo in sourcerepositories CRD name which causes registration to fail

go.sum
go.sum had been regenerated but was missing the entries for the windows
specific dependencies.
fixes #
=> chore(build) add missing go.sum entries

pkg/jx/cmd/get_build_logs.go
It would be nice to have a smart way of retrieving logs using jx, instead of always making the user pass the repo and owner name. More often than not you want the logs of the project that matches your current folder. In this PR I'm adding a new flag that automatically detects the repo and owner names from the current folder, and uses that to filter the list of available build pods.
We could even make this option to always fetch the most recent build number? WDYT?
=> [WIP] Add flag to auto detect repo and owner from current dir

pkg/jx/cmd/preview.go, pkg/jx/cmd/preview_test.go, pkg/jx/cmd/step_changelog.go, pkg/users/git.go, pkg/users/users.go
=> feat: extract a generic user resolver

go.mod, go.sum, pkg/apis/jenkins.io/v1/types_pipeline.go, pkg/kube/activity.go
Adds the repository name, owner and branch to `pipelineactivities` Custom Resources. This allows filtered queries, which are much faster than getting _evenything_ from the system.
fixes #
=> feat(pipelineactivities): label pipeline activities with repo, owner and branch

pkg/helm/helm_helpers.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/common_environments.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/delete_application.go, pkg/jx/cmd/install.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/test_helpers.go, pkg/jx/cmd/upgrade_apps.go, pkg/util/files.go
=> feat: refactor to allow entire template to be modified

pkg/jx/cmd/delete.go, pkg/jx/cmd/delete_eks.go
- made delete_eks lint-friendly
- added extra comments to make command more user-friendly
=> Made delete_eks lint-friendly. Added extra comments.

pkg/jx/cmd/step_bdd.go
The jx step bdd command currently allow us to run bdd tests for jenkins-x, but we could use it to run tests for applications that require a running jx platform.
With these changes you can specify not only a different git repository to checkout, but a specific branch. That way you can checkout changes that are pending to be merge and test if they work.
=> Allow to checkout a different branch while running bdd tests

pkg/jx/cmd/step_changelog.go, pkg/users/git.go, pkg/users/git_test.go, pkg/users/users.go
- [?] Change is covered by existing or new tests.
I tested the resolver code, but there was no test to add to for the changelog, so I didn't directly test it
fixes #2729
=> fix: attempt at fixing getting user by git signature

Makefile
=> using the recently built binary when generating changelog

pkg/jx/cmd/common_domain.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go, pkg/jx/cmd/step_buildpack_apply_integration_test.go, pkg/jx/cmd/step_stash_integration_test.go
=> fix(install): make sure that a domain is configured even when the skip-ingress option is active

pkg/helm/values_tree.go, pkg/helm/values_tree_test.go, pkg/util/types.go
=> feat: generate `values.yaml` from a directory tree

go.mod, pkg/jx/cmd/create_spring.go, pkg/jx/cmd/import.go
Select the git repository and check its valid before doing anything else.  Once confirmed as valid and available then use that as the app name / artifact id. This stops the situation where the repository name and artifact id can be different which will cause the import into another cluster to fail.
Fixes #2699
fixes #2699
=> fix (import) : Select Git Repository first

pkg/jx/cmd/upgrade_ingress.go
We introduce this issue when resolving a merge conflict.
fixes #2704
=> fix(upgrade ingress): apply the cert-manager annotation after clearing the annotations

pkg/jx/cmd/common_plugins.go, pkg/jx/cmd/delete_application.go, pkg/jx/cmd/delete_extension.go, pkg/jx/cmd/gc_previews.go, pkg/jx/cmd/get_activity.go, pkg/jx/cmd/get_applications.go, pkg/jx/cmd/get_issue.go, pkg/jx/cmd/serve_buildnumbers.go, pkg/jx/cmd/step_changelog.go, pkg/jx/cmd/step_next_buildnumber.go, pkg/jx/cmd/step_post_run.go, pkg/jx/cmd/step_stash.go, pkg/jx/cmd/upgrade_extensions.go
This means the mocks get used
Continuation of work for #2741 
This one is less safe as I didn't write all the involved code :-/
fixes #
=> fix: never create a new kube client or jx client

pkg/gits/git_local.go
`GitLocal` is a partially faked out git - remote and global operations
use a fake git client but local operations on a git repo use the git cli
fixes #
=> feat: add `GitLocal` for tests

pkg/helm/values_tree_test.go, pkg/users/git_test.go
=> fix: mark some tests as parallelizable

Dockerfile.builder-maven, Dockerfile.jenkins-maven
=> fix: use the :latest image for docker builds

pkg/collector/bucket_collector.go, pkg/collector/git_collector.go, pkg/util/files.go, pkg/util/files_test.go, pkg/util/test_data/glob_test/artifacts/goodbye.txt, pkg/util/test_data/glob_test/hello.txt
so that we can properly process a wildcard glob with a tree of directories and files for both buckets and git storage
=> fix: improve the glob behaviour of Collector

pkg/jx/cmd/common_cert_manager.go, pkg/jx/cmd/upgrade_ingress.go, pkg/kube/pki/certificate.go, pkg/kube/services/services.go
=> fix(upgrade ingress): get the upgrade ingress command working in batch mode with and without TLS

pkg/jx/cmd/add_app.go, pkg/surveyutils/basicTypes.test.schema.json, pkg/surveyutils/constValues.test.schema.json, pkg/surveyutils/defaultValues.test.schema.json, pkg/surveyutils/descriptionAndTitle.test.schema.json, pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/surveyutils/objectType.test.schema.json, pkg/surveyutils/validators.go
=> chore: start to write tests for jsonschema

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_terraform.go
=> feat(gke) added options to use premptible VMs in the node-pool

pkg/surveyutils/exclusiveMaximum.test.schema.json, pkg/surveyutils/exclusiveMinimum.test.schema.json, pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/surveyutils/maxLength.test.schema.json, pkg/surveyutils/maximum.test.schema.json, pkg/surveyutils/minLength.test.schema.json, pkg/surveyutils/minProperties.test.schema.json, pkg/surveyutils/minimum.test.schema.json, pkg/surveyutils/multipleOf.test.schema.json, pkg/surveyutils/pattern.test.schema.json, pkg/surveyutils/required.test.schema.json, pkg/surveyutils/validators.go
=> chore: tests for lots of validators for jsonschema

pkg/jx/cmd/create_addon_sso.go
=> fix(sso): update the default namespace and wait for dex certificate to be issued

pkg/apis/jenkins.io/v1/register.go
added missing list type
fixes #
=> fix(sourcerepositories): added missing list type

pkg/jx/cmd/common_install.go, pkg/jx/cmd/step_post_run.go
We need to make sure we have a valid jx client, otherwise we may get a nil pointer dereference
=> Initialize jxclient

.github/issue_template.md
=> chore: update the GitHub issue template with Jenkins installation type

pkg/jx/cmd/upgrade_ingress.go
It defines a new flag in the upgrade ingress command which allows to specify where the ingress config map is stored. This option is required 
for BDD tests to be able to run the upgrade ingress in a self-contained namespace without modifying the entire cluster configuration.
fixes #
=> feat(ingress): define a new flag in the upgrade ingress command which allows to specify the namespace where the ingress config is stored

pkg/jx/cmd/install.go
=> fix: prompting for Serverless/Static before generating helm values

pkg/jx/cmd/step_helm_apply.go
=> feat: generate values.yaml from tree during `jx step helm apply`

pkg/helm/helm_template.go, pkg/jx/cmd/common.go, pkg/jx/cmd/common_install.go, pkg/kube/git_services.go
but we can find the git provider kind from the git secrets
=> fix: avoid failing create project if no GitService

pkg/jx/cmd/common_git.go
=> fix: oops, bad refactor on 20df278c909a9fc1a5c1abd41f027f30d3c998a5

pkg/config/admin_secrets.go, pkg/config/admin_secrets_test.yaml
=> fix: adding authentication for mirror repository

Jenkinsfile, pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/helpers.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go, pkg/jx/cmd/mocks/factory.go, pkg/jx/cmd/mocks/matchers/versioned0_interface.go, pkg/jx/cmd/mocks/matchers/versioned1_interface.go, pkg/jx/cmd/mocks/matchers/versioned_interface.go, pkg/jx/cmd/step_changelog.go
=> Various fixes to improve the way we do serverless builds

pkg/apis/jenkins.io/v1/types_pipeline.go
The annotations need to go on the struct
fixes #
=> fix: unbreak the pipeline CRD

pkg/jx/cmd/create_terraform.go
=> fix: defaulting to disable legacy auth, to be consistent with jx create cluster gke

pkg/jx/cmd/get_build_logs.go, pkg/kube/pod.go
=> fix: wait for each init container to start in `jx get build log`

pkg/config/admin_secrets.go, pkg/jx/cmd/upgrade_platform.go
=> feat(upgrade platform) upgrade platform is more consistent in how it deals with secrets

pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/step_bdd.go, pkg/util/strings.go
=> fixes for the new BDD test suite

pkg/config/admin_secrets.go, pkg/jx/cmd/upgrade_platform.go
=> fix: updated order of upgrade platform

pkg/kube/vault/vault_factory.go
=> fix(install): wait for vault to be initialized and unsealed before retrieving the auth token

pkg/jx/cmd/common.go
=> fix(upgrade ingress): pass the whitelisted services to the expose controller

pkg/apis/jenkins.io/v1/types_users.go, pkg/jx/cmd/create_user.go
New command line flag --create-service-account that gets stored in User.createServiceAc **(boolean).**
fixes #
=> feat(create user): add new flag to User CRD to enable serviceaccount.

pkg/kube/pki/cert-manager.go
Do not regenerate certificate issuers if it is not needed (it's already the issuer required by ingress config and email matches).
This is an alternative to https://github.com/jenkins-x/jx/pull/2862
=> fix(issuer): do not regenerate issuers if it is not needed

pkg/gits/github.go
=> bug: validate webhook url when setting up GitHub webhooks.

pkg/jx/cmd/factory.go
=> fix(vault): search the system vault in the dev namespace when creating the client

pkg/jx/cmd/start_pipeline.go
=> fix: need to set job type

pkg/util/cache.go
Fixed lint errors by adding documentation.
=> Fixed lint errors / added documentation

pkg/jx/cmd/upgrade_ingress.go
=> fix(certs): always wait for certs

pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_flagger.go, pkg/kube/constants.go
Install [Flagger](https://docs.flagger.app) for canary deployments
and automated rollbacks
=> feat: create Flagger addon for canary deployments

Makefile, pkg/auth/mocks/auth_interface.go, pkg/buildnum/mocks/build_num.go, pkg/gits/mocks/git_provider.go, pkg/gits/mocks/gitter.go, pkg/gits/mocks/organisation_checker.go, pkg/gits/mocks/organisation_lister.go, pkg/helm/mocks/helmer.go, pkg/jx/cmd/mocks/factory.go, pkg/jx/cmd/mocks/matchers/versioned0_interface.go, pkg/jx/cmd/mocks/matchers/versioned1_interface.go, pkg/jx/cmd/mocks/matchers/versioned2_interface.go, pkg/jx/cmd/mocks/matchers/versioned_interface.go, pkg/kube/mocks/kuber.go, pkg/kube/mocks/sourcerepoer.go, pkg/kube/resources/mocks/installer.go, pkg/util/mocks/commander.go, pkg/vault/mocks/vault_client.go
=> fix: use the version of pegomock from `go.mod`

Makefile
Work around the inception problem
fixes #
=> fix: use the newly built jx to generate docs

pkg/gits/bitbucket_cloud.go, pkg/gits/bitbucket_cloud_test.go, pkg/gits/test_data/bitbucket_cloud/issue-comments.issue-1.json, pkg/gits/test_data/bitbucket_cloud/pullrequests.test-comment.json
Introduces support for creating comments on issues and PRs on Bitbucket Cloud.
fixes #2856
=> Issue and PR comments for Bitbucket Cloud

pkg/jx/cmd/create_addon_sso.go
These versions are tested with cert-manager version v0.6.0
fixes #
=> chore: pin the version of sso-operator and dex

pkg/jx/cmd/add_app.go
=> fix: bugs in argument processing for jx add app

Makefile
=> fix: need to add apidocs to git on release

pkg/kube/env.go
=> fix(install): get the create dev environment creation working in batch mode

pkg/jx/cmd/install.go
Added user friendly error message suggesting BitBucket Server users what could be wrong with their configuration.
=> Added user friendly message to BitBucket installation

pkg/users/git.go, pkg/users/git_test.go, pkg/users/users.go, pkg/users/users_test.go
Fix: a couple of nasty little bugs in user resolution
* matched on empty empty emails :-(
* generated empty references
=> Fix: a couple of nasty little bugs in user resolution

pkg/config/helm_values.go, pkg/config/helm_values_test.go, pkg/config/helm_values_test_with_urltemplate.yaml, pkg/kube/ingress.go
Add the exposecontroller option `urltemplate` to the helm values.
Would like to know how I could test these thing
=> Add exposecontrollers urltemplate

pkg/cloud/iks/datacenters.go, pkg/cloud/iks/helper.go, pkg/jx/cmd/create_cluster_iks.go
=> #2982 Add missing X-Region header for IBM k8s API calls

pkg/jx/cmd/create_cluster_oke.go
=> fix: fail early if oke options can't be fetched

pkg/jx/cmd/add_app.go
=> fix: add a success message!

pkg/jx/cmd/step_pr.go, pkg/jx/cmd/step_pr_labels.go
Add jx step pre labels command
fixes #2990
=> Add jx step pr labels command

pkg/config/admin_secrets.go, pkg/jx/cmd/upgrade_platform.go
=> feat: detect if adminSecrets.yaml is invalid and attempt to repair

pkg/jx/cmd/upgrade_platform.go
=> feat: attempt to fix the jx-install-config secret in the cluster

pkg/jx/cmd/step_bdd.go
Add a flag to disable cloning of the bdd repository so its easy to use a local checkout
=> Skip bdd repo clone

pkg/jx/cmd/create_cluster.go
=> chore(crate cluster): remove duplicated line in help message

pkg/jx/cmd/step_helm_apply.go
fixes typo discovered while reviewing `jx step helm apply` issues I'm seeing
=> fix typo in vault arg

pkg/helm/constants.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/common_cert_manager.go, pkg/jx/cmd/common_helm.go, pkg/jx/cmd/create_addon_sso.go, pkg/jx/cmd/create_addon_vault.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go, pkg/jx/cmd/upgrade_apps_test.go, pkg/kube/constants.go, pkg/kube/namespaces.go, pkg/kube/namespaces_test.go, pkg/kube/pki/cert-manager.go
Also slightly refactored the DefaultChartURL to reduce duplication.
fixes #
=> fix(sso): use the locked version instead of hard-coding for cert-manager, sso-operator, dex and vault-operator

pkg/kpipelines/syntax/pipeline.go, pkg/kpipelines/syntax/pipeline_internal_test.go, pkg/kpipelines/syntax/pipeline_test.go, pkg/kpipelines/syntax/test_data/stage_name_validation/jenkins-x.yml, pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_duplicates.yaml, pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_duplicates_with_multiple_sub_stages.yaml, pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_duplicates_with_sub_stages.yaml, pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_ok.yaml, pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_ok_with_sub_stages.yaml, pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_with_sub_stages.yaml
Now pipelines are validated checking that all Stages have unique names.
Checking stage names are unique within the pipeline
fixes #
=> feat: Validate Stage names for duplicates

pkg/jx/cmd/delete.go
Enables `jx delete app` command
=> Fix: Delete app command is disabled

Makefile, pkg/jx/cmd/common_buildpacks.go, pkg/jx/cmd/import.go, pkg/jx/cmd/import_integration_test.go, pkg/jx/cmd/test_data/import_projects/docker-helm/Dockerfile, pkg/jx/cmd/test_data/import_projects/docker-helm/charts/REPLACE_ME_APP_NAME/Chart.yaml, pkg/jx/cmd/test_data/import_projects/docker/Dockerfile, pkg/jx/cmd/test_data/import_projects/helm/charts/REPLACE_ME_APP_NAME/Chart.yaml, pkg/tests/files.go
=> fix: allow pure docker and/or helm build packs

pkg/kube/vault/vault.go
=> chore: set the version of the docker iamge for vault-operator and bank-vaults to 0.4.7

pkg/jx/cmd/controller_workflow.go
This is basically copying the workaround for issue #2410 from `PromoteOptions.waitForGitOpsPullRequest()` into
the workflow controller so that PipelineActivities get updated when the promotion PR merges. Normally, this is
done via `jx promote` during the build, but if that fails/times out then this ensures the workflow controller
tidies up the status to reflect that the PR is merged & promotion is complete.
fixes #
=> bug: update activities to complete on PR merge.

pkg/jx/cmd/delete_application.go
Only attempt to delete applications from environments which are `Permanent`.
fixes #2714
=> Only delete apps from Permanent envs

README.md
Change directory in readme from `.jenkins-x` to `.jx`
Just making sure I'm doing it right...
Just a doc change
=> Minor doc change

pkg/jx/cmd/common_helm.go
=> fix: minor spelling mistake in error message

pkg/jx/cmd/controller_workflow.go
=> chore: remove extraneous (but benign) debug.

pkg/cloud/cloud.go, pkg/jx/cmd/common_domain.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_cluster_aks.go, pkg/jx/cmd/create_cluster_aws.go, pkg/jx/cmd/create_cluster_eks.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_terraform.go, pkg/jx/cmd/create_cluster_iks.go, pkg/jx/cmd/create_cluster_minikube.go, pkg/jx/cmd/create_cluster_minishift.go, pkg/jx/cmd/create_cluster_oke.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go, pkg/jx/cmd/update_cluster_gke.go, pkg/jx/cmd/update_cluster_gke_terraform.go, pkg/jx/cmd/upgrade_platform.go
=> refactor: move kubernetes providers names into cloud package

pkg/helm/helm_template.go, pkg/jx/cmd/upgrade_platform.go
=> fix(upgrade platform): read the chart version from deployment label for no-tiller

pkg/jx/cmd/common_app.go
fixes #3068
Fixes an issue when running the add app bdd test
=> fix: Error: running postinstall hooks during jx add app

OWNERS
=> chore: add David Conde to OWNERS

README.md
=> chore: add some badges in the README

.gitignore, pkg/helm/tiller.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/factory.go, pkg/jx/cmd/install.go
=> refactor: move into helm package all helper methods for tiller

pkg/jx/cmd/common_pipelines.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_changelog.go, pkg/jx/cmd/step_post_run.go, pkg/jx/cmd/step_pre_extend.go
=> refactor: move the common pipeline methods in a separate file

pkg/jx/cmd/add_app_test.go
=> fix: try to make the failing console test pass

pkg/jx/cmd/install.go
fix two typos in the command line options for `--no-gitops-env-setup`
I also checked the unit tests for install, the method is aligned and the long-option signature is not elsewhere.
=> fix two typos with --no-gitops-env-setup

pkg/auth/file_config_saver.go, pkg/auth/types.go, pkg/io/config_writers.go, pkg/jx/cmd/common_environments.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_cluster_aws.go, pkg/jx/cmd/create_docs.go, pkg/jx/cmd/create_jhipster.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/delete_branch.go, pkg/jx/cmd/helpers.go, pkg/jx/cmd/import.go, pkg/jx/cmd/init.go, pkg/jx/cmd/step_blog.go, pkg/jx/cmd/step_changelog.go, pkg/jx/cmd/step_create_build.go, pkg/jx/cmd/step_git_credentials.go, pkg/jx/cmd/step_gpg_credentials.go, pkg/jx/cmd/step_split_monorepo.go, pkg/jx/cmd/step_tag.go, pkg/jx/cmd/sync.go
=> refactor: remove duplicated const for file default write permissions

pkg/jx/cmd/create_addon_flagger.go, pkg/jx/cmd/delete_addon.go, pkg/jx/cmd/delete_addon_flagger.go, pkg/kube/constants.go
Follow up from https://github.com/jenkins-x/jx/pull/2878
display flagger addon in jx get addon
fixes #
=> fix: more flagger configuration

pkg/jenkins/constants.go, pkg/jenkinsfile/jenkinsfile.go, pkg/jx/cmd/common_buildpacks.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/get_activity.go, pkg/jx/cmd/import.go, pkg/jx/cmd/import_integration_test.go, pkg/jx/cmd/step_buildpack_apply.go, pkg/jx/cmd/step_buildpack_apply_integration_test.go, pkg/jx/cmd/step_post_install.go
=> refactor: use proper command options and move jenkinsfile related consts to jenkinsifle package

pkg/jx/cmd/delete_application.go
=> chore: wrap errors instead of returning them directly

pkg/jenkins/utils.go, pkg/jx/cmd/common.go, pkg/jx/cmd/common_logs.go, pkg/jx/cmd/common_pod.go, pkg/jx/cmd/completion.go, pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/logs.go, pkg/jx/cmd/metrics.go, pkg/jx/cmd/start_pipeline.go
=> refactor: move some common methods for logs and pods in separate files

pkg/jx/cmd/common_helm.go, pkg/jx/cmd/init.go, pkg/jx/cmd/step_helm_release.go
=> refactor: move helm initialization in common and refactor it to avoid dependency cycles with cmd package

pkg/jx/cmd/delete_application.go
Respect `--no-env` flag for `jx delete application`
I did compile this change locally and was able to remove an application without sending PRs to environments.
fixes #2626
=> Respect --no-env flag for jx delete application

pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/delete_app_test.go, pkg/jx/cmd/upgrade_apps_test.go
=> fix: move app test helpers to new pkg

pkg/jx/cmd/init.go
=> chore: improve the message of skip-ingress option and add a  warning message

go.mod, go.sum, pkg/builds/build_number.go, pkg/builds/constants.go, pkg/builds/helpers.go, pkg/jx/cmd/controller_build.go, pkg/jx/cmd/controller_commitstatus.go, pkg/jx/cmd/controller_pipelinerunner.go, pkg/jx/cmd/step_create_task.go
This depends on the chart update at
https://github.com/jenkins-x-charts/knative-build-pipeline/pull/10 -
it'll do nothing useful until that's merged, and it is needed once
that is merged.
I also fixed a replacement in `step_create_task` while I was here.
n/a
=> fix: Fix pod detection with newer Build Pipeline changes

pkg/cloud/gke/gcloud.go, pkg/jx/cmd/create_cluster_gke.go
=> fix: corrected enable apis command

pkg/jx/cmd/common_helm.go
Attempting to fix issue when the update to jenkins-x-versions fails intermittently.
Will test in combination with https://github.com/jenkins-x/jx/pull/3123
fixes #3117
=> Refactor clone JX Versions Repo

go.mod, go.sum, pkg/gits/bitbucket_cloud.go
Fixes a bug that causes Bitbucket Cloud to return 400 during promotion.
=> Fix Bitbucket Cloud merge bug

pkg/jx/cmd/upgrade_platform.go
Just fixing a missing error check
=> fix(upgrade): add missing error check

go.mod, go.sum, pkg/kpipelines/pipelines.go
=> chore: fix broken upstream dependency

Jenkinsfile, Makefile, pkg/apis/jenkins.io/v1/types_extensions.go, pkg/apis/jenkins.io/v1/types_pipeline.go, pkg/jx/cmd/get_quickstarts.go
Run the linter (golint and go vet) during CI, so we now the formatting of the code is correct.
Heads up: I've cleaned some unused stuff from the Makefile, if you think it should be kept, just let me know.
=> Run linter during CI

pkg/jx/cmd/step_pr_labels.go
Minor fixes to the `jx step pr labels` command. cc: @jstrachan
=> fix: spaces in labels, PR- prefix in BRANCH_NAME

pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go, pkg/jx/cmd/step_get.go, pkg/jx/cmd/step_get_version_changeset.go, pkg/version/version_data.go
This step can be used to diff the changes between different branches of the version stream
For example:
`$ jx step get version-changeset --stable-branch stuff --pr 21
JX_CHANGED_VERSIONS="charts:jenkins-x/jenkins-x-platform:0.0.3368"
JX_STABLE_VERSIONS="charts:jenkins-x/jenkins-x-platform:0.0.3402"`
fixes ##3057
=> feat: Create a jx step that returns a list of version updates

pkg/apps/gitops.go, pkg/apps/helmops.go, pkg/apps/install.go, pkg/apps/values.go, pkg/environments/gitops.go, pkg/helm/helm_helpers.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/common_helm.go, pkg/jx/cmd/delete_app_test.go, pkg/jx/cmd/delete_application.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/upgrade_apps.go, pkg/jx/cmd/upgrade_apps_test.go, pkg/surveyutils/jsonschema.go
Also adds support for batch mode
fixes #
=> Feat: Only ask new questions on upgrade of apps

pkg/apps/helmops.go, pkg/apps/install.go, pkg/apps/values.go, pkg/helm/helm_template.go, pkg/jx/cmd/get.go, pkg/jx/cmd/get_applications.go, pkg/jx/cmd/get_apps.go, pkg/jx/cmd/get_apps_test.go, pkg/util/urls.go
Implements `jx get app` and `jx get apps`. Removes old behaviour of linking to `jx get applications` 
fixes #2976
=> feat: Implement jx get app / apps

pkg/jx/cmd/step_helm_apply.go, pkg/jx/cmd/step_next_version.go
=> fix: ensure the CommonOptions is set on setp next version and helm version

pkg/jx/cmd/controller_pipelinerunner.go
=> (chore): use tekon bot service account instead of build bot

pkg/apis/jenkins.io/v1/register.go
The new Fact CRD needs to be registered in the client so that it can be used.
=> Register Fact CRD in the client

pkg/jx/cmd/common.go, pkg/jx/cmd/create_devpod.go, pkg/jx/cmd/create_git_api_token.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go, pkg/jx/cmd/step_bdd.go
=> refactor: remove the headless flag and replace its usage with batch flag

pkg/tekton/pipeline_info.go, pkg/tekton/pipeline_info_test.go, pkg/tekton/test_data/pipeline_info/from-build-pack/activity.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/pipeline.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/pipelineresources.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/pipelinerun.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/pods.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/taskruns.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/tasks.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/activity.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipeline.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipelineresources.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipelinerun.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pods.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/structure.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/taskruns.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/tasks.yml, pkg/tekton/test_data/pipeline_info/from-yaml/activity.yml, pkg/tekton/test_data/pipeline_info/from-yaml/pipeline.yml, pkg/tekton/test_data/pipeline_info/from-yaml/pipelineresources.yml, pkg/tekton/test_data/pipeline_info/from-yaml/pipelinerun.yml, pkg/tekton/test_data/pipeline_info/from-yaml/pods.yml, pkg/tekton/test_data/pipeline_info/from-yaml/structure.yml, pkg/tekton/test_data/pipeline_info/from-yaml/taskruns.yml, pkg/tekton/test_data/pipeline_info/from-yaml/tasks.yml
Basically a followup to #3164 - making sure we have tests to validate expected behavior and all that jazz.
n/a
=> chore: test creation of PipelineRunInfo from resources

pkg/jenkins/jobs.go, pkg/jx/cmd/common_import.go, pkg/jx/cmd/step.go, pkg/jx/cmd/step_custom_pipeline.go
so we can use NextGenPipeline / tekton to orchestrate jenkins pipelines in custom Jenkins server Apps
=> fix: add a command to trigger pipelines in custom jenkins apps

pkg/jx/cmd/step_git_merge.go, pkg/prow/env_vars.go, pkg/prow/env_vars_test.go
=> fix: properly use PULL_REFS

pkg/expose/exposecontroller.go
This needs to merged after https://github.com/jenkins-x/jenkins-x-versions/pull/66.
fixes #
=> fix: use the locked version of the exposecontroller chart

pkg/gits/helpers.go
=> fix: work around older git in images

pkg/builds/build_number.go, pkg/builds/build_number_test.go, pkg/jx/cmd/common.go, pkg/jx/cmd/step_bdd.go, pkg/jx/cmd/step_create_task.go, pkg/kube/crds.go
=> fix: passing parameters into tekton pipelines

pkg/jx/cmd/step_create_task.go
Make sure we create the `Pipeline.Spec.Params` when relevant.
n/a
n/a
=> fix: add Pipeline parameters to YAML-generated CRDs

pkg/jenkinsfile/pipeline.go, pkg/jx/cmd/step_create_task.go
Works in both from-yaml and from-build-pack paths of step_create_task
Yeah, needs tests, but that'll come when we rewrite `step_create_task.go` to unify the paths anyway. =)
n/a
=> feat: Add PipelineConfig.Env for global environment variables

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/structure.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/packs/import_dir/classic/javascript/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/import_dir/classic/maven/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/import_dir/classic/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/javascript/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/maven/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/podTemplates.yml, pkg/tekton/pipeline_info_test.go, pkg/tekton/pipelines.go, pkg/tekton/syntax/pipeline.go, pkg/tekton/tekton_helpers_test/test_helpers.go, pkg/tekton/tektontesthelpers/test_helpers.go
Rewriting `step_create_task.go` to still do the same thing, but in a better organized and unit-testable way.
n/a
fixes #3260
=> fix(tekton): make step_create_task.go unittestable

pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
Followup to https://github.com/jenkins-x/jx/pull/3262 fixing some tests
n/a
=> chore: update expected task lists

pkg/jx/cmd/step_get_version_changeset.go, pkg/jx/cmd/step_get_version_changeset_test.go
Adding some test coverage for `jx step get version-changeset`
=> chore: Add coverage for version changeset step

pkg/jx/cmd/common_git.go, pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/step_tag.go, pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/packs/javascript/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/maven/pipeline.yaml, pkg/tekton/syntax/constants.go, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/structure.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/taskruns.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/tasks.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/structure.yml
also fix a couple of tekton bugs around duplicate parameters + `jx get build log` sometimes not working
=> add kaniko support for tekton build packs

pkg/jx/cmd/get_apps.go
=> fix: drop lowercase alias

pkg/config/admin_secrets_test.go, pkg/jx/cmd/scan_cluster.go, pkg/jx/cmd/start_protection_test.go, pkg/prow/config/tide.go, pkg/prow/prow.go, pkg/prow/prow_test.go, pkg/surveyutils/jsonschema.go
=> feat: correctly set the tide url to the deck app

pkg/helm/helm_template.go, pkg/jx/cmd/create_jenkins_token.go, pkg/kube/job.go
=> improvements for no-tiller and jenkins API token creation

pkg/apis/jenkins.io/v1/types_fact.go
Correctly set the required and optional fields for the Fact CRD.
=> Fact measurements must be mandatory, while statements and original are optional

pkg/jx/cmd/controller_build.go, pkg/jx/cmd/get_build_logs.go, pkg/tekton/pipeline_info.go, pkg/tekton/pipeline_info_test.go
Avoid a ton of unnecessary/repeated API calls when generating
`PipelineRunInfo` via either of its paths.
fixes #3316
=> fix: Drastically decrease API calls for PipelineRunInfo creation

pkg/jx/cmd/create_docker_auth.go
style(comment):  correct the method comment
=> style(comment): correct the method comment

pkg/config/admin_secrets.go, pkg/jx/cmd/install.go
=> Add --default-admin-username flag on jx-install

pkg/jx/cmd/upgrade_platform.go
If you use `jx upgrade platform` with the `--update-secrets` flag, it does not end up saving the updated secretes to the Kubernetes secret.  I think next time, if you do an upgrade without the `--update-secrets` flag, then you would end up using the _old_ secrets.
Tested the changes against my cluster.
=> fix(upgrade): save updated secretes to k8s

pkg/gits/github.go, pkg/gits/provider.go, pkg/jx/cmd/step_create_task.go
=> fix: don't fork a private github repo

pkg/jx/cmd/gc_gke.go
This change adds cleanup commands for more items not removed when clusters are removed from GKE
fixes #3285
=> fix: Add cleanup for GKE addresses

docs/apidocs/config.yaml, pkg/client/openapi/all/openapi_generated.go
Add Fact CRD to the OpenAPI generated docs.
=> Add fact CRD to openapi docs

pkg/jx/cmd/get_build_logs.go, pkg/tekton/pipeline_info.go
Pointers are hard. For me, at least.
I still need to write a bunch of unit tests for `get_build_logs` one of these days.
Fixes #3370
=> fix: Don't accidentally reuse PipelineStructures

.updatebot.yml
Adds the jenkins-x/dev-env to updatebot configuration to ensure that the jx version ARG is updated on new jx release.
=> Added dev-env repo to updatebot config

pkg/util/files_test.go
Fixes a unit test that made bad assumptions.  (windows path seporator is not `/`)
there's still a few windows failures, but this means there is on less.
=> fix a dog test so it works on windows too

pkg/kube/patch.go
Added a utility to generate a JSON patch. Returns the JSON patch bytes ready to be applied, e.g. using the generated clientset.
fixes #
=> feat: add utility to generate a JSON patch.

go.mod, pkg/jx/cmd/clients/mocks/factory.go, pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go, pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go, pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go, pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go, pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go, pkg/jx/cmd/controller_build.go
fix up the storage of logs with tekton which got disabled
=> fix: the storage of logs with tekton

pkg/cloud/amazon/vault/naming.go, pkg/cloud/amazon/vault/vault_backend.go, pkg/cloud/gke/vault/naming.go, pkg/cloud/gke/vault/vault_backend.go, pkg/jx/cmd/clients/factory.go, pkg/jx/cmd/create_vault.go, pkg/jx/cmd/delete_vault.go, pkg/jx/cmd/install.go, pkg/jx/cmd/step_helm_apply.go, pkg/kube/vault/vault.go, pkg/kube/vault/vault_test.go
Adding support for vault on AWS with DynamoDB as storage.
This is untested work in progress that is submitted to get feedback.
=> Support creating vault on AWS

pkg/buildnum/mocks/matchers/kube_pipelineid.go, pkg/helm/helm_cli.go, pkg/helm/helm_cli_test.go, pkg/helm/helm_helpers.go, pkg/helm/helm_template.go, pkg/helm/interface.go, pkg/helm/mocks/helmer.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/install.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/preview_test.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_helm_apply.go, pkg/jx/cmd/upgrade_addons.go, pkg/jx/cmd/upgrade_platform.go
when upgrading the addon any previous values for customosation where
lost.  Thic change tells helm to merge existing values with ones that
where used previously when upgrading.
Please think about any other usage that this may break, I hope I have confined it to just addons.
fixes #3399
=> fix(addon) upgrades ignored previous values

Makefile, pkg/jx/cmd/version.go, pkg/jx/cmd/version_test.go, pkg/log/log.go, pkg/surveyutils/jsonschema_test.go
Fix flaky unit tests by refactoring them. It seems that monkey patching library is not properly working with Go 1.12.
fixes #
=> test: refactor some flaky unit tests to get them passing with Go 1.12

README.md
Change from link of badge display to link of report display.
=> Fix go report card link

pkg/util/go.go
=> fix: set modules to on always

pkg/jx/cmd/preview.go
`PipelineActivity` should be updated in dev namespace, not preview environment namespace.
fixes #3427
=> Update PipelineActivity for preview env in dev namespace

pkg/jx/cmd/step_tag.go
Took me a while to debug that `jx step tag` was updating a rogue `Chart.yaml` that was checked into the root of the repo. This additional output would have made it clear what was going on.
fixes #
=> Additional output on jx step tag

pkg/users/git.go, pkg/users/git_test.go, pkg/users/users_test.go
=> fix: don’t try to overwrite user id

pkg/jx/cmd/clients/factory.go, pkg/jx/cmd/step_bdd.go
as when we guess the name its sometimes wrong ;)
=> fix: lets default the vault name from the installation details

pkg/jx/cmd/create_env.go, pkg/jx/cmd/install.go, pkg/jx/cmd/promote.go, pkg/kube/env.go
also return errors if we cannot register environments
=> fix: register the dev env for GitOps

pkg/kube/activity.go
`error: PromoteStepActivityKey was not valid`
In a git working dir (any git, not necessarily the same project we are promoting)
```
$ jx promote croc-hunter-jenkinsx --version 0.0.16 --env production
prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
Promoting app croc-hunter-jenkinsx version 0.0.16 to namespace jx-production
No $BUILD_NUMBER environment variable found so cannot record promotion activities into the PipelineActivity resources in kubernetes
No changes made to the GitOps Environment source code. Code must be up to date!
```
Outside a git working copy
```
$ jx promote croc-hunter-jenkinsx --version 0.0.16 --env production
prow based …
```
=> jx promote fails outside of a git working copy

pkg/jx/cmd/upgrade_ingress.go
The `urltemplate` option should not be required to have a non-empty value.
cc: @jstrachan and @amuniz 
fixes #
=> The urltemplate can be empty

pkg/apps/helmops.go, pkg/apps/install.go, pkg/apps/utils.go, pkg/apps/values.go, pkg/client/openapi/all/openapi_generated.go, pkg/helm/helm_helpers.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go
Support for `jx add app /path/to/chart`
fixes #
=> Feat: add app from local path

pkg/jx/cmd/delete_user.go
=> chore(users) fix incorrect warning message

pkg/helm/helm_helpers.go, pkg/jx/cmd/add_app_test.go
=> Chore: fix rendering of table in generated readme

pkg/config/admin_secrets.go, pkg/config/admin_secrets_test.yaml
=> fix: removed duplicate maven server settings

pkg/jx/cmd/controller_pipelinerunner.go
=> chore: fix typo in pipelineRunMethods func name

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/install.go
=> feat: enabled kaniko/enhanced scopes & apis as part of next gen install

pkg/jx/cmd/create_cluster_aws.go
This PR allows users to create clusters on AWS (with kops) and manage all instance groups using [Spotinst](https://spotinst.com) (see: https://github.com/kubernetes/kops/pull/5922). Usage example:
```sh
jx create cluster aws --zones us-west-2a,us-west-2b,us-west-2c --spotinst
```
N/A
=> Add support for Spotinst

Makefile
=> Revert "chore: clean up Makefile"

pkg/jx/cmd/init.go
Added publish-service arg to the ingress-controller so that external-dns can expose services using the load balancer IP
=> Added publish-service arg to ingress-controller

pkg/jx/cmd/common.go, pkg/jx/cmd/edit_userrole.go, pkg/jx/cmd/get_user.go, pkg/kube/roles.go
fix(userrole) lookup users from the correct namespace
fix(userrole) add the current roles to the prompt
The `jx edit userroles` failed when you tried to use it in a teams
namespace as the user lookup failed.
Additionally the prompt for adding roles did not default to the users
current roles meaning roles could get accidently lost (as it appeared as
though a user had none)
fix(userrole) lookup users from the correct namespace
fix(userrole) add the current roles to the prompt
The `jx edit userroles` failed when you tried to use it in a teams
namespace as the user lookup failed.
Additionally the prompt for adding roles did not default to the users
current roles meaning roles could get accidently lost (as it appeared as
though a user had none)
=> fix(userrole) lookup users from the correct namespace

jx/scripts/update-website.sh, pkg/jx/cmd/common_install.go, pkg/jx/cmd/step_create_task.go
to avoid us breaking knative build as we iterate on upstream prow with
tekton
=> fix: use a different version of prow for knative build

jx/scripts/update-website.sh
=> fix: using pushd/popd to navigate dirs when building website

jx/scripts/update-website.sh
=> fix: corrected jx dir when generating website

pkg/jx/cmd/upgrade_ingress.go
Added the missing argument `--domain` to `jx upgrade ingress`
fixes #3498
=> Added domain argument to 'jx upgrade ingress'

pkg/pipelinescheduler/builder.go, pkg/pipelinescheduler/builder_test.go, pkg/pipelinescheduler/config.go, pkg/pipelinescheduler/prow/config_builder.go, pkg/pipelinescheduler/prow/config_builder_test.go, pkg/pipelinescheduler/prow/test_data/repo/config.yaml, pkg/pipelinescheduler/prow/test_data/repo/repo.yaml, pkg/pipelinescheduler/prow/test_data/with_parent/config.yaml, pkg/pipelinescheduler/prow/test_data/with_parent/parent.yaml, pkg/pipelinescheduler/prow/test_data/with_parent/plugins.yaml, pkg/pipelinescheduler/prow/test_data/with_parent/repo.yaml, pkg/pipelinescheduler/prow_config.go, pkg/pipelinescheduler/testhelpers/helpers.go, pkg/surveyutils/jsonschema.go
Note that this is still under development, but want to get this part merged so that keeping up with trunk is easier
fixes #
=> feature: hiearchical config for prow.

pkg/jx/cmd/install.go
=> feat: enabling cloudkms api when --vault is used

pkg/cloud/gke/vault/vault_backend.go, pkg/jx/cmd/clients/factory.go, pkg/jx/cmd/common.go, pkg/jx/cmd/common_auth.go, pkg/jx/cmd/common_bucket.go, pkg/jx/cmd/common_gke.go, pkg/jx/cmd/create_vault.go, pkg/jx/cmd/install.go, pkg/kube/vault/vault.go
=> fix: various issues to get the --ng option working in the install

pkg/jx/cmd/controller_build.go
Complete additional git information in tekton based PipelineActivities
=> fix(git-info): complete tekton based PAs with git information

pkg/jx/cmd/common_gke.go, pkg/jx/cmd/create_cluster_gke.go
=> fix: improve selection of regional/zonal clusters

go.mod, pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_gloo.go, pkg/jx/cmd/get.go, pkg/jx/cmd/get_stream.go, pkg/jx/cmd/step_create_version_pr.go, pkg/kube/activity.go, pkg/version/version_data.go
so that we have version stream for builder images
=> fix: support generating PRs for docker builder images

pkg/jx/cmd/clients/factory.go
=> fix: use the dev namespace when fetching the secret location

pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/structure.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/tasks.yml, pkg/tekton/syntax/pipeline.go
A better solution should get cooked up for "no, really, don't use `/bin/sh -c`" cases, but this unblocks the most common use case for that, Kaniko, for now.
n/a
=> fix: Special-case command for kaniko steps

pkg/gits/gitlab.go
Fixed order of arguments in function called by gitlab CreateWebHook.
fixes #3575
=> fix: order of arguments passed to function

pkg/apps/install.go, pkg/jx/cmd/upgrade_apps.go
=> fix: minor fixes to upgrade app

pkg/apps/install.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go
=> Fix: release name needs to include namespace

pkg/jx/cmd/opts/helm.go
=> Fix: don’t error if vault is not available

pkg/jx/cmd/step_tag.go
trim the content of the VERSION file, before using it
=> fix(tag): trim the content of the VERSION file

pkg/apps/install.go, pkg/apps/values.go, pkg/helm/helm_helpers.go, pkg/helm/helm_helpers_test.go, pkg/helm/interface.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/create_addon.go, pkg/jx/cmd/create_addon_ambassador.go, pkg/jx/cmd/create_addon_anchore.go, pkg/jx/cmd/create_addon_environment_controller.go, pkg/jx/cmd/create_addon_flagger.go, pkg/jx/cmd/create_addon_gitea.go, pkg/jx/cmd/create_addon_kubeless.go, pkg/jx/cmd/create_addon_pipeline_events.go, pkg/jx/cmd/create_addon_sso.go, pkg/jx/cmd/create_addon_vault.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_helm_apply.go, pkg/jx/cmd/step_helm_install.go, pkg/jx/cmd/upgrade_addons.go, pkg/jx/cmd/upgrade_platform.go, pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/vault/helpers.go
=> feat: replace vault: references with secrets

pkg/apps/install.go, pkg/helm/helm_helpers.go, pkg/helm/helm_helpers_test.go, pkg/helm/helm_template.go, pkg/jx/cmd/opts/helm.go
Redo the integration so the work happens when we add repos, not when we do installs
fixes #
=> fix: rework the helm credentials

pkg/vault/helpers.go, pkg/vault/helpers_test.go
=> Add a test and linting

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/opts/common.go, pkg/jx/cmd/opts/common_test.go, pkg/jx/cmd/test_helpers.go
=> Issue #3205 - Add ability to determine whether a given flag was explicitly set

pkg/client/openapi/all/openapi_generated.go, pkg/jx/cmd/opts/jenkins.go, pkg/jx/cmd/opts/team_settings.go, pkg/jx/cmd/update_webhooks.go
=> feat: added extra flags to update webhooks

pkg/helm/helm_helpers.go
=> Fix: use the hostname without the port

go.mod, go.sum, pkg/client/openapi/all/openapi_generated.go, pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go, pkg/jx/cmd/step_create_task.go
=> fix: use a shallow clone in create task

pkg/jx/cmd/opts/team_settings.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/step_create_task.go, pkg/kube/pod_templates.go, pkg/users/git.go
as the Service is not immediately available when using knative
=> fix: lets add a retry to get the preview URL

pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/helpers.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/step_bdd.go
Previously it assumed that there was a branch called baseBranch already in existence
fixes #
=> fix: fix the merge logic

OWNERS
Just adding my handle to the OWNERS file so I can help with PRs
Already an owner of the jx organization
=> chore: added dgozalo to OWNERS

pkg/kube/vault/vault.go
This mitigates a concurrency issue when vault gets unsealed in HA mode.
fixes #
=> fix(vault): provision a single vault instance

pkg/jx/cmd/opts/helm.go
It also feels annoying to alway see them in the install logs even
though the versions repository can be re-cloned.
fixes #
=> chore: remove logs messages because they are not quite informative

.github/issue_template.md
=> chore: udpate the issue template with the current installation types

pkg/jx/cmd/delete_app.go
=> fix: allow default ns

pkg/jx/cmd/add_app_test.go, pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/surveyutils/test_data/AllOfIf.test.schema.json, pkg/surveyutils/test_data/ifThenElse.test.schema.json, pkg/surveyutils/test_data/ifThenElseNested.test.schema.json
This PR adds support for conditional questions when configuring an app. The conditional questions are supported via the json schema support listed [here](https://json-schema.org/understanding-json-schema/reference/conditionals.html)
fixes #3378
=> feat: Support conditional questions when configuring an App

charts/jx/.helmignore, pkg/apis/jenkins.io/v1/types_environment.go, pkg/helm/helm_template.go
=> fix: avoid tiller less failing with empty templates

pkg/apps/install.go, pkg/apps/utils.go, pkg/helm/helm_helpers.go, pkg/helm/helm_helpers_test.go, pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/controller_workflow.go, pkg/jx/cmd/controller_workflow_integration_test.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/preview_test.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_release.go, pkg/jx/cmd/upgrade_apps_test.go
=> feat: prompt for repo username/password if needed

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/packs/no-default-agent/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/override-default-agent/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
That was wrong. Don't do that.
n/a
=> fix: jenkins-x.yml agent.container was getting cleared for buildpacks

charts/jx/values.yaml, pkg/jx/cmd/gc_activities.go, pkg/jx/cmd/get_build_pods.go, pkg/log/log.go
so we default to nice text based formatting apart from our helm charts
=> fix: logging

pkg/expose/exposecontroller.go, pkg/jx/cmd/get_quickstarts.go, pkg/jx/cmd/upgrade_ingress.go, pkg/kube/ingress.go, pkg/kube/services/services.go
=> Add support for cluster-issuer when exposing services

pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/simple_jenkinsfile/jenkins-x.yml
Since the step name ends up being the container name, it's gotta be a
valid DNS label, so let's mangle it.
n/a
=> fix: Step name needs to be mangled to rfc1035

.github/dco.yml, DCO
This adds the developer certificate of origin (DCO) and enable the DCO bot,
which enforces contributors sign-off excepting the members of jenkins-x organisation.
https://github.com/probot/dco
https://github.com/apps/dco
fixes #3385
=> chore: add the developer certificate of origin (DCO)

go.mod, go.sum
pick up a patched version of logrus which fixes the bad default formatter on windows (it was dropping color support)
fixes #3708
fixes #3688
=> Update logrus to fix picking up wrong format on windows.

pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/step_create_task.go
=> fix: centralise shallow clone logic in gitter

pkg/jx/cmd/add_app_integration_test.go
=> Chore: disable noisy test

pkg/jx/cmd/create_addon_flagger.go, pkg/jx/cmd/delete_addon_flagger.go
```
Error: Non-absolute URLs should be in form of repo_name/path_to_chart, got: flagger
```
fix: delete the Flagger addon in the correct namespace
fixes #
=> fix: flagger installation fails with no tiller

pkg/apis/jenkins.io/v1/types_environment.go, pkg/apps/install.go, pkg/apps/values.go, pkg/helm/helm.go, pkg/helm/helm_cli.go, pkg/helm/helm_cli_test.go, pkg/helm/helm_helpers.go, pkg/helm/helm_template.go, pkg/helm/interface.go, pkg/helm/mocks/helmer.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/clients/mocks/factory.go, pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/delete_app_test.go, pkg/jx/cmd/get_addon.go, pkg/jx/cmd/get_apps.go, pkg/jx/cmd/get_apps_test.go, pkg/jx/cmd/step_helm_list.go, pkg/jx/cmd/step_validate.go, pkg/jx/cmd/test_data/get_apps/get_apps_table_json.json, pkg/jx/cmd/test_data/get_apps/get_apps_table_yaml.yaml, pkg/jx/cmd/upgrade_addon_prow.go, pkg/jx/cmd/upgrade_addons.go, pkg/jx/cmd/upgrade_apps_test.go, pkg/jx/cmd/upgrade_platform.go, pkg/jx/cmd/version.go
=> feat: enable shortnames e.g. jx add app athens

pkg/apps/install.go
=> Fix: ensure repositories are added

Makefile, cmd/jx/app/jx.go, go.mod, go.sum, pkg/features/features.go, pkg/features/features_test.go, pkg/jx/cmd/cmd.go, pkg/jx/cmd/create_cluster_aks.go, pkg/jx/cmd/create_cluster_aws.go, pkg/jx/cmd/create_cluster_eks.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_iks.go, pkg/jx/cmd/create_cluster_minikube.go, pkg/jx/cmd/create_cluster_minishift.go, pkg/jx/cmd/create_cluster_oke.go, pkg/jx/cmd/install.go
Initial Check In of Jenkins X Distribution
Initial implementation of the cloudbees distribution. This currently it disables `jx create cluster` commands for all cloud providers apart from gke. It also disables JenkinsFileRunner builds.
This is a series of PRs that will introduce necessary functionality to enable a full cloudbees distribution to be built.
fixes #
=> CloudBees Jenkins X Distribution 

jenkins-x.yml
Build Cloudbees distribution before updating downstream
fixes #
=> Update build order

pkg/environments/gitops.go
=> fix: don’t barf when templating doesn’t work

pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go
We weren't specifying it for...some reason I thought was wise at some point in the distant past. That was a bad decision. Let's fix that.
/assign @joseblas 
n/a
=> fix(tekton): targetPath for stages after first needs to be specified.

pkg/jx/cmd/upgrade_apps_test.go
=> fix: try disabling parallel for this test

pkg/jx/cmd/delete_addon.go, pkg/jx/cmd/delete_addon_istio.go
=> fix: delete the Istio addon in the correct namespace

pkg/jx/cmd/opts/commands.go, pkg/jx/cmd/step_values_schema_template.go, pkg/jx/cmd/step_values_schema_template_test.go
=> Feat: add jx step values schema template

pkg/jx/cmd/upgrade_addons.go
command had wrong descriptions 
error if passed addon is not found
some errors were ignored
feat: allow passing versions-dir, versions-repo, versions-ref to upgrade addon
versions-repo, versions-ref were already there but ignored
fixes #
=> fix: upgrade addons fixes

pkg/config/helm_values.go, pkg/gits/github.go, pkg/jx/cmd/get_env.go, pkg/jx/cmd/get_preview.go, pkg/jx/cmd/install.go
also lets disable workflow controller for prow and docker registry with tekton+GKE
=> fix for controller build

pkg/environments/gitops.go, pkg/surveyutils/jsonschema.go, pkg/util/types.go
=> fix: support conditions other than true in questions

pkg/jx/cmd/step_create_task.go
as it doesn't work for promotions
=> revert: shallow clone logic

pkg/jx/cmd/opts/helm.go
to avoid breaking the version stream stuff
=> fix: clone an actual revision

pkg/config/project_config.go, pkg/jx/cmd/delete_application.go, pkg/jx/cmd/get_applications.go, pkg/jx/cmd/import.go, pkg/jx/cmd/opts/docker.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/preview_test.go, pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_tag.go, pkg/jx/cmd/step_tag_test.go, pkg/jx/cmd/test_data/step_tag_project/charts/mydemo/values.yaml, pkg/jx/cmd/test_data/step_tag_project/jenkins-x.yml, pkg/prow/prow.go
whether the docker registry host (e.g. docker.io / gcr.io or some ECR/ACR)
and the organisation/owner of the image
=> fix: make it easy to use `jenkins-x.yml` to override the registry

pkg/jx/cmd/step_create_task.go
=> Buildpackurl

pkg/apps/install.go, pkg/environments/gitops.go
=> Values preprocessor

go.mod, pkg/pipelinescheduler/builder.go, pkg/pipelinescheduler/builder_test.go, pkg/pipelinescheduler/prow/config_builder.go, pkg/pipelinescheduler/prow/config_builder_test.go, pkg/pipelinescheduler/prow/test_data/merger_with_parent/config.yaml, pkg/pipelinescheduler/prow/test_data/merger_with_parent/parent.yaml, pkg/pipelinescheduler/prow/test_data/merger_with_parent/plugins.yaml, pkg/pipelinescheduler/prow/test_data/merger_with_parent/repo.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins/parent.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins/plugins.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins/repo.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins_from_parent/parent.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins_from_parent/plugins.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins_from_repo/plugins.yaml, pkg/pipelinescheduler/prow/test_data/only_plugins_from_repo/repo.yaml, pkg/pipelinescheduler/prow/test_data/only_with_parent/config.yaml, pkg/pipelinescheduler/prow/test_data/only_with_parent/parent.yaml, pkg/pipelinescheduler/prow/test_data/only_with_parent/plugins.yaml, pkg/pipelinescheduler/prow/test_data/policy_with_parent/config.yaml, pkg/pipelinescheduler/prow/test_data/policy_with_parent/parent.yaml, pkg/pipelinescheduler/prow/test_data/policy_with_parent/plugins.yaml, pkg/pipelinescheduler/prow/test_data/policy_with_parent/repo.yaml, pkg/pipelinescheduler/prow/test_data/with_parent/repo.yaml, pkg/pipelinescheduler/testhelpers/helpers.go
Tests for the Prow config model
Closed the other PR, it did something weird after a rebase.
fixes #
=> Adding tests to the feature: hiearchical config for prow

pkg/gits/github.go, pkg/jx/cmd/update_webhooks.go
=> fix(webhook): create a webhook when running update webhook command if the repository does not have any webhooks

pkg/jx/cmd/clients/fake/fake_factory.go, pkg/jx/cmd/clients/fake/fake_factory_test.go, pkg/tekton/pipelines.go
=> fix: lets add a FakeFactory for easier testing

pkg/jx/cmd/step_credential.go
=> feat: support for optional creds

README.md
hey @ccojocar @rawlingsj found this near tool called "codescene" which gives all sorts of analysis around code health, hostspots and things that have a lot of churn or need refactoring. 
Thought it is worth a try (at the moment it looks at a few repos)
=> Update README.md to add codescene reporting

pkg/jx/cmd/create_vault.go
=> docs: improve log statement

pkg/jx/cmd/opts/common.go, pkg/jx/cmd/opts/install.go, pkg/prow/prow.go
=> fix: ng install after prow config refactoring

pkg/jx/cmd/install.go
=> fix: store the dev environment in the jx config folder instead of the current directory

jx/scripts/update-website.sh, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/step_syntax_schema.go
as it doesn't seem to work around the tekton issues - so lets roll back to an older tekton instead
=> chore: revert using a default image type on GKE for tekton

pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/validation_failures/duplicate_step_names/jenkins-x.yml
We want to make step names unique or container definitions will end up messed up. So.
n/a
=> fix(tekton): Reject duplicate step names within a stage

pkg/jx/cmd/add_app_test.go
=> fix: add the expect ***

pkg/cloud/gke/gcloud.go
=> feat: create Kaniko service account with a distiguishable name

pkg/jx/cmd/create_addon_prow.go, pkg/jx/cmd/install.go, pkg/jx/cmd/opts/install.go, pkg/jx/cmd/upgrade_addon_prow.go
When installing prow use the myvalues.yml to allow the user to override values in the helm chart
Needed by #3813 to help fix issue #3786
=> (feat) Install prow with myvalues.yml

pkg/jx/cmd/preview.go
=> fix: wait for a 200 before saying the app is ready

pkg/jx/cmd/opts/install.go
=> chore: Don't say "installing knative" when it's tekton

pkg/apis/jenkins.io/v1/types_environment.go, pkg/collector/helpers.go, pkg/jx/cmd/controller_build.go, pkg/jx/cmd/get_storage.go, pkg/jx/cmd/step_stash.go
=> fix: attempt to avoid the storage location being wiped

pkg/gits/helpers.go
=> Fix: don’t do a pull, it doesn’t reliably work

jenkins-x-integration.yml, jenkins-x.yml, jx/scripts/update-clients.sh
Note that to test it I put it in a PR build but that needs removing before we merge
fixes #
=> chore: enable update-clients

pkg/cloud/gke/gcloud.go, pkg/cloud/gke/storage/long_term_storage.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go
…the Google Cloud Storage permissions are set
feature: added a way to provide the name of the long term storage bucket and fall back to a random generated one if not provided
feature: added long term storage when installing Jx, also makes sure the Google Cloud Storage permissions are set
Added a way to enable Long Term Storage for a Jenkins X installation on GKE by providing the flag `--long-term-storage`. 
It also adds the posibility to provide the target bucket, it will do the following checks to it:
- Checks if it exists within the current GCP project
- If it does, just use that one
- If it doesn't, try to create it, if it fails generate a random named one
Note: This feature needs the scope …
=>  Enable gcs buckets as default storage for Jenkins X when using GCP

OWNERS
Adding a new owner/reviewer
N/A
N/A
=> chore: added joseblas to OWNERS

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go
it creates a PipelineActivity within *jx step create task* cmd
fixes #
=> feat: 'jx step create task' should create a PipelineActivity early

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_terraform.go
Forces Kaniko to be used when installing "serverless pipelines" (Tekton) through the UI, same as the `--tekton` flag.
Also defaults to use gcr.io on GKE as the container repository if the argument `--docker-registry` is not provided.
fixes #3839
=> fix(install): Force Kanoko with Tekton on GKE when interactive

pkg/jx/cmd/create_addon_flagger.go
=> feat: allow passing the grafana version to flagger addon

pkg/jx/cmd/create_addon_vault.go, pkg/jx/cmd/create_vault.go, pkg/kube/vault/vault.go, pkg/kube/vault/vault_test.go
=> feat(vault): get the versions of docker images used by vault from versions repository

pkg/cloud/cloud.go, pkg/jx/cmd/init.go
=> feat: initial support for Alibaba Container Service installation

cmd/codegen/generator/open_api.go
=> fix: sanitise go package names

go.mod, go.sum
This is the revision we're using in the Tekton chart currently, so
let's build against it as well. This will also let us start working on
stage retry support.
cc @joseblas 
n/a
=> chore(tekton): Bump Tekton to May 8 rev

cmd/codegen/generator/docs.go
=> fix: correct path to gen-apidocs

pkg/jx/cmd/login.go
=> fix: get the login command working with latest chrome version

jenkins-x-integration.yml, jenkins-x.yml
=> chore: update the version of jx image used by the pipelines to 2.0.128

pkg/helm/helm_cli.go
It was failing if an entry contained optional app version value.
fixes #
=> Fixing bug with parsing helm releases.

pkg/jx/cmd/cmd.go, pkg/log/log.go, pkg/log/log_test.go
=> fix: make sure log level specified via --log-level gets applied

pkg/config/helm_values.go, pkg/config/helm_values_test.go, pkg/config/helm_values_test_with_ingress_class.yaml
Add ingress-class flag to install command to pass the value to exposecontroller (https://github.com/jenkins-x/exposecontroller/commit/f5d8bd613d524b1d0da1ab2aad8258f371e384ff)
Not sure if I should also add IngressClass handling to pkg/kube/ingress.go
=> feat(install): added flag to pass ingress-class to exposecontroller

pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/delete_app_test.go, pkg/jx/cmd/step_helm_apply_test.go, pkg/jx/cmd/upgrade_apps_test.go
=> Fix: disable parallel testing with pegomock, it doesn’t work

jenkins-x.yml
=> chore: more resources for the release build

pkg/kube/sourcerepositories.go
Fixes issue where references in a source repository can disappear
=> Deep copy the source repository so nested info is not lost

Makefile, README.md, codecov.yml, jenkins-x-integration.yml, jenkins-x.yml
=> chore: add a codecov target

pkg/jx/cmd/install.go
=> Print correctly environment name

jenkins-x.yml
=> chore: try to set JAVA_OPTS too

pkg/builds/build_info.go, pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/get_build_pods.go, pkg/tekton/pipeline_info.go
We're gathering the context, why not filter on it too? =)
n/a
=> chore(tekton): Add --context filter option for get build logs and pods

jenkins-x.yml, jx/scripts/update-clients.sh
=> Chore: try to enable the client update script

Makefile
This provides a baseline for the coverage reports
fixes #
=> chore: do the integration tests during release

jenkins-x-integration.yml
`test-slow-integration` runs all the tests anyway, so we don't need to run the check target as well
fixes #
=> chore: don’t run the unit tests twice!

jenkins-x.yml
=> fix: need to use .462 as .461 was a build failure

pkg/helm/helm_cli.go, pkg/helm/helm_cli_test.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/opts/install.go
=> feat: supporting the new helm3 alpha1

jx/scripts/update-website.sh
We’re seeing builds fail due to other pushes appearing, and this is quite a long process!
fixes #
=> chore: fetch & rebase before doing commit

jx/scripts/update-clients.sh
=> fix: VERSION is an env var in the `Makefile`

jenkins-x.yml
=> fix: add the CODECOV_TOKEN

jx/scripts/update-website.sh
=> fix: rebase needs to be after commit

pkg/helm/helm_template.go
=> fix: chart is not fetched if a dir in current directory exists

.codecov.yml, jenkins-x.yml
=> Chore: move the codecov upload earlier

pkg/jx/cmd/get_vault.go
=> fix: print a message instead of an error when vault cannot be listed

pkg/jx/cmd/controller_pipelinerunner.go, pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/step_git_merge.go, pkg/log/log.go, pkg/tekton/crds.go, pkg/tekton/pipelines.go
=> refactor(tekton): restructure of 'step create task'

Makefile
=> fix: oops, not var syntax

cmd/codegen/generator/open_api.go, pkg/jx/cmd/shell.go
=> Fix a couple of small bugs

pkg/gits/helpers.go, pkg/gits/helpers_test.go, pkg/jx/cmd/step_create_task.go
=> fix: don’t error on force-push

Makefile
=> chore: use coverage flags more appropriate for integration tests

OWNERS
=> Adding macox to OWNERS

pkg/jx/cmd/create_terraform.go
=> fix: improved help message to make it more obvious that only GKE is supported

Makefile, cmd/jx/app/jx-win.go, cmd/jx/app/jx.go, cmd/jx/jx.go, cmd/jx/jx_test.go, pkg/jx/cmd/cmd.go
Also refactor file to remove some duplication
fixes #
=> feat: support for a jx binary that will report coverage

pkg/gits/provider_test.go, pkg/jx/cmd/add_app_integration_test.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/get_apps_test.go, pkg/jx/cmd/opts/commands_test.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/uninstall_test.go, pkg/jx/cmd/upgrade_apps_test.go, pkg/kube/env_test.go, pkg/kube/vault/vault_selector_test.go, pkg/surveyutils/jsonschema_test.go, pkg/tests/console_wrapper.go
=> fix: attempt to cleanup expect usage

pkg/jx/cmd/step_create_task.go
=> fix(tekton): make sure the repo clone url is properly set

cmd/jx/app/jx.go, pkg/jx/cmd/cmd.go
Attempt fix for kube config not switching
=> Revert args parsing

cmd/jx/app/jx-win.go, cmd/jx/app/jx.go, cmd/jx/jx.go, cmd/jx/jx_test.go
=> fix: try another way to set args for covered binary

.updatebot.yml
=> chore: removed unused downstream updatebot repo

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_terraform.go
Prompt the user for a cluster name if non is specified using the -n flag.  The default is a generated silly name.
=> Prompt for GKE cluster name

pkg/jx/cmd/create_terraform.go
=> feat: terraform fixes for v0.12

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/install.go, pkg/util/color.go
Reduces the number of questions asked by the CLI when not in batch mode.
Implements an --advanced flag which hides some of the questions and uses sensible defaults unless the user specifies this flag.
=> Simplify CLI UX of 'jx create cluster'

Makefile
=> chore: report branch correctly

pkg/jx/cmd/step/create/test_data/step_create_task/command-as-multiline-script/jenkins-x.yml, pkg/jx/cmd/step/create/test_data/step_create_task/command-as-multiline-script/pipeline.yml, pkg/tekton/syntax/pipeline.go
Since Tekton already provides retries, one new param has to be passed to it.
This PR just makes sure that the param coming from jenkins-x.yml goes into Tekton Pipeline CRD.
fixes #
=> feat: adding retries to Stages (tekton based solution)

Makefile, jenkins-x-bdd.yml, jenkins-x-integration.yml
=> Parallelism

jenkins-x-integration.yml
=> chore: bump up ram a bit to try to achieve -p2

jenkins-x.yml
=> chore: disable distro target

pkg/jx/cmd/bdd/bdd_clusters.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/step_bdd.go
=> feat: added a terraform flag for the cluster.yaml in the bdd tests

jenkins-x-tekton.yml, jenkins-x.yml
We should be consistent on parallelism in all contexts. We may still need to drop this to 1, though, due to OOM compiler errors.
n/a
=> chore: Set PARALLEL_BUILDS in release and tekton contexts

pkg/jx/cmd/step_bdd.go
=> fix: for terraform bdd use cluster name for org name

.codecov.yml, Makefile, cmd/jx/jx_test.go, jenkins-x-bdd.yml, jx/scripts/ci.sh
=> Chore: enable bdd coverage

Makefile, hack/codecov-validate.sh, hack/run-all-checks.sh
=> Chore: add lint for .codecov.yml

Makefile, cmd/jx/jx_test.go, jenkins-x-bdd.yml
=> chore: use a build tag to prevent building covered binary at other times

jenkins-x-bdd.yml, jenkins-x-integration.yml, jx/scripts/ci.sh
=> chore: stash the results from the e2e tests

.codecov.yml
=> chore: don’t include e2e tests in contexts

pkg/jx/cmd/gc_activities.go
lets only GC PipelineRun if we are using prow
=> fix: gc activities if no tekton

jenkins-x-bdd.yml, jenkins-x-images.yml, jx/scripts/ci.sh
=> chore: add a prefix to the versions used for covered images

cmd/jx/jx_test.go, jx/scripts/ci.sh
=> fix: move the output stripper to the bdd test runner

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go
Hide the installation of ingress controller behind the '--advanced' flag to further simplify 'jx create cluster gke'
#3915
=> Hide ingress installation behind advanced flag

jx/scripts/ci.sh
=> chore: remove the set -x - was in there for debugging

cmd/codegen/codegen.go, hack/linter.sh, pkg/client/clientset/versioned/typed/jenkins.io/v1/testutil.go, pkg/gits/commits.go, pkg/tekton/syntax/pipeline.go, pkg/util/json/patch.go
=> chore: enabled error checking in linter

jenkins-x.yml
=> chore: run bdd tests during build in order to produce coverage baseline

pkg/cloud/gke/gcloud.go, pkg/cloud/gke/gcloud_test.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_test.go, pkg/jx/cmd/install.go, pkg/jx/cmd/opts/install.go, pkg/tenant/tenant.go, pkg/tenant/tenant_test.go
Adding the ability to for jx to create a managed-zone within CloudDNS
=> feat: Automate dns managed zone creation for tenant cluster

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/init.go, pkg/jx/cmd/opts/common.go, pkg/jx/cmd/opts/helm.go
If not in advanced mode (`--advanced`) default to pulling the latest jenkins-x-versions repo
#3915
=> Default to pull latest versions repo during install

pkg/gits/git_cli.go, pkg/jx/cmd/install.go
Recreate the cloud environments repository if `--advanced` flag not specified.
Also minor rewording.
#3915
=> Default recreate cloud environments repo

pkg/gits/provider_test.go, pkg/jx/cmd/add/add_app_integration_test.go, pkg/jx/cmd/add/add_app_test.go, pkg/jx/cmd/get_apps_test.go, pkg/jx/cmd/opts/commands_test.go, pkg/jx/cmd/uninstall_test.go, pkg/jx/cmd/upgrade_apps_test.go, pkg/kube/env_test.go, pkg/kube/vault/vault_selector_test.go, pkg/surveyutils/jsonschema_test.go, pkg/tests/helpers.go
=> fix: increase the expect timeout for some tests

pkg/jx/cmd/controller_build.go
=> Buildalerts

jx/scripts/update-clients.sh, pkg/gits/helpers.go, pkg/gits/provider.go, pkg/jx/cmd/create_pullrequest.go
=> Fix create pr

charts/jx/templates/deployment.yaml
=> fix: removing attributes unknown (not supported) by kubernetes deployment

pkg/helm/helm_template.go, pkg/helm/helm_template_test.go, pkg/helm/test_data/multi_objects/objects_separator_namespace.yaml
=> fix: support multi-namespaces in charts with tillerless

pkg/helm/helm_template.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/step/create/step_create_task.go, pkg/jx/cmd/step/helm/step_helm.go, pkg/tekton/crds.go
=> first spike at an interpret mode for 'jx step create task'

jenkins-x.yml
=> chore: upgrade the builder to fix the client update script

pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/create_terraform_integration_test.go, pkg/jx/cmd/step_bdd.go
=> feat: added vault & kaniko flags into terraform vars

pkg/jx/cmd/add/add_app_integration_test.go, pkg/jx/cmd/add/add_app_test.go, pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/upgrade_apps_test.go, pkg/surveyutils/jsonschema_test.go, pkg/tests/console_wrapper.go, pkg/tests/helpers.go, pkg/tests/retry.go, pkg/tests/retry_test.go
=> Chore: retry tests that use expect as they are flaky

pkg/jx/cmd/step/step_changelog.go
=> fix: don’t include the parent commit!

pkg/jx/cmd/create_terraform.go
=> feat: refactored to use error writer pattern

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/edit_buildpack.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/jx/cmd/opts/helm.go, pkg/util/color.go, pkg/util/strings.go, pkg/util/strings_test.go
Format defaulted prompt/answers when using `--advanced` flag to feel the same as prompted questions.
=> Formatting default answers in advanced mode

Makefile
=> fix: making sure go modules is enabled for test rules

pkg/jx/cmd/init.go, pkg/jx/cmd/install.go
Brings the domain prompt earlier if using external-dns
=> feat: Improve how extenral-dns prompts user for domain

pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/loop_step_with_name/jenkins-x.yml
If the step name is set in a loop then ensure its unique
Fixes #4228
=> Unique Loop Name

pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/create_terraform_test.go
=> feat: added some basic validation to the terraform clustername

pkg/jx/cmd/opts/install.go, pkg/jx/cmd/step/verify/step_verify.go, pkg/jx/cmd/step/verify/step_verify_git.go, pkg/jx/cmd/step/verify/step_verify_install.go, pkg/jx/cmd/step/verify/step_verify_pod_count.go
so we can more easily verify a valid installation
=> fix: added a few verify steps

pkg/cloud/iks/registry.go, pkg/cloud/oke/helper.go, pkg/collector/git_collector.go, pkg/gits/github.go, pkg/jx/cmd/create_cluster_iks.go, pkg/jx/cmd/create_cluster_oke.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/delete_eks.go, pkg/jx/cmd/get_eks.go, pkg/jx/cmd/get_preview.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/step/git/step_git_fork_and_clone.go, pkg/jx/cmd/step/verify/step_verify_pod_ready.go, pkg/kube/activity.go, pkg/terraform/terraform.go
=> chore: converted fmt.Print* to log.Logger()

pkg/util/downloads.go
Each file inside the tarball is kept open while tarball is extracted
fixes #
=> fix: too many open files installing istio addon

pkg/cmd/create/install.go, pkg/cmd/opts/common.go, pkg/cmd/opts/install.go
=> feat: create the managed zone when using external-dns

pkg/cmd/initcmd/init.go, pkg/cmd/opts/common.go
Was incorrectly placed in common flags
=> Move advanced flag to init flags

pkg/helm/helm_template.go
Switching some logging to Debugf to reduce noise during install process. Can be seen using `--verbose`
=> Make some logging Debugf

jenkins-x-lint.yml
The `build-step-lint` container is currently speaking load pretty badly and takes waaaaaaay longer than would be expected, so let's set explicit requests/limits for it.
n/a
=> chore: Set resource request and limit for lint context

pkg/cmd/opts/helm.go
Refactor `CloneJXVersionsRepo` to avoid recloning if the repo already exists and is up to date.
fixes #4022
=> Refactor clone jx-versions repo

pkg/cmd/clients/factory.go, pkg/cmd/create/install.go, pkg/cmd/initcmd/init.go, pkg/cmd/opts/domain.go, pkg/cmd/opts/helm.go, pkg/cmd/opts/install.go, pkg/config/admin_secrets.go, pkg/gits/git_repo.go, pkg/helm/helm_cli.go, pkg/helm/helm_helpers.go, pkg/helm/helm_template.go, pkg/kube/env.go, pkg/kube/secrets.go, pkg/version/version_data.go
Reduce and reorder some logging on install process
=> Refactor install logging

pkg/cmd/create/create_cluster_oke.go, pkg/cmd/create/install.go, pkg/cmd/gc/gc_previews.go, pkg/cmd/importcmd/import.go, pkg/cmd/opts/buildpacks.go, pkg/cmd/opts/cert_manager.go, pkg/cmd/preview/preview.go, pkg/cmd/status.go, pkg/cmd/step/pr/step_pr_labels.go, pkg/gits/bitbucket_cloud.go, pkg/gits/bitbucket_server.go, pkg/gits/github.go, pkg/helm/helm_template.go, pkg/users/user_details.go
=> chore: improved logging statements
