pkg/jx/cmd/create.go, pkg/jx/cmd/import.go
as they will be new projects by definition.
This avoids possible issues if folks run, say, `jx create spring` inside a git clone'd repo
=> create projects should not scan for local .git/config files

pkg/gits/provider.go, pkg/jx/cmd/common.go, pkg/jx/cmd/create_env.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/import.go, pkg/jx/cmd/promote.go
if the user opts out of draft and jenkinsfile defaulting
also lets display a more meaningful message about why we need a github user name (e.g. for webhook, create repo, setup credential etc)
=> lets allow the clone to be avoided on import

pkg/jx/cmd/console.go, pkg/kube/services.go
e.g. so you can type: `jx open nexus` even if the service name has a prefix
=> allow jx open to take a text filter to find the service to open

README.md
These instructions should be more reliable for getting started on the Mac.
I suspect we might want to take care of helm/tiller initialization - this caused `jx install` to fail for me rather cryptically.
Fixes #204
=> Getting started experience with BYO minikube

README.md
Update Hyperkit driver installation instructions so that they can be pased into a command prompt
=> Paste-able Hyperkit driver installation instructions

pkg/jx/cmd/create_cluster_minikube.go
Reverts jenkins-x/jx#392
Maybe for now on minikube we disable rbac, lets revert until we decide.
=> Revert "fix(rbac): enable rbac on minikube so jx install works"

pkg/jx/cmd/install.go
Update the help & example with --git-api-token rather than --git-token
--git-token doesn't exist
=> Update the help & example with --git-api-token

pkg/jx/cmd/create_cluster.go
Removes the extra newlines from the `jx create cluster --help` command output:
```
* draft (CLI that makes it easy to build applications that run on kubernetes) \n
* minikube (single-node Kubernetes cluster inside a VM on your laptop ) \n
* virtualisation drivers (to run minikube in a VM) \n
```
=> Remove unnecessary newlines from create cluster command help message

README.md
The current link redirects to the old docs which I guess isn't where it should go :)
=> fixes link to command line reference doc

pkg/jx/cmd/create_spring.go, pkg/jx/cmd/import.go, pkg/jx/cmd/util/factory.go, pkg/spring/model.go
can either use:
``` jx create spring -x
``` to get prompted for the project types or add
``` jx create spring --type gradle-project
```
see #462 requires this PR to also merge:
https://github.com/jenkins-x/draft-packs/pull/9
=> feat:(gradle) allow `jx create spring` to create gradle projects

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_test.go
Hi there!
Amazing project, really looking forward to see what I can contribute with.
This tries to fix an issue I had today while trying out the `jx create cluster gke` command. My user name is "firstname.lastname" on mac so the command failed with 
`ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=invalid field 'cluster.resource_labels.value': "jose.ordiales". It must begin with a lowercase character ([a-z]), end with a lowercase alphanumeric ([a-z0-9]) with dashes (-), and lowercase alphanumeric ([a-z0-9]) between.`
The sanitize function just replaces any non-allowed characters with `-` but I guess it could be made smarter if there's a need.
I only applied this to the "created-by" label because the user doesn't have a lot of control over that one. The ones …
=> Sanitize user name label when creating GKE cluster

pkg/jx/cmd/create.go
Sorry, just a small OCD thing.
```
jx create options
Creates a new resource.
Valid resource types include:
* archetype
* cluster
* env
* git
* spring (aka 'springboot')
```
The first 4 lines were tab indented and the last one space indented :)
=> Align list of valid resource types for create

pkg/gits/provider.go, pkg/gits/provider_test.go
This fixes an issue I was discussing yesterday on the Slack channel with @jstrachan, where if the user belongs to just 1 organisation then that organisation was always used by default to create repos.
=> Always include user account as part of organisation list

pkg/jx/cmd/create_cluster_aws.go
This gives jx the ability to spit out [terraform](https://www.terraform.io/) configuration when creating a cluster on aws via kops. This is extremely useful for using configuration management of an infrastructure.
```
$ jx create cluster aws --terraform /path/to/output
```
=> Add ability to output terraform configuration to a specific directory

pkg/jx/cmd/version.go
It is possible to create unpredictable problems when maintaining a cluster if using a mis-matched version of kubectl so by adding this to the output of `jx version` it will be easier to check as part of issue management.
=> feat: Added kubectl version number to jx version

pkg/jx/cmd/create_quickstart.go
"WIP-" quickstarts are excluded from the shown quickstarts, but this is not something currently depicted in the help message of the command.
=> Enhance help message with note for WIP quickstarts

pkg/gits/bitbucket.go, pkg/gits/bitbucket_test.go, pkg/gits/test_data/bitbucket/issues.test-repo.issue-1.json, pkg/gits/test_data/bitbucket/issues.test-repo.json, pkg/jx/cmd/util/factory.go
Some things aren't supported by the Bitbucket Cloud API, and as such the following methods throw errors:
* `AddPRComment`
* `CreateIssueComment`
* `UpdateRelease`
The first two can be done by POSTing to the same URLs that the web interface uses. This method doesn't support app passwords, however, so we'd have to get the user's web password. 2FA would then have to be dealt with. Releases are simply not supported on Bitbucket Cloud. There is a notion of downloads, but they don't support tagging, release notes, change logs, or really any of the fields of a `GitRelease`
=> Implements remaining BitbucketCloudProvider methods, closes #36

docs/contributing/hacking.md, pkg/auth/config_service.go, pkg/auth/types.go, pkg/config/admin_secrets_test.go, pkg/gits/constants.go, pkg/gits/github.go, pkg/gits/provider.go, pkg/jx/cmd/common.go, pkg/jx/cmd/import.go, pkg/jx/cmd/import_test.go, pkg/jx/cmd/step.go, pkg/jx/cmd/step_git.go, pkg/jx/cmd/step_git_credentials.go, pkg/jx/cmd/step_git_credentials_test.go, pkg/jx/cmd/step_validate_test.go, pkg/jx/cmd/util/factory.go, pkg/jx/cmd/util/factory_auth_test.go, pkg/kube/activity_test.go, pkg/testkube/secrets.go, pkg/tests/helpers.go, pkg/tests/secrets.go
uses the current pipeline git credentials to generate the git credentials file
this avoids build pods having to mount a secret and having to post process any secrets after any changes are made incrementally to add new git services
fixes #596
=> feat:(jx step git credentials) add new command to generate git creds

pkg/jx/cmd/cmd.go, pkg/jx/cmd/create.go, pkg/jx/cmd/create_lile.go
Now its possible to create and import lile generated gRPC services
Fixes #476
=> pkg/jx/cmd/{cmd.go,create.go,create_lile.go}: Added support for lile

pkg/apis/jenkins.io/v1/types.go, pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go, pkg/client/clientset/versioned/clientset.go, pkg/client/informers/externalversions/factory.go, pkg/gits/bitbucket.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/gitlab.go, pkg/gits/provider.go, pkg/jx/cmd/preview.go
For some use cases, we need additional information stored in K8s resources pertaining to the users and pull requests where preview environments were created, this seems to suffice to provide enough data.
@jstrachan PTAL
=> Add more information for preview environments

pkg/gits/bitbucket.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/gitlab.go, pkg/gits/provider.go, pkg/jx/cmd/preview.go
There was an issue where the preview was always reporting the cluster creator as the author, this corrects it as reported by the git provider.
@jstrachan PTAL
=> Fix preview author

pkg/jx/cmd/cmd.go
Add support for the standard `--version` flag that cobra supports. This only prints the version of the binary.
See: https://github.com/spf13/cobra#version-flag
=> Add standard --version option to print the binary version

pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_cluster_minikube.go
JX should support KVM2 driver which is intended to replace support for KVM driver in Minikube - https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver .
=> Added KVM2 support to minikube

pkg/jx/cmd/console.go
This PR addresses #470 - which asks to use BlueOcean as a default for `jx console`. From @jstrachan's idea, I went ahead and added a `--classic` for people that would still like to use the original skin (sadists 😜). 
I decided to keep this option without modifying `Open` as was discussed, as I felt this was currently a pretty specific use case, and would have involved opening a pretty big can of worms (at what level
should something know if it has a path?). `Open` gets used a lot, so I decided to just keep this in the `console` command. The downside of this is that `jx open jenkins` does not open Blue, but the classic skin. It might get messy supporting this - as open would have to allow a special call for `jx open jenkins` :/
Let me know if anyone has ideas here!
=> Default to BlueOcean

pkg/jx/cmd/common_commands.go, pkg/jx/cmd/create_cluster_minikube.go
Hi,
Currently `jx` is kinda "chatty" ;) . For example creating new minikube cluster generates the following output:
```
Starting local Kubernetes v1.7.3 cluster...
Starting VM...
oving files into cluster...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
```
While by default the following should be more than enough:
```
Creating Minikube cluster...
Minikube cluster created.
```
Jx already comes with common `--verbose` flag set to `false` by default, so I propose to start respecting it more.
In particular I would like to start by changing `CommonOptions#runCommand` not to redirect std out and err in non-verbose mode and limit it only to displaying error message. Std out and err should be …
=> Running commands should not be verbose by default

pkg/jx/cmd/create_cluster_minikube.go
When creating Minikube cluster prompt for VM driver should not be invoked if driver option has been used. 
Basically if I execute `jx create cluster minikube --vm-driver=kvm2` I don't want jx to prompt me again for VM driver, but with `kvm2` selected as default. I just want jx to use `kvm2` instead.
=> Minikube: Prompt for VM driver should not be invoked if driver option has been used

pkg/jx/cmd/common_helm.go
After merging #768 jx is that "chatty" anymore, what is cool! However now we have to add some nice minimal messages in places where jx dumped std out/err before.
For example when adding add-on jx should inform users nicely if it tries to register new Helm repo:
```
$ jx create addon ambassador
Helm repository datawire (https://www.getambassador.io) not found. Adding...
Succesfully added Helm repository datawire.
```
There's a bunch of places like this - I will try to make appropriate pull requests over the time. Starting with this one.
=> Helm repository installation should provide basic information in non-verbose mode.

pkg/jx/cmd/constants.go, pkg/jx/cmd/create_cluster_minikube.go
This is continuation of #772. Choosing cpu and memory via cmd options should not invoke input prompt. In particular executing command like `jx create cluster minikube --cpu=4 --memory=8000 --vm-driver=kvm2` should work in a kinda "batch mode".
=> Minikube cpu/memory cmd options should not invoke prompt

pkg/jx/cmd/create_cluster_aws.go
`jx create cluster aws` should include common options. In particular `--verbose`.
=> 'jx create cluster aws' should include common options

pkg/jx/cmd/aks/helper.go, pkg/jx/cmd/create_cluster_aks.go
* Node Size (kept only premium instances, standard disks are too slow in Azure)
* Additional 'az aks create' options supported
* Rely on 'az' default kubernetes version
* Fix interactive login
* Options to skip login, provider registration and resource group creation
=> Improvements to 'create cluster aks'

pkg/jx/cmd/sync.go
See issue: https://github.com/jenkins-x/jx/issues/874
=> add ksync to the path so users don't have to

pkg/jx/cmd/step.go, pkg/jx/cmd/step_gpg_credentials.go, pkg/jx/cmd/step_gpg_credentials_test.go, pkg/kube/config.go, pkg/kube/constants.go
as mounting the GPG secrets no longer works on k8s clusters due to the `~/.gnugpg` folder needing to be mutable
fixes #947
=> feat:(jx step gpg credentials) automate setting up the gpg credentials

pkg/jx/cmd/step_post_build.go
Fixes a very small typo.
```
Options:
--image='': The full image name to be analysed including teh registry prefix
```
=> Fixes a helptext typo

pkg/jx/cmd/common_commands.go, pkg/jx/cmd/uninstall.go
In addition removes also the jx namespace in order to clean up all orphan
resources such as secrets.
=> Clean up the charts of each environment when uninstall the jenkins platform

pkg/auth/config.go, pkg/auth/config_service.go, pkg/auth/config_test.go, pkg/jx/cmd/uninstall.go
Remove the current servers from Jenkins and Chartmuseum configuration when uninstalling the Jenkins platform.
=> Cleanup the configuration when uninstalling the jenkins platform

pkg/jx/cmd/uninstall.go
Make the cleanup work also when the platform is installed in a different namespace
=> Cleanup also the environment namespaces when uninstall the platform

pkg/jx/cmd/gc.go, pkg/jx/cmd/gc_helm.go, pkg/jx/cmd/gc_helm_test.go
Checks for versions of ConfigMaps in kube-system created by Helm for each release and prunes the number of versions retained to a value defined by --revision-history-limit (defaults to 10).
=> feat: Add gc for helm configmaps

pkg/gits/git.go, pkg/gits/git_url.go, pkg/gits/git_url_test.go, pkg/jx/cmd/common_environments.go, pkg/jx/cmd/common_git.go, pkg/jx/cmd/common_import.go, pkg/jx/cmd/common_issues.go, pkg/jx/cmd/create_issue.go, pkg/jx/cmd/gc_previews.go, pkg/jx/cmd/import.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/step_changelog.go, pkg/kube/env.go
The bitbucketserver git urls are of the form
http://test-user@example.bitbucketserver.com/scm/test-org/node-http.git
while others are of the form https://github.com/jenkins-x/jx.git
I think I took a wrong approach to solve this problem by introducing the `hasSCM` parameter to the `parsePath` function - https://github.com/jenkins-x/jx/blob/master/pkg/gits/git_url.go#L156
```
func parsePath(path string, hasSCM bool, info *GitRepositoryInfo) (*GitRepositoryInfo, error) {
arr := strings.Split(strings.TrimPrefix(path, "/"), "/")
if len(arr) >= 2 {
if hasSCM {
info.Organisation = arr[1]
info.Project = arr[1]
info.Name = strings.TrimSuffix(arr[2], ".git")
} else {
info.Organisation = arr[0]
info.Name = strings.TrimSuffix(arr[1], ".git")
}
return info, nil
} else {
return info, …
```
=> Fix environment pull request hasSCM parameter

pkg/jx/cmd/preview.go
Could help with: 
https://github.com/jenkins-x/jx/issues/919
Seemed a simple way to pump out the temporary/preview url so other tools could use it. 
Thoughts @jstrachan @rawlingsj ?
=> write the preview app url to the workspace so other cli tools can use it

pkg/gits/bitbucket_cloud.go
In some cases Mercurial repo is created, while we intend to create Git repo. I suspect this has something to do with organization settings in Bitbucket.
As we currently support only Git type of repositories anyway, it should be ok to hardcode it here for now.
Note: there's separate bug in go_bitbucket library, which does not seem to pass these options to the API at all. I've notified author of the library about this, and investigating a fix there.
=> Pass repo type as parameter to the library

pkg/jx/cmd/import.go
Test and skip symlinks when walking project directory to perform "replacing placeholders"
=> fixes bug #1282

Gopkg.lock, pkg/jx/cmd/compliance_results.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go
=> fix:(compliance) check the status of the compliance before retrieving the results

CONTRIBUTING.MD, pkg/jx/cmd/init.go
In response to #1316 
* Adds instructions for lacking a custom DNS name *before* inputting anything for AWS
Extra:
* Added a symlink for a top-level `CONTRIBUTING.MD`as the contributing instructions are nested under the docs folder
=> Add messaging for setup without a custom domain

pkg/jx/cmd/common_helm.go, pkg/jx/cmd/gc_activities.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go
lets switch to NLB by default for AWS and EKS so we get stable IP addresses
for the load balancer so we can use `$IP.nip.io` as the domain name so we
don't have to use wildcard DNS to kick the tyres
=> fix: create cluster eks

pkg/jx/cmd/import.go, pkg/jx/cmd/import_test.go, pkg/util/files.go
As far as I can see the mentioned problem is fixed: Jenkins happily picks up the desired file `Jenkins-XXX` for build. Are any unit/integration tests required?
=> jenkins-x/jx#1352 Fix create/import jenkinsfile option

pkg/jx/cmd/common_install.go, pkg/jx/cmd/install_test.go
Cloudshell uses GCP configurations when activating a user account.  This
leads to an extra line of text stating which configuration is active when 
trying to access 'core/account'.  This currently breaks the prow installation
=> fix: prow installation should support gcp configurations

pkg/jx/cmd/rsh.go
First implementation of extension '-e cmd' to `jx rsh`
=> jenkins-x/jx#1469 Add option "-e cmd" to jx rsh

pkg/jx/cmd/init.go
We were seeing different behavior when using the `--domain` option in `jx create cluster eks` vs not using it and manually entering it when prompted.  With the option, the domain is not registered with a CNAME whereas when using the prompt, the domain does get a CNAME.
Assuming that the behavior should be the same regardless of where the domain comes from.
=> Register domain in AWS when using the 'domain' option

pkg/gits/git_repo.go, pkg/jx/cmd/common_git.go, pkg/jx/cmd/install.go
This allows for the creation of private git repositories.
I tested creating private repositories with Bitbucket Cloud via `jx create cluster eks`.  I realize there are several other commands that also get this flag and other git providers, but I haven't tested those individually.
I was a little surprised by the change I had to make in `pkg/jx/cmd/install.go`, unsure if other options need to be mapped over?  Like Username or ApiToken?
=> Add --git-private flag to make private repositories

pkg/gits/git_url.go, pkg/jx/cmd/install.go
This fixes the: `jx install --git-provider-url=https://gitlab.com` command
=> fix: install command with gitlab provider

pkg/jx/cmd/create_cluster_aws.go
when executing the command "jx create cluster aws" the following error occurs and the process hangs: 
retrying after error: Command failed 'kops get cluster CLUSTER_NAME -ojson': cannot mix --name for cluster with positional arguments exit status 1
Full command:
jx create cluster aws \
--zones=eu-west-1a,eu-west-1b,eu-west-1c \
--node-size=m4.xlarge \
--master-size=t2.medium \
--cluster-name=${KOPS_CLUSTER_NAME} \
--state=${KOPS_STATE_STORE} \
--default-admin-password=MY_PASSWORD \
--default-environment-prefix=MY_PREFIX \
--docker-registry=MY_ECR_URL \
--git-private=true \
--domain=MY_DOMAIN \
--namespace=MY_NAMESPACE \
--environment-git-owner=MY_GIT_OWNER
Versions:
KOPS version: 1.10.0
KUBECLT version: 1.11.0
JX version: v1.3.188 jx-linux-amd64
kops accepts the following command: 'kops …
=> fix for error during cluster creation on AWS:

pkg/jx/cmd/common_install.go
Right now `jx upgrade cli` displays the following output:
```jx upgrade cli
Downloading https://github.com/jenkins-x/jx/releases/download/v1.3.191/jx-linux-amd64.tar.gz to /home/hekonsek/.jx/bin/jx.tgz...
Downloaded /home/hekonsek/.jx/bin/jx.tgz
```
What is kinda confusing for end user as it looks like jx client tar has been downloaded by not extracted and that I'm supposed to do it by myself as manual step.
So I've added extra line of message to stress that `jx upgrade cli` command does extract and install jx and no other action is needed:
```jx upgrade cli
Downloading https://github.com/jenkins-x/jx/releases/download/v1.3.191/jx-linux-amd64.tar.gz to /home/hekonsek/.jx/bin/jx.tgz...
Downloaded /home/hekonsek/.jx/bin/jx.tgz
Jenkins X client has been installed into …
```
=> CLI upgrade should show final binary path

pkg/jx/cmd/install.go
Hi,
Right now jx doesn't copy username and token Git options when creating new environment. That causes `jx install --provider=eks --git-api-token=mySecret --git-username=hekonsek --git-provider-url=https://bitbucket.org` command to fail.
We should simply copy whole `GitRepositoryOptions` struct to avoid this issue.
=> All Git options should be copied for 'jx install'

pkg/jx/cmd/create_tracker_token.go
This seems to have been an search and replace error
The effect of the fix is that the secret for jira is found when creating changelog.
=> Correct kind for jira secret

pkg/config/helm_values.go, pkg/jx/cmd/install.go
The following PR adds support pushing and pulling images from the Openshift registry.
- Registry defaulted to docker-registry.default.svc:5000 for Openshift and Minishift providers
- New serviceaccount is created called jenkins-x-registry
- registry-admin permissions added to the jenkins-x-registry service account
- Docker secret is auto populated using the token from the jenkins-x-registry serviceaccount
- Any authenticated user is granted permissions to pull images from jenkins-x namespace to simplify image pulling for preview namespaces
=> Openshift registry support

pkg/gits/bitbucket_cloud.go, pkg/gits/bitbucket_server.go, pkg/gits/gerrit.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/gitlab.go, pkg/gits/provider.go, pkg/gits/provider_fake.go, pkg/quickstarts/model.go
Looking for feedback on implementation.  I went with an interface because not all git providers may have a way to download (though I don't have an example of one right now).  The interface allows for checking if the download can even happen before querying for repositories.
An alternative implementation would be to add a method to the `GitProvider` interface and the default implementation would be to return an empty string and log a warning.  Elsewhere when the quickstart is created, it does check for a non-empty download URL, so it would error out there.
Tested all three of these providers: GitHub, Bitbucket Cloud and Bitbucket Server.
=> fix: allow for downloading quickstarts from other git providers

pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/promote.go, pkg/jx/cmd/step_changelog.go
even if `$JOB_NAME` is not set lets allow the pipeline name to be deduced
from the specified application name
=> fix: make jx promote update the PipelineActivity resource

pkg/jx/cmd/create_cluster.go
Hi,
I'd like our devOps team to use Jenkins X to provision Kubernetes cluster on EKS, but I'd like to do it in a dedicated step, without installing actual Jenkins X platform into it. I'd like to achieve something like:
```
jx create cluster eks
jx install --provider=eks
```
I'd like to use such approach, because it is easier to re-provision Jenkins X if needed with Ansible playbooks if we have dedicated playbook for cluster provisioning and Jenkins X installation. 
Would you consider adding `--skip-installation` flag to `create cluster` command? That would solve our issue:
```
jx create cluster eks --skip-installation
jx install --provider=eks
```
Thanks!
=> Added --skip-installation option to 'create cluster' command

Makefile, charts/jx/templates/deployment.yaml, pkg/jx/cmd/common.go, pkg/jx/cmd/controller_workflow.go, pkg/jx/cmd/controller_workflow_integration_test.go, pkg/jx/cmd/promote.go
lets use the workflowName on the PipelineActivity to trigger the new
promotion engine
we can then make `jx promote` decide to use the new model by setting this
value or keep things as they are for now while also reusing the workflow
controller to keep PipelineActivity updated as folks do manual promotions
=> fix: disable the new workflow engine unless specified

pkg/jx/cmd/controller_workflow.go
particularly ones currently not completed! causes an update storm with the changes from those running stages via the jx-resources plugin
=> fix: avoid unnecessarily updating PipelineActivity resources

pkg/util/dirs.go, pkg/util/dirs_test.go
Right now `jx` binary location lookup is practically limited to `which jx` invocation. This is fine for most cases, however I'd like to be able specify `jx` location via env variable. This feature would be primarily useful when user didn't add jx to classpath but still would like to upgrade binary for example. It will also make testing easier, as right now unit testing `CommonOptions#installJx()` is impossible without affecting your existing installation.
=> JXBinaryLocation() function should attempt to lookup for result in env variable

pkg/jx/cmd/common_install.go
Right now `CommonOptions.installJx()` ignores version argument. Fixed that.
=> Version should be respected by CommonOptions.installJx()

pkg/jx/cmd/create_devpod.go
lets always reuse the devpods correctly when not syncning and always output the URLs/IDE stuff
=> fix: create devpods

pkg/jx/cmd/gc_activities.go
The error returned ends up being 'error: deployments.apps "prow-build" not found' which is expected when prow is not enabled.
=> fix: ignore error when detecting if prow is enabled

pkg/jx/cmd/rsh.go
Fixes https://github.com/jenkins-x/jx/issues/1575
Adds an optional "environment" flag to the `jx rsh` command so that users can select deployments by environment, if they wish.
For an example of it in use, see below. I created a test environment called "tester" and from there,
exec'd into two pods in different environments (one in "johncollier", the other in "dev").
```
Johns-MacBook-Pro-3:jx johncollier$ jx env tester
Using environment 'tester' in team 'jx' on server 'https://9.37.135.251:8001'.
Johns-MacBook-Pro-3:jx johncollier$ jx rsh --environment johncollier
? Pick Pod: microprofile-microprofilex-5bf9b5b6f5-t6lzb
root@microprofile-microprofilex-5bf9b5b6f5-t6lzb:/# exit
exit
Johns-MacBook-Pro-3:jx johncollier$ jx rsh --environment dev
? Pick Pod: jenkins-598db5b8b7-4k9pn …
```
=> Add an environment flag to "jx rsh"

pkg/jx/cmd/delete_aws.go
Added AWS region resolving logic to `jx delete aws command`, so user don't have to always specify it via command line flag.
=> Added AWS region resolving logic

pkg/jx/cmd/create_docker_auth.go
Not setting the e-mail directly when running `jx create docker auth` will not set it in config.json. Not sure it has any impact (I did not see one)
=> Correct email value in create docker auth command

pkg/jx/cmd/delete_env.go, pkg/jx/cmd/promote.go
all other references for Environment for delete help has upper case
=> standardize casing for Environment

charts/jx/values.yaml
Hopefully fixes https://github.com/jenkins-x/jx/issues/1705
**WARNING: this change is just a guess, I do not know how to test/verify it!**
`jx gc activities` now calls `kubectl get deployments` here:
https://github.com/jenkins-x/jx/blob/8d7538980cb4887bc9866152732fafd7a62a5830/pkg/kube/namespaces.go#L100
This currently fails due to permissions, example:
```
❯ kubectl logs --tail=100 jenkins-x-gc-activities-1537207200-zwb8m -n jxmt
error: deployments.apps "prow-build" is forbidden: User "system:serviceaccount:jxmt:jenkins-x-gc-activities" cannot get deployments.apps in the namespace "jxmt"
```
=> fix: gc-activities needs permission to get deployments to detect prow

pkg/jx/cmd/common_install.go
As agreed in #1663 I've moved eksctl version into constant and also provided version of function which could take custom version as argument.
=> eksctl binary version should be extracted into const

pkg/jx/cmd/cmd.go, pkg/jx/cmd/diagnose.go
Fixes https://github.com/jenkins-x/jx/issues/1258
Implements a `jx diagnose` command that users can run when they run into issues. The users can then look at the output (or paste it on a github issue) when they're debugging.
As discussed in the issue, it's a fairly simple command currently, it just outputs the following:
```
Kube namespace
jx version
jx status
kubectl get pvc
kubectl get po
kubectl get ingress
kubcetl get secrets
```
It includes a link to the Jenkins-X known issues page, telling users to check there for any issues they may be hitting. I also added support for a `--namespace` flag, allowing users to get Kube resources from alternate namespaces.
The command can be updated in the future as needed, to add more / less output and to make it "smarter" if needed. For the time …
=> feat(diagnose): Add a `jx diagnose` command to help with debugging.

pkg/cloud/amazon/common.go, pkg/cloud/amazon/common_test.go, pkg/cloud/amazon/ecr.go, pkg/jx/cmd/delete_aws.go
Right now we have AWS region resolving logic duplicated in two places. It should be centralized in a single location. Also it will make it easier to add aws profiles support to it, if it is centralized.
=> Extracted AWS region resolving logic

pkg/jx/cmd/login.go
=> fix:(login) remove the tailing slash in the cloudbees application URL

pkg/jx/cmd/common.go, pkg/jx/cmd/common_cert_manager.go, pkg/jx/cmd/create_devpod.go
Migrated a couple of `installChart()` calls to `installChartOptions()` function introduced in #1741. We should prefer using `installChartOptions()` as it doesn't require refactoring when we add new arguments to the function definition.
This is the same PR as #1772 but created from dedicated branch.
=> Migrated installChart() calls to installChartOptions()

pkg/cloud/amazon/common.go, pkg/cloud/amazon/common_test.go, pkg/jx/cmd/create_cluster_eks.go
`jx create cluster eks` should respect region resolving logic.
Also added `ResolveRegionIfOptionEmpty` function which makes it easier to fallback to ENV region resolving if `--region` option passed to commands is empty.
=> `jx create cluster eks` should respect region resolving logic

pkg/gits/bitbucket_cloud.go, pkg/gits/bitbucket_cloud_test.go, pkg/gits/bitbucket_server.go, pkg/gits/bitbucket_server_test.go, pkg/gits/gerrit.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/gitlab.go, pkg/gits/gitlab_test.go, pkg/gits/interface.go, pkg/gits/mocks/git_provider.go, pkg/gits/provider_fake.go, pkg/jx/cmd/import.go
Add pipeline user as collaborator in organisation so it works if it's different from user. Previously 404 was returned by github.
Skip accepting invitation as pipeline user if credentials are missing. Previously we got "panic: runtime error: invalid memory address or nil pointer dereference"
If pipeline user is part of organisation the acceptance step isn't needed anyway.
=> Fixes to adding pipeline user as collaborator

pkg/jx/cmd/create_cluster_aws.go
This fixes #1376 by using the AWS region resolved by either the
AWS_REGION or AWS_DEFAULT_REGION environment variables instead of
hardcoding us-west-1.
=> Use AWS region in kops s3 bucket creation

pkg/binaries/binaries.go, pkg/jx/cmd/common_install.go
Upgraded eksctl version to 1.1.3. You can upgrade eksctl version managed by jx by executing `jx upgrade binaries`.
@jstrachan This is so cool to start having binaries version under control finally. I can now go to out devOps team and tell them to execute `jx upgrade binaries` as soon as this PR is merged. This is exactly what we needed. I will proceed with migrated other binaries to be controlled via this mechanism.
=> Upgraded eksctl version

pkg/cloud/amazon/ecr.go, pkg/cloud/amazon/s3.go, pkg/jx/cmd/create_cluster_aws.go, pkg/jx/cmd/get_aws_info.go, pkg/jx/cmd/get_eks.go
Right now some AWS-related commands respect `--region` and `--profile` flags and some not. It confuses AWS users, as it is not clear where jx searches for AWS configuration among different commands.
This PR adds support for those flags for `jx get eks` and `jx get aws info` commands.
=> AWS commands should respect --region and --profile flags

pkg/jx/cmd/common.go, pkg/jx/cmd/common_import.go, pkg/jx/cmd/import.go
Support separate external url for git web hooks.
Typically needed when having a private kubernetes cluster on an internal domain.
=> External Jenkins URL

pkg/jx/cmd/upgrade_platform.go
`jx upgrade platform` should use the version of platform read from cloud-env or passed via `--version` option. Right now we're ignoring that version and upgrade platform to the latest version anyway.
=> `upgrade platform` should use platform version from cloud-env

pkg/apis/jenkins.io/v1/types_environment.go, pkg/auth/config.go, pkg/auth/config_service.go, pkg/auth/types.go, pkg/jx/cmd/common_team_settings.go, pkg/jx/cmd/edit.go, pkg/jx/cmd/import.go, pkg/jx/cmd/install.go, pkg/tests/helpers.go
Add git server, organisation, pipeline git user name and docker registry
organisation to team settings. Set git server, organisation and pipeline
git user name on jx install. The values are used during import.
Transferring team settings to options to avid fetching team settings multiple times.
Removing option default-owner since it overlaps and is confused with git-provider-url and org.
Removing PipelineUSer and PipeLineServer from AuthConfig since they now is placed in TeamSettings
Fixes #764 
This is not properly tested manually yet. Also I don't know how to run the integration tests.
=> [WIP] Store defaults in team settings

pkg/jx/cmd/upgrade_platform.go
Right now `jx upgrade platform` attempts to upgrade version of platform no matter if the proper version is installed or not. We should detect which version of platform is installed, which is requested and then upgrade platform or just display information that proper version is already installed.
Even when upgrading we should display information that we are `upgrading from X to Y`,  not only `upgrading to Y`.
=> `jx upgrade platform` should not perform upgrade if given version is installed

pkg/jx/cmd/create_devpod.go
Since `jx create devpod` accepts the headless flag:
```
--headless=false: Enable headless operation if using browser automation
```
I've updated create_devpod.go so that if the headless flag has been set, we don't exec into the devpod's shell after creation. We don't want to exec into a shell in headless mode, because access to a TTY shell may not be available.
To do this, I simply added a check for `!o.Headless` around the lines of code that add the shell exec command. 
See below for an example:
```
Johns-MacBook-Pro-3:testmp johncollier$ jx create devpod -l maven --sync --headless
Creating a DevPod of label: maven
Created pod johncollier-maven - waiting for it to be ready...
Updating Helm repository...
Using helmBinary helm with feature flag: none
Helm repository update done.
Pod …
```
=> When headless mode is set, don't exec into devpod shell after creation.

pkg/binaries/binaries.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/upgrade_binaries.go
Heptio AWS authenticator binary version should be managed by jx. This PR implements this change.
To make this PR possible I've added `Archived` option to generic binaries installer. Also in order to make `installOrUpdateBinary` calls more refactoring-friendly, I've converted it to use options struct instead of list of arguments.
=> Heptio AWS authenticator version should be managed by jx

pkg/jx/cmd/create_addon_anchore.go
The latest version of Anchore brings a lot of improvements. Most useful to me, this also enables the NVD feed by default so that my projects' jars, gems, etc., can also be scanned for CVEs in addition to the existing operating system package checks.
=> Upgrade to Anchore chart 0.2.3 by default

pkg/jx/cmd/create_cluster_minikube.go
`jx create cluster minikube --verbose` does not currently do anything (although it does accept the option). So I've added a couple lines to create_cluster_minikube.go that check for the flag, and if its set, adds a couple verbose logging flags to the `minikube start` command.
This should help a bunch with debugging if Minikube cluster creation hangs for whatever reason.
=>  Allow for verbose logging on `jx create cluster minikube` 

pkg/jx/cmd/import.go
If organisation isn't specified neither as option, in TeamSettings or comes from existing repo it has defaulted to git username.
This created a mismatch if user choosed another organisation upon the question before push.
This is now fixed by asking user earlier.
Fixes #1275
=> fix: ask for organisation before replacing placeholders

pkg/jx/cmd/install.go
If you try to install jx with command `jx install --provider=eks` into cluster that has not been created using `jx create cluster eks`, eksctl and heptio-authenticator-aws will not be installed and `jx install` command is gonna to fail.
We should detected required binaries for EKS and perform installation in `jx install` command as well, not only in `jx create cluster eks`.
=> `jx install --provider=eks` should check for binaries dependencies

pkg/gits/provider.go
Right now running `jx install --git-server=https://bitbucket.org ...` fails because Git server kind is undefined. As a result of this jx tries to fall back to GitHub provider, which in turn fails because jx tries to invoke wrong API urls and passes BitBucket token to GitHub API.
`CreateProvider` function should be smart enough to figure out that if server is `https://bitbucket.org`, then BitBucket Cloud provider should be used even if server kind is unspecified.
=> BitBucketCloudProvider should be automatically detected from server URL

pkg/jx/cmd/common_install.go
Fixes https://github.com/jenkins-x/jx/issues/1893
Updates the JX cli update code in `common_install.go` so that we extract the jx binary into a temp folder first, and only overwrite the old JX binary if it extracted successfully.
Previously we were deleting the old JX binary first, before extracting the tar file. So if a corrupted tarball was downloaded and couldn't be extracted, the user was left without a working JX binary. This is now prevented.
Tested on both macOS and Linux.
=> fix(cli upgrade): Extract JX tarball to temp folder during cli upgrade.

pkg/jx/cmd/gc.go
jx gc outputs this:
....
Examples:
jx gc previews <- duplicate 
jx gc activities
jx gc helm
jx gc gke <- breaks the alphabetical order
jx gc previews
jx gc releases
....
=> Deleted duplicate option given at gc example

pkg/jx/cmd/create_cluster.go
Simple review of comments while reading jx code for another PR. Especially the "call jx init" is misleading at it is in fact called from `jx install `
=> docs: correct misleading comments in create cluster and formatting

pkg/jx/cmd/create_quickstart.go, pkg/quickstarts/model.go
Proposed fix for https://github.com/jenkins-x/jx/issues/1953
The `jx create quickstart` command prompts for selection even if the batch mode `-b` option is specified. This causes scripts to hang. This PR simply adds a check for batch mode and returns an error to avoid prompting.
=> Avoid prompting when creating from quickstart in batch mode

CONTRIBUTING.MD
With the change to using Go modules in Jenkins X (introduced in Go 1.11), JX builds using a version of Go <= 1.10 now fail. So I've updated the contributing docs to mention a minimum of Go 1.11 required to build
=> Update minimum Go version mentioned in Contributing.MD

pkg/jx/cmd/install.go
Both `create` and `install` were enforcing the use of a `nip.io` address with minikube. My initial PR only fixed the `create` part and not the part where it delegates to `install`.
fixes #2162
=> Use domain if specified

pkg/jx/cmd/init.go
Correct the URL for Chartmuseum
Since the changes to the chartmuseum layout last week, .build no longer has jenkins-x-platform updates in it
fixes #
=> fix: correct url for chart museum

pkg/gits/git_cli.go, pkg/jx/cmd/preview.go
For Jenkins pipeline builds triggered by PRs from Bitbucket Cloud, the `discoverGitUrl` logic currently pulls the incorrect repo from the pipeline workspace's git conf. `CHANGE_URL` should always contain the correct repo for git providers that have a Branch Source plugin, such as Bitbucket and GitHub, so pulling that env variable is now part of the git URL discovery logic. 
There's likely a similar gremlin lurking in promotion somewhere.
fixes #2174
=> fix:(preview) Try getting CHANGE_URL env variable for PRs, fixes #2174

pkg/jx/cmd/create_terraform.go
=> fix: using gke as the provider when generating the context name

pkg/gits/git_url.go
Addresses a bug uncovered by #2175 where pull request URLs are not parsed correctly.
Holding as WIP until I can test with the right builder image snapshot.
=> fix(git): Cleanup git URL parsing logic.

pkg/jx/cmd/shell.go
I had originally added
```bash
source <(jx completion bash)
```
to my `~/.bashrc`. But this made it slower to start shells for unrelated work, and when I deleted a GKE cluster, I was unpleasantly surprised to find that newly opened shells hung indefinitely, I suppose trying to contact a now-decommissioned API server.
Since there is already a `jx shell` command which sets up a prompt and all that, and this already pays the cost of contacting the API server, it seemed to make sense to automatically install shell completion there as well. I have tried to make this conditional on `bash-completion` being installed and JX completion not already loaded from another source, though the former is tricky to test.
I did not attempt to do the same for zsh as I am not familiar with it.
=> Automatically source <(jx completion bash) from jx shell

pkg/util/dirs_test.go
On OS-X the temp directory is defined as /tmp but this is a sym link to
/private/tmp which causes the test to fail.
so resolve symlinks before calling the test as a dirty quick fix
please test locally on ox-x as I have no access to this environment.
=> fix unit test on OS-X

pkg/jx/cmd/create_cluster_aws.go, pkg/jx/cmd/create_cluster_eks.go
Add `--tags` flag to `jx create cluster aws` and `jx create cluster eks` commands and pass that onto `eksctl` and `kops`.
Tested both of these changes by standing up a cluster for each.
no related issues
=> feat(aws): add tags flag to tag AWS resource

pkg/auth/auth_config.go, pkg/auth/auth_config_test.go, pkg/auth/config.go, pkg/auth/config_test.go, pkg/auth/server.go, pkg/auth/user_auth.go, pkg/auth/user_auth_test.go, pkg/gits/provider.go, pkg/gits/provider_test.go, pkg/io/config_readers.go, pkg/io/config_readers_test.go, pkg/io/config_writers.go, pkg/io/config_writers_test.go, pkg/jx/cmd/common_git.go, pkg/jx/cmd/create_chat_token.go, pkg/jx/cmd/create_token_addon.go, pkg/jx/cmd/create_tracker_token.go, pkg/jx/cmd/factory.go, pkg/jx/cmd/gc_previews.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/step_changelog.go, pkg/jx/cmd/step_split_monorepo.go, pkg/kube/constants.go, pkg/kube/metadata.go, pkg/util/environ.go, pkg/util/environ_test.go, pkg/util/maps.go, pkg/util/urls.go
Implements some building blocks for refactoring the current auth config, such as:
- Updates the config data model to reflect the current type of users and servers
- Implements readers for getting the config from a local file, environment variables and Kubernetes secrets
- Implements writers to store the config into a local file or Kubernetes secrets
- Tests which cover the added functionality
Also it implements  a fix for Git providers when created in the cluster with pipeline user 
and adds tests for git provider creation.
The Git provider fix is in the last commit.
fixes #
=> refactor(auth config): create the building blocks for refactoring the current auth config (updated data model, readers and writers)

pkg/jx/cmd/common_gke.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_terraform.go
For GKE, use the `default-environment-prefix` in preference to `cluster-name` if given. Also, clean up linter warnings.
fixes #2233
=> Use default-environment-prefix if provided

pkg/gits/git_url.go, pkg/gits/git_url_test.go
We need to handle URLS of the form
```
/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}
```
=> fix:(bitbucket) Handle some more idiosyncratic Bitbucket Server URLs

pkg/jx/cmd/common_team_settings.go, pkg/jx/cmd/create_devpod.go, pkg/jx/cmd/create_quickstart.go, pkg/jx/cmd/get_activity.go, pkg/jx/cmd/get_env.go, pkg/jx/cmd/get_issue.go, pkg/jx/cmd/get_preview.go, pkg/jx/cmd/get_release.go, pkg/jx/cmd/get_user.go, pkg/jx/cmd/get_workflow.go, pkg/jx/cmd/import.go, pkg/jx/cmd/step_post_install.go
A jenkins-x user administered with `jx edit userroles` and `jx controller role` doesn't have the
permissions to register CRDs. But the CRDs should have been registerad during install or upgrade anyway.
So the following commands don't register CRD anymore: `create devpod`, `create quickstart`, `import` and all `get`.
=> Fix: Allow non admin to execute various jx commands

pkg/jx/cmd/create_vault.go
Prompt the user for a vault name if in interactive mode an no vault name is specified.
fixes #
=> `create vault` prompts the user for a vault name if in interactive mode

Jenkinsfile
Copied from https://github.com/jenkinsci/jenkins/commit/9d269168a59f2863467bf17ebe1ed8800da04bd2. This would have failed on #2167, for example, as building that touches `go.mod` + `go.sum` to register new modules. The build succeeds, but is presumably nondeterministic as Go is just guessing at the versions to use each time. We want the author of the PR to commit these files and have that commit be tested.
=> Fail the build if there are uncommitted modifications

pkg/jx/cmd/cmd.go, pkg/jx/cmd/controller.go, pkg/jx/cmd/serve_buildnumbers.go
I previously added the new build numbers http endpoint at the top level cmd - its actually another controller, so just moving it underneath
that command to avoid cluttering the top level help/overview.
fixes #
=> fix(controller): Move build number controller under 'jx controllers'

Makefile
The reason for calling `docker system prune` should be fixed and it was
possibly the cause for failed builds on the node with messages like
```
Step 3/3 : COPY ./build/linux/jx /usr/bin/jx
No such container:
197a16d47ba8cd38249f75fc21d8996a8f1d08e4f358032b047cb6596afab30d
```
As we believe the initial issue is fixed in k8s 1.9 and higher we should
just remove this and see if it fixes the failed builds and that the
initial issue does not come back.
=> chore remove internal call to docker system prune for releases.

pkg/jx/cmd/get_build_logs.go
This is handy if you do `jx get build logs -p` and there is only one build
pending as otherwise you don't know whether it is for 'your' build, or
'your' build has finished and you are now tailing someone-else's build logs.
=> feat(buildlogs): Displays which build it is printing logs for

Makefile, pkg/jx/cmd/version.go, pkg/util/system/version.go, pkg/util/system/version_darwin.go, pkg/util/system/version_linux.go, pkg/util/system/version_test.go, pkg/util/system/version_unknown.go, pkg/util/system/version_windows.go
It is useful to know the OS version of the client in reports so this
change addes an "Operating System" column to the details listed by
`jx version`
tested on `Windows 10 Pro 1803`, `OSX` (some version), `Bash on Ubuntu on Windows` and `centos`, `debian` and `alpine` docker images.
=> feat(jx) add the OS details to `jx version` output

go.mod, go.sum, pkg/gits/provider_test.go, pkg/jx/cmd/common_commands_test.go, pkg/jx/cmd/common_import_test.go, pkg/jx/cmd/create_env_test.go, pkg/jx/cmd/uninstall.go, pkg/jx/cmd/uninstall_test.go, pkg/kube/env_test.go, pkg/tests/console_wrapper.go, pkg/tests/helpers.go, pkg/vault/vaultselector_test.go
This refactors the `go-expect` tests by hiding the actual `console` behind a wrapper. The wrapper will automatically assert that there are no errors as a result of the `Expect` clauses (previously almost-all errors were not assigned to any variable and just discarded).
Previously, if a `go-expect` test failed, the output would be:
```
panic: Test: TestUninstallOptions_Run_ContextSpecifiedViaCli_FailsWhenContextNamesDoNotMatch Timeout waiting for Terminal output: "\x1b[0G\x1b[2K\x1b[1;92m? \x1b[0m\x1b[1;99mEnter the current context name to confirm uninstalllation of the Jenkins X platform from the ns namespace: \x1b[0m\x1b[36m[? for help]\x1b[0m \x1b[?25l\x1b7\x1b[999;999f\x1b[6n\x1b8\x1b[?25h"
goroutine 56 [running]:
github.com/jenkins-x/jx/pkg/tests.expectNoTimeoutError.func1(0x0, 0x0, …
```
=> chore(tests): Refactored go-expect tests to support better error reporting

pkg/kube/activity.go, pkg/kube/activity_test.go, pkg/util/k8s.go, pkg/util/k8s_test.go
Current impl. converts any name-illegal chars into -, which could cause collisions and
therefore two pipelines to share the same build number ID space.
(there is also a bug in the current impl. that won't properly support upper case owner/repo/branch names).
fixes #
=> bug(controller buildnumbers): Encode PipelineActivity names to avoid collisions

pkg/gits/provider.go
This fixes error on promote without configured api tokens: POST https://api.github.com/repos/org/environment/pulls: 401 Bad credentials []
There is a bit of cleanup in related code.
Will also solve other cases of missing api tokens.
I think any additional tests would need to be integration tests. But I haven't written any since it's difficult for me to do without access to the test environment.
=> Fix: Create API token on promote if needed

pkg/jx/cmd/common_install.go, pkg/jx/cmd/import.go
This fixes a regression appearing with the introduction of prow that made
import and other commands calling ImportOptions.Run with another team
namespace than dev as the current namespace fail with:
`error: no environment with name 'dev' found`
=> fix: Import from non dev team namespace

pkg/jx/cmd/create_vault.go, pkg/jx/cmd/upgrade_ingress.go
Add a flag to skip the update of jx related resource in the 'upgrade ingress' command. This allows to run the command 
before installing the jx platform. For instance when exposing the Vault used to stored the credentials.
fixes #
=> refactor(upgrade ingress): add a flag to skip the update of jx related resources

pkg/jx/cmd/common_install.go
There are two `return` statements missing in Helm installation code. It leads to weird behavior if Helm initialization fails.
=> Fixed Helm installation error handling

pkg/jx/cmd/status_test.go
It seems that the test fails randomly with pegomock crashes due to concurrency.
fixes #
=> test(status): do not run the test in parallel

go.mod, go.sum, pkg/jx/cmd/create_addon_vault.go, pkg/jx/cmd/create_vault.go, pkg/jx/cmd/delete_vault.go, pkg/jx/cmd/install.go, pkg/kube/roles.go, pkg/vault/vault.go, pkg/vault/vault_test.go
Ensure that the created vault has a service account and a proper role binding
Starting with kubernetes 1.10, a cluster role binding is required for service account token review. Vault
uses this feature to authenticate with a Kubernetes service account.
fixes #
=> fix(vault): ensure that the created vault has a service account and a proper role binding

pkg/jx/cmd/get_applications.go
we forgot to include the environment name as part of the tree.
this change helps us test apps hit staging/production in the bdd tests
=> chore: expose results from `jx get app` in a better structure

pkg/gits/provider_test.go
`go-expect` tests don't work on windows. Please remember this
fixes #
=> chore(tests): Windows tests fail

pkg/jx/cmd/compliance_results.go
Signed-off-by: runzexia <runzexia@yunify.com>
I followed the documentation to run the compliance test before installing jx, and I failed in the test. When I run `jx compliance results` I can only get very little information, so I don't know where the problem is. Output TEST-CLASS is good for user positioning problems
The error message I got:
```
STATUS TEST
FAILED BeforeSuite
```
After adding TEST-CLASS
```
STATUS TEST TEST-CLASS
FAILED BeforeSuite Kubernetes e2e suite
```
fixes #
=> get more test info

pkg/io/secrets/secret_locations.go, pkg/io/secrets/secret_locations_test.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/extraValues.yaml, pkg/jx/cmd/factory.go, pkg/jx/cmd/install.go, pkg/jx/cmd/interface.go, pkg/kube/configmap.go
If `jx install --vault` is run, secrets get stored in vault. With this PR, it will now update the `jx-install-config` configmap with a new entry: `useVaultForSecrets: "true"` that tells the client that secrets are stored in vault (as opposed to on the file systme).
This can (and is) queried by the client to determine whether to load the secrets from vault.
=> feat(vault): Store a flag in the jx-install-config to denote if secrets are to be stored in vault

pkg/jx/cmd/controller_build.go, pkg/jx/cmd/controller_team.go, pkg/jx/cmd/step_helm_apply.go
so that `jx step helm apply` works more like `helm install releaseName dir`
=> fix: if no options specified lets reuse the arguments

pkg/jx/cmd/create_env.go
=> fix: using correct env.Name when creating environments in prow

pkg/apis/jenkins.io/v1/types_environment.go, pkg/gits/helpers.go, pkg/jx/cmd/controller_build.go, pkg/jx/cmd/controller_team.go, pkg/jx/cmd/edit_storage.go
lets refactor and add a reusable function too
=> fix: ensure git user + email is setup

pkg/cloud/gke/gcloud.go, pkg/io/secrets/secret_locations.go, pkg/io/secrets/secret_locations_test.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/extraValues.yaml, pkg/jx/cmd/factory.go, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go, pkg/jx/cmd/interface.go, pkg/jx/cmd/mocks/factory.go, pkg/jx/cmd/mocks/matchers/versioned0_interface.go, pkg/jx/cmd/mocks/matchers/versioned1_interface.go, pkg/jx/cmd/mocks/matchers/versioned_interface.go, pkg/jx/cmd/step_helm_apply.go, pkg/jx/cmd/uninstall.go, pkg/util/files.go, pkg/vault/constants.go, pkg/vault/vault_client.go
- Breaks the install command in smaller methods in oder to understand the flow
- Make the cloud provider configuration during the install more self contained in dedicated method
- Extract the helm values configuration and helm values file creation
- Separate the secrets files from helm values files
- Extract the GitOps logic in separate method
- Ensure that the GitOps secrets.yaml file is stored in Vault
- Ensure that secrets.yaml is fetch from vault when environment chart is installed
fixes #
=> refactor(install): break the install command in smaller methods and make the cloud providers configuration more self contained

pkg/jx/cmd/import.go
When re-importing a previously imported app, the charts directory already exsists and is named correctly, so don't try to rename it to itself.
fixes #
=> fix(applications): Don't try to name the charts dir to the same name

pkg/gits/git_cli.go
If you try to do a jx import, or jx delete app (new PR) it tries to do a pull request to the environment repos. The URLs for these repos are HTTPS, meaning that if you haven't set up a git credential helper, you will get an error: `fatal could not read Username for `https://github.com`: No error: exit status 128
This is because the git cli will go "you're not authenticated" and prompt you for a username password, but because we don't attach stdin/out to the git process, it fails.
This error prompts you to do the better thing - check that you have the git credential helper set up so it will automatically pass your creds over to your git repo when doing a write operation.
fixes #
=> fix(git): Handier error message if you get errors pushing to https

pkg/jx/cmd/uninstall.go, pkg/jx/cmd/uninstall_test.go
- [ x] Change is code complete and matches issue description.
- [ x] Change is covered by existing or new tests.
fixes #
=> test(uninstall): make uninstall command test state independent

pkg/jx/cmd/update_webhooks.go
#2113 introduced a command but this bit of help text seems to have been forgotten.
As an aside, I find the behavior when `--repo` is missing to be odd. It is enumerating all repositories in the org, then updating the per-repo webhook. Why would you not simply update the _organization_ webhook (once)? Is it because some orgs in the repo might have unrelated endpoints?
=> Why would the help for `jx update webhooks` claim it is not implemented?

pkg/jx/cmd/common_team_settings.go, pkg/jx/cmd/controller_team.go, pkg/jx/cmd/delete_team.go
The code tries to use the admin namespace as returned by kube.GetAdminNamespace(), but this appears to just return
the current namespace rather than finding the admin namespace - i.e. it can change!
Fixed by being explicit at all times about the admin NS to use. But I think there is another todo to sort out the current
'TODO' in kube.GetAdminNamespace():
`// TODO find the admin namespace via a label on the current dev namespace - or use current?`
fixes #
=> bug(create team): Update status on the Team CRD in the admin namespace

pkg/jx/cmd/status.go
=> fix: removed additional 'Needs more' in jx status output

pkg/jx/cmd/common_git.go, pkg/jx/cmd/step_split_monorepo.go, pkg/jx/cmd/upgrade_extensions.go, pkg/jx/cmd/upgrade_extensions_repository.go
- Move some functions from `step_split_monorepo` to `common_git`. They were misplaced.
- gits.ParseGitURL doesn't recognize `github.com/org/repo`, pass `org/repo` instead.
This should fix build issues seen at https://github.com/jenkins-x/jenkins-x-extensions/pull/30
fixes #
=> Fix jx upgrade extensions repository

pkg/auth/auth_config.go, pkg/jx/cmd/install.go
=> refactor(install): revamp the git auth configuration and make the organization selectable for environment repositories

pkg/jx/cmd/add_app.go, pkg/kube/namespaces.go, pkg/kube/namespaces_test.go
* also add a default repository
fixes #
=> fix: `jx add app` error if no repo defined

pkg/jx/cmd/create_addon_istio.go
- [?] Change is covered by existing or new tests.
Trying to `jx create addon istio` on a windows system fails because Windows is using the zipped archive. The zipped archive is unzipped to the outputDir, which is `outputDir := filepath.Join(binDir, "istio-"+latestVersion.String())` This causes the unzipped Istio resources to be created in istio-1.0.4\istio-1.0.4\ instead of isitio-1.0.4\ when jx is trying to install the resources it is looking in istio-1.0.4\ and not in istio-1.0.4\istio-1.0.4\ and therefor fails to install istio. As also for the  UnTargzAll method the Unzip method needs to write the files to the binDir and not the outputDir.
This is my first PR and first golang code. Please be gentle.  Not sure if this code was covered by existing unit tests, but I could not find any. I …
=> fix(istio-addon): changed directory that istio is unziped in from outputDir to binDir.

pkg/jx/cmd/compliance_status.go
=> fix(compliance): print a more user friendly message in the status command when no compliance is found

pkg/jx/cmd/create_devpod.go, pkg/jx/cmd/status.go
1) Prevent `jx create devpod` from exiting with `127` when `yum` or `apt-get` is not available to install bash completion packages.  
2) If `yum` is not available, attempt to use `apt-get` to support debian based images
fixes #2496
=> fixes(#2496) add support for bash completion on debian devpod images

pkg/jx/cmd/create_git_api_token.go, pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_platform.go, pkg/kube/constants.go
This secret does not seems to be used anymore by the pipeline.
Remove the old and unused jenkins-git-credentials secret from code. This is also the cleanup from the platform https://github.com/jenkins-x/jenkins-x-platform/pull/4502
fixes #
=> fix(secrets): clean up the old jenkins-git-credentials secret

pkg/jx/cmd/create_devpod.go
We need to redirect both stdout and stderr to /dev/null so that we don’t see an error when one of them doesn’t exist
fixes #
=> fix: hide the error about missing apt-get/yum

Jenkinsfile, pkg/jx/cmd/step_git.go, pkg/jx/cmd/step_git_envs.go, pkg/version/info.go
=> fix(Jenkinsfile): cleanup the old github credential from Jenkinsfile

pkg/jx/cmd/common_install.go
On a clean system with no previous jx install, there will be no existing K8S context. During the auto-installation of helm, `helm init` is run, which tries to install the tiller server
into the cluster and will fail because it hasn't been created yet. Since the actual requirement at this stage of the process is _only_ to install the helm client, and the (client-side)
secrets plugin, Run configure the helmer for client only mode to avoid trying to install tiller. Later, when the cluster has been created tiller will still get installed via a later
`Helmer.init()` call.
fixes #2507
=> bug(install): use client-only mode to install the Helm secrets plugin.

pkg/jx/cmd/common.go, pkg/jx/cmd/delete_team.go
JXClient, KubeClient, and namespaces are all cached for efficiency, but after switching namespaces these values might
be wrong. Clear them all out when changing namespaces, which will force the various setup methods in CommonOptions
(e.g. JXClient()) to create new ones, and recalculate dev namespaces etc.
fixes #2451
=> bug(delete team): Clear cached clients & namespaces when switching namespaces

pkg/jx/cmd/get_eks.go
Added verbose flag to `eks get` command.
=> Added verbose flag to `eks get` command

pkg/config/admin_secrets.go, pkg/config/types.go, pkg/expose/exposecontroller.go, pkg/jx/cmd/create_addon_prometheus.go, pkg/jx/cmd/install.go, pkg/jx/cmd/step_helm_apply.go, pkg/util/auth.go, pkg/vault/constants.go, pkg/vault/helpers.go, pkg/vault/vault_client.go, pkg/vault/vault_path.go
=> feat(install): store the amdin secrets in vault and to not print the admin password in logs if vault is enabled

pkg/jx/cmd/create_env.go
Right now you cannot specify Git organization/owner in `jx create env` command. Fixed this. Owner option (if set) is now automatically respected during Git repository creation process.
=> Added --git-owner flag to `create env` command

pkg/cloud/amazon/eks.go, pkg/jx/cmd/create_cluster_eks.go
If EKS cluster creation process is interrupted or if cluster with given name already exists, there will be CloudFormation stack in ROLLBACK_COMPLETE state left. Such dead stack prevents eksctl from creating cluster with the same name. This is common activity then to remove stacks like this and this function performs this action.
This PR detects such dead stacks and deletes them before creating the cluster with eksctl.
Also we should try to detect that cluster with given name exists before running eksctl, otherwise we end up with CloudFormation stack being initialized and failing after some time. If we know that cluster with given name already exists, we should just detect this fact and inform user about it as soon as possible. This PR implements this as well.
=> EKS cluster creation should deal with rolled back stacks

pkg/jx/cmd/delete_eks.go
Minor text change to  make `jx delete eks` command help output in sync with other `jx delete` commands.
=> Changed "Delete" -> "Deletes" in help for `jx delete eks`

pkg/gits/git_repo.go, pkg/jx/cmd/common_git.go, pkg/jx/cmd/install.go
Hi @jstrachan . Here is the missing Git provider kind option we've been discussing earlier today.
=> Added Git provider kind option to `jx install`

pkg/jx/cmd/promote.go
`Could not find Jenkins URL: services "jenkins" not found in namespace jx`
instead of 
`Could not find Jenkins URL services "jenkins" not found in namespace jx`
=> Better error message

Jenkinsfile
Amends https://github.com/jenkins-x/jx/pull/2257 analogously to https://github.com/jenkinsci/jenkins/pull/3832.
=> Simpler check for local file modifications

pkg/gits/provider.go
When performing `jx upgrade ingress`, an empty selection is presented to the user (because `userName` is passed as `nil`)
fixes #2389
=> fix(ingress): Don't use empty strings in possible organisations

pkg/gits/github.go, pkg/gits/provider.go, pkg/jx/cmd/update_webhooks.go, pkg/jx/cmd/upgrade_ingress.go
`jx upgrade ingress` wasn't correctly setting the webhooks in github.
It was incorrectly checking whether the webhook matched the _new_ URL (that you were trying to set it _to_)
fixes #2018
=> fix(ingress): github webhooks weren't being updated on `jx upgrade ingress`

pkg/util/downloads.go, pkg/util/downloads_test.go
using the Github API unauthenticated will impact the low (60/hour) API limits. This can affect teams working behind a common IP address.
We can find the latest release by getting the redirect issues by github when trying to GET https://github.com/org/repo/releases/latest and use this instead.
This still tries to use the API as a fallback if it does not succeed.
fixes #2062
=> fix(install): use http redirects to get latest github releases

go.mod, go.sum, pkg/jx/cmd/create_addon_knative_build.go, pkg/jx/cmd/delete_addon_knative_build.go, pkg/jx/cmd/upgrade_addon_prow.go, pkg/jx/cmd/upgrade_addons.go
the latest prow rebase requires a knative build 0.2.x install so lets check and upgrade if not on a new enough version.  This also handles an issue that the knative CRD cannot be upgraded so we need to reinstall instead.
=> feat(upgrade) add a command to upgrade prow which handles if knative build is not on 0.2.x

pkg/helm/helm_cli.go, pkg/helm/helm_cli_test.go, pkg/helm/helm_template.go, pkg/helm/interface.go, pkg/helm/mocks/helmer.go, pkg/helm/mocks/helmer_fake.go, pkg/jx/cmd/common_helm.go, pkg/jx/cmd/create_addon_ambassador.go, pkg/jx/cmd/create_addon_cloudbees.go, pkg/jx/cmd/create_addon_sso.go, pkg/jx/cmd/create_addon_vault.go, pkg/jx/cmd/edit_extensionsrepository.go, pkg/jx/cmd/init.go, pkg/jx/cmd/install.go, pkg/util/commands.go
If you were using a password protected helm repo (`jx create addon cloudbees`) and enterred the username/password incorrectly (or some other error occurred), then the password was printed out to the command line in plaintext.:
```
? CloudBees Preview password [? for help] **
Adding missing Helm repo: cb https://chartmuseum.jx.charts-demo.cloudbees.com
error: failed to add the repository 'cb' with URL 'https://chartmuseum.jx.charts-demo.cloudbees.com': failed to run 'helm repo add cb https://chartmuseum.jx.chart
s-demo.cloudbees.com --username myusername --password mypassword' command in directory '' <snip>
```
This fix will replace it with asterisks
```
? CloudBees Preview password [? for help] **
Adding missing Helm repo: cb https://chartmuseum.jx.charts-demo.cloudbees.com
error: failed …
```
=> fix(helm): Passwords for helm repos were logged in plaintext to the command line

pkg/jx/cmd/get_applications.go
This fixes that the details about each application from `jx get applications` doesn't align to the headers of the correct environment unless all application are running in all environment.
Also environments without any running apps (typically edit environments) are now skipped.
So instead of `jx get apps -pu` giving:
```
APPLICATION               EDIT   PRODUCTION STAGING TEST
jx-aws-cluster-autoscaler 0.9.0
jx-charter-trailer        1.0.39 1.0.40     1.0.40
jx-meta-airhotel-control  0.0.15
jx-sms                    1.0.20 1.0.20
selenium-grid-exporter    7
```
The output becomes:
```
APPLICATION               PRODUCTION STAGING TEST
jx-aws-cluster-autoscaler 0.9.0
jx-charter-trailer        1.0.39     1.0.40  1.0.40
jx-meta-airhotel-control             0.0.15
jx-sms …
```
=> Correct aligment in jx get applications

pkg/buildnum/build_num_gen.go, pkg/jx/cmd/serve_buildnumbers.go, pkg/jx/cmd/start_pipeline.go, pkg/jx/cmd/step_bdd.go, pkg/jx/cmd/step_next_buildnumber.go, pkg/kube/activity.go, pkg/kube/activity_test.go, pkg/kube/pipeline_cache.go, pkg/util/strings.go
so we don't have to wait to List all PipelineActivity resources every time we need a build number; instead we only do it on startup of the build number generator
fixes #
=> fix: add caching into the build number generator

pkg/jx/cmd/preview.go
Adds a `--no-comment`flag to the `jx preview` command which in turn determines whether 
Any tests I can write/append here?
fixes #2664
=> feat(cli): add --no-comment flag to `jx preview` cmd

pkg/kube/activity.go
Trying to build https://github.com/jenkins-x/oauth2_proxy, it fails
eg:
```
time="2019-01-14T14:38:19Z" level=error msg="Unable to get next build number for pipeline jenkins-x/oauth2_proxy/master" error="PipelineActivity.jenkins.io \"jenkins-x-oauth2_proxy-master-1\" is invalid: metadata.name: Invalid value: \"jenkins-x-oauth2_proxy-master-1\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```
=> fix(buildnum): Services fails on repos with underscores

pkg/jx/cmd/controller_team.go, pkg/kube/teams.go, pkg/kube/teams_test.go
Various commands need to know where the admin namespace is, this change
now records the admin namespace for a team as an annotation on the team
It will also update any existing teams with the annotation when the team
controller is run.
fixes #2662
=> feat(teams) store the admin namespace in the team

charts/jx/templates/clusterrolebinding.yaml, charts/jx/templates/cronjob.yaml, charts/jx/templates/deployment.yaml, charts/jx/templates/rolebinding.yaml, charts/jx/templates/serviceaccount.yaml, charts/jx/values.yaml, pkg/jx/cmd/common.go, pkg/jx/cmd/delete_preview.go, pkg/jx/cmd/gc_previews.go, pkg/jx/cmd/preview.go, pkg/jx/cmd/preview_test.go, pkg/kube/constants.go, pkg/kube/env.go, pkg/kube/env_test.go
Instead of just deleting the Environment resource and the associated namespace,
deleting a preview should also delete (purge) the helm release:
- allows to run pre/post-delete helm hooks
- if using std helm - without the template or no-tiller flag - it avoids leaving broken releases behind
Our use-case is that we have charts using hooks to register and cleanup cloud resources. the registration part works well when the chart is deployed in a preview environment, but the delete hooks are never called, because right now the helm release is never deleted.
Calling helm in the gcpreviews jobs also has impacts on the RBAC setup, because if the team setting is to use a local tiller, then the job will need to have sufficient rights to create/delete resources.
To handle this, I added a new feature …
=> fix(preview): when deleting the preview, also purge the helm release

pkg/jx/cmd/start_protection.go, pkg/jx/cmd/start_protection_test.go, pkg/prow/config/branch_protection.go
Oops, told @agentgonzo this wasn't needed anymore, when in fact it is :-)
fixes #
=> fix: re-add support for `jx start protection`

pkg/users/git_test.go
This means we use the mock, not the real thing
Part of the fix for #2741
=> fix: don’t create a new JXClient, use the existing one

pkg/collector/git_collector.go
so that we store persistent logs correctly in git
=> fix: broken git file location for Collector

pkg/jx/cmd/common.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/get_build_logs.go, pkg/jx/cmd/promote.go
which does not need the build number to be included
=> fix: allow `jx get build logs jobName` to be used with prow

pkg/kube/git_services.go, pkg/kube/git_services_test.go
we don't find the git service kind due to the secret name not having a `-github-ghe` prefix when we create clusters via `jx create cluster gke ... --git-provider-url`
=> fix: add test case and fix for failure in BDD create cluster tests

pkg/jx/cmd/step_bdd.go
Not all BDD tests that use `jx step bdd` may be creating a `reports` directory and the command currently fails if it does not exist.
=> Make bdd reports optional

pkg/buildnum/build_num_gen.go, pkg/buildnum/http_build_num.go, pkg/buildnum/interface.go, pkg/buildnum/mocks/build_num.go, pkg/kube/pipeline_cache.go
Add two new HTTP endpoints, `/health` and `/live` to be used as K8S liveness & readiness probes. (Separate PR/repo to make use of these).
fixes #
=> feat: add liveness & readiness probe endpoints to build number service.

pkg/jx/cmd/install.go
As in @kris-nova’s [video](https://youtu.be/QdwtefUsoNI?t=3425), it might be useful to mention this tool. See also https://github.com/jenkins-x/jx-docs/pull/724.
=> Mention `jx shell` during installation

pkg/jx/cmd/common_buildpacks.go, pkg/util/pom_flavour.go, pkg/util/pom_flavour_test.go
I've added Java 11 build pack detection for Maven projects.
Also simplified POM flavor detection logic by removing conditional branches that are never executed.
=> Added Java11 POM detection

pkg/binaries/binaries.go, pkg/jx/cmd/common_install.go, pkg/jx/cmd/upgrade_binaries.go
IMHO jx should control the `kubectl` version it is using the same way it controls `eksctl` and `heptio-authenticator-aws` versions. We should try to avoid pulling random latest version of binaries dependencies. Instead jx should download version which is "jx-certified" and tested against given version of jx.
This PR locks `kubectl` version and manages it using the same way as `eksctl` and `heptio-authenticator-aws` are managed. It means that you can execute `jx upgrade binaries` command to upgrade your kubectl version to the version that your current jx cli is expecting.
=> jx should control kubectl version it is using

pkg/jx/cmd/create_addon_cloudbees.go, pkg/jx/cmd/delete_addon_cloudbees.go, pkg/kube/pki/certificate.go
`jx create addon cloudbees --sso` now waits for the TLS configuration to be ready (certificate issued for the service).
Output:
```
$ jx create addon cloudbees --sso
Configuring single sign-on...
? Domain: my-domain.com
? Dex URL: https://dex.sso.my-domain.com
Looking for cert-manager deployment in namespace cert-manager...
Updating Helm repository...
Helm repository update done.
Waiting for cert: tls-core...
Ready Cert: tls-core
Addon installed successfully.
jx cloudbees Open the app in a browser
``` 
fixes #2876
=> feat(certs): wait for certificate issuer on create addon cb

pkg/jx/cmd/step_changelog.go, pkg/kube/crds.go
Added `all` category to all the CRDs so that jenkins-X resources are displayed when `kubectl get all` is done. 
I couldn't find any e2e tests where I could add a test for checking output of `kubectl get all` having some of the jenkins-X resource hence I kept the second checkbox un-checked. 
fixes https://github.com/jenkins-x/jx/issues/2827
=> refactor: added category 'all' to CRDs

pkg/jx/cmd/step_pre_extend.go
Currently, only the last extension defined in the repository is added to
the PipelineActivity by `jx step pre extend`.
`PostExtensions` is currently overwritten for each of the extensions defined in the repository YAML so only the last one is actually applied.
=> Add all extensions

pkg/jx/cmd/step_bdd.go
Make it easier to run the BDD tests locally by allowing dependencies to be installed
=> Support passing --install-dependencies to bdd tests

pkg/jx/cmd/create_terraform.go
the --environment-git-owner flag on `jx create terraform` was not being used to create the environment repos
=> fix(import): Honour the --environment-git-owner flag doing create terraform

pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_platform.go, pkg/kube/activity.go, pkg/kube/activity_test.go, pkg/kube/sourcerepository_impl.go
we were using the PipelineActivity Name as the repo name (which is actually
the orgName-repoName) which ended up with a double org name also fixed up
logic that was losing the actual error when trying to create a
SourceRepository
=> fix: various issues around SourceRepository

pkg/jx/cmd/create_terraform.go
Removed unnecessarily import `GitRepositoryOptions` as it is a part of `Install
Options`
https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/install.go#L59
fixes #
=> chore(create): InstallOptions already had GitRepositoryOptions embedded

pkg/jx/cmd/create_cluster.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/create_terraform_test.go
This adds the similar --cluster-name (shorthand: -n) flag that create cluster
and create terraform gke have.
This allows compatibility with the jx step bdd config files that specify
a cluster name, eg https://github.com/jenkins-x/jenkins-x-versions/blob/master/jx/bdd/prow.yaml#L2
=> feat(terraform): Added --cluster-name and --cloud-provider

pkg/jx/cmd/step_bdd.go
The -n flag can't be specified in create terraform so use the longhand version
Also expand environment variables in the arguments list
=> chore(bdd): don't use shorthands in tests

pkg/jx/cmd/create_cluster_eks.go
A simple addition of the volume size option of `eksctl` when creating a eks cluster.
fixes #
=> Adding Node Volume Size to EKS command

pkg/cloud/gke/gcloud.go, pkg/cloud/gke/gcloud_test.go, pkg/cloud/gke/vault/naming.go, pkg/cloud/gke/vault/vault_backend.go, pkg/jx/cmd/common_bucket.go, pkg/jx/cmd/create_vault.go, pkg/jx/cmd/delete_vault.go, pkg/jx/cmd/factory.go, pkg/jx/cmd/install.go, pkg/kube/cluster/cluster.go, pkg/kube/cluster/cluster_test.go, pkg/kube/vault/vault.go, pkg/vault/constants.go
The short cluster name consists of the first 16 characters of the full cluster name. The reason for
this shortcut is to avoid exceeding the GCP limits on resources name such as bucket and keyring.
fixes #
=> feat(vault): prefix the system vault and all the related resources with the short cluster name

pkg/jx/cmd/step.go, pkg/jx/cmd/step_verify.go, pkg/jx/cmd/step_verify_pod.go, pkg/jx/cmd/step_verify_pod_test.go
Output the status of all kubernetes pods, i.e. running, successful, failed etc. The idea being that this can then be used by the BDD tests to determine if all CronJobs have been success and hence fix issue 2806.
To run:
`jx step verify pod`
Also to create a log file with the log output from any failed pods:
`jx step verify pod --debug`
Relates to #2806
=> (feat) Add `jx step verify pod` to output status of all kubernetes pods

pkg/jx/cmd/common_helm.go
It clones the repository if not folder exists at all or something goes wrong with the fetching.
fixes #
=> fix: check if jenkins-x-versions repository is already up to date, if not fetch the latest version

pkg/gits/bitbucket_cloud.go
Bitbucket webhook on project import was missing triggers for PR events - created, updated,rejected and fulfilled(merged) 
None
fixes #2238
=> fix: Add webhook triggers for PR events in bitbucket

pkg/jx/cmd/delete_application.go
fix delete application so that it tries to intelligently figure what org the associated repo belongs to so that the `sourcerepository` crd object it is associated with can be deleted
When deleting an application, `jx` should remove the `sourcerepository` metadata associated with it.  To do this, it needs to know the organization name (because the `sourcerepository` objects are named `<org>-<reponame>`)
I am not completely happy with this approach, and am creating this PR to solicit some feedback and ideas on how this could be better solved (even if it means revisiting the way we name the object metadata in the `sourcerepository` crd)
It might be worth adding a `--force` option to `jx delete` that could be used to clean up projects that are left in an inconsistent state.  For example, in …
=> chore: fix delete application so that it tries to intelligently figure what org the associated repo belongs to

go.mod, go.sum, pkg/kpipelines/syntax/pipeline.go, pkg/kpipelines/syntax/pipeline_test.go
We were using the working dir from the podTemplate, and we weren't mashing together the command and args specified in the YAML into something suitable for `/bin/sh -c`. More work needed on setting working dir, but this unblocks things for the moment.
cc @dwnusbaum 
n/a
=> fix(kpipelines): Override workspace from podtemplate, fix args generation

pkg/jx/cmd/import.go
userAuth is nil when importing a Github repo
=> Check userAuth is not nil

pkg/jx/cmd/import.go, pkg/jx/cmd/import_test.go
`jx import https://github.com/orga/myrepo` should automatically set the
organisation to be 'orga'. If an additional `--org orgb` is specified,
this should be ignored.
fixes #3073
=> fix(import): use the org from a github repo when importing

pkg/jx/cmd/step_next_version.go
this change allows us to use `jx step next-version --filename package.json --tag` in a pipeline to update the package.json and optionally the `Chart.yaml` and then push the commit to a tag
=> fix: jx step next-version update the package.json

pkg/config/project_config.go, pkg/jx/cmd/controller_pipelinerunner.go, pkg/jx/cmd/step_create_task.go
if we pass a prow context name lets use it to try discover a custom
pipeline YAML file
=> fix: allow a context to be used to run a different pipeline YAML file

pkg/jx/cmd/import.go
With pull request #2771 git repo was created before default options where read from team settings. The most severe effect i.m.h.o. being that that the setting to make the repository private didn't take effect. But also having to choose organisation despite it being set in Team Settings was annoying.
This PR fixes these regressions.
=> fix (import) : Defaults from team settings for create quickstart and spring

pkg/jx/cmd/get.go, pkg/jx/cmd/get_quickstarts.go
Adds a new command `get quickstarts` that will output a list of all available quickstart types.
```
>$ ./build/jx get quickstarts
jenkins-x-quickstarts/golang-http
jenkins-x-quickstarts/node-http
jenkins-x-quickstarts/spring-boot-rest-prometheus
jenkins-x-quickstarts/rails-shopping-cart
jenkins-x-quickstarts/spring-boot-http-gradle
jenkins-x-quickstarts/android-quickstart
jenkins-x-quickstarts/dlang-http
jenkins-x-quickstarts/python-http
jenkins-x-quickstarts/rust-http
jenkins-x-quickstarts/open-liberty
jenkins-x-quickstarts/node-http-watch-pipeline-activity
jenkins-x-quickstarts/spring-boot-watch-pipeline-activity
jenkins-x-quickstarts/angular-io-quickstart
jenkins-x-quickstarts/vertx-rest-prometheus
jenkins-x-quickstarts/react-quickstart
jenkins-x-quickstarts/aspnet-app …
```
=> feature:  add new command 'get quickstarts' that returns a list of available quickstarts

pkg/util/files.go, pkg/util/files_test.go
The utility function `util.DeleteDirContents()` didn't seem to be deleting anything - seems the filepath Glob was wrong.
fixes #
=> bug: fix directory deletion, add test.

pkg/jx/cmd/upgrade.go, pkg/jx/cmd/upgrade_crd.go
Introduce a new `jx upgrade crd` command that will make sure all jenkinsx CRDs are registered in Kubernetes, and updated to the latest version.
This can be used if you want to upgrade the jenkins-x-platform charts without using the `jx upgrade platform` command, for example using a tool like https://github.com/roboll/helmfile, but still making sure you get the latest CRDs registered.
=> feat(upgrade): new 'upgrade crd' cmd to upgrade all jenkinsx CRDs

pkg/jx/cmd/create_addon_ambassador.go
Ambassador addon ignored the -f flag
This makes the ambassador add on respect the -f flag
=> Make Ambassador add on does respect the -f flag

pkg/jx/cmd/common_helm.go
We were discarding secrets passed to `installChartOrGitOps` if we weren't using gitops. Which was bad. So don't do that.
fixes #3190
=> fix: Don't discard secrets in non-gitops helm chart install

pkg/jx/cmd/create_addon_flagger.go, pkg/jx/cmd/create_addon_istio.go
feat: print the ip of the Istio gateway ingress service
after installing the Istio addon
Note that if the kubernetes provider doesn't support LoadBalancer it will wait for one minute to print the ip of the service
fixes #
=> feat: create Istio gateway for canaries

pkg/flagger/flagger.go, pkg/jx/cmd/get_applications.go
Flagger creates new deployments to manage canaries and they get printed in `jx get apps`
```
$ jx get apps
APPLICATION                  STAGING PODS URL                                                 PRODUCTION PODS URL
croc-hunter-jenkinsx         0.0.126 1/1  https://croc-hunter-jenkinsx.jx-staging.example.com 0.0.126         http://croc-hunter-jenkinsx.jx-production.example.com
croc-hunter-jenkinsx-primary
```
fixes #
=> Ignore flagger canary auxiliary deployments from get apps

pkg/jx/cmd/delete_devpod.go
when creating the devpod, the username is converted to a "valid kubernetes name".
but when deleting it, the same conversion was missing. so people could not easily delete a devpod they created with default values.
also fixing a missing error check, and an error message
=> fix(devpod): 'delete devpod' was not using the right pod name

go.mod, go.sum, pkg/gits/bitbucket_server.go, pkg/gits/bitbucket_server_test.go, pkg/gits/test_data/bitbucket_server/webhooks.json, pkg/jx/cmd/update_webhooks.go
Improve support for web hooks for Bitbucket Server:
* Implement `ListWebHooks`
* Implement `UpdateWebHook`
* On `CreateWebHook`, make sure there isn't an existing web hook with the same URL.  Prevents duplicates.
* Random fix: pass in web hook ID when updating web hooks via `jx update webhooks`.  Without this, it is possible that the `UpdateWebHook` method may not find the appropriate web hook to update.
I specifically tested re-importing a project and I did not get a duplicate web hook, but instead got the log message `Already has a webhook registered for...`
None that I could find.
=> Improve Bitbucket server webhook support

pkg/jx/cmd/step_env_apply.go
This pr will expose the flag to override the release name used when using the command `jx step env apply`.
Currently the release is set to jenkins-x and there is no way to override it, `jx helm apply`.
The flag named used here is the same from `jx helm apply`
fixes #3215
=> include flag to enable passing the release name to cli.

pkg/jx/cmd/step_create_task.go
we can then pass the `version` in as a pipeline parameter for easier interop with tools like kankio
=> fix: add support for tagging git before we trigger tekton releases

pkg/jx/cmd/get_build_logs.go
Got annoyed at `jx get build logs` giving the same message when it can't find any builds, regardless of whether it's looking for Knative Builds or Tekton pipelines. So...
n/a
=> chore: Different message for no Tekton pipelines logs found

pkg/jx/cmd/get_build_logs.go, pkg/tekton/pipeline_info.go, pkg/tekton/pipeline_info_test.go, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/activity.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipeline.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipelineresources.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipelinerun.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/taskruns.yml, pkg/tekton/test_data/pipeline_info/completed-from-build-pack/tasks.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/activity.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipeline.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipelineresources.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipelinerun.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/structure.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/taskruns.yml, pkg/tekton/test_data/pipeline_info/completed-from-yaml/tasks.yml
When a PipelineRun has finished and its pods have been GC'd, we should
just ignore it for the purposes of `PipelineActivity` and `jx get
build logs`.
n/a
=> fix: Don't keep trying to get pods for completed PipelineRuns

pkg/jx/cmd/init.go
There is only one listener created on EKS NLB controlled by `--http=true|false` option for `jx install --provider eks` command. This causes problems when creating cluster in EKS with a single TCP 80 listener enabled on NLB and then trying to do `jx upgrade ingress --cluster` to enable TLS on nginx ingresses with domain name. The ingress upgrade then fails, because there is no TCP 443 listener on NLB.
There is a hack workaround described in https://github.com/jenkins-x/jx/issues/3079 to make it work, but it requires manual steps to patch Nginx controller service and fix EC2 security groups which is not ideal experience. 
I have successfully installed Nginx ingress manually after creating new EKS cluster with `eksctl create cluster` command with the following values, so I am confident you …
=> fix: (init.go) enable both  ports for EKS NLB

pkg/jx/cmd/common_git.go, pkg/jx/cmd/controller_build.go, pkg/jx/cmd/controller_pipelinerunner.go
as the secrets can get created after the pipelinerunner starts and can change at any time
=> fix: run 'jx step git credentials' on each pipeline trigger

pkg/jx/cmd/install.go, pkg/kube/vault/vault_factory.go
Retry with an exponential backoff to authenticate with the kubernetes auth backend.
It usually takes about 10 seconds to initialize the auth backends after the vault was unsealed.
fixes #
=> fix: retry with an exponential backend to authenticate with the kubernetes auth backend

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_test.go
As described in [Issue 3251](https://github.com/jenkins-x/jx/issues/3251), `jx create cluster gke` needs some validation of the `--cluster-name` / `-n` option. This PR introduces validation which checks against [Google's current requirements](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create) for cluster names. 
N/A
fixes #3251
=> Issue 3251: Cluster name validation for jx create cluster gke

pkg/tekton/pipeline_info.go, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_internal_test.go, pkg/tekton/test_data/pipeline_info/from-build-pack/pods.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/taskruns.yml, pkg/tekton/test_data/pipeline_info/from-build-pack/tasks.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pods.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/taskruns.yml, pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/tasks.yml, pkg/tekton/test_data/pipeline_info/from-yaml/pods.yml, pkg/tekton/test_data/pipeline_info/from-yaml/taskruns.yml, pkg/tekton/test_data/pipeline_info/from-yaml/tasks.yml
Ignore the branch name, I changed directions. =) But basically, we're mangling stage names to RFC1135 strings for use in labels, which created some problems with trying to get logs or activity for stages with upper-case letters, spaces, etc, so let's map that better. Also make the duplicate stage name validation case-insensitive.
n/a
n/a
=> fix(tekton): Logs and activity should work with upper-case stage names

pkg/jx/cmd/create_cluster_gke.go
As described in [Issue 3282](https://github.com/jenkins-x/jx/issues/3282), `jx create cluster gke` now has validation for the cluster name provided via either `--cluster-name` or `-n`. But the wording is all wrong and it's bothering me.
N/A
fixes #3282
=> fix: Issue 3282 improve error message

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/no_pipeline_config/jenkins-x.yml
Previously, running `jx step create task --pack=none` with a `jenkins-x.yml` that did not have a `pipelineConfig` section would fail with a nil pointer error. This PR changes that to a controlled failure with an error message.
/assign @abayer 
N/A
=> fix(tekton): Improve error handling when PipelineConfig is nil

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml, pkg/tekton/syntax/constants.go, pkg/tekton/test_data/pipeline_info/from-build-pack-init-containers/structure.yml
Fixes the issue @jstrachan stumbled over w.r.t. build pack stage name and `jx get build logs` and `PipelineActivity` population for real.
n/a
=> fix: Properly mangle/to-lower-case build pack stage name

charts/jx/templates/job.yaml, pkg/jx/cmd/create_quickstart_integration_test.go, pkg/jx/cmd/get_build_logs.go
lets just ignore bad pods for now (logging warnings in verbose mode) as it could be the pod wasn't useful anyway, there could be other pods.
also we want the `jx get build logs --wait owner/repo/branch` command to wait and return a valid result when the pod starts up and is valid as we use this in our BDD tests
=> fix: lets not fail a `jx get build log` if we find a pod thats invalid

pkg/jx/cmd/import.go, pkg/jx/cmd/import_integration_test.go
Description
When importing new git projects, jx import command asks to confirm git username. Here I have added a new argument 'use-default-git' to give consent that use knows his/her default account and use. The account is taking from the current pipeline. 
Trying to resolve this issue:
https://github.com/jenkins-x/jx/issues/334
=> Added arg 'use-default-git' to select default git account and avoid prompting user

pkg/helm/helm_template.go, pkg/helm/helm_template_test.go, pkg/helm/test_data/set_labels/clusterrole.yaml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml, pkg/tekton/syntax/constants.go, pkg/tekton/test_data/pipeline_info/from-build-pack-init-containers/structure.yml
lets properly remove just the cluster roles installed from one namespace at a time with no-tiller
fixes #
=> fix: handle no-tiller with cluster wide resources better

pkg/jx/cmd/step_split_monorepo.go, pkg/util/files.go, pkg/util/files_test.go
When splitting a monorepo, jx split command clones if the separate repo already created. But if there are files deleted in the monorepo, jx split does not remove it from the separate repo. it only copies files.
To fix this, delete all contents of the separate repo except the ".git" directory after cloning it. Then copy all from monorepo and push it.
=> jx step split monorepo does not remove files.

pkg/jx/cmd/common_buildpacks.go
Signed-off-by: Wei Cheng <calvinpohwc@gmail.com>
Fixes typo for `backupJeninsfile` to `backupJenkinsfile` in previous commit.
fixes #
=> fix: typo backupJeninsfile to backupJenkinsfile

pkg/jx/cmd/get_applications.go
This fixes the examples for `jx get applications`. `apps` is not an alias for `applications`. 
```
$ jx get apps -e staging
Error: unknown shorthand flag: 'e' in -e
Aliases:
apps, app
Examples:
jx get apps
jx get app cheese
Options:
-o, --output='': The output format such as 'yaml'
Usage:
jx get apps [flags] [options]
Use "jx options" for a list of global command-line options (applies to all commands).
```
n/a
n/a
=> docs(applications): fix get applications examples

pkg/apis/jenkins.io/v1/types_pipeline.go, pkg/jx/cmd/controller_build.go
Skipped pipeline steps have a status of `NotExecuted` which should not result in a `PipelineActivity` being marked as `Failed`.
fixes #3175
=> NotExecuted is not a failure

go.mod, pkg/addon/config.go, pkg/auth/config.go, pkg/auth/file_config_saver.go, pkg/auth/types.go, pkg/binaries/binaries.go, pkg/cloud/gke/gcloud.go, pkg/config/project_config.go, pkg/config/project_config_test.go, pkg/io/config_readers.go, pkg/io/config_writers.go, pkg/jenkinsfile/gitresolver/resolvers.go, pkg/jenkinsfile/modules.go, pkg/jenkinsfile/pipeline.go, pkg/jx/cmd/bdd/bdd_clusters.go, pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go, pkg/jx/cmd/common.go, pkg/jx/cmd/create_addon_prometheus.go, pkg/jx/cmd/get_eks.go, pkg/jx/cmd/import.go, pkg/jx/cmd/import_test.go, pkg/jx/cmd/scan_cluster.go, pkg/jx/cmd/upgrade_platform.go, pkg/prow/config.go, pkg/reports/project_history.go, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/test_data/loop_step/jenkins-x.yml, pkg/version/version_data.go
This will let us incorporate k8s and Tekton types directly into
jenkins-x.yml - previously, we'd have trouble with that due to the use
of JSON struct tags in k8s/Tekton/etc, so that the default golang YAML
library would not unmarshal correctly.
This did require changing `loop_step/jenkins-x.yml` - a bare `- on` as
part of a string slice (or `foo: on` for a string field) would end up
unmarshalling as the string `true`, so yeah, `on`, `off`, `t`, `f`,
etc do need to be quoted if they're supposed to result in strings now.
(this will make https://github.com/jenkins-x/jx/issues/3312 and https://github.com/jenkins-x/jx/issues/3366 easier to implement)
n/a
=> chore: Switch to sigs.k8s.io/yaml

pkg/binaries/binaries.go, pkg/jx/cmd/common_install.go
Now when we have ekctl version defined in external repository (https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/eksctl.yml) we can remove static version.
Also added some extra code comments and parameter checks.
=> Eksctl version should not be hardcoded

Makefile, cmd/jx/app/jx-win.go, cmd/jx/app/jx.go
On modern windows 10 (and server) variants windows supports native ansi
escape code handling.  We just need to enable it :-o
before and after
fixes #711
=> fix(windows) make ansi escape sequences render correctly

pkg/config/helm_values.go, pkg/expose/exposecontroller.go, pkg/jx/cmd/install.go, pkg/jx/cmd/upgrade_ingress.go
Adds `urltemplate` option to install and upgrade ingress. This allows the caller to specify `--exposecontroller-urltemplate` option during the install process with commands such as
```
$ jx install --provider=gke \
--git-username=my-bot-user \
--git-api-token=my-bot-token \
--default-admin-password=myPW \
--no-default-environments=true \
--git-private=true \
--no-tiller=false \
--domain=my-domain \
--exposecontroller-urltemplate="\"{{.Service}}-{{.Namespace}}.{{.Domain}}"\"
```
Then running `jx upgrade ingress` will use the same `urltemplate`
@jstrachan / @rawlingsj - discussed indirectly on the slack channels https://kubernetes.slack.com/archives/C9MBGQJRH/p1553108179054500?thread_ts=1553073542.008000&cid=C9MBGQJRH and https://kubernetes.slack.com/archives/C9LTHT2BB/p1553507621379200
=> feat: Add urltemplate option to install and upgrade ingress

pkg/jx/cmd/create_addon_cloudbees.go
the CloudBees addon can create users with a default role assigned.
This is useful for some projects like Jenkins-X who want all users to be
able to sign on and see the build result of pull-requests (and even
smaller companies that only have one team where everyone should have
committer type access.
fixes #
=> expose the defaultRole option in the Cloudbees addon

pkg/jx/cmd/common_install.go, pkg/jx/cmd/create_addon_istio.go, pkg/packages/packages.go, pkg/packages/packages_test.go
Hi,
As agreed with @jstrachan some time ago, I've refactored `binaries` package to `packages`. After this change we will be also in sync with `https://github.com/jenkins-x/jenkins-x-versions/tree/master/packages` when it comes to naming.
Thanks!
=> Refactored "binaries" => "packages" 

go.mod, go.sum
Thrift is no longer available at the location in `go.sum`. It's now distributed on Github at github.com/apache/thrift. The official documentation has also [been updated](https://thrift.apache.org/lib/go). This change renames the import in go.mod so fetching may work again.
fixes #3320
=> chore: fix the location of thrift

pkg/kube/client_generator.go
a second time, or it will fail
```
jx create client docs
Generating docs to /Users/csanchez/dev/jenkins-x/jx/docs/apidocs
Installing https://github.com/kubernetes-incubator/reference-docs.git 096940c697f8b79873e2cfd2c1c4da1f6df76c40 to /Users/csanchez/.jx/bin
error: running go mod init, output go mod init: go.mod already exists: failed to run 'go mod init' command in directory '/Users/csanchez/.jx/codegen/src/github.com/kubernetes-incubator/reference-docs', output: 'go mod init: go.mod already exists'
make: *** [generate-docs] Error 1
```
=> Delete go.mod when running create client docs

go.mod, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/container_options_env_merge/jenkins-x.yml, pkg/tekton/syntax/test_data/merge_container_options/jenkins-x.yml, pkg/tekton/syntax/test_data/stage_level_container_options/jenkins-x.yml, pkg/tekton/syntax/test_data/stage_overrides_top_level_container_options/jenkins-x.yml, pkg/tekton/syntax/test_data/top_level_container_options/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/top_level_container_options_with_command/jenkins-x.yml
Adds a new `containerOptions` to both `pipeline` and `stage`
`options`, which takes a `Container`. All steps underneath that
context then start with that `Container`'s configuration, with
`pipeline` configuration merged into `stage` configuration (and parent
`stage` merged into child `stage`).
Down the road, we may choose to add this for steps as well, but let's
see if what this adds is sufficient first.
cc @kshultzCB @joseblas 
Fixes #3312, #3366
=> feat: Allow specifying container configuration in pipeline YAML

pkg/jx/cmd/upgrade_addons.go
this did not only re-use the values passed by set but also the previous
default values of the chart (and did not even merge with the default
values of the new version of the chart).
#3406 caused a serious regression where it was not the options passed to --set that where re-used but also the previous default values from when the chart was installed.
when this includes the version of the software to install things get a little wonky and you end up upgrading the chart but it keeps the old software.  also any new flags in the chart end up being missing so you can not upgrade the chart.  For now just revert it whilst a better fix is thought about.
fixes #
@amuniz @markawm @pmuir
=> partial revert of #3406 / #3399

pkg/auth/types.go
Changing to `sig.k8s.io/yaml` resulted in untagged struct fields being
written as their actual field names, not lowercase, so let's force
lowercase tags for the field names.
cc @kshultzCB 
fixes #3464
=> fix: Add JSON struct tags to auth types.

pkg/jx/cmd/shell.go
Allows JX Shell to use cmd.exe as the shell on windows.
fixes #2183
=> feat(windows) Make `jx shell` work on vanilla windows

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go
This creates some small differences in the resulting CRDs for build
packs - namely, reordering environment variables and volumes a bit,
changing the task name, and adding output resources to the task. The
last is not ideal, but it's a more general issue where we're copying
the workspace as output for all tasks, but shouldn't for "final" tasks
- we'll tackle that in the next two weeks separately.
cc @joseblas @kshultzCB 
n/a
=> chore: Unify build pack and YAML syntax Tekton CRD generation

pkg/jx/cmd/delete_user.go, pkg/jx/cmd/get_user.go, pkg/users/users.go
CRD name needs to be valid k8s identifier (which is handled in users.CreateUser),
but the other user commands didn't support if CRD Name was different from Login.
Also fixed removal of roles for deleted user. The old code seemed unfinished.
A case that will be common for having logins that are illegal names in k8s is when using aws-iam-authenticator configured to map all users in an AWS account to users in the cluster. Then authenticated name of the user becomes the AWS ARN of the user, so something like `arn:aws:iam::123456789012:user/Bob`.
=> fix: Use login not CRD name / Remove roles from deleted user

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/structure.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml, pkg/tekton/constants.go, pkg/tekton/pipelines.go, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go
Otherwise, updating a Pipeline while a build is in progress causes the running Pipeline to adjust the rest of its execution to match the new state, which means the build would execute partly using the old version and partly using the new version, which is a little confusing in most cases but could be a serious correctness issue depending on the nature of the changes to the Pipeline.
[Here](https://gist.github.com/dwnusbaum/8e7222372c789f3e863138b1b2efee71) is an example Gist showing the build logs for a Pipeline where one of the Tasks was updated while the Pipeline was still running. The logs show that the Pipeline ran the original version of the first Task, but the updated version of the second Task.
Uniqueness is handled by adding build numbers to Pipelines and Tasks. Build numbers are …
=> fix(tekton) make pipelines and tasks unique per-build

go.mod, go.sum, pkg/jx/cmd/upgrade_ingress.go
`jx upgrade ingress` does not have the `--urltemplate` argument, even though it can be set when running in non-batch mode.
This change allows us to change the UrlTemplate when running `jx upgrade ingress` in batch mode.
fixes #3487
=> Added '--urlTemplate' argument to 'jx upgrade ingress'

pkg/apps/helmops.go, pkg/apps/install.go, pkg/expose/exposecontroller.go, pkg/helm/helm_helpers.go, pkg/helm/helm_helpers_test.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/upgrade_apps.go
If Vault is available automatically store repo creds in it, and use them the next time the repo is accessed. If new creds are provided, they will replace the old creds.
fixes #
=> feat: store helm repo creds in Vault

pkg/jx/cmd/step_tag.go, pkg/jx/cmd/step_tag_test.go, pkg/jx/cmd/test_data/step_tag_project/charts/mydemo/Chart.yaml
When running `jx step tag`, we update the `version` field of the chart. This PR also update the `appVersion` field to the same value
Setting the `appVersion` field to the same value as the `version` field shouldn't be an issue, because in Jenkins X, it's assumed that the chart has the same lifecycle and versioning as the app.
Setting this field allows to easily see the version when running commands such as `helm list`, and to get a better integration with helm-based tools
=> feat(tag): set the chart's appVersion when tagging

pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go
#3585 nuked the usage of `PipelineConfig.Env` variables - this puts that back. We're still ignoring `ProjectConfig.Env`, since that was already being ignored by build packs using Knative Build, though. We also stop running `git merge` for stages after the one that actually needs to do the checkout, since we're reusing the workspace from the initial stage anyway.
n/a
=> fix: Use pipelineConfig.Env again, don't merge for later stages

pkg/apps/helmops.go, pkg/apps/install.go, pkg/apps/values.go, pkg/jx/cmd/add_app.go, pkg/jx/cmd/add_app_test.go, pkg/jx/cmd/clients/mocks/factory.go, pkg/jx/cmd/delete_app.go, pkg/jx/cmd/delete_app_test.go, pkg/jx/cmd/get_apps.go, pkg/jx/cmd/get_apps_test.go, pkg/jx/cmd/test_data/get_apps/get_apps_table_json.json, pkg/jx/cmd/test_data/get_apps/get_apps_table_yaml.yaml
Modifies the add app command to include the `ReleaseName` Helm label to the Apps CRD object and refactor to separate the responsibilities of `StashValues`and `addApp` functions.
Modified the get apps command to show the release name as the app name and use the CRD List API to list Apps by the `ReleaseName` label.
fixes #3658
=> Fix to the get, upgrade and delete app commands after the side effects of the add apps changes

pkg/apps/install.go
fixes: #3664
Correctly set the app name when it has been passed in from the current directory.
=> fix: jx add app . does not create a valid chart directory

pkg/jx/cmd/install.go
Solved the helm namespace issue when installing the IBM block storage chart.
This chart is installed for the `iks` provider is.
The installation overrides the namespace to `default` which fails to resolve resource resolution.
fixes #3391
=> Solved helm namespace issue for IBM block storage

pkg/apps/gitops.go
…a version but the version itself is empty when calling helm
While using GitOps: 
When calling `jx upgrade app jx-app-datadog` without providing a version, it couldn't find the actual latest version because a version named `latest` was being passed to Helm. 
In order to find the latest version, Helm needs the `--version` flag to be empty.
The branch will still be named `<PREFIX>-latest`. 
fixes #3674
=> Make sure the command `jx upgrade app` finds the correct latest version when not providing one

pkg/apps/gitops.go, pkg/jx/cmd/delete_app_test.go
…nts.yaml file as it causes the apps upgrade to panic
When deleting an app in GitOps mode, a null reference was added to the `requirements.yaml` in the place of the deleted app. This causes the `jx app upgrade` command to panic when going through the requirements file.
With this fix, the app is just removed from the slice.
fixes #3699
=> Avoid having a null reference as a list element in the requirements.yaml file when deleting an app in GitOps mode

pkg/cloud/gke/helper.go
`gcloud config get-value project` returns a multi-line value which includes the current configuration and then the project ID.  GetCurrentProject() is not handling this.
None reported yet
=> fix(gke): GetCurrentProject can be multi-line causing error(s)

pkg/apps/gitops.go, pkg/environments/gitops.go, pkg/helm/helm_helpers.go, pkg/jx/cmd/delete_application.go, pkg/jx/cmd/opts/helm.go, pkg/jx/cmd/promote.go
Fixes the behavior that happened after upgrading an app that had configuration questions. 
The questions were being asked again because the CLI wasn't able to find the distribution's `values.yaml` file containing all already provided answers and was only finding the main chart's yaml file.
It will now look into the dependencies in the `requirements.yaml` file and attempt to find a valid `values.yaml` in the composed path. It will warn the user if it's unable to find a values.file.
fixes #3673
=> Fixes the upgrade app command so it doesn't ask for already answered configuration questions

pkg/helm/helm_template.go, pkg/jx/cmd/create_addon_istio.go
fix: Istio addon needs to install istio-init chart (#3724)
fix: Istio addon fails to install when using --no-tiller (#3724)
The helm template installation fails when the chart is installed from the
filesystem Only when using no-tiller (the default now)
fixes #3724
=> Istio addon fails to install when using --no-tiller

go.mod, pkg/jx/cmd/install.go
Adding a flag to specifically enable a static jenkins master instead of it being the default option if
prow, tekton or ng is selected.
fixes #
=> Flag for static jenkins master

pkg/jx/cmd/clients/mocks/factory.go, pkg/jx/cmd/create_terraform.go, pkg/jx/cmd/opts/auth.go
When running `jx create terraform` JX tries to retrieve Git credentials via Kubernetes Secrets in an active Kubeconfig client config. If you don't have such configuration, or it is unsuitable, the process fails.
It would be very useful for people to have no active cluster available and still generate the terraform configuration, especially as that might be the cluster you want to use - later - for JX in the first place.
I could not get pegomock to work, and I could really use some help with testing the multi-step processes such as this one.
Discussed potential approach with James Strachan, who recommended using a fake KubeClient.
This might be related to the wrong context, but this - see PR code - is how I interpreted it.
fixes #3640
=> add flag for ignoring kubeconfig if no valid available

pkg/gits/github.go, pkg/gits/github_test.go, pkg/jx/cmd/clients/mocks/factory.go, pkg/jx/cmd/update_webhooks.go, pkg/jx/cmd/update_webhooks_test.go, pkg/jx/cmd/upgrade_ingress.go, pkg/jx/cmd/upgrade_ingress_test.go
This allows both the direct `update webhooks` and `upgrade ingress` commands to update webhooks belonging to either an organisation or to a user account.
In `upgrade ingress` it makes sure to also check for the current user as an option in the selection for where to look for updating webhooks.
In the GItHub implementation for the repo retrieval, it does a check to see if the org is the same as the user.  If it is the same, we should retrieve the list of repositories via the user-based API instead.
In summary, this allows people to update webhooks for a GitHub account rather than org.
This is sort-of "patched" in with a trick. Maybe it would be better to do a more thorough change for adding this kind of support. Or, add a warning this is not supported for accounts and people should use …
=> add support for updating webhooks in user account

pkg/jx/cmd/step.go, pkg/jx/cmd/step_values_schema_template.go
=> fix: add missing step values schema template

pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml, pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/environment_at_top_and_in_stage/jenkins-x.yml
Allow specifying environment variables for individual steps.
Note that we're using `env` for per-step env vars - in #3841, we allow `env` for stage and pipeline env vars as well.
/assign @joseblas 
n/a
=> feat(tekton): Add support for per-step environment variables

pkg/gits/github.go, pkg/jx/cmd/update_webhooks.go, pkg/jx/cmd/update_webhooks_test.go, pkg/jx/cmd/upgrade_ingress.go
Using `CommonOptions` should be preferred, as it will aid code flows using other commands, such as `upgrade ingress`.
Also included some verbose logging and throwing an error when there's no `owner` set, to avoid hanging on retrieving repositories forever.
Related to PR 3527
fixes #3810, fixes #3115 (already closed, but affected)
=> user commonoptions username field instead

pkg/jx/cmd/namespace.go, pkg/jx/cmd/namespace_test.go, pkg/jx/cmd/opts/common.go, pkg/kube/config.go
fixes issue #3846
Adds a `--create` option to `jx ns <name>` and adds some tests around the namespace command.
=> feat: adding ability to create namespace via 'jx ns --create <name>

pkg/jx/cmd/step_bdd.go
Adding a flag to indicate if the PR is a versions repository PR. If it's not
then use the master branch and head revision for the jenkins-x-versions repositories
fixes #
=> (fix) git version for jx step bdd versions repository

pkg/jx/cmd/create_cluster_gke.go
fixes #3854 due to old docker images causing problems with tekton
=> fix: lets default to using a newer image type

go.mod, go.sum, pkg/tekton/pipeline_info.go
Part of the grand process of moving to Tekton Pipelines v0.3.1 (i.e., containers rather than init containers, and a bunch of other things that aren't near as significant).
https://github.com/jenkins-x-charts/tekton/pull/28 has the related chart change.
This should be ok to merge as is.
n/a
=> chore: Update to Tekton Pipelines v0.3.1

pkg/builds/jenkinsfiles.go, pkg/builds/jenkinsfiles_test.go, pkg/config/project_config_test.go, pkg/jenkinsfile/pipeline.go, pkg/jx/cmd/create_step.go, pkg/jx/cmd/create_variable.go, pkg/jx/cmd/step_buildpack_apply_test.go, pkg/jx/cmd/step_create_task.go, pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/packs/apps/pipeline.yaml, pkg/jx/cmd/test_data/step_create_task/packs/maven/pipeline.yaml, pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/container_options_env_merge/jenkins-x.yml, pkg/tekton/syntax/test_data/environment_at_top_and_in_stage/jenkins-x.yml, pkg/tekton/syntax/test_data/loop_step/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/agent_container_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/agent_dir_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/comment_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/container_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/groovy_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/legacy_steps_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/sh_field/jenkins-x.yml, pkg/tekton/syntax/test_data/validation_failures/when_field/jenkins-x.yml, pkg/util/jenkinsfile_writer.go, pkg/util/jenkinsfile_writer_test.go
Here specifically, we're getting rid of `PipelineAgent` and
`PipelineStep`, so that you can use the `jenkins-x.yml` syntax for
agents and steps within a build pack or for overriding/adding to a
build pack in `jenkins-x.yml`. The existing syntax still works in
build pack context, but can't be used when defining the whole pipeline
- you'll get validation errors telling you what you should do
instead.
More is likely to come - but since this is functional as is with no
backwards compatibility concerns that I can find, hey, might as well
toss it up.
cc @sharepointoscar 
n/a
=> chore: Initial work on unification of build pack and jenkins-x.yml syntax

pkg/jx/cmd/import.go
This PR fixes this issue:
- When importing a project into an aws cluster, the wrong organisation is passed to the LazyCreateRegistry function, where the the git org is passed instead of the docker registry org.
fixes #
=> Fix the lazily created ecr docker registry organisation

pkg/jx/cmd/import.go
This PR fixes this issue:
- When importing a project, if there's no Dockerfile and the project doesn't require one, the code still goes and creates an ecr repository for the project, this PR skips that step in that case.
fixes #
=> Skip ECR docker repository creation if a project doesn't need a docker image/file

pkg/kube/cluster/cluster.go, pkg/kube/cluster/cluster_test.go, pkg/kube/vault/vault.go
Fixes the case that the cluster name is a FQDN which then ends up with a short name ending in a dot which forms an invalid name used for creating the vault service account
fixes #3755
=> fix: Handle shortening cluster names for clusters named by their FQDN.

pkg/cloud/gke/gcloud.go
we've seen this fail first time in the BDD tests due to optimistic concurrenncy issues
=> fix: lets retry trying to assign roles to the SA

pkg/tekton/syntax/pipeline.go, pkg/tekton/syntax/pipeline_test.go, pkg/tekton/syntax/test_data/dir_on_pipeline_and_stage/jenkins-x.yml
Syntax is:
```
pipeline:
dir: some-dir
...
stages:
- name: some-stage
dir: /an/absolute/dir
...
```
Relative directories are appended to the base working directory (i.e.,
`/workspace/source`), and absolute directories are used directly.
Pipeline `dir` is overridden by stage `dir` and/or step `dir`, and
stage `dir` is overridden by either nested stages' `dir`s or step `dir`.
/assign @joseblas 
fixes #3838
=> feat(tekton): Allow specifying default working dir on pipeline and stage

pkg/jx/cmd/get_applications.go
The JX Environment listed in `ApplicationEnvironmentInfo` here:
https://github.com/jenkins-x/jx/blob/443b821c5093b71eabbd1eca0d7334b6f89429af/pkg/jx/cmd/get_applications.go#L47
Is always set to the last environment that was iterated over.  I think this is caused by variable shadowing.  The fix was to clone the environment struct.
Manually built and tested the fix.
None.
=> fix(cmd): application environment was always the last environment

pkg/jx/cmd/step_syntax_validate_pipeline.go
We had the wrong yaml library in `step_syntax_validate_pipeline`. Sigh.
fixes #3944
=> fix(tekton): Non-schema-errors weren't showing up in validation

pkg/jx/cmd/environment.go, pkg/kube/config.go
At present, the 'jx env' command returns information on the current environment which contains the server in which it's connected. I propose replacing the server value (as it doesn't provide a good reference to the cluster) with the cluster name. This is valuable when used within the status bar of a terminal or detecting specific environments.
=> Amended environment to return cluster name

pkg/jx/cmd/get_apps.go, pkg/jx/cmd/get_apps_test.go
There was an issue with the status of installed apps after it moved to no tiller clusters
=> Fixed the status for listed installed apps when not in gitops mode

pkg/jx/cmd/install.go
When using external-dns it's easier if all services operate on the domain rather than the subdomain (namespace)
=> Set URLTemplate when external-dns flag is set

pkg/kube/pod.go, pkg/tekton/pipeline_info_test.go
Even with non-init containers used for steps, init containers are still used by Tekton for a few things at the very beginning of the run. So let's make sure to include those in the logs.
n/a
=> fix(tekton): Include init containers for things like cred init in logs

pkg/jx/cmd/controller_team.go
The `jx create team` does not copy the admin team settings for git.
I couldn't figure out how to actually run this.
None.
=> fix(controller_team): copy team settings for git

pkg/jx/cmd/controller_enviornmentcontroller.go, pkg/jx/cmd/create_addon_environment_controller.go
* `create addon envctl` used to path `source.serverURL` when chart was
expecting the `source.serverUrl`
* `controller environment` had `no-register-webhook` pointing to the
wrong struct field (`NoGitCredeentialsInit` instead of `NoRegisterWebHook`)
=> Two typos in environment controller related commands are fixed

pkg/kube/pod.go
Stumbled across this when running `jx get build logs` while, as it
turns out, there was a pod that failed to provision due to
insufficient resources:
```
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/kube.GetContainersWithStatusAndIsInit(...)
/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/kube/pod.go:248
```
So let's fix that by not trying to pull in any pod that doesn't have
as many container statuses as it does containers.
n/a
=> fix: Don't barf on pods without container statuses

pkg/jx/cmd/step_create_task.go
This will mean that when the `PipelineActivity` is GCed, the
`Pipeline`, `Task`s, and all other CRDs owned by those (i.e., `PipelineRun`, `TaskRun`s,
`PipelineStructure`) will get GCed as well.
`PipelineResource` is *not* owned by `PipelineActivity`, since that's
per-branch, not per-build.
n/a
=> chore(tekton): Make Pipeline/Tasks owned by PipelineActivity

pkg/jx/cmd/step_create_task_test.go, pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/jenkins-x.yml, pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipeline.yml, pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipelineresources.yml, pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipelinerun.yml, pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/structure.yml, pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/tasks.yml
Relevant to #3767 - I opened #3952 to add a new `script` field, but
yeah, we didn't need that, `command` can already be used for that. So
here's a test demonstrating that.
cc @vfarcic  @sharepointoscar 
n/a
=> chore(tekton): Demonstrate that command can be used for multiline script

pkg/jx/cmd/opts/gcp.go
Use the user configured zone/region (if it's set) as the default option when executing `jx create cluster gke` in interactive mode
fixes #
=> Default to configured zone/region on GKE interactive install

pkg/jx/cmd/clients/factory.go
The `ns` argument to `GetJenkinsURL` gets immediately overwritten with the current namespace stored in kube config.  Very likely they are always the same, but in places like running JX in the cluster, they are not.
Just giving some more details as to how I ran into this problem: it was from doing a JX install from within the cluster.  On install, it builds the `CreateJenkinsUserOptions` command and specifies the Namespace it should run in in order to generate the Jenkins API token.  Then in `CreateJenkinsUserOptions.Run` it calls `CustomJenkinsURL`, passing in the namespace.  Once you make it to `GetJenkinsURL`, the namespace argument is ignored and it reads the namespace from the kube config or pod namespace.
I'm hoping the BDD tests cover this change.
None.
=> fix(cmd): GetJenkinsURL ignores the ns argument

pkg/gits/helpers.go, pkg/jx/cmd/create_mlquickstart.go
Uses the fork status from the repo details rather than the input parameter.
It's not clear why `fork` was being passed explicitly as an input so this change may break something in the GitOps functionality in gitops.go which is the only other consumer of this method. I have therefore just changed the source of the fork status but not removed this from the API. If all the tests still work for GitOps, then we need to clean this up by removing the `fork` parameter from the function.
fixes #3994
=> fix: Get fork status from repo

go.sum, pkg/jx/cmd/create_env.go, pkg/jx/cmd/edit_env.go, pkg/jx/cmd/install.go, pkg/kube/env.go, pkg/kube/env_test.go
in GitOps mode the behavior is different and re-installation fails
```
Creating default staging and production environments
Using xxx environment git owner in batch mode.
error: creating the environments: failed to create staging environment in namespace jx: Environment staging already exists!
```
fixes #
=> Do not try to create the environments if they already exist

pkg/apps/gitops.go, pkg/environments/gitops.go, pkg/gits/helpers.go, pkg/jx/cmd/create_pullrequest.go, pkg/jx/cmd/step_git_fork_and_clone.go
Fixes below error where a pull request on a fork is missing a prefix. Refactored to better encapsulate the fork parameter.
`error: adding Prow config to environment repo: creating pr for prow config: POST https://api.github.com/repos/cb-kubecd/environment-shriekviolet-dev/pulls: 422 Validation Failed [{Resource:PullRequest Field:head Code:invalid Message:}]`
=> Chore: refactor usage of fork when creating a pull request

pkg/cloud/gke/storage/long_term_storage.go, pkg/jx/cmd/install.go
…, so we are going to create the buckets with gsutil
A bug surfaced yesterday which didn't allow people with a newer version of gcloud to create buckets for long term storage.
After further investigation, an incompatibility between gcloud and `go-cloud`, the library we were using to abstract the cloud provider. 
The method to create buckets has changed to use gsutil instead.
fixes #
=> Fix: There was an incompatibility problem between gcloud and go-cloud so we are going to create buckets with gsutil

pkg/jx/cmd/step_changelog.go, pkg/users/git.go
Right now it spews out errors about not being to find users with no details, which isn’t helpful
fixes #
=> Fix: make `jx step changelog` less verbose

pkg/kube/version.go
It seems that the applications are prefixed with `jx-` regardless of the namesapce
where they are installed. This can create confusion when for instance users are trying to
promote an application. They are often use the application with the jx prefix which
leads to an error, because the chart is published without the prefix.
fixes #
=> fix: remove the 'jx-' prefix from application name

pkg/jx/cmd/opts/import.go
I think is fine to remove the `jx console` command from import message. We can add maybe later a link to the UI.
fixes #3831
=> fix: remove the "jx console" command from import message

jenkins-x-integration.yml, pkg/jx/cmd/install.go, pkg/jx/cmd/install_gitops_integration_test.go
Store and name the dev environment folder consistently with other environments.
```
.jx
├── environments
│   └── ccojocar
│       ├── environment-cosmin-devenv12345-dev
│       ├── environment-cosmin-devenv12345-production
│       └── environment-cosmin-devenv12345-staging
```
fixes #3741 #3695 #3694 #3684
=> fix: store the dev environment next to other environments in the .jx folder

pkg/jx/cmd/upgrade_cli.go, pkg/jx/cmd/upgrade_cli_test.go
fixes issue #4018
Not 100% sure whether the issue reported on #4018 is exactly the same, but this fix tries to make sure that if brew is used to upgrade jx, brew is also used to check the latest available version.
ATM, the latest available version is determined by the GitHub release which might not have properly propagated to Homebrew.
=> fix(cmd): on macOS use 'brew info' to determine latest jx version

pkg/cloud/amazon/routes.go, pkg/jx/cmd/create_cluster_eks.go, pkg/jx/cmd/delete_eks.go, pkg/jx/cmd/get_eks.go, pkg/jx/cmd/import.go, pkg/jx/cmd/install_dependencies.go, pkg/jx/cmd/opts/domain.go, pkg/jx/cmd/opts/install.go, pkg/jx/cmd/step_bdd.go, pkg/jx/cmd/upgrade_binaries.go, pkg/kube/services/services.go, pkg/packages/packages.go
Fixes #3826 - iam binary name
Fixes: #3801 - batch mode prompts for questions
Fixes: #3816 - BDD tests for EKS
Also contains:
- Environment controller can use ingress hostname created by EKS services of type LoadBalancer
- Improvements around registering wildcard domain in Route 53
=> EKS BDD Fixes

pkg/jx/cmd/create_cluster_gke.go
Fixes an issue where cluster name wasn't being passed to the `gcloud container clusters create` command after #4122
=> Fix missing cluster name

Makefile, cmd/jx/codecov/info.go, cmd/jx/jx_test.go, go.mod, go.sum, jenkins-x-bdd.yml, jx/scripts/ci.sh, myvalues.yaml.template, pkg/util/commands.go
If called when compiled into coverage mode, this binary will call itself, adding the `test.coverprofile` argument, and, after the subprocess exits, upload the coverage to codecov. It also fixes the output to remove the coverage lines generated by go. This allows us to use it transparently in tests, only setting the `CODECOV_TOKEN` into the environment.
=> feat: switch to a self uploading covered binary

pkg/jx/cmd/create_cluster_gke.go
Cluster name is being passed to get-credentials command incorrectly.
=> Fix cluster name for install and credentials

pkg/jx/cmd/gc_activities.go, pkg/jx/cmd/gc_activities_test.go
Equaled the PR and Batch CRDs expiration times so they get garbage collected together
In an effort to link PRs and Batch builds together in the UI, the expiration time needs to be the same  for both resources so one doesn't get collected before the other and leave broken links in the UI.
fixes #4091
=> Equaled the PR and Batch CRDs expiration times so they get garbage collected together

pkg/auth/auth_config.go, pkg/gits/provider_test.go, pkg/jx/cmd/create_cluster_gke.go, pkg/util/strings.go, pkg/util/strings_test.go
Further extends the usage of the --advanced flag for jx create cluster gke. This reduces the questions asked, simplifying the UX of the CLI.
#3915
=> Extend use of jx create cluster advanced flag

pkg/jx/cmd/create_devpod.go, pkg/jx/cmd/opts/common.go, pkg/jx/cmd/opts/common_test.go, pkg/kube/constants.go
* lets make it faster at returning if there's already a devpod (by labelling the devpod with the repos its being used for)
* lets also create the edit environment before waiting for the pod to startup to speed up initial setup a little
* also lets use a callback for reporting status so we can reuse the feedback in a web UI too
* add an option for cloning git from a URL on setup
=> fix: improve devpod

pkg/jx/cmd/get.go, pkg/jx/cmd/get_lang.go
A utility option to determine what pack would be used if you were to `jx import` the current working directory
<details>
<summary>Error</summary>
```
SmithBen2289:dev benjaminsmith$ mkdir empty
SmithBen2289:dev benjaminsmith$ cd empty/
SmithBen2289:empty benjaminsmith$ /Users/benjaminsmith/dev/jx/build/jx get lang
error: failed to discover task pack in dir /Users/benjaminsmith/dev/dst/postgres-db/empty: there was an error detecting the language
SmithBen2289:empty benjaminsmith$ 
```
</details>
<details>
<summary>Success</summary>
```
SmithBen2289:flask benjaminsmith$ ls
performing pack detection in folder /Users/benjaminsmith/dev/quickstart/flask
--> Draft detected Python (47.904483%)
selected pack: /Users/benjaminsmith/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/p …
```
=> jx get lang command

pkg/jx/cmd/opts/install.go
fix(jx create addon gloo): HTTP 404 during downloading glooctl
Changed the 2 parameter used to generate the download url to GOOS.
fixes #4178
=> fix for error during `jx create addon gloo` #4178

pkg/jx/cmd/opts/install.go
/hold this does not work because tekton is installed individually and not part of the platform.
It would need to have the tekton values in the top level
```yaml
pvc:
size: 20Gi
```
https://github.com/jenkins-x/cloud-environments/pull/5
=> fix: pass helm values files to tekton chart installation

pkg/jx/cmd/install.go
Retrieve Project ID from gcloud when using the tenant service
fixes #
=> Retrieve Project ID from gcloud

pkg/jx/cmd/controller_build_test.go, pkg/jx/cmd/test_data/controller_build/update_stage_info/pod.yml, pkg/kube/pod.go, pkg/tekton/pipelines.go, pkg/tekton/tekton_helpers_test/test_helpers.go
`pod.Status.ContainerStatuses` does not appear to have a consistent order, unlike init containers. So we shouldn't be using that as the basis for the order we add steps to stages in `PipelineActivity`. Instead, we should use the `pod.Spec.Containers` order.
/assign @vfarcic 
fixes #4016
=> fix(tekton): Populate activity with correct step order

Makefile, pkg/gits/git_cli.go, pkg/gits/github.go, pkg/jx/cmd/step/step_changelog.go
This should fix jx step changelog
fixes #
=> fix: the logic for determining tag history

pkg/jx/cmd/get_preview.go
`jx get preview --current` currently logs the url. We should print it so that it's easy for scripts to capture the output.
=> jx get preview --current should print the url

pkg/jx/cmd/edit_buildpack.go
Default work loads buildpack to `Kubernetes Workloads: Automated CI+CD with GitOps Promotion` when using `--advanced` mode
=> Defaulting workload type

pkg/jx/cmd/create_cluster_gke.go, pkg/jx/cmd/create_cluster_gke_test.go, pkg/jx/cmd/install.go
Restrict gke cluster name length to 27 as it is used as a prefix to service account names e.g. `${cluster_name}-ko` which are limited to 30 chars
#4210
=> Restrict cluster name length

pkg/cloud/gke/externaldns/external_dns.go, pkg/cloud/gke/helper.go, pkg/cloud/gke/naming.go, pkg/cloud/gke/vault/vault_backend.go, pkg/cmd/create/install.go, pkg/cmd/deletecmd/delete_vault.go
Follow the template for `${cluster_name}-ko`generated service accounts names. Ensuring cluster name doesn't exceed the limited 30 characters. Done for kaniko, external dns and vault service accounts.
#4210
=> Template for naming service accounts

pkg/cmd/create/create_terraform.go
brings the terraform service account name inline with the kaniko
and vault SAs
=> chore: minor rename of terraform service account

pkg/cmd/create/install.go
setting this flag in this way will no longer make any difference to the output
displayed when installing JX.
=> fix: removed the hack to set the verbose flag

pkg/cmd/create/install.go
When running in non-batch mode without the --advanced-mode flag LTS is set to true which then later creates an error if the provider is not GKE. This change defaults LTS to false if provider is not GKE.
If change is good - I'll write tests to cover since current tests run only in batch mode and I'll need to figure that out.
=> fix: defaulting LTS to false if provide not GKE as not supported by other providers

pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/surveyutils/test_data/generatedToken.test.schema.json, pkg/util/secrets/secrets.go, pkg/vault/helpers_test.go
feat: support for generated secrets in schemas
If `"default":"<generated>”` is used on a token or a password then it will default to a generated secret
#4328
=>  feat: support for generated secrets in schemas

pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml, pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml, pkg/cmd/step/create/test_data/step_create_task/override-steps/jenkins-x.yml, pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml, pkg/tekton/syntax/pipeline.go
I discovered, thanks to @tdcox, that I screwed up and the `override-steps` test was trying to override the `set-version` step, which isn't showing up in our test cases in the first place (since we have `NoReleasePrepare` set to `true`). Whoops. So let's use a different step. And while I'm here, let's preserve the step name when we override a step with a single step and that new step doesn't have a name specified. That just seems nice.
/assign @joseblas 
/assign @wbrefvem 
n/a
=> fix(tekton): Preserve overridden step name and fix override test

pkg/apps/install.go, pkg/apps/values.go, pkg/cmd/add/add_app_test.go, pkg/cmd/opts/helm.go, pkg/cmd/step/create/step_create_task.go, pkg/cmd/step/create/step_create_values.go, pkg/cmd/step/create/test_data/step_create_values/install/values.schema.json, pkg/cmd/step/create/test_data/step_create_values/install/values.yaml.golden, pkg/kube/constants.go, pkg/secreturl/client.go, pkg/secreturl/localvault/client.go, pkg/secreturl/mocks/secreturl_client.go, pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/util/dirs.go, pkg/vault/fake/client.go
also lets polish a little the directory structure + file names to be more concise
also lets allow the secret base path to be configured; when bootstrapping a new cluster we may not be able to find the name yet; so providing a consistent path to secrets helps avoid things moving during the bootstrap proces
=> fix: lets let `jx step create values` work with vault + local files

pkg/cmd/step/helm/step_helm_apply.go, pkg/spring/model.go
=> fix: default to use a temporary directory for applying helm charts

pkg/cmd/create/install.go, pkg/cmd/create/install_test.go
a regression was introduced during a recent refactor that force enabled kaniko 
on EKS.
=> fix: disabling kaniko by default on EKS

pkg/cmd/boot/boot.go, pkg/cmd/boot/boot_test.go, pkg/cmd/boot/test_data/jenkins-x.yml, pkg/cmd/boot/test_data/jx-requirements.yml, pkg/cmd/cmd.go, pkg/cmd/step/create/step_create_task.go
to bootstrap an installation using a flexible GitOps pipeline on any kubernetes cluster; created via Teraform, by hand or by `jx create cluster --skip-install`
fixes #4404
=> fix: add a 'jx boot' command

.gitignore, .goreleaser.yml, Makefile, jenkins-x.yml
This is part of a series of updates which intend on improving the way in which jx is released. The first part will replace progrium/gh-release for goreleaser https://goreleaser.com/
#4364
=> feat: Updated release to use goreleaser

jenkins-x.yml
It seems that the default builders version within the platform version is too old to contain goreleaser
=> Specifying the builders version for the release step

pkg/cloud/gke/gcloud.go, pkg/cmd/create/create_cluster_gke.go, pkg/cmd/create/create_cluster_gke_terraform.go, pkg/cmd/create/create_cluster_gke_test.go, pkg/cmd/create/create_terraform.go, pkg/cmd/create/install.go, pkg/util/strings.go, pkg/util/strings_test.go
Bucket labels failing when containg a `.`, move and utilise an existing SanitizeLabel function
=> Sanitize bucket labels

pkg/apis/jenkins.io/v1/types_environment.go
if we lose the import mode for some reason on the teamSettings, lets default to jenkins x pipelines if we prow/tekton
fixes #4456
=> fix: lets default to jenkins x pipelines if there's a missing importmode

pkg/cmd/step/scheduler/step_scheduler_config_apply.go, pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
Update scheduler migration help. Also support applying pipeline schedulers directly to the cluster when using `jx step scheduler config apply --direct=true` in gitops mode.
=> chore: Fix scheduler docs

Makefile
Updating the release notes doesn't seem to work as expected, so the approach is to generate the release notes and then upload with the release artefacts.
=> fix: Try uploading the release note with the release

pkg/cmd/controller/controller_enviornmentcontroller.go
looks like a regression in the code - using the git repo URL not the git service URL (https://github.com) to find the pipeline auth token
fixes #4316
=> fix: environment controller not finding git token if GIT_KIND

Makefile
So that we can generate a changelog we need to explicitly set `--update-release false`, this will allow `jx step changelog` command to generate the changelog.md file using the `--output-markdown` option.
=> fix: Don't update release when generating changelog

.goreleaser.yml, Makefile
It seems that the list of `ldflags` options only seems to evaluate the last option in the list. A `test-release` make target has also been added to debug builds. This should hopefully resolve #4482 
=> fix: place all ldflag parameters onto one line

Makefile
Assigning the boolean to the `--update-release` parameter explicitly.
=> fix: Assign boolean to update-release explicitly

Makefile
Removed the goreleaser line which generates a conflict when uploading binaries which are already present
=> fix: Remove pre goreleaser call

pkg/cmd/create/install.go
Fix for environment prefix defaulting to a generated name, rather than using the cluster name
=> fix: Environment prefix defaulting to generated name

go.mod, pkg/cmd/step/step_changelog.go, pkg/cmd/step/step_next_version.go, pkg/gits/bitbucket_cloud.go, pkg/gits/bitbucket_server.go, pkg/gits/gerrit.go, pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/gitea.go, pkg/gits/github.go, pkg/gits/gitlab.go, pkg/gits/helpers.go, pkg/gits/interface.go, pkg/gits/mocks/git_provider.go, pkg/gits/mocks/gitter.go, pkg/gits/provider_fake.go, pkg/semrel/semrel.go
This adds the `--semantic-release` flag to `jx step next-version` which uses conventional commits to work out the next version number
fixes #
=> feat(versions): Add support for semantic releases

pkg/cmd/get/get_build_logs.go
`buildMap` is not initialized anymore in the case of `jx get build logs -b name-of-the-build`
`(len(args) != 0)` so https://github.com/jenkins-x/jx/pull/3258/files#diff-88a655068fa6bd90e8016b5a9642d098R269 equals nil.
Not sure of this fix as it's a partial revert of https://github.com/jenkins-x/jx/pull/3258 which was suppose to also fix an issue.
@jstrachan any insights are welcome to be sure it's not making a regression
fixes #4518
=> fix: get build logs batch mode

pkg/cmd/controller/controller_pipelinerunner.go, pkg/cmd/step/create/step_create_task.go
For now, let’s just add a `--semantic-release` flag to `jx step create task` and the `pipelinerunner` so that we can optionally use semantic-release as a `jx step next-version` strategy.
Once meta-pipeline is in, and stabilises, we can perhaps do the `jx step next-version` in there, and use it to customise the semantic release.
This is not ideal
fixes #
=> fix: add a path to enable semantic releases

pkg/cmd/step/create/step_create_meta_pipeline.go, pkg/cmd/step/create/step_create_task.go, pkg/tekton/pipelines.go
`PipelineRun` names may be truncated to the point where they're not unique across branches and contexts, so we should be looking them up for determining the next build number by looking at their labels instead.
fixes #4523
=> fix(tekton): Look for run by labels, not name

jenkins-x-tekton.yml, jenkins-x.yml
Followup to #4301. Also fixes a bad image name I put in. Sigh.
n/a
=> chore: Add Tekton BDD to release coverage baseline generation

jenkins-x-lint.yml
The container used for the git merge has two gits - one in /usr/local/git/bin, and one in /usr/bin. The latter is too old, and the former is the one we want. We're overriding the path to get go stuff to work, so let's prepend /usr/local/git/bin to that path.
n/a
=> fix: Use /usr/local/git/bin in path for lint build

jenkins-x-bdd.yml, jenkins-x-tekton.yml, jenkins-x.yml
3 CPUs and 3gb RAM was overkill for the request, IMO. Let's drop the CPU to 1 and the RAM to 2gb.
Adding the `tekton` context has resulted in a bunch of `PENDING` pods due to requests not being satisfied, hence this.
fixes #4574
=> chore: Cut down on resource requests for BDD tests

pkg/cmd/create/install.go
Was testing out a local [kind](https://kind.sigs.k8s.io) cluster to play with Tekton and friends. My install command was:
```
jx install --provider=kubernetes --no-default-environments --default-admin-password=admin --advanced-mode --on-premise --external-ip 'MY_IP' --gitops=false --prow=true --tekton=true --static-jenkins=false --vault=false
```
Then, when I tried to do a quickstart, it applied a normal `Jenkinsfile` instead of `jenkins-x.yaml`.  Turned out the import mode on the dev environment team settings was set to `Jenkinsfile` instead of `YAML`.
100% guessing on where to fix it. But did test the fix, team settings were correct after the change.
N/A
=> fix(install): use YAML import mode for Tekton

go.mod, pkg/cmd/cloudbees/cloudbees.go, pkg/cmd/config/patch_configmap.go, pkg/cmd/config/patch_configmap_test.go, pkg/cmd/step.go, pkg/cmd/test_data/step_config/config_map1.txt
…gMaps and literal json/yamls in the Data field
feature: changed the way the patch is applied
feature: added needed dependency
fix: removed unused file
feature: added a step to apply json patches to config maps and second level embedded items in config maps
As a first step to be able to modify the configuration based on installed apps / addons, a step has to be created to aply JSON patches to ConfigMaps as some of them have second level embedded properties which are yaml / json themselves and Kubectl couldn't handle those.
You can specify the usual json patch types and follow the standard syntax.
Specifying the `first-level-property` flag would apply the patch into the value of the specified property only in JSONPatch format, if and …
=> Created a step to handle JsonPatch syntax queries into Configmaps and a way to apply them into second level embedded resources

pkg/cloud/gke/gcloud.go, pkg/cmd/create/create.go, pkg/cmd/create/create_domain.go, pkg/cmd/create/create_domain_gke.go, pkg/cmd/create/install.go, pkg/cmd/create/install_test.go, pkg/util/strings.go, pkg/util/strings_test.go
I did debate whether to call the command `jx create domain gcp` but wanted to keep consistency with other create cluster and install commands, so stuck with `gke` so folks don`t have to keep remembering different combinations.
When the command runs it looks like the following:
```
jx create domain gke --domain foo.bar.io
? Google Cloud Project: cheese
Managed Zone exists for foo.bar.io domain.
Getting nameservers for foo.bar.io domain
Please update your existing DNS managed servers to use the nameservers below
ns-foo-bar1.googledomains.com.
ns-foo-bar2.googledomains.com.
ns-foo-bar3.googledomains.com.
ns-foo-bar4.googledomains.com.
```
=> feat: Add a jx create domain command so we can add domains to managed dns services like Googles

pkg/cmd/step/create/step_create_meta_pipeline.go, pkg/cmd/step/create/step_create_meta_pipeline_test.go, pkg/cmd/step/create/step_create_task.go, pkg/tekton/metapipeline/metapipeline.go, pkg/tekton/metapipeline/metapipeline_test.go
- removing parameters which can be derived from step_create_meta_pipeline
- adding step to merge pull refs in meta pipeline
- making sure the right parameters are passed in step create task in meta pipeline
fixes issue #4551
=> fix(tekton): deriving build related meta information from pull refs

pkg/cmd/controller/controller_build.go, pkg/cmd/get/get_build_logs.go, pkg/cmd/get/get_build_logs_test.go, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pipelineruns.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pipelines.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pods.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/structures.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/taskruns.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/tasks.yml, pkg/cmd/step/create/step_create_task_test.go, pkg/tekton/pipeline_info.go, pkg/tekton/pipeline_info_test.go, pkg/tekton/pipelines.go, pkg/tekton/tekton_helpers_test/test_helpers.go
So let's look for all pipelines that match an org/repo/branch/build number, which will give us both the metapipeline and the generated pipeline.
Tests are still needed, just want to see how this, y'know, *builds*.
fixes #4362
=> fix(tekton): Activity and get build logs should support metapipeline

pkg/builds/build_info.go, pkg/cmd/get/get_build_logs.go, pkg/cmd/get/get_build_logs_test.go, pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/activity.yml, pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/pipelinerun.yml, pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/pod.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/activity.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pipelineruns.yml, pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pipelines.yml, pkg/logs/tekton_logging.go, pkg/logs/tekton_logging_test.go, pkg/logs/test_data/pods.yml
Added an abstraction for logs and enabled long term storage in the CLI
feature: added changes to filtering
feature: fixed the lookup of pipeline activities
feature: renamed the logging file and fix after rebase
feature: finished refactor and added tests
feature: added tests
feature: added batch capabilities
chore: lint and fmt
Added an abstraction layer on the logging so both the CLI and the UI can reuse the same logic.
This is done through the interface `LogWriter` which can be implemented by both to define how to 
deal with logs in different mediums.
The CLI's implementation of `LogWriter` is `CLILogWriter` and streams logs for running builds using `TailLogs`which calls Kubectl and single writes are done through the logger.
Also …
=> feat: Added an abstraction for logs and enabled long term storage in the CLI

pkg/cmd/get/get_build_logs.go, pkg/cmd/step/create/step_create_task.go, pkg/cmd/step/create/step_create_task_test.go, pkg/logs/tekton_logging.go, pkg/logs/tekton_logging_test.go, pkg/logs/test_data/pipelinerun.yml, pkg/tekton/metapipeline/metapipeline.go, pkg/tekton/metapipeline/metapipeline_test.go
Fixes for a number of issues uncovered in the process of getting #4610 to pass.
* Env vars can contain commas, so pass as separate --env
* Pass build number to create task in metapipeline
* Handle logs for runs started after get build logs is called
* Labels should be specified individually as well
* Remove unused combineEnvVars function
fixes #4361
=> fix(tekton): Fixes for metapipeline run from prow

pkg/cmd/importcmd/import.go
Run command line below and found --org and --name parameters doesn't work.
"jx create quickstart --git-username='sonyafenge' --org='sonyafenge' --name='demo070207'"
Check the file "import.go" and found "--org" and "--name" stored in struct "ImportOptions", not in struct "GitGitRepositoryOptions", so config GitGitRepositoryOptions.Owner and GitGitRepositoryOptions.RepoName before func "GetGitRepositoryDetails" call func "PickNewOrExistingGitRepository".
Two rows code changed in function "GetGitRepositoryDetails":
options.GitRepositoryOptions.Owner = options.Organisation
options.GitRepositoryOptions.RepoName = options.Repository
This fix is to reduce the impact to minimum. another way is to fix "AddGitRepoOptionsArguments" in "git.go".
fixes #4549
=> fix: jx create quickstart "--org" and "--name" options doesn't work

pkg/cloud/gke/gcloud.go, pkg/cmd/gc/gc_gke.go, pkg/cmd/step/e2e/step_e2e_gc.go, pkg/cmd/step/e2e/step_e2e_gc_test.go, pkg/cmd/step/e2e/step_e2e_label.go
The e2e GC now checks for clusters on a PR that have old build numbers.
=> chore: Delete bdd clusters that have old build numbers

.goreleaser.yml
Associated with #4596 
`goreleaser` is currently updating jenkins-x/homebrew-jx, however it's doing so by a direct commit to master which is a little dirty in our eyes :). So we'll be moving to our now internal version of `updatebot` (`jx step create pr brew ...`) once it's merged (https://github.com/jenkins-x/jx/pull/4561) to perform the update of the jx binary and it's sha256 sum.
=> fix: disable brew update by goreleaser

jenkins-x-bdd.yml, jenkins-x-integration.yml, jenkins-x-tekton.yml, jenkins-x.yml
Removing the use of jx images and replacing with builder-jx
fixes #
=> fix: Updating to builder-jx

pkg/cmd/create/create_quickstart.go, pkg/gits/git_repo.go
jx create quickstart --org and --name options now work.
Added additional feedback and repo flag `--name` validation to check if it already exists
fixes #4549
=> fix: jx create quickstart --org and --name options

pkg/tekton/syntax/constants.go
For a while now, #4615 has resulted in `gcr.io/jenkinsxio/builder-maven` (and similarly image URLs without tags) always using `latest`, rather than the latest in the version stream. The desired result, however, is to use the pod template image, so let's just be cleaner and use the pod template name here. That'll always resolve correctly in practice.
n/a
=> fix(tekton): Use pod template name for default image

pkg/gits/github.go
Issue reported by @abayer on slack
=> fix: set the release id when a new release is created

pkg/cmd/create/create_mlquickstart.go, pkg/cmd/create/create_quickstart.go, pkg/cmd/get/get_quickstarts.go, pkg/quickstarts/model_test.go, pkg/quickstarts/quickstarts.go, pkg/quickstarts/types.go, pkg/util/strings.go, pkg/util/strings_test.go
This PR addresses several issues relating to machine-learning quickstarts as a new class of quickstart by adding an additional field to QuickstartFilter such that by default it will filter out machine-learning quickstarts unless they are explicitly requested, either as part of `jx create mlquickstart` or by setting the `--machine-learning` flag on other quickstart commands. It also prevents the accidental usage of machine-learning project sets from within `jx create quickstart`.
Invoking `jx create mlquickstart` results in a survey containing only machine-learning project sets and quickstarts.
Invoking `jx create quickstart` and `jx get quickstarts` now shows only non-machine-learning quickstarts.
Invoking `jx create quickstart …
=> fix: Isolate machine-learning quickstarts from conventional quickstarts

pkg/logs/tekton_logging.go, pkg/logs/tekton_logging_test.go
Fixes an infinite loop when running `jx get build logs` for a pipeline without `GetBuildLogsURL` or any active pods.
n/a
=> fix: If no pods are found for a pipeline, don't loop looking for logs

pkg/logs/tekton_logging.go, pkg/logs/tekton_logging_test.go, pkg/logs/test_data/legacy_pipeline_run/pipelinerun.yml, pkg/logs/test_data/legacy_pipeline_run/pods.yml
This is a fix to allow getting build logs for older PipelineRuns (i.e: ones without the Build label)
=> fix: Fixed jx get build logs for old pipeline runs

pkg/cloud/gke/gcloud.go, pkg/cmd/get/get_build_logs.go, pkg/cmd/get/get_build_logs_test.go, pkg/logs/tekton_logging.go, pkg/logs/tekton_logging_test.go
Changed the bucket calls to use gsutil to avoid authentication issues
Modified the way we call buckets to obtain logs to use gsutil instead of gocloud so we can avoid having the user generate application credentials to access the bucket.
Opened #4657 to create the mocks interface and be able to create tests for this.
Which issue this PR fixes
fixes #4661
=> feat: Changed the bucket calls to use gsutil to avoid authentication issues

pkg/builds/build_info.go, pkg/cmd/get/get_build_logs.go, pkg/logs/tekton_logging.go
`PipelineActivity` doesn't have the `context` label, so if you specify `--context=whatever` to `jx get build logs`, it never finds anything. Let's add a function to get the `PipelineActivity`-specific label selectors.
n/a
=> fix: PipelineActivity doesn't have context label so skip in filter

pkg/cmd/preview/preview.go, pkg/kube/services/services.go, pkg/kube/services/services_test.go
This PR changes the behaviour of the setup for post preview jobs. The environment variable `JX_PREVIEW_URL` will now be set to the URL of the external ingress if one is configured, otherwise it will be set to the URL of the internal service local to the namespace.
Construction of the internal URL prefers https over http and common ports over named exotic ports.
Additionally, some new environment variables are created to permit more flexiblity for composing post preview jobs.
I am unable to test RunPostPreviewSteps in a build environment so I would be grateful if someone could smoke test this build or send me a copy of the executable so I can run manual tests?
This fix addresses problems with the owasp-zap addon. Consideration needs to be given …
=> fix: Allow post preview jobs without ingress

pkg/surveyutils/jsonschema.go, pkg/surveyutils/jsonschema_test.go, pkg/surveyutils/test_data/generatedHmacToken.test.schema.json
This allows you to do `”default” : “<generated:hmac>”` in your `*.schema.json` files
fixes #
=> feat: support for <generated:hmac> in schema

pkg/cmd/step/create/pr/step_create_pr.go, pkg/gits/errors.go, pkg/gits/git_cli.go, pkg/gits/git_fake.go, pkg/gits/git_local.go, pkg/gits/github.go, pkg/gits/helpers.go, pkg/gits/interface.go, pkg/gits/mocks/gitter.go
Previously we were using the origin remote as the upstream, which works fine if the users fork is correct (i.e. has the branch which is to be updated) but fails if it doesn’t (e.g. a different user runs the command). By switching to the `pull/<ID>/head` remote on the upstream, we’re guaranteed to always be able to do fetch the branch.
We were also always trying to update a PR, regardless of owner, which won’t work.
Finally, we need to handle the case that rebases don’t ignore
empty commits. This seems to only happen in some cases. This patch
adds the ability to look out for those errors and run `git rebase —skip` if they happen.
fixes #
=> fix: various fixes for the fork / rebase logic

pkg/cmd/create/install.go
CheckFlags() is setting up some flags / variables without knowing if the cluster is a static or serverless one, defaulting to wrong values if you want to create a serverless tekton cluster.
We should ask which type of installation the users wants before calling CheckFlags().
Testing locally installing a new cluster using `jx create cluster gke` then creating a new quickstart.
Without the fix the pipeline was not triggered with the following logs in the pipeline runner:
```{"level":"error","msg":"failed to create effective project configuration: Missing option: --docker-registry failed to create effective project configuration: Missing option: --docker-registry","time":"2019-07-15T09:29:50Z"}```
With this fix, the pipeline is running fine.
fixes #4557
=> fix: select install type before checkFlags

pkg/cmd/boot/boot.go, pkg/cmd/step.go, pkg/cmd/step/boot/step_boot.go, pkg/cmd/step/boot/step_boot_upgrade.go, pkg/cmd/step/boot/step_boot_vault.go
Fixes a clash with `jx step boot vault` and `jx step boot upgrade`
Signed-off-by: David Conde <dconde@cloudbees.com>
=> chore: Refactor step boot to contain base command

jenkins-x-bdd.yml, jenkins-x-images.yml, jenkins-x-tekton.yml, jenkins-x.yml, jx/bdd/tekton/ci.sh, jx/scripts/ci.sh, myvalues.yaml.tekton.template, myvalues.yaml.template
When running e2e tests, Instead of copying the jx binary with the PR changes into an old jx docker image, use the docker image build and pushed by the pipeline.
I've also replaced the references to Docker Hub registry with Google Cloud Registry.
=> feat: use the docker image that we just built as step image in pipelines

jenkins-x.yml
This got changed inadvertently and overlooked, so now `controllerworkflow` can't start, because it's using `jenkinsxio/jx:VERSION`, not `gcr.io/jenkinsxio/jx:VERSION`. So...let's roll that back to push to docker.io. Figured this out due to failures on https://github.com/jenkins-x/jenkins-x-versions/pull/331.
n/a
=> fix: Push jenkinsxio/jx:VERSION to docker.io, not gcr.io

pkg/cmd/step/create/pr/step_create_pr_chart.go
This helps with #4771 (though I don't think it fixes _everything_, since we still end up making changes to the PR for each `jx step create pr ...` call rather than batching all those changes into one push), so I think it's worth doing on its own.
Not sure how to test this without writing a full-on test framework for `jx step create pr ...`, which we obviously do need to do, but that's a followup IMO.
n/a
=> fix: Allow updating multiple charts in a single `jx step create pr chart`

pkg/cloud/gke/helper.go, pkg/cloud/gke/helper_test.go, pkg/cmd/create/create_cluster_gke.go, pkg/cmd/create/create_domain_gke.go, pkg/cmd/create/create_vault.go, pkg/cmd/create/install.go, pkg/cmd/deletecmd/delete_vault.go, pkg/cmd/gc/gc_gke.go, pkg/cmd/opts/bucket.go, pkg/cmd/opts/gcp.go, pkg/cmd/step/verify/step_verify_preinstall.go
Fixes #4792
With this change the user is prompted:
```
...
Currently connected cluster is facelie in europe-west1-b in project apps-dev-229310
? Do you want to jx boot the facelie cluster? Yes
...[? for help] 
```
If they are already connected to a cluster and select Y at the confirmation prompt. If they select N, they will get something like
```
Currently connected cluster is facelie in europe-west1-b in project apps-dev-229310
? Do you want to jx boot the facelie cluster? No
? Google Cloud Project: apps-dev-229310
? Google Cloud Zone: europe-west1-b
? Cluster name [? for help] (facelie)
```
If they aren’t connected to a cluster they will get something like:
```     
Enter the cluster you want to jx boot
? Google Cloud Project: apps-dev-229310
? Google Cloud Zone: <pick list with …
```
=> fix: use current cluster in jx boot

jx/scripts/ci.sh
It's failing due to there not being a `production` environment in the `jx-bdd-tests` cluster we reuse for each `bdd` run. With https://github.com/jenkins-x/bdd-jx/pull/47, this env var lets us skip that manual promotion here but leave it on everywhere else.
/assign @fiunchinho 
n/a
=> fix: Disable manual promotion test in bdd context
