jenkins-x/jx

pkg/cmd/create/install.go

Default use of long term storage for logs during install, unless `--advanced-mode` is used

Default long term log storage

---

pkg/cloud/gke/gcloud.go
pkg/cloud/gke/storage/long_term_storage.go

Add a `created-by` label to long term storage buckets for easier identification

Add user label to lts bucket

---

pkg/cmd/step/create/step_create_task.go

Without this, we use the original `pipelineConfig`, which may not have its pipelines populated.
n/a

fix(tekton): Pass the updated pipelineConfig, not the stale one

---

pkg/cmd/get/get_build_logs.go

The pod for a stage after an earlier stage has failed will never actually get created, so just skip it.
#4305 opened to track the need to create tests for this.
fixes #4303

fix(tekton): Don't wait for pods for stages after a failure

---

pkg/cmd/clients/factory.go
pkg/cmd/opts/install.go
pkg/kube/services/services.go

if folks wanna create Ingress resources by hand, lets ensure we use those instead of exposecontroller annotations

fix: fix service URL discovery so it can work without exposecontroller

---

pkg/cmd/opts/helm.go
pkg/cmd/opts/install.go
pkg/cmd/preview/preview.go

Signed-off-by: rawlingsj <rawlingsj80@gmail.com>

fix getting secrets from vault when deploying to preview environments

---

pkg/cmd/get/get_preview.go

fix: make it easier to capture the preview URL from scripts/shell

---

.gitignore
.goreleaser.yml
Makefile

This contributes towards #4120

feat: Updated release process to use goreleaser

---

go.mod
pkg/cmd/opts/step.go
pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/git/step_git_merge.go
pkg/cmd/step/git/step_git_merge_test.go
pkg/gits/testhelpers.go

fix: making sure the right Run function is called for step git merge

---

pkg/cmd/step/create/test_data/step_create_task/add-env-to-default-in-buildpack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps-in-jenkins-x-yml/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/command-as-multiline-script/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/correct-pipeline-stage-is-removed/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/default-in-buildpack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/default-in-jenkins-x-yml/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/from_yaml/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/maven_build_pack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/override_block_step/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/per_step_container_build_pack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/pipeline-timeout/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/remove-stage-from-jenkins-x-yml/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/remove-stage/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps-in-jenkins-x-yml/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
pkg/tekton/syntax/pipeline.go

fix: updating git merge image used in Tekton pipeline

---

pkg/cmd/create/create_addon_owasp.go
pkg/cmd/create/create_post_preview_job.go

Adds explict timestamps to spec.teamSettings.postPreviewJobs.metadata.creationTimestamp and
spec.teamSettings.postPreviewJobs.spec.template.metadata.creationTimestamp in order to pass validation.
fixes #4289

fix: Added missing timestamps

---

pkg/apps/values.go
pkg/cmd/add/add_app_test.go
pkg/cmd/step/create/test_data/step_create_values/install/values.schema.json
pkg/cmd/step/create/test_data/step_create_values/install/values.yaml.golden
pkg/surveyutils/jsonschema.go
pkg/surveyutils/jsonschema_test.go
pkg/vault/fake/client.go

fix: remove the secret abstraction in jsonschema

---

pkg/cloud/gke/gcloud.go
pkg/cmd/create/create_cluster_gke.go
pkg/cmd/create/create_terraform.go
pkg/cmd/opts/common.go

reduced info logging to debug during install

chore: reduced install logging further

---

pkg/cloud/gke/gcloud.go
pkg/cmd/create/create_terraform.go
pkg/cmd/opts/auth.go

no longer returning an error if unable to connect to a cluster for 
secrets, increased privs for terraform SA because it needs to create
other SA accounts

fix: 'jx create terraform' working again with increased priv

---

pkg/cmd/create/create_user.go
pkg/cmd/create/create_user_integration_test.go
pkg/kube/names.go

fix: if the user is fully numeric, prepend an X

---

pkg/cmd/create/create_cluster_aws.go
pkg/cmd/create/create_cluster_eks.go
pkg/cmd/create/create_cluster_gke.go
pkg/cmd/create/create_terraform.go
pkg/cmd/create/install.go
pkg/cmd/opts/common.go
pkg/cmd/step/env/step_env_apply.go
pkg/cmd/step/helm/step_helm_apply.go
pkg/cmd/step/verify/common.go
pkg/cmd/step/verify/step_verify.go
pkg/cmd/step/verify/step_verify_install.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/step_verify_preinstall_test.go
pkg/cmd/step/verify/test_data/preinstall/no_kaniko_or_terraform/jx-requirements.yml
pkg/cmd/step/verify/test_data/preinstall/terraform_kaniko/jx-requirements.yml
pkg/config/install_requirements.go

to ensure the required cloud resources are created (the jx ns and kaniko
secret)

fix: add a 'jx step verify preinstall' step

---

pkg/cmd/step_bdd.go
pkg/util/commands.go

chore: improve formatting of `step bdd` status report

---

pkg/cmd/step/create/step_create_task_test.go
pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/jenkins-x.yml
pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/pipeline.yml
pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/pipelineresources.yml
pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/pipelinerun.yml
pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/structure.yml
pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/packs/maven-with-resource-limit/pipeline.yaml
pkg/jenkinsfile/pipeline.go

We weren't copying over the build pack's `containerOptions` on extension, so let's do that.
fixes #4369

fix(tekton): Pick up build pack top-level containerOptions properly

---

go.mod

chore: set a valid version for bank-vaults

---

.goreleaser.yml
Makefile

fix: Resolving lack of tags in repo during release

---

.goreleaser.yml

Try and implement a separate build for each binary

---

pkg/cmd/step/verify/step_verify_preinstall_test.go
pkg/prow/env_vars_test.go

Chore: Added retry around some tests which appear to be flaky

---

Makefile

Also added 'dist' to the list of directories to be cleaned up

Fix path to linux binary when calling changelog

---

Makefile

Allow changelog step to update the release

---

go.mod
go.sum
pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/create/pr/step_create_pr_chart.go
pkg/cmd/step/create/pr/step_create_pr_docker.go
pkg/cmd/step/create/pr/step_create_pr_regex.go
pkg/gits/git_cli.go
pkg/gits/git_fake.go
pkg/gits/git_local.go
pkg/gits/helpers.go
pkg/gits/interface.go
pkg/gits/mocks/gitter.go
pkg/helm/helm_helpers.go
pkg/util/regex.go
pkg/util/regex_test.go

feat: add support for regex and chart based version updates

---

pkg/cmd/create/create_cluster_gke.go
pkg/cmd/create/create_cluster_gke_test.go

Fix AddLabel, it was over sanitizing
Fixes #4467

Fix AddLabel

---

pkg/cmd/step/syntax/step_syntax_effective.go

Otherwise we can end up with a nil pointer here, which is, y'know, bad.
/assign @wbrefvem 
n/a

fix(tekton): Make sure parsed.Options is initted.

---

.gitignore
Makefile

fix: Ignoring temporary edits when releasing

---

semantic.yml

Configure https://github.com/probot/semantic-pull-requests to force all commits and PR titles to be conventional
fixes #

chore: configure semantics-commits bot

---

pkg/cmd/step/create/step_create_task.go

Metapipeline fun - if we don't clone first, we end up with no repo, which unsurprisingly is bad when we try to get the `GitInfo`. If the repo's already cloned (as will be the case when we switch over to `jx
step create pipeline`), we don't need to clone here, but for now...
I've tested this by hand after reproducing the original issue by hand, and it works, so yay. This sort of thing will get caught automatically once #4301 lands.
fixes #4478

fix(tekton): Clone before getting GitInfo in step create task

---

go.mod
pkg/cmd/create/create_cluster_gke.go
pkg/cmd/create/install.go
pkg/cmd/opts/common.go
pkg/cmd/opts/common_test.go

Use [Viper](https://github.com/spf13/viper) in conjunction with the Cobra CLI to allow cluster creation config to be specified via yaml

feat: Create cluster GKE using yaml config

---

pkg/cmd/create/create_addon_istio.go

cache it locally under `~/.jx/cache`
in case of flaky networks
fixes #

feat: do not redownload istio tarball

---

Makefile

chore: better document how the test targets works

---

pkg/surveyutils/jsonschema.go

fix: allow environment variables to be used in batch mode for defaults

---

jenkins-x-bdd.yml
jenkins-x-integration.yml
jenkins-x-tekton.yml
jenkins-x.yml

the `jx-ts-client` update in the release is failing due to being on an old builder image, so let's just bump everything to a consistent version.
n/a

fix: Update jenkins-x[-context].yml builder images

---

pkg/cmd/opts/install.go

added .exe in minikube download url, when in windows environment
fixes #4463

fix: added .exe to minikube download url for windows

---

pkg/apis/jenkins.io/v1/types_environment.go

fix: support legacy prow configuration mode

---

.github/semantic.yml
semantic.yml

fix: configuring semantic commit bot to check all commits

---

jx/scripts/update-bot.sh

chore: replace updatebot with jx step create pr

---

pkg/tekton/pipeline_info.go

chore(tekton): Forgot to add build number to PRI name

---

Makefile

chore: only fetch the current tag

---

jx/scripts/update-bot.sh

chore: fix the path to the jx binary

---

.goreleaser.yml
.updatebot.yml
jx/scripts/update-bot.sh

Get goreleaser to generate the update for homebrew, should hopefully fix https://github.com/jenkins-x/jx/issues/4503

fix: Adding brew config for goreleaser

---

pkg/cmd/create/install.go

Allowing the following config to be set via the `--config-file`
```
install:
tekton:
prow:
static-jenkins:
next-generation:
gitops:
```

feat: Install type config enabled

---

pkg/cloud/gke/storage/long_term_storage.go
pkg/cmd/create/create_vault.go
pkg/cmd/create/install.go

Enable lts config and tidy up some logging during install

feat: long term storage config enable

---

jx/scripts/update-bot.sh
pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/create/pr/step_create_pr_repositories.go

fix: specify the repo for updatebot

---

pkg/cmd/create/create_pullrequest.go
pkg/cmd/step/create/pr/step_create_pr.go
pkg/environments/gitops.go
pkg/gits/helpers.go
pkg/gits/interface.go

fix: sort and dedupe versions

---

.codecov.yml
jenkins-x-tekton.yml
jx/bdd/tekton/ci.sh
jx/bdd/tekton/cluster.yaml
myvalues.yaml.tekton.template
pkg/cmd/deletecmd/delete.go
pkg/cmd/deletecmd/delete_gke.go
pkg/cmd/step.go
pkg/cmd/step/e2e/step_e2e.go
pkg/cmd/step/e2e/step_e2e_gc.go
pkg/cmd/step/e2e/step_e2e_label.go
pkg/cmd/step_bdd.go

This is waiting for @daveconde to nail down cluster cleanup before it's ready to merge.
/hold

chore(tekton): Add Tekton BDD test context to PRs

---

pkg/cmd/deletecmd/delete_application.go
pkg/cmd/get/get_applications.go
pkg/cmd/get/get_issue.go
pkg/cmd/opts/team_settings.go
pkg/cmd/step/step_release.go
pkg/cmd/step/verify/step_verify_environments.go

we may not have started the tekton pipeline yet so lets not fail early if there are no pipelines yet

fix: avoid failing early in wait mode

---

jx/scripts/update-clients.sh
pkg/cmd/step/git/step_git_fork_and_clone.go

fix: write the directory to stdout

---

pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repogroup_scheduler/config.yaml
pkg/pipelinescheduler/builder.go

fix: Remove duplicate branches from post submits

---

pkg/cmd/create/create_cluster.go

Allows `skip-installation` to be specified within the `--config-file` file

feat: Enable skip install config

---

pkg/cmd/step/git/step_git_merge.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go

Removed verbose flag, using Debugf instead

chore: minor logging improvements to git helper

---

pkg/cmd/step/create/step_create_meta_pipeline.go
pkg/tekton/metapipeline/metapipeline.go
pkg/tekton/metapipeline/metapipeline_test.go

fix(tekton): skiping git merge step if there are no pull refs to merge

---

jenkins-x-images.yml
jenkins-x-integration.yml
jenkins-x-lint.yml
jenkins-x-tekton.yml
jenkins-x.yml

Remove the use of rawlingsj and use standard build images
fixes #

fix: standardise build images

---

pkg/cmd/gc/gc_gke.go

Also enabled default flags such as --batch-mode & --verbose

feat: 'jx gc gke' can select a project

---

pkg/gits/provider_test.go

fix(tests): wrap a flaky test in retry

---

pkg/gits/helpers.go

Currently if there is more than one PR that has the
label `updatebot` then a new PR will be created. With
this change the most recent one will be rebased instead.
fixes #

fix: choose the most recent PR to rebase

---

pkg/cmd/controller/pipelinerunner.go

fix: pass the semantic release flag through

---

.pre-commit-config.yaml
.secrets.baseline
CONTRIBUTING.MD

feat: added pre-commit configuration and secrets basline

---

pkg/cmd/start/start_pipeline.go
pkg/gits/bitbucket_cloud.go
pkg/gits/bitbucket_server.go
pkg/gits/gerrit.go
pkg/gits/gitea.go
pkg/gits/github.go
pkg/gits/gitlab.go
pkg/gits/interface.go
pkg/gits/mocks/git_provider.go
pkg/gits/provider.go
pkg/gits/provider_fake.go
pkg/util/types.go

chore: expose PULL_BASE_SHA to jx start pipeline

---

pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/create/pr/step_create_pr_make.go
pkg/cmd/step/create/pr/step_create_pr_regex.go

Also add support for named capturing groups
fixes #

feat: add jx step create pr make

---

jx/scripts/update-bot.sh

Associated with #4596 
Update the version of brew using the new create pr command
This change depends upon #4561

feat: Brew package version update using new create pullrequest [command]

---

pkg/cmd/step/create/pr/step_create_pr_brew.go

fix: removing override of validate options

---

pkg/cmd/controller/pipelinerunner.go

fix: git server url is hardcoded in pipelinerunner #4588

---

pkg/cmd/step/create/pr/step_create_pr.go

* prevent a panic by ignoring missing releases
* fail fast if source repo cannot be determined
fixes #

fix: couple of fixes for new updatebot

---

pkg/cmd/step/e2e/step_e2e_gc.go

Pass pipes through to the gc script command

chore: Enable logging from the GC script so its easier to see failed cleanup

---

pkg/cmd/get/get_build_logs.go
pkg/logs/tekton_logging.go
pkg/logs/tekton_logging_test.go

Improvements on the logs filters.
The context should be added to `PipelineActivity` in the future so we could avoid the first call on `PipelineRun` and the manipulation of filters.

feat: some improvements on jx get build logs filters

---

pkg/cmd/opts/version.go
pkg/cmd/step/verify/step_verify.go
pkg/cmd/step/verify/step_verify_packages.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/version.go
pkg/config/install_requirements.go
pkg/version/test_data/jenkins-x-versions/packages/kubectl.yml
pkg/version/version_data.go
pkg/version/version_data_test.go

supporting both exact ranges or ranges depending on the data in the version stream
added an environment variable override mechanism for testing
fixes #4697

fix: add validation steps to verify the CLI packages are valid

---

pkg/cmd/create/create_addon_environment_controller.go

fix: Make Environment Controller work with private repo

---

pkg/cmd/step/create/pr/step_create_pr_chart.go

fix: handle spaces properly

---

pkg/gits/github.go
pkg/gits/helpers.go
pkg/gits/provider.go

Cover the case that the user who created the PR pushed to a fork other than their own
fixes #

fix: correct user for repo

---

pkg/cmd/step/step_changelog.go
pkg/gits/git_cli.go
pkg/gits/git_fake.go
pkg/gits/git_local.go
pkg/gits/interface.go
pkg/gits/mocks/gitter.go

fix: don’t retag in step changelog

---

pkg/cmd/step/verify/step_verify_preinstall.go

Trim requirements input, to help the user not enter invalid values.

chore: trim requirement inputs

---

pkg/cmd/version.go

When running `jx version`, jx is constantly asking current user "Would you like to upgrade to the new jx version?" even if the current version is already up to date.
With this change, jx only asks this question if current version is lower than the latest one. 
fixes #4496

fix: do not try to upgrade CLI if current version is already up to date

---

pkg/logs/tekton_logging.go
pkg/logs/tekton_logging_test.go

Just an informative message when the bucket config is not present, it was making the UI to fail.

feat: handle different schemes on get build logs

---

pkg/gits/helpers.go

fix: amend PR title

---

pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/create/step_create_task_integration_test.go
pkg/cmd/step/git/step_git_merge.go
pkg/cmd/step/git/step_git_merge_test.go
pkg/gits/git_cli.go
pkg/gits/git_cli_test.go
pkg/gits/provider.go
pkg/gits/provider_test.go
pkg/gits/testhelpers.go
pkg/tekton/metapipeline/metapipeline.go
pkg/tekton/metapipeline/metapipeline_test.go

 fix: adding info about merged commits for step git merge

---

pkg/gits/git_cli.go
pkg/gits/git_cli_test.go

fix: don’t add a filter for “”

---

jenkins-x.yml

We're not building images with the release version here yet, so we shouldn't be using them in the release pipeline.
n/a

fix: Use existing images for release pipeline

---

jenkins-x.yml

fix: Use a jx image that actually exists.

---

pkg/cmd/step/git/step_git_merge_test.go
pkg/gits/git_cli.go
pkg/gits/git_cli_test.go
pkg/gits/testhelpers.go

 fix(git): improve GetCurrentGitTagSHA and GetPreviousGitTagSHA implementation

---

go.mod
go.sum
myvalues.yaml.tekton.template
pkg/builds/build_info.go
pkg/cmd/controller/controller_build.go
pkg/cmd/controller/controller_build_test.go
pkg/cmd/controller/controller_enviornmentcontroller.go
pkg/cmd/controller/pipelinerunner.go
pkg/cmd/step/create/step_create_meta_pipeline.go
pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/create/step_create_task_test.go
pkg/cmd/test_data/controller_build/update_stage_info_pre_tekton_0.5.1/pod.yml
pkg/kube/pod.go
pkg/logs/tekton_logging.go
pkg/tekton/metapipeline/metapipeline.go
pkg/tekton/metapipeline/metapipeline_test.go
pkg/tekton/pipeline_info.go
pkg/tekton/pipeline_info_test.go
pkg/tekton/pipelines.go
pkg/tekton/syntax/pipeline.go
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/activity.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/pipeline.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/pipelineresources.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/pipelinerun.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/pods.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/structure.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/taskruns.yml
pkg/tekton/test_data/pipeline_info/from-yaml-pre-tekton-0.5/tasks.yml

Testing Tekton v0.5.0 (waiting for v0.5.1 to release shortly).
n/a

chore(tekton): Update to Tekton v0.5.1

---

pkg/cmd/step/verify/step_verify_preinstall.go

Suggest the currently connected cluster name as the one to use with `jx boot`

chore: Suggest currently connected cluster name

---

pkg/cmd/gc/gc_gke.go

Do not remove iam policy bindings if they are in use
fixes #

fix: GC GKE - IAM Policy bindings

---

pkg/cmd/step/verify/step_verify_preinstall.go

fix: improve text for long term storage

---

README.md

- [N/A] Change is covered by existing or new tests.
Updates the `http://` URLs in the README to `https://` - both jenkinsx.io and nip.io have working https 
No code changes.
No issue raised - documentation issue.

chore: change http:// links to https:// in README.md

---

pkg/cmd/boot/boot.go
pkg/cmd/create/create_addon_vault.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/kube/constants.go

Make sure helm is installed correctly and the jenkins-x repo is added

fix: Make sure helm is setup correctly when using boot

---

pkg/cmd/step/helm/step_helm_apply.go

fix: log the error

---

pkg/cmd/step/verify/step_verify_preinstall.go

Correct `jx boot` requirements error messages

fix: preinstall requirements error messages

---

pkg/cmd/create/create_vault.go
pkg/cmd/step/boot/step_boot_vault.go
pkg/cmd/step/create/step_create_install_values.go
pkg/cmd/step/create/step_create_install_values_test.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go
pkg/config/install_requirements_test.go

fix: avoid use of env/cluster/values.yaml

---

pkg/config/install_requirements.go

fix: add optional git server, name and kind

---

go.mod
go.sum
pkg/cmd/opts/version.go
pkg/cmd/step/helm/step_helm_apply.go
pkg/cmd/step/verify/step_verify.go
pkg/cmd/step/verify/step_verify_git.go
pkg/cmd/step/verify/step_verify_packages.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/step_verify_requirements.go
pkg/cmd/step/verify/step_verify_requirements_integration_test.go
pkg/cmd/step/verify/test_data/verify_requirements/boot-config/env/requirements.yaml
pkg/version/test_data/jenkins-x-versions/charts/repositories.yml
pkg/version/version_data_test.go

to verify the requirements.yaml files have the versions populated from the
version stream

fix: add 'jx step verify requirements'

---

pkg/cmd/step/syntax/step_syntax_effective.go
pkg/cmd/step/syntax/step_syntax_effective_test.go

Otherwise we don't know what exactly to run in `setBuildVersion`.
fixes #4844

fix(tekton): Make sure the effective pipeline yml contains release.setVersion

---

pkg/cmd/opts/common.go
pkg/cmd/opts/helm.go
pkg/cmd/step/step_next_version.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
pkg/cmd/step/verify/test_data/preinstall/no_kaniko_or_terraform/jx-requirements.yml

fix: for boot helm init

---

pkg/cmd/upgrade/upgrade_addon_prow.go
pkg/cmd/upgrade/upgrade_addons.go

Defer to the `jx upgrade add on prow` command when upgrading all add ons including jx-prow.
fixes #3392
https://github.com/jenkins-x/jx/issues/3392

fix: use the upgrade addon prow command

---

pkg/cmd/create/create_variable.go

fix: Typo in create var dialog

---

pkg/apps/gitops.go
pkg/cmd/boot/boot.go
pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/git/step_git_fork_and_clone.go
pkg/cmd/step/helm/step_helm_apply.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/config/install_requirements.go
pkg/environments/gitops.go
pkg/gits/git_cli.go
pkg/gits/git_fake.go
pkg/gits/git_local.go
pkg/gits/github.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/gits/interface.go
pkg/gits/mocks/gitter.go
pkg/gits/provider_fake.go

* add REPO_URL env var
* add support for duplicating repos (vs fork) as described at https://help.github.com/en/articles/duplicating-a-repository with test
* improve `jx step verify environment` to create git repo for dev env and PR changes
* add `CloneBare` and `PushMirror` to `Gitter`
* fix bugs in GitHub provider
* compute the unique branch name for the push URL not the local URL
* fix gitter.RemoteBranchNames to actually filter on the prefix
* support in `FakeProvider` for creating repos that are backed
contributes to  #4789

feat: create dev repo during pipeline & pr config

---

pkg/apps/gitops.go
pkg/cmd/boot/boot.go
pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/git/step_git_fork_and_clone.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/environments/gitops.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go

Rather than making a duplicate during the fork
we need to make a duplicate first and then use the
normal fork logic to handle the user/org scenario.
There are no tests for the duplicator right now, I'll do those next in a separate PR.
fixes #

fix: need to duplicate the repo first

---

pkg/gits/helpers.go
pkg/gits/helpers_test.go

fix: handle branch as committing for duplicating git repo

---

pkg/boot/constants.go
pkg/cmd/create/create_pullrequest.go
pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/environments/gitops.go
pkg/gits/helpers.go

* add `jx/boot` label to PRs create by `jx boot`
* rebase any PRs with the `jx/boot` label on subsequent runs
No tests, will add them in subsequent PR when I finish the partially complete test framework for the PR creation functions
contributes to #4789

feat: rebase existing PR during jx boot

---

README.md

docs: remove former logo from README.md

---

pkg/cmd/create/create_cluster_gke.go
pkg/cmd/create/create_terraform.go
pkg/cmd/create/create_terraform_gke.go

feat: allowing static-jenkins flag when using terraform

---

pkg/cmd/step/create/pr/step_create_pr.go
pkg/gits/operations/pull_request_op.go
pkg/gits/operations/pull_request_op_test.go

Refactored the create PR logic into a different package and added some tests

feat: add tests to create PR and refactor

---

pkg/config/install_requirements.go

the git clone doesn't handle logical version numbers just yet but can do tags so for semantic versions of the version stream repo lets add a `v` prefix to turn it into a tag
when we refactor the git code later on for more consistency we can remove this

fix: lets use the tag not version for version stream in boot

---

pkg/cmd/initcmd/init.go

fix: run `helm repo update` when installing ingress

---

jx/bdd/tekton/ci.sh

This won't pass until https://github.com/jenkins-x/bdd-jx/pull/54 is merged, but I'm going to be out the next few days, so might as well get this queued up. =)
/assign @fiunchinho 
n/a

chore(tekton): Add BDD test using jenkins-x.yml to Tekton context

---

pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/gits/provider_fake.go

* now has a fork and join flow rather than tree flow
* adds tests for major scenarios
fixes # 4789

fix: refactor create pull request

---

pkg/cmd/preview/preview.go

When `http.Get` failed with error it will trigger `backoff. Permanent` which will tell backoff to stop trying. This fix is to restore ExponentialBackoff functionality. 
`backoff` will exponentially back off for a total of 5 mins before it stops trying and fail. 
fixes #

fix: Exponential backoff while waiting for DNS to propagate

---

.secrets.baseline
pkg/cloud/gke/gcloud.go
pkg/cloud/gke/gcloud_test.go
pkg/cmd/step_bdd.go

fix: don't rely on specific name format for dns managed-zones

---

pkg/cmd/boot/boot.go

fix: allow boot config git ref to be overridden

---

jx/scripts/update-bot.sh

chore: Add jenkins-x-builders-ml to update-bot.sh

---

pkg/cmd/step/git/step_git_validate.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go

Still need to actually wire this in to `jx-requirements.yaml`
fixes #4903

fix: support private repos

---

pkg/cmd/boot/boot.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go

There was an issue when executing boot on a brand new cluster that was making it impossible to create the dev environment.
By only checking for the git version on the main repository, we avoid having to create tags when executing boot on forks.
We are passing the ref of the boot config repository by using the `BASE_CONFIG_REF` env variable.
Also, we will now get the URL and current branch from the directory passed by `--dir` (or `.`). Otherwise an URL would need to be passed by `--git-url` if someone wanted to use a fork.
This way you only need to define the directory, but it would still get overwritten by what is defined in `--git-url` and `--git-ref`.
I'd like some comments on the last change (getting the git configuration from the …

feat: only check for tags on the main repository when creating the environments

---

pkg/cmd/deletecmd/delete_devpod.go

Enable batch mode in delete devpod. This is needed to facilitate end to end tests.
fixes #

fix: Enable batch mode in delete devpod

---

.secrets.baseline
pkg/cmd/step/verify/step_verify_preinstall.go

fix: moved error check to ensure that namespace is verified

---

.secrets.baseline
pkg/config/install_requirements.go

fix: updated incorrect requirements environment variable

---

.pre-commit-config.yaml
.secrets.baseline
pkg/cmd/step/verify/step_verify_preinstall.go

feat: added a flag to jx boot to avoid cluster reconnection if using workload identity

---

pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/create/pr/step_create_pr_go.go
pkg/cmd/step/create/pr/step_create_pr_regex.go

fix: add a CLI command to create a PR for go module updates

---

pkg/cmd/get/get_issues.go
pkg/cmd/opts/git.go
pkg/cmd/step/git/step_git.go
pkg/cmd/step/git/step_git_close.go
pkg/gits/bitbucket_cloud.go
pkg/gits/bitbucket_server.go
pkg/gits/constants.go
pkg/gits/errors.go
pkg/gits/features/disable_features.go
pkg/gits/features/disable_features_test.go
pkg/gits/gerrit.go
pkg/gits/git_url.go
pkg/gits/git_url_test.go
pkg/gits/gitea.go
pkg/gits/github.go
pkg/gits/gitlab.go
pkg/gits/interface.go
pkg/gits/mocks/git_provider.go
pkg/gits/operations/pull_request_op.go
pkg/gits/provider.go
pkg/gits/provider_fake.go
pkg/issues/constants.go

This will close issue trackers, projects and wikis not currently in use
Fixes #4881

feat: add jx step git close

---

pkg/cmd/preview/preview.go

fix: updated logic to correct scenario

---

pkg/cmd/promote/promote.go

fix: make promote pr title & commit a semantic style message

---

go.mod
go.sum
pkg/cmd/controller/controller_build.go
pkg/cmd/controller/controller_build_test.go
pkg/kube/constants.go
pkg/tekton/metapipeline/metapipeline.go

this is a tactical solution; we are hoping longer term to use tekton PullRequestResource outputs instead

fix: added optional git reporting of pipelines for lighthouse

---

jenkins-x-bdd.yml
jenkins-x-tekton.yml

This got missed earlier. =)
/assign @pmuir
n/a

fix: Remove codecov from tekton context

---

pkg/jenkins/health.go

chore: fix spelling of healthy

---

pkg/cmd/create/create_jenkins_token.go

* Change spelling of "teh" to "the" in the flag help message for --recreate-token.
* Capitalize Jenkins in Run func string
* Improve grammar
* Capitalize Jenkins in error string
Signed-off-by: Joshua Swick <joshuaswickirl@gmail.com>
Repaces #4723 with conventional commit
fixes #4723

chore: Fix typos and grammar

---

pkg/cmd/controller/pipelinerunner.go
pkg/logs/tekton_logging.go

fix: making meta pipeline the default in pipelinerunner

---

charts/jx/templates/deployment.yaml

fix: revert bad change in quoting that seems to cause issues

---

pkg/cmd/boot/boot.go

`o.GitRef` flag was being used even when not set
fixes #5016

fix: auto clone boot config failing

---

jenkins-x-bdd.yml
jenkins-x-images.yml
jenkins-x-integration.yml
jenkins-x-tekton.yml
jenkins-x.yml

And while I was here, just update all the builder images to use a consistent version.
Picks up the fix from #5022, killing off #4785 properly.
n/a

fix: Update images used in release pipeline for double PR fix

---

pkg/cmd/clients/factory.go
pkg/kube/services/services.go
pkg/kube/vault/vault.go
pkg/kube/vault/vault_factory.go

Whilst fixing a gcpreview issue #4970 I added some useful logging for debugging vault issues
fixes #

chore: add debug logging for vault

---

jenkins-x-bdd.yml
jenkins-x-tekton.yml

This uploads the junit report as an HTML report to a Google Bucket.
The idea is to later publish the bucket on an easy to remember URL that serves the HTML report, so we can always take a look at the latest report.

chore: generate html report for tests and upload it

---

pkg/cmd/update/update_webhooks.go
pkg/gits/gitlab.go

also lets properly detect gitlab webhooks which include a suffix

fix: avoid duplicate webhooks with jx boot

---

pkg/cmd/cmd.go
pkg/cmd/create/create_lile.go
pkg/cmd/create/create_micro.go
pkg/cmd/create/install.go
pkg/cmd/opts/common.go
pkg/cmd/step/create/step_create_meta_pipeline.go
pkg/cmd/step/scheduler/step_scheduler_config_apply.go
pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
pkg/cmd/step/step_custom_pipeline.go
pkg/cmd/step/syntax/step_syntax_effective.go
pkg/cmd/upgrade/upgrade_cli.go

fix: separating global flag options and install/create cluster flags

---

pkg/cmd/boot/boot.go
pkg/gits/git_cli.go
pkg/gits/git_fake.go
pkg/gits/git_local.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/gits/interface.go
pkg/gits/mocks/gitter.go
pkg/gits/provider.go

Please review but I want to get @chrismellard to try the fix out before we merge it ideally.
fixes #4931

fix: handle existing commits on local branch

---

pkg/cmd/boot/boot.go

fix: allow the cloudbees profile to override

---

pkg/cmd/boot/boot.go
pkg/config/install_requirements.go

fix: use the stream specified

---

pkg/cmd/promote/promote.go

Signed-off-by: Wei Cheng <calvinpohwc@gmail.com>
fixes #

fix: typo `promomote ` to `promote`

---

pkg/cmd/controller/controller_build.go
pkg/cmd/get/get_build_logs.go
pkg/cmd/get/get_build_logs_test.go
pkg/logs/tekton_logging.go
pkg/logs/tekton_logging_test.go

Various fixes to the formatting of logs, it also now controls the flow of the streaming, avoiding to show empty steps after a previous one has failed.
Made a big refactor around the writers, before this, each implementation was responsible to get the logs from the pods / containers, which led to discrepancies. This was wrong as the implementation should only focus on showing the logs the way they need and not on how to obtain them.
Now we make use of channels to send / receive instances of LogLine, which also contains some metadata (in this case, whether the line should be masked or not) this also leaves the masking ( and how to do it ) to the implementation's choice.
Making use of LogWriters, I modified the implementation of `controllerbuild` to obtain the logs in order to store them the …

feat: refactor tekton logging and skip steps on failure

---

pkg/cmd/create/create_addon_vault.go
pkg/cmd/create/create_vault.go
pkg/kube/vault/vault.go

Use the vault operator version from the vault-operator in jenkins-x-charts (https://github.com/jenkins-x-charts/vault-operator/blob/master/vault-operator/values.yaml)
This should then allow us to remove the version info in the jenkins-x-versions (https://github.com/jenkins-x/jenkins-x-versions/blob/master/docker/banzaicloud/vault-operator.yml) 
fixes #4988

fix: Use vault operator version from chart

---

Dockerfile.builder-go
pkg/cmd/controller/controller_build.go
pkg/cmd/step/boot/step_boot_vault.go
pkg/cmd/step/git/step_git_merge.go
pkg/cmd/step/git/step_git_merge_test.go
pkg/cmd/step/verify/step_verify_git.go
pkg/cmd/step/verify/step_verify_install.go
pkg/cmd/step/verify/step_verify_pod_ready.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/helm/values_tree.go
pkg/kube/services/services.go
pkg/kube/vault/vault.go
pkg/logs/tekton_logging.go
pkg/surveyutils/jsonschema.go
pkg/surveyutils/jsonschema_test.go
pkg/tekton/metapipeline/metapipeline.go
pkg/tekton/metapipeline/metapipeline_test.go

Fixes for tekton weasel
fixes #

fix: Jenkins X Cumulative fixes 

---

pkg/helm/values_tree.go

fix: handle the case when the vault client url is nil in the value tree

---

pkg/cmd/gc/gc_activities.go
pkg/cmd/gc/gc_activities_test.go

Also, it shouldn't assume that the list of activities is sorted, just to be safe, based on weirdness seen on the prod cluster where the oldest two activities for a PR were kept. Additionally, we don't need to explicitly delete `PipelineRun`s any more - those are now properly owned by the relevant `PipelineActivity` and will get cleaned up automatically when we delete the activity.
n/a

fix: gc activities shouldn't try to delete running activities

---

pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/gitops_basic/cb-kubecd-jx-scheduler-test-group-repo-scheduler-sch.yaml
pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/gitops_basic/cb-kubecd-jx-scheduler-test-repo-scheduler-sch.yaml
pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/gitops_basic/config.yaml
pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/nongitops_advanced/config.yaml
pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/nongitops_advanced/schedulers.yaml
pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/nongitops_basic/config.yaml
pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/nongitops_basic/schedulers.yaml
pkg/pipelinescheduler/config_builder.go
pkg/pipelinescheduler/config_builder_test.go
pkg/pipelinescheduler/test_data/merger_with_mergemethod/config.yaml
pkg/pipelinescheduler/test_data/merger_with_mergemethod/parent.yaml
pkg/pipelinescheduler/test_data/merger_with_mergemethod/plugins.yaml
pkg/pipelinescheduler/test_data/merger_with_mergemethod/repo.yaml

fix: enable merge method on scheduler

---

pkg/logs/tekton_logging_test.go

fix(test): use log.CaptureOutput instead os.Pipe() to capture log output

---

go.sum
pkg/cmd/opts/common_test.go
pkg/surveyutils/jsonschema.go

test: mock the resources used by the namespace test to allow running the unit tests without a cluster connection

---

pkg/cmd/controller/pipeline/pipelinerunner_controller.go
pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go
pkg/logs/tekton_logging_test.go

chore: wrap flaky test in retry

---

pkg/cmd/step/verify/step_verify_environments.go

fix: exit with a diff in pipeline

---

pkg/cmd/controller/pipeline/pipelinerunner_controller.go
pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go
pkg/logs/tekton_logging_test.go

fix(test): waiting for HTTP to be open prior to making requests

---

pkg/boot/constants.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step_bdd.go

fix: disable TLS warning for tests

---

pkg/cmd/step/create/pr/step_create_pr_versions.go
pkg/cmd/step/create/pr/step_create_pr_versions_test.go

fix: make excludes not break out the loop

---

pkg/cmd/uninstall/uninstall.go
pkg/cmd/uninstall/uninstall_test.go

Add confirmation message to uninstall and be explicit about what the command will do.
fixes #4969

fix: add confirmation to uninstall command

---

pkg/tekton/metapipeline/clientfactory.go
pkg/tekton/metapipeline/clientfactory_test.go

If we don't do this, we can't actually checkout the ref.
fixes #5195

fix: Fetch ref in pipelinerunner version stream checkout

---

.secrets.baseline
pkg/cmd/step/verify/step_verify_environments.go
pkg/gits/github.go
pkg/gits/helpers.go
pkg/helm/helm_helpers.go

Make the gitops dev environment pipeline use the git values of the bot user.
#4943

fix: dev environment git auth env vars

---

pkg/cmd/step/create/pr/step_create_pr_versions.go
pkg/dependencymatrix/matrix.go
pkg/gits/operations/pull_request_op.go
pkg/versionstream/version_data.go

fixes #5092 
fixes #5219 
fixes #5220 
fixes #5218

fix: various jx step create versions fixes

---

pkg/cmd/step/verify/step_verify_environments.go

fix: need to check that we are in cluster as well

---

pkg/cmd/step/helm/step_helm_apply.go

fix: hide warning when override is not relevant

---

pkg/gits/operations/pull_request_op.go

fix: Override search name for FindLatestChart

---

pkg/cmd/create/create_vault.go

It should wait for vault service to become ready even though
the service is not directly exposed.
fixes #

fix: wait for vault service to become ready after provisioning

---

pkg/cmd/create/create_step.go

many thanks for the PR on jx-docs and feedback on this from @martin-patsov

docs: typo in command help

---

pkg/cmd/boot/boot.go

fix: resort to default version stream ref if not set

---

pkg/cmd/controller/controller_build.go

it seems some recent changes in metapipeline mean the status wasn't
Succeeded before we do the check for log storage (which can update the
status) - so moved the git reporting after the log processing + status
update code

fix: ensure we always update the git status correctly

---

pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/create/pr/step_create_pr_versions.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/gits/operations/pull_request_op.go
pkg/gits/operations/pull_request_op_test.go
pkg/gits/operations/testdata/CreatePullRequestGitReleasesFn/git/fake.git/acme/roadrunner.yml
pkg/gits/provider_fake.go
pkg/versionstream/version_data.go

Also a fix to create a new PR if the existing one is by a different author
fixes #5200 
fixes #5217

feat: create PRs against boot config in versions repo

---

pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
pkg/cmd/step/verify/test_data/preinstall/lighthouse_gitlab/jx-requirements.yml
pkg/cmd/step/verify/test_data/preinstall/prow_github/jx-requirements.yml
pkg/cmd/step/verify/test_data/preinstall/prow_gitlab/jx-requirements.yml

and fail with a nice error message if not

fix: verify folks only use github with prow and boot

---

pkg/auth/memory_config_saver.go
pkg/auth/types.go
pkg/cmd/boot/boot.go
pkg/cmd/update/update_webhooks.go
pkg/kube/sourcerepositories.go

this lets us use `jx boot` with Jenkins servers

fix: register jenkins jobs as part of boot

---

pkg/cmd/boot/boot.go
pkg/cmd/step/create/step_create_task.go

so you can opt out of re-applying ingress/cert-manager/external-dns and the like if you just want to modify some environment configuration
fixes #5269

fix: allow boot to start at a specified step

---

pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go

based on folks using standard public git servers

fix: better defaulting of the git kind + webhook in boot

---

pkg/pipelinescheduler/config_builder_test.go
pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/config.yaml
pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/parent.yaml
pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/plugins.yaml
pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/repo.yaml

chore: added test to verify no postsubmit

---

pkg/cmd/add/add_app_test.go
pkg/kube/vault/vault_factory.go

fix: increase the vault health retry timeout to 10 minutes and add some more logging

---

Dockerfile.builder-base
Dockerfile.builder-go
Dockerfile.builder-go-maven
Dockerfile.builder-gradle
Dockerfile.builder-jx
Dockerfile.builder-maven
Dockerfile.builder-nodejs
Dockerfile.builder-python
Dockerfile.builder-python2
Dockerfile.builder-ruby
Dockerfile.builder-rust
Dockerfile.builder-scala
Dockerfile.builder-swift
Dockerfile.builder-terraform

chore: using the 'latest' tagged images in bdd tests

---

pkg/cmd/boot/boot.go

we were not properly failing if we fail to parse the requirements file.
Also we may end up with a new requirements file anyway after a new git clone - so lets move the parsing + validation logic after the git clone

fix: lets properly handle errors parsing the requirements file in boot

---

jenkins-x.yml

chore: push the 'latest' release of the jx image

---

cmd/codegen/generator/client_set.go
cmd/codegen/generator/docs.go
cmd/codegen/generator/open_api.go
cmd/codegen/util/go.go
cmd/codegen/util/go_test.go

Without disable the update, it leads to this kind of errors when Go modules is enabled by default in the system.
```
go_test.go:137:
Error Trace:    go_test.go:137
Error:          Received unexpected error:
failed to run 'go get -u -d golang.org/x/lint/golint' command in directory '', output: 'package golang.org/x/lint/golint: unrecognized import path "golang.org/x/lint/golint" (https fetch: Get https://gola
ng.org/x/lint/golint?go-get=1: dial tcp 172.217.168.49:443: i/o timeout)'
error running go get -u -d golang.org/x/lint/golint, output package golang.org/x/lint/golint: unrecognized import path "golang.org/x/lint/golint" (https fetch: Get https://golang.org/x/lint/golint?go-get=
1: dial tcp 172.217.168.49:443: i/o timeout)
github.com/jenkins-x/jx/cmd/codegen/util.GoGet …
```

test: make the go get test to not update the dependencies

---

pkg/cmd/create/create_env.go
pkg/cmd/deletecmd/delete_application.go
pkg/cmd/importcmd/import.go
pkg/cmd/opts/import.go

If using schedulers don’t manually adjust the prow config, just delete the source repo and regenerate the prow config
fixes #4958

fix: regenerate prow config from source repositories after delete

---

pkg/surveyutils/jsonschema.go

fix: don’t include data in error

---

pkg/cmd/create/create_quickstart.go
pkg/quickstarts/model.go
pkg/versionstream/test_data/jenkins-x-versions/packages/git.yml
pkg/versionstream/version_data.go
pkg/versionstream/version_data_test.go

to simplify the UX a little
fixes #5307

fix: ask the user for a quickstart first before the git repo

---

pkg/cmd/create/create_mlquickstart.go
pkg/cmd/create/create_quickstart.go
pkg/cmd/get/get_quickstarts.go
pkg/cmd/opts/quickstarts.go
pkg/cmd/opts/quickstarts_test.go
pkg/cmd/opts/test_data/quickstarts/version_stream/quickstarts.yml
pkg/cmd/step/create/pr/step_create_pr.go
pkg/cmd/step/create/pr/step_create_pr_go.go
pkg/cmd/step/create/pr/step_create_pr_quickstarts.go
pkg/cmd/step/create/pr/step_create_pr_versions.go
pkg/kube/quickstarts.go
pkg/quickstarts/model.go
pkg/quickstarts/model_test.go
pkg/quickstarts/quickstarts.go
pkg/quickstarts/types.go
pkg/versionstream/version_data.go

fix: lets load quickstarts from the version stream

---

pkg/cmd/step/verify/step_verify_packages.go
pkg/cmd/step/verify/step_verify_preinstall.go

fix: properly verify kubectl/git/helm packages in boot

---

Dockerfile.builder-ml
jenkins-x-images.yml
pkg/cmd/create/create_pullrequest.go

fix: correct setup the gitInfo on jx create pullrequest

---

pkg/cmd/boot/boot.go
pkg/cmd/boot/boot_test.go
pkg/cmd/boot/test_data/jenkins-x.yml
pkg/cmd/boot/test_data/jx-requirements.yml
pkg/cmd/opts/common.go
pkg/cmd/step/boot/step_boot_upgrade.go
pkg/cmd/step/boot/step_boot_vault.go
pkg/cmd/step/create/step_create_install_values.go
pkg/cmd/step/create/step_create_values.go
pkg/cmd/step/env/step_env_apply.go
pkg/cmd/step/expose/step_expose.go
pkg/cmd/step/helm/step_helm_apply.go
pkg/cmd/step/verify/step_verify_install.go
pkg/cmd/step/verify/step_verify_preinstall.go

fix: Revert "fix: use namespace from jx-requirements"

---

pkg/tenant/tenant.go
pkg/tenant/tenant_test.go

chore: simplify the domain verification regexp

---

go.mod
go.sum
pkg/cloud/amazon/vault/vault_resources.go
pkg/cmd/create/create_vault.go
pkg/cmd/create/install.go
pkg/kube/vault/vault.go

Signed-off-by: Milinda Dias <mjosephd@gmail.com>
This PR is used to create the AWS preresiquite resources automatically instead of relying on manual creation such as using a separate terraform script.
This would be the first OSS submission here.
fixes #

feat: Added auto create vault aws resource requirements

---

pkg/cmd/get/get_build_logs.go
pkg/kube/activity.go
pkg/logs/tekton_logging.go
pkg/logs/tekton_logging_test.go

fix: Add context label to PipelineActivity

---

pkg/environments/gitops.go
pkg/gits/gitlab.go

fix: population of organisation + project on gitlab

---

pkg/tekton/pipeline_info.go
pkg/tekton/pipeline_info_test.go
pkg/tekton/test_data/pipeline_info/pr-yaml/activity.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/pipeline.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/pipelineresources.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/pipelinerun.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/pods.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/structure.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/taskruns.yml
pkg/tekton/test_data/pipeline_info/pr-yaml/tasks.yml

so we can properly update the pipeline status in git for lighthouse

fix: detect lastCommitSha in latest tekton pods

---

jx/scripts/update-bot.sh
pkg/cmd/step/create/pr/step_create_pr_go.go
pkg/gits/operations/pull_request_op.go

so we can automate PRs for go releases across repos
fixes #5359

fix: fixes the `jx step create pr go` command

---

jenkins-x.yml

fix: Use builder-go for update-bot due to create pr go

---

pkg/cmd/controller/controller_enviornmentcontroller.go
pkg/cmd/step/create/step_create_task.go

When deploying environment with jenkins concurrent execution of pipelines are disabled with disableConcurrentBuilds in Jenkinsfile. Nothing like that is available in Tekton and thus some other way of preventing dangerous race conditions is needed.
fixes #5281

fix: Prevent concurrent environment deploys

---

pkg/cmd/step/verify/step_verify_environments.go

fix: enable TLS only when it is enabled in the environment configuration

---

jx/scripts/update-bot.sh
pkg/cmd/step/report/step_report.go
pkg/cmd/step/report/step_report_chart.go
pkg/cmd/step/report/step_report_chart_test.go
pkg/cmd/step/report/step_report_image_version.go
pkg/cmd/step/report/step_report_version.go
pkg/cmd/step/step_stash.go
pkg/collector/git_collector.go
pkg/gits/git_cli.go
pkg/kube/job.go
pkg/kube/pod.go

here's an example of the output it generates: https://github.com/jstrachan/nodey222/tree/gh-pages/reports/imageVersions/0.6.0

fix: add a report of packages in images

---

pkg/cmd/step/verify/step_verify_environments.go

always create the dev-repo if gitops is true, only create the PR 
if it looks like a user is running the command.

fix: creation of dev repo in 'jx boot'

---

pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go

feat: can use private env repo from env variable

---

pkg/cmd/step/create/pr/step_create_pr_docker.go
pkg/cmd/step/create/pr/step_create_pr_regex.go

fix: Allow multiple names to `jx step create pr (docker|regex)`

---

pkg/cmd/step/create/pr/step_create_pr_go.go

fix: `jx step create pr go` should ignore build errors by default

---

pkg/cmd/step/report/step_report_image_version.go
pkg/util/strings.go

* lets add batching to avoid the pods getting killed before they finish
* add more flexible filtering so we can more easily add gcr.io/jenkinsxio images and exclude, say, machine learning

fix: jx step report iv

---

pkg/cmd/step/create/step_create_install_values.go
pkg/cmd/step/get/step_get.go
pkg/cmd/step/get/step_get_subdomain.go

new step is called `jx step get subdomain`

feat: extract tenant service call into own step

---

.secrets.baseline
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go

feat: add env variable to toggle vault storage type

---

pkg/cmd/step/verify/step_verify_environments.go

fix: use JX_INTERPRET_PIPELINE to decided whether to create PR

---

pkg/cmd/boot/boot.go
pkg/cmd/clients/factory.go
pkg/cmd/opts/common.go
pkg/cmd/opts/team_settings.go
pkg/config/install_requirements.go
pkg/helm/helm_cli.go

fix: allow helm3 to be enabled for boot

---

pkg/cloud/gke/gcloud.go
pkg/cloud/gke/interface.go
pkg/cloud/gke/mocks/gclouder.go
pkg/cluster/constants.go
pkg/cluster/factory/factory.go
pkg/cluster/fake/fake.go
pkg/cluster/gke/gke.go
pkg/cluster/helpers.go
pkg/cluster/helpers_test.go
pkg/cluster/interface.go
pkg/cmd/get/get.go
pkg/cmd/get/get_cluster.go
pkg/cmd/opts/clusters.go
pkg/cmd/step.go
pkg/cmd/step/cluster/step_cluster.go
pkg/cmd/step/cluster/step_cluster_label.go
pkg/cmd/step/cluster/step_cluster_lock.go
pkg/cmd/step/cluster/step_cluster_unlock.go
pkg/cmd/step/helm/step_helm_apply.go
pkg/util/maps.go
pkg/util/maps_test.go
pkg/util/suggestions.go

to lock a test cluster and connect to it to run commands such as BDD tests on one of a pool of test clusters

fix: add 'jx step cluster lock'

---

.secrets.baseline
pkg/cmd/step.go
pkg/cmd/step/create/step_create_install_values.go
pkg/cmd/step/step_override_requirements.go
pkg/cmd/step/step_replicate.go
pkg/cmd/step/verify/step_verify_preinstall.go

step is called `jx step override-requirements`

feat: extract requirments overrides into own step

---

pkg/cmd/create/create_vault.go

chore: handle errors when setting up the vault resources for AWS

---

go.mod
go.sum
pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/create/step_create_task_test.go
pkg/tekton/metapipeline/clientfactory.go
pkg/tekton/pipelines.go
pkg/tekton/pullrefs.go

to trim dependencies so we don't have to pull in prow inside lighthouse

chore: minor refactor

---

.secrets.baseline
pkg/cloud/gke/gcloud.go
pkg/cloud/gke/vault/vault_backend.go
pkg/cmd/create/create_vault.go
pkg/cmd/step/boot/step_boot_vault.go
pkg/cmd/step/step_override_requirements.go
pkg/config/install_requirements.go

correctly uses the vault key & keyring and bucket from the jx requirements

chore: fixes for customising keyring & key within vault config

---

pkg/cmd/step/step_replicate.go

feat: replicate secrets can create missing namespaces if required

---

pkg/cmd/step/create/step_create_install_values.go

we log a warning that the combination has not been tested though
fixes #5451

fix: avoid failing boot if folks want TLS and are not using GKE

---

pkg/cmd/scan_cluster.go

chore: use the kube-hunter image from version stream

---

pkg/cloud/gke/gcloud.go
pkg/logs/tekton_logging.go

Before this change, we'd be downloading files from a GCS bucket into a temp file, then we'd read the contents and delete the file.
That was unnecessary as both `GCS` and `S3` support Stream Transfers by adding `-` as the destination, this means we can get the contents directly by creating a stdout pipe and a scanner.
fixes #5467

feat: get files from GCS by stream transfer instead of file copy

---

pkg/cmd/opts/cert_manager.go
pkg/kube/pki/cert-manager.go

fix: Add Helm repo for jetstack/cert-manager

---

pkg/cmd/step/step_override_requirements.go
pkg/config/install_requirements.go

JX_REQUIREMENT_WEBHOOK="prow|lighthouse"

fix: allow webhook type to be configurable by env variable

---

.secrets.baseline
pkg/cmd/step/step_override_requirements.go
pkg/config/install_requirements.go

feat: adding overrides for storage requirements

---

pkg/cmd/step/verify/step_verify_environments.go

fix: prevent creation of dev env pr in cluster

---

pkg/cmd/opts/helm.go
pkg/cmd/step/helm/step_helm_apply.go
pkg/helm/helm_helpers.go
pkg/helm/helm_helpers_test.go

feat: use vault substitutions in app

---

pkg/cmd/preview/preview.go

fixes: #5264
Signed-off-by: Harsh Vardhan <harsh.vardhan@mayadata.io>
fixes #5264

fix: Add 403 resp code for successful deployment

---

pkg/jenkinsfile/gitresolver/buildpack.go

fix: enable build packs to checkout tags

---

go.mod
go.sum

Updated  `aws-sdk-go` dependency that includes many bugfixes and new features that we might need when for EKS support.
Tested with the creation of a static masters and tekton cluster.
fixes #5427

feat: update aws-sdk-go to the latest version

---

pkg/pipelinescheduler/config_builder.go
pkg/pipelinescheduler/config_builder_test.go
pkg/pipelinescheduler/test_data/multiple_contexts/config.yaml
pkg/pipelinescheduler/test_data/multiple_contexts/repo.yaml
pkg/pipelinescheduler/testhelpers/helpers.go

fix: support multiple contexts

---

jx/scripts/update-website.sh

fix: use the new website path for docs creation

---

pkg/cmd/deletecmd/delete_application.go
pkg/kube/activity.go
pkg/kube/activity_integration_test.go
pkg/kube/activity_test.go
pkg/kube/field_map.go
pkg/kube/field_map_test.go

fix(pipeline): introducing ListSelectedPipelineActivities to select by label and field

---

pkg/tekton/metapipeline/clientfactory.go
pkg/tekton/metapipeline/clientfactory_test.go

Followup to #5550 for #5552
n/a

fix: Add test for pull refs ending up on activity key

---

jx/scripts/update-website.sh

More parent directories than there used to be, so more relative parents in the path.
n/a

fix: Proper relative path for jx binary in update-website.sh

---

pkg/cmd/step/helm/step_helm_apply.go

fix: lets add a warning if boot is being used without a clusterName

---

pkg/cmd/opts/cert_manager.go
pkg/kube/pki/cert-manager.go

Trying to address #5353 - the initial attempt to do so in #5464 failed, for a couple reasons, and was reverted. So let's try again and see exactly what's wrong at this point.
fixes #5353

fix: Upgrade to newer cert-manager

---

.goreleaser.yml
jenkins-x.yml
jx/scripts/update-bot.sh

feat: perform pre-release of jx prior to version stream release

---

pkg/cmd/step/get/step_get.go
pkg/cmd/step/get/step_get_dependency_version.go
pkg/dependencymatrix/matrix.go
pkg/dependencymatrix/matrix_test.go

Can be used either with the version stream or a local directory.
First step of #5595
n/a

feat: Add a step to get a dependency version from the dependency matrix

---

pkg/cmd/upgrade/test_data/upgrade_boot/jx-requirements.yml
pkg/cmd/upgrade/upgrade_boot.go
pkg/cmd/upgrade/upgrade_boot_test.go
pkg/gits/git_cli.go

Some unit tests for boot upgrades and minor fixes

chore: boot upgrade tests

---

pkg/cmd/opts/domain.go
pkg/cmd/step/create/step_create_install_values.go

Default to *.nip.io when booting an EKS cluster without providing a domain.
Also some fixes to avoid asking for input when running the step in batch mode.
fixes #5439

feat: avoid asking the user to create a custom domain when booting and default to nip.io if a domain is not provided

---

pkg/gits/helpers.go
pkg/gits/helpers_test.go

fix: always fetch to a new local branch

---

go.mod
go.sum
pkg/cmd/compliance/compliance.go
pkg/cmd/compliance/compliance_results.go
pkg/cmd/compliance/compliance_run.go
pkg/cmd/compliance/compliance_status.go

Also remove the dependency to our fork of sonobuoy.
fixes #5603

feat: update the compliance to use sonobuoy v0.16.0

---

pkg/cmd/step/step_credential.go

chore: revert remove the --file flag from 'jx step credential'

---

pkg/cmd/boot/boot.go
pkg/cmd/upgrade/test_data/upgrade_boot_alternative/jx-requirements.yml
pkg/cmd/upgrade/upgrade_boot.go
pkg/cmd/upgrade/upgrade_boot_test.go
pkg/config/install_requirements.go

feat: write/read bootConfigURL from dev env requirements

---

pkg/cmd/uninstall/uninstall.go
pkg/cmd/uninstall/uninstall_test.go

feat: restore the status check as it uses the Helm template instead of the CLI
chore: added tests
We need to delete the `jxing` chart when uninstalling JX.
With EKS, the cluster is created using `eksctl` which uses two CloudFormation stacks to create every resource in AWS, this also creates a VPC.
When installing the `nginx-ingress` chart for EKS, it creates an `ELB` which is then attached to the cluster's VPC but is not part of the CloudFormation stacks. 
When attempting to delete the CloudFormation stack, it fails because there's a resource (the ELB) attached to the cluster's VPC, so it fails.
Deleting the `jxing` chart deletes the ELB.
fixes #5430

feat: remove the nginx-ingress chart when uninstalling

---

pkg/apps/gitops.go
pkg/apps/install.go
pkg/cmd/step/bdd/step_bdd.go

fix(test): fetch test-git-branch prior to checking it out

---

pkg/cmd/step/boot/step_boot_vault.go
pkg/kube/vault/vault.go

fix: lookup the vault operator image tag used by boot vault into the version stream

---

pkg/cmd/start/start_pipeline.go
pkg/cmd/step/step_changelog.go
pkg/gits/git_cli.go
pkg/gits/git_fake.go
pkg/gits/git_local.go
pkg/gits/interface.go
pkg/gits/mocks/gitter.go

fix: complete changelog on first release

---

hack/linter.sh

fix: increase linter deadline to 15 minutes

---

README.md

docs: add CII Best Practicies badge

---

pkg/tenant/tenant.go

feat: passing user email temporarily on the subdomain call

---

pkg/gits/helpers.go

I just did a batch of experiments and verified that the `synchronize` GitHub webhook event does get sent twice if you push to an existing PR, and then within a sufficiently rapid timeframe, edit the PR. I'm not sure whether it's the title or the description being changed that's the issue (or both), but regardless, updating the PR's title/description _before_ we push results in only a single `synchronize` event being sent. Woo!
fixes #5446

fix: Update existing PR before pushing in `jx step create pr`

---

pkg/cmd/step/create/pr/step_create_pr_versions.go

fix: create PR on all jenkins-x.yml files

---

pkg/cmd/create/install.go
pkg/cmd/step/get/step_get_subdomain.go
pkg/tenant/tenant.go
pkg/tenant/tenant_test.go

feat: passing cluster with subdomain call

---

jenkins-x.yml

So that we don't need to update this in the future to pick up fixes like #5691.
n/a

fix: Use builder from version stream in release

---

pkg/cmd/step/create/step_create_values.go

refactors the old `jx import` logic for registry defaulting to boot for #5549

fix: add better defaulting of the container registry

---

jenkins-x-bdd.yml
jenkins-x-tekton.yml
jx/bdd/boot-vault/ci.sh
jx/bdd/boot-vault/jx-requirements.yml
jx/bdd/tekton/ci.sh

chore(test): making boot-vault context gitops enabled

---

pkg/cmd/controller/controller_build.go
pkg/cmd/controller/controller_build_test.go
pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/activity.yml
pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pipelineruns.yml
pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pipelines.yml
pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pods.yml
pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/structures.yml
pkg/cmd/controller/test_data/controller_build/running_generated/expected/activity.yml

fix: Set not-yet-really-running steps to Pending in PipelineActivity

---

pkg/cmd/diagnose.go

Adds a show option to allow control over what is displayed when using `jx diagnose` e.g. `jx diagnose --show version` would only show version diagnosis. 
All existing checks are shown by default.

feat: allow control of jx diagnose output

---

pkg/apis/jenkins.io/v1/types_extensions.go
pkg/environments/gitops.go
pkg/kube/sourcerepositories.go
pkg/util/urls.go
pkg/util/urls_test.go

fixes https://github.com/cloudbees/jenkins-x-security/issues/11

fix: sanitize all the URLs stored in the source repository CRD

---

pkg/cmd/step/step_override_requirements.go

fix: use non-boolean value to represent enabled

---

pkg/cmd/opts/clusters.go

fix: 'jx step cluster label' now supports the --gke-project flag

---

pkg/gits/bitbucket_cloud.go

fix: get promote working on bitbucket cloud

---

README.md

feat: add the JX build status badge

---

OWNERS

- N/A: Change is code complete and matches issue description.
- N/A: Change is covered by existing or new tests.
I am not currently working on JX, but sometimes I get randomly
assigned to review PRs and such. Seems best to remove myself from
OWNERS so that active maintainers are the ones getting assigned as
reviewers instead.

chore: Remove @dwnusbaum from OWNERS

---

docs/apidocs/config.yaml

docs: add the Scheduler CRD

---

pkg/cmd/boot/boot.go

fix: prevent updates to bootConfigURL from being lost

---

jenkins-x.yml

fix: use the builder-go for the jxui-backend update

---

pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/step_verify_preinstall_test.go

Right now we are using the versions repo and ref defined in the team settings in the `dev` environment CRD.
We need to use the VersionsResolver created from the current `jx-requirements.yaml` instead so we can boot using the new version when upgrading the cluster. 
fixes #5660

feat: make step boot vault use the version stream defined in jx-requirements.yaml

---

pkg/health/health.go

fix: kuberhealthy err response

---

pkg/cmd/boot/boot.go

fix: log error if we can't find the git info in the current dir

---

.secrets.baseline
pkg/cmd/step/step_override_requirements.go
pkg/config/install_requirements.go

feat: gitPublic can be configured from jx-requirements

---

Makefile

fix: change git command to determine lastest dev version

---

jx/bdd/boot-vault/ci.sh
jx/bdd/tekton/ci.sh

fix: UI App BDD tests

---

pkg/cmd/boot/boot.go

An existing boot clone should include a `jx-requirements.yml` as well as a pipeline file.
Clearer variable names.

chore: existing boot clone should include requirements

---

jx/bdd/tekton/ci.sh

It's redundant - we're running it in `boot-vault` anyway, so let's speed things up a wee bit.
n/a

chore: Remove golang-http quickstart from Tekton context

---

pkg/cmd/create/create_domain_gke.go

fix: make sure that the DNS API is enabled when running create domain gke command

---

pkg/cmd/create/create_project.go

fix: Fix create project typo in create_project.go

---

pkg/cmd/create/create_micro.go

Why:
This change addresses the need by:
https://github.com/micro/micro/issues/320
jx create micro failed with following errors:
```
go: finding github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
go: finding golang.org/x/tools v0.0.0-20181019005945-6adeb8aab2de
go get: error loading module requirements
ERROR: Error: Command failed  go get -u github.com/micro/protoc-gen-micro
```
$ jx --version
2.0.86
fixes #

fix: install latest micro in go module syntax

---

pkg/kube/activity.go
pkg/kube/activity_test.go

If a PR goes into a batch build after its most recent `PipelineActivity`(s) have been GC'd, it will currently cause a panic due to the list of `PipelineActivity`s for the commit and branch from the pull refs not having any elements in it. Let's bypass that - if there are no such activities, we don't bother adding batch info for that particular batch pull ref.
fixes #5812

fix(activity): Don't panic for batch builds with PRs without activities

---

pkg/cmd/create/create_cluster_gke.go

Enable StackDriver k8s monitoring by default when creating a new GKE.
fixes #5109

feat: Enable new stackdriver k8s monitoring

---

pkg/cmd/get/get_build_logs.go
pkg/logs/tekton_logging.go

This PR also removes quite a bit of the knative logic that is no longer used.

fix: fail-with-pod works with tekton logging

---

jenkins-x.yml

It's no longer used/supported.
n/a

fix: Stop creating jenkins-x-serverless PRs

---

pkg/apis/jenkins.io/v1/types_pipelinestructure.go
pkg/logs/tekton_logging.go
pkg/logs/tekton_logging_test.go
pkg/logs/test_data/metapipeline_failure/pipelineruns.yml
pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/activity.yml
pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pipelineruns.yml
pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pipelines.yml
pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pods.yml
pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/structures.yml
pkg/logs/test_data/pipelineruns.yml

Without this, we loop forever trying to find the pod(s) for stages that were never actually run.
fixes #5830

fix(logs): For completed builds, only check for pods that ran

---

Makefile.codegen
docs/refdocs/config.json

fix: add a better api docs generation

---

.secrets.baseline
pkg/cmd/step/get/step_get_tenant_token.go
pkg/config/install_requirements.go
pkg/tenant/tenant.go
pkg/tenant/tenant_test.go

feat: added step for tenant token

---

pkg/gits/helpers.go

fix: initial commit message of duplicate git repo

---

Makefile.codegen

chore: fix makefile for doc generation

---

pkg/cmd/create/create_pullrequest.go
pkg/cmd/upgrade/upgrade_boot.go
pkg/environments/gitops.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/gits/operations/pull_request_op.go

This allows for more clear error messages when something goes wrong with adding the labels, since the PR has been successfully created.
fixes #5759

fix: Separate creation of pull request and adding labels

---

pkg/logs/tekton_logging.go
pkg/logs/tekton_logging_test.go
pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/activity.yml
pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/pipelineruns.yml
pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/pipelines.yml
pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/pods.yml
pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/structures.yml

I prefer checking the run, but there is a rare edge case where that won't be enough, so let's check the activity's status as well.
Also realized that the `controller_build_test` for a running `PipelineRun` wasn't 100% accurate, though it makes no functional difference. I cleaned it up anyway.
fixes #5851

fix(logs): Check if activity is done or if run is done to get stage count for logs

---

pkg/boot/constants.go
pkg/cmd/boot/boot.go
pkg/cmd/create/install.go
pkg/cmd/opts/expose.go
pkg/cmd/opts/helm.go
pkg/cmd/opts/team_settings.go
pkg/cmd/opts/upgrade/upgrade_ingress.go
pkg/cmd/opts/version.go
pkg/cmd/step/get/step_get_version_changeset.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/cmd/step/verify/step_verify_environments_test.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
pkg/cmd/upgrade/upgrade_boot.go
pkg/cmd/upgrade/upgrade_platform.go
pkg/gits/git_cli.go
pkg/gits/git_cli_test.go
pkg/gits/git_fake.go
pkg/gits/git_local.go
pkg/gits/interface.go
pkg/gits/mocks/gitter.go
pkg/versionstream/versionstreamrepo/gitrepo.go
pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go

No tests atm, need to investigate if I can add some
Fixes #5087

fix: lock versions stream to tag

---

pkg/cmd/boot/boot.go

The requirements file provided as a CLI argument will override the default file from the boot repository,
if not file is specified the default requirements will remain unmodified.
fixes #5863

feat: add an option to boot command to override the default requirements file from repository

---

pkg/cmd/boot/boot.go

Small refactor to functionalise cb profile setup in boot

chore: functionalise cb profile setup

---

pkg/cmd/step/verify/step_verify_environments.go
pkg/cmd/step/verify/step_verify_environments_test.go
pkg/cmd/step/verify/test_data/verify_environments/pipeline_git_env_vars/env/parameters.yaml
pkg/cmd/step/verify/test_data/verify_environments/pipeline_git_env_vars/jenkins-x.yml

We need `GIT_COMMITTER_EMAIL`, at a minimum, as well as `GIT_AUTHOR_EMAIL`, so let's be consistent here.
fixes #5887

fix: Add GIT_COMMITTER_* env vars to dev env pipeline

---

pkg/cmd/step/verify/step_verify_environments.go

chore: fix comment typo

---

pkg/cmd/get/get_preview_test.go

I'm trying to follow up on issue #3713. With this initial PR I'd like to add test cases for the current state of the implementation. Currently I managed to create two cases for the failed scenarios, however I wasn't sure how to create an environment and a preview to test the positive case. Guidance on how to do this would be appreciated and since this is my first PR also any comments and suggestions on the added tests.
Once tests are in place my plan would be to fix the issue reported by the user.

test: adds get preview test

---

charts/jx/values.yaml
pkg/cmd/cmd.go
pkg/cmd/cmd_test.go

fixes #5080 
@ilpianista, here is the new pull request. I added a test as well. Sorry about messing with your original PR #5717.

feat: set the logging level via JX_LOG_LEVEL

---

pkg/cmd/step/create/step_create_templated_config.go
pkg/cmd/step/create/step_create_templated_config_test.go

feat: add an option to templated config command which allows to provide parameter values

---

pkg/cmd/deletecmd/delete_application.go
pkg/cmd/promote/promote.go

fix: use tide based merging for promotion

---

go.mod
go.sum
pkg/auth/auth_config_test.go
pkg/auth/configmap_vault_config_saver.go
pkg/auth/configmap_vault_config_saver_test.go
pkg/auth/test_data/configmap_vault_auth.yaml
pkg/auth/test_data/configmap_vault_corrupted_auth.yaml
pkg/auth/test_data/configmap_withoutvault_auth.yaml
pkg/auth/types.go
pkg/cmd/clients/factory.go
pkg/cmd/clients/fake/fake_factory.go

feat: add a new auth config saver which can load the auth config from a configmap and resolve the secret URIs from vault

---

pkg/cmd/importcmd/import.go
pkg/cmd/promote/promote.go
pkg/cmd/step/create/pr/step_create_pr_versions.go

so that if folks re-create the cluster and re-run boot the SourceRepository
gets recreated

fix: lets generate a PR on the dev environment when we import a project

---

pkg/cmd/step/step_override_requirements.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go
pkg/gits/git_url.go

and add a repository configuration for pluggable repository providers for https://github.com/jenkins-x/jx/issues/5997
fix: only replace `gcr.io/jenkinsxio/builder-.*` images in pipelines
to avoid replacing unrelated images with builder versions in pipeilnes

fix: a couple of boot gremlins

---

pkg/cmd/step/create/step_create_templated_config.go

fix: use the template file when config file is not specified

---

OWNERS

chore: remove people from OWNERS file who don't anymore contribute to jx

---

pkg/secreturl/fakevault/client.go
pkg/secreturl/helpers.go
pkg/secreturl/helpers_test.go
pkg/secreturl/localvault/client.go
pkg/vault/vault_client.go

fix: ensure that secretsurl client resolves only vault URIs from YAML values

---

pkg/gits/github.go

fix: Adding clarity to git access error message

---

Makefile
pkg/cmd/boot/boot.go
pkg/cmd/opts/install.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/upgrade/upgrade_boot.go
pkg/config/install_requirements.go
pkg/util/downloads.go
pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go

This will allow for setting these values for a distribution's binary of `jx` without needing to change source code.
NOTE: This is just an experiment right now.
fixes #5968

chore: Switch distro-specific strings to overrideable vars, not constants

---

pkg/auth/vault_config_handler.go

fix: only use the base file path when loading the auth config from vault

---

pkg/config/install_requirements.go

https://kubernetes.slack.com/archives/C9LTHT2BB/p1572989629047700

fix: remove typo

---

pkg/auth/kube_config_handler.go
pkg/auth/kube_config_handler_test.go
pkg/auth/types.go
pkg/auth/vault_config_handler.go

feat: add an auth config handler for Kubernetes secerets which is intended to abstract the configuration loading behind the service

---

pkg/cmd/boot/boot.go
pkg/gits/helpers.go

fix: add ability to clone sha during 'verify env'

---

README.md

docs: fix a few links

---

pkg/tekton/metapipeline/metapipeline.go

This keeps the request/limits fairly low, but still high enough that `mvn versions:set` should still work.
n/a

chore: Add resource request/limit to metapipeline

---

pkg/cmd/add/add_app.go
pkg/cmd/step/create/step_create_values.go
pkg/cmd/step/create/step_create_values_test.go
pkg/cmd/step/create/test_data/step_create_values/local_secrets_install/jx-requirements.yml
pkg/cmd/step/create/test_data/step_create_values/local_secrets_install/parameters.tmpl.schema.json
pkg/cmd/step/create/test_data/step_create_values/local_secrets_install/parameters.yaml.golden
pkg/secreturl/localvault/client.go
pkg/surveyutils/jsonschema.go
pkg/surveyutils/jsonschema_test.go
pkg/surveyutils/test_data/ifThenElseTrueBoolean.test.schema.json

Some changes needed to get a Jenkins-x running in PKS (and any k8s cluster not in a Cloud really).
We are now going to be defaulting to dockerhub for clusters other than GKE, EKS and AKS, we needed to handle creating the secret correctly and assigning the right push url to dockerhub.
Also, the dev environment master pipeline was failing when using local secrets. While using Vault should be the default and highly encouraged, we need to make it easy for people to try Jenkins-x in a standalone k8s cluster.
Local secrets are going to be added to a cluster secret and mounted as an optional volume in the build pods at `/builder/home/.jx/localSecrets/currentCluster`.
The `FileSystemSecretsClient` has been updated to fall back to this path if it doesn't find the secrets at …

feat: allow to install on PKS

---

pkg/cmd/deletecmd/delete_application.go
pkg/cmd/deletecmd/delete_application_test.go

This PR removes any environments from the list of applications that can be deleted.
Before
```
$ jx delete application
? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter]
> [ ]  mauromorales/environment-mm-ghi-5668-dev
[ ]  mauromorales/environment-mm-ghi-5668-production
[ ]  mauromorales/environment-mm-ghi-5668-staging
[ ]  mauromorales/jx-qs-test-delete-apps
```
After
```
$ jx delete application
? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter]
> [ ]  mauromorales/jx-qs-test-delete-apps
```
fixes #5668

fix: filter environments from delete application

---

SECURITY.md

Set up the GitHub security policy
fixes #

docs: create Security Policy for Jenkins-X project

---

pkg/cmd/step/verify/step_verify_environments.go

* lets only store the requirements in the Environment CRD if they exist
* lets find the server/token via githup apps if using github app mode

fix: support github app tokens better

---

pkg/cmd/clients/factory.go

so we can create a new factory using a jxfactory.Factory for remote connections

fix: add a helper method

---

pkg/cmd/opts/install.go

Fixes #6133. This changes the order when looking for updates to check the location of LatestVersionStringsBucket if it is set.

fix: Support checking for updates in a gcloud bucket

---

pkg/cmd/create/create_quickstart.go
pkg/cmd/importcmd/import.go
pkg/github/github_app.go

Determine if the github app is installed and if not prompt the user to install.
fixes #

feat: output GitHub app installation url

---

pkg/cmd/upgrade/upgrade_boot.go

fix: Return an error if upgrade boot gets a nil userAuth

---

pkg/config/install_requirements.go

fix: avoid possible exception

---

pkg/cloud/amazon/aws_cli.go
pkg/cloud/amazon/eks.go
pkg/cluster/eks/clusterclient.go
pkg/cluster/eks/clusterclient_test.go
pkg/cluster/factory/factory.go
pkg/cmd/create/create_cluster_eks.go

The EKS implementation for `cluster.interface` so we can start implementing Garbage collection for clusters other than GKE.
fixes #5578

feat: implement cluster.interface for EKS

---

pkg/cmd/step/step_stash.go

Remove a small typo on `jx step stash` command
fixes #

docs: Fix typo. Remove '-' too much on --bucket-url

---

pkg/cmd/get/get_stream.go
pkg/cmd/upgrade/upgrade_cli.go
pkg/versionstream/resolver.go
pkg/versionstream/version_data.go

Fix the links shown in the jx binary output for Jenkins-X Version Stream documentation.

docs: Version Stream documentation links

---

pkg/cmd/deprecation/deprecated.go

chore: add some commands which were announced to be deprecated in the deprecation list

---

.secrets.baseline
pkg/config/install_requirements.go

feat: added override for velero serviceaccount

---

pkg/cmd/controller/controller_build.go

I found missing space between the word PipelineActivities and the next word.

fix: Add missing space between words

---

pkg/config/install_requirements.go

Signed-off-by: craigdbarber <craigbarber@google.com>
- [X ] Change is code complete and matches issue description.
- [ X] Change is covered by existing or new tests.
Fixes out of date TLS doc URL.
fixes #

fix: corrected out of date TLS doc URL

---

pkg/cmd/preview/preview.go

This allows the user to specify how long they wish to wait for a
preview application to become healthy, which was previously
hardcoded to 5 minutes
I've not overloaded the --timeout parameter as per the below issue.
The --timeout param doesn't seem to be a part of the jx preview command.
(I've no idea where that's being picked up from)
Instead, I've used a more precise timeout name specific to the portion of
the preview command it affects.
If you think it's worth adding a unit test for this functionality, any pointers
would be welcome.
fixes #3530

feat: add option to customise preview timeout

---

pkg/gits/provider.go
pkg/gits/provider_githubapp_test.go
pkg/gits/provider_test.go

chore: improve error handling in the git provider constructor

---

pkg/auth/kube_config_handler.go
pkg/auth/types.go
pkg/cmd/clients/factory.go
pkg/gits/provider.go

fix: bring back old function + minor refactor

---

pkg/auth/kube_config_handler.go
pkg/auth/kube_config_handler_test.go
pkg/cmd/opts/auth.go
pkg/cmd/opts/git.go
pkg/cmd/step/git/step_git_credentials.go
pkg/cmd/step/git/step_git_credentials_test.go
pkg/gits/git_cli.go

so we cmn more easily use a github app token for a specific organisation

fix: improve the git credentials command for GitHub Apps

---

pkg/cmd/upgrade/upgrade_boot.go
pkg/gits/git_cli.go

Allow upgrading boot to the latest version stream release tag, rather than just master or a supplied Ref
fixes #6214

feat: allow boot upgrade to latest version stream release tag

---

pkg/cmd/controller/controller_build.go

and an optional flag so we can terminate the build controller if we can't create a git provider

fix: add better error handling for missing git auth

---

pkg/cmd/step/verify/step_verify_preinstall.go

fix: make sure the cluster zone is stored in jx-install-config

---

pkg/cmd/step/verify/step_verify_preinstall.go

chore: bring velero gcp serviceaccount suffix inline with others

---

pkg/cmd/step/create/step_create_install_values.go

Resolves: https://github.com/jenkins-x/jx/issues/6128
Prior to this commit, `jx step ceate install values` forced external dns when detecting a GKE cluster with a custom domain.
This behavior could not be prevented by the user, and would lead to a failure if the service account did not have sufficient rights to configure the external dns.
Signed-off-by: Aurélien Lambert <aure@olli-ai.com>
Prior to this commit, `jx step ceate install values` forced external dns when detecting a GKE cluster with a custom domain.
This behavior could not be prevented by the user, and would lead to a failure if the service account did not have sufficient rights to configure the external dns.
fixes https://github.com/jenkins-x/jx/issues/6128

fix: do not force external dns on GKE cluster with custom domain

---

pkg/gits/git_cli_test.go

Some tests for git HasChanges and HasFileChanged functions

chore: add git file change tests

---

pkg/cmd/add/add_app.go
pkg/cmd/deletecmd/delete_app.go
pkg/cmd/get/get_apps.go
pkg/cmd/upgrade/upgrade_apps.go

chore: add some clarification on help messages from app commands to reduce confusion

---

jx/bdd/boot-vault/jx-requirements.yml
pkg/cloud/buckets/buckets.go
pkg/cloud/gke/gcloud.go
pkg/cloud/gke/storage/bucket_provider.go
pkg/cmd/controller/controller_build.go

so that we can use write timeouts

fix: lets use the gcloud API to write to buckets

---

pkg/cmd/clients/factory.go
pkg/helm/helm_cli.go

fix: check helm compatibility to avoid using helm v3

---

pkg/cmd/create/create.go
pkg/cmd/create/create_quickstart.go
pkg/cmd/importcmd/import.go
pkg/github/github_app.go

fix: only prompt once if github app is enabled but not installed

---

pkg/kube/activity.go
pkg/kube/naming/names.go
pkg/kube/naming/names_valid_test.go

fix: avoid adding invalid labels to PipelineActivity

---

pkg/cmd/boot/boot.go

The url of the documentation was incorrect after the documentation system was changed.
The current url is returning the chinese version (best guess by the documentation system).
The proposed change returns the english version.
fixes #6280

fix: The documentation url is changed.

---

pkg/cmd/deprecation/deprecated.go

This command is no longer needed so we should remove it from JX.
fixes #6283

chore: Deprecate create codeship command

---

pkg/cmd/preview/preview.go
pkg/users/git.go
pkg/users/users.go

fix: previews when using github apps

---

pkg/cmd/upgrade/upgrade_boot.go
pkg/gits/helpers.go
pkg/gits/helpers_test.go
pkg/gits/operations/pull_request_op.go

An extension and refactor following  #6292

chore: add PR labels as part of PR creation

---

pkg/cmd/get/get_applications.go

How and when to display these applications needs to be defined
We are currently in the process of refactoring all application commands to deal with user applications and not deployments in general (relates to #6097). However there are some additional cases that might need to be addressed, one of them is **undeployed applications** e.g. you create a quickstart but for some reason deployment fails, you are left with one source repository that has no deployments. It would be good to have a way to display these in the get application command, either by default or through a flag.
I'm reverting this change because atm there's a BDD test that breaks with the following error:
```
reates a spring application and promotes it to staging
[It]
/workspace/source/test/suite/spring/jx_create_spring.go:36 …
```

fix: do not display undeployed applications

---

Makefile

feat: format the imports when executing the fmt goal

---

pkg/cmd/step/pr/step_pr_comment.go
pkg/dependencymatrix/updates_test.go
pkg/gits/operations/pull_request_op.go

feat: make it easier for `jx step pr comment` to be run in a pipeline

---

Makefile

feat: ensure that we have goimports for import formatting

---

pkg/config/install_requirements.go

Allow velero backup schedule and time to live values to be configurable from the requirements file

feat: configurable velero backups from requirements 

---

pkg/helm/helm_template.go
pkg/helm/helm_template_test.go
pkg/helm/test_data/helm_hooks/crds.yaml
pkg/helm/test_data/helm_hooks/post-install-job.yaml

This change allows the helm apply function to iterate and apply all crd part files
fixes #6344

fix: Allow all crds with hooks to be processed

---

pkg/cmd/opts/install.go

- [X ] Change is code complete and matches issue description.
Bump helm version based on the value specified in version stream package version field.  
None
fixes #

feat: Bump helm versions using version stream

---

pkg/config/install_requirements_test.go
pkg/config/test_data/jx-requirements.yml

Introducing a test for the envconfig functionality before rolling out further

chore: test for envconfig usage in OverrideRequirementsFromEnvironment

---

pkg/cmd/deprecation/deprecated.go

People in the U.S. are thinking we are deprecating features on Jan 1 2020.  Small change to alleviate the matter.
Helps with https://github.com/jenkins-x/jx/issues/6340, among others.

feat: Update deprecation dates format to address confusion

---

pkg/cmd/step/restore/step_restore_from_backup.go

fix: return info when using --latest for velero restore

---

pkg/cmd/create/install.go

chore: update project name in log info printed during installation

---

pkg/cmd/create/create_docs.go

refactor: handle the errors when generating the documentation of the commands

---

pkg/applications/applications.go
pkg/applications/applications_test.go
pkg/cmd/get/get_env.go
pkg/cmd/opts/pod.go
pkg/flagger/flagger.go
pkg/kube/activity_test.go
pkg/kube/deployments.go
pkg/kube/namespaces.go

Signed-off-by: Jiang Yitao <jiangyt.cn@gmail.com>
support kube 1.16+ apis
fixes
https://github.com/jenkins-x/jx/issues/6358
https://github.com/jenkins-x/jx/issues/6068

fix: support kube 1.16+ api

---

pkg/cmd/deprecation/deprecated.go

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>
fixes #6324

chore: edit jx create step deprecation warning

---

pkg/cmd/step/verify/step_verify_behavior.go

fix: quote log variables and correct message

---

pkg/cloud/amazon/eks/eks.go
pkg/cloud/amazon/vault/vault_resources.go
pkg/cmd/create/create_cluster_eks.go
pkg/cmd/step/bdd/step_bdd.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/vault/create/create.go

feat: fix a bug with credentials and handle the clusters data better when garbage collecting
Changes needed to get EKS BDD tests running and a small fix for a regression created by the Vault refactoring.
fixes #6039

feat: changes to make EKS BDD tests work

---

jx/bdd/boot-vault/ci.sh

fix: change the boot vault BDD to use the version of boot config from version stream instead of master

---

pkg/cmd/create/create_quickstart.go
pkg/cmd/importcmd/import.go
pkg/cmd/importcmd/import_reporter.go

to report progress of the create quickstart / import project wizard so its
easier to reuse the code in other kinds of UI

fix: add a reporter interface to quickstart wizard

---

pkg/helm/helm_template.go

fix: improve error handling and some log messages in helm template

---

pkg/cmd/clients/fake/fake_factory.go
pkg/cmd/testhelpers/cmd_test_helpers.go

when testing with fake clients

fix: make it easier to pass in a fake tekton/dynamic client

---

CONTRIBUTING.MD

Following up on pull request #6390 sorting out the commit message issues

docs: Update CONTRIBUTING.MD with supported Golang versions

---

pkg/cmd/step/helm/step_helm_apply.go

fix: make the step help apply to also load the requirements from the team settings if not requirements file is found locally

---

pkg/cmd/importcmd/import_deploy_integration_test.go
pkg/cmd/importcmd/test_data/import_projects/nodejs/server.js
pkg/cmd/promote/promote.go

to avoid issues downloading / running maven as part of the import

fix: lets make the import deploy test not use maven

---

pkg/cmd/create/create_git_server.go

Signed-off-by: Jiang Yi Tao <jiangyt.cn@gmail.com>
failed to add git providers after boot. 
The output after fix:
```
$ ./build/linux/jx get git                                                                                                                     ‹ruby-2.6.3›  /home/jiangytcn
Name Kind   URL
ghe  github https://github.xxx.com
~/go/src/github.com/jenkins-x/jx light.ystacks.com on  fix-git-commands! ⌚ 0:23:18
$ ./build/linux/jx create git server -k gitea -u http://github.192.168.1.12.nip.io -n undercloud --apiuser jiangytcn  --secret xxxx
Added Git server undercloud for URL http://github.192.168.1.12.nip.io
already has GitService undercloud in namespace jx for URL http://github.192.168.1.12.nip.io
Ensured we have a GitService called undercloud for URL …
```

fix: create git provider with auth info

---

pkg/cmd/step/verify/step_verify_git.go

Let's make `jx step verify git` github app aware.

fix: lets make step verify git github app aware

---

pkg/cmd/create/create_spring.go

chore: Revert "chore: default spring version to 2.2.3 in `jx create spring`"

---

pkg/cmd/step/syntax/step_syntax_effective.go
pkg/cmd/step/syntax/step_syntax_schema.go

so we can reuse this logic easier inside the jxui

fix: expose helper function

---

docs/refdocs/templates/pkg.tpl
pkg/cmd/create/create_docs.go

fix: polish the jx CLI reference generation

---

README.md

docs: update community info

---

pkg/cmd/opts/import.go
pkg/cmd/step/verify/step_verify_behavior.go

feat: add ability to override git_organisation for bdd tests

---

README.md

docs: add link to CONTRIBUTING.MD

---

pkg/cmd/deprecation/deprecated.go

as its used to add custom Jenkins X pipelines to users projects - see https://jenkins-x.io/docs/using-jx/faq/pipelines/#how-do-i-add-a-custom-step
fixes #

fix: remove deprecation of `jx create step`

---

docs/contributing/hacking.md

docs: delete unnecessary file

---

pkg/cmd/step/create/helmfile/create_helmfile.go
pkg/cmd/step/create/helmfile/create_helmfile_test.go
pkg/cmd/step/create/helmfile/test_data/create-namespace-chart/jx-apps.yml
pkg/cmd/step/create/helmfile/test_data/system/jx-apps.yml
pkg/config/install_applications.go
pkg/config/install_applications_test.go
pkg/config/test_data/jx-apps-phase-bad/jx-apps.yml
pkg/config/test_data/jx-apps-phase-good/jx-apps.yml

Signed-off-by: James Rawlings <rawlingsj80@gmail.com>

feat: support different phases when generating helmfiles

---

pkg/cmd/deprecation/deprecated.go

chore: push the deprecation date for some still used commands to June 1st

---

pkg/cmd/step/git/credentials/step_git_credentials.go
pkg/cmd/step/verify/step_verify_behavior.go

feat: allow the bdd suite to be configured

---

pkg/cmd/opts/auth.go
pkg/cmd/opts/git.go
pkg/cmd/step/git/credentials/step_git_credentials.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/cmd/step/verify/step_verify_git.go

chore: check for githubapp mode when verifying environment

---

Makefile

- using existing TEST_PACKAGE to unify test1 and test1-pkg
- removed very specific test rules which are basically covered by test1 to reduce
complexity of Makefile
- removed unnecessary header
Example usage (TEST_PACKAGE optional):
```bash
$ make test1 TEST_PACKAGE=./pkg/gits TEST=TestGitCLI
```
fixes #6667

fix: combining rules test1 and test1-pkg into single rule

---

go.mod
go.sum
pkg/log/log.go

feat: add a stackdriver log formatter

---

pkg/cmd/step/git/credentials/step_git_credentials.go
pkg/cmd/step/git/credentials/step_git_credentials_test.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/gits/helpers.go

feat: always pass the repo owner to the credential helper

---

.secrets.baseline
pkg/cmd/create/create_devpod.go
pkg/cmd/step/git/credentials/step_git_credentials.go
pkg/cmd/step/git/credentials/step_git_credentials_test.go

fix: only check the repo owner if gha is enabled

---

pkg/cmd/step/helm/step_helm_apply.go

feat: added information on env vars to step helm apply

---

jx/bdd/static/ci.sh

downstream of https://github.com/jenkins-x/bdd-jx/pull/126
n/a

fix: Don't test update of PipelineActivity in static master context

---

pkg/cmd/clients/factory.go
pkg/cmd/clients/fake/fake_factory.go
pkg/cmd/clients/interface.go
pkg/cmd/clients/mocks/factory.go
pkg/cmd/opts/common.go
pkg/cmd/opts/install.go
pkg/cmd/opts/kustomize.go
pkg/cmd/opts/kustomize_integration_test.go
pkg/cmd/opts/kustomize_test.go
pkg/cmd/testhelpers/cmd_test_helpers.go
pkg/kustomize/interface.go
pkg/kustomize/kustomize_cli.go

feat: Ensure Kustomize

---

pkg/cmd/boot/boot.go

fix(boot): fix --dir flag
use the dir flag to check for jenkins-x.yml file
fixes #6756

fix(boot): fix --dir flag

---

jenkins-x-bdd.yml
jenkins-x-boot-lh-ghe.yml
jenkins-x-boot-vault.yml
jenkins-x-tekton.yml
jx/bdd/boot-lh-ghe/ci.sh
jx/bdd/boot-vault.platform.yaml.template
jx/bdd/boot-vault.prow.yaml.template
jx/bdd/boot-vault/ci.sh

Part of #6726 - valuable enough on its own even if we weren't to do anything else for cross-repo PR testing.
fixes #6753

test: Add image tag overrides for all controllers/cronjobs to boot test

---

pkg/cmd/importcmd/import.go

Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
fixes #6775

fix: repositoryResouce httpCloneURL should not be an sshURL

---

pkg/cmd/edit/requirements/requirements_test.go
pkg/cmd/opts/common.go
pkg/cmd/step/bdd/step_bdd.go
pkg/cmd/step/expose/step_expose.go
pkg/cmd/step/expose/test_data/http/jx-requirements.yml
pkg/cmd/step/expose/test_data/https/jx-requirements.yml
pkg/cmd/step/helm/step_helm_apply.go
pkg/cmd/step/helm/step_helm_apply_test.go
pkg/cmd/step/verify/step_verify_preinstall.go
pkg/cmd/step/verify/test_data/verify_ingress/jx-requirements.yml
pkg/cmd/step/verify/test_data/verify_requirements/boot-config/jx-requirements.yml
pkg/config/install_requirements.go
pkg/config/install_requirements_test.go

fix: Check if the requirements config was read from the existing file

---

pkg/gits/github.go

feat: adding ability to trace GitHub API calls via TRACE_GITHUB_API=1

---

pkg/cmd/step/create/step_create_task_test.go
pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/jenkins-x.yml
pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/pipeline.yml
pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/pipelineresources.yml
pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/pipelinerun.yml
pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/structure.yml
pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/tasks.yml

I had a problem using an env var defined in the `pipelineConfig` using a secret, and wanted to verify that this actually does work as expected. It does, so I was doing something else wrong, but adding a test doesn't seem like a bad idea. =)
n/a

test: Add test to verify that pipelineConfig env secrets get used

---

pkg/cmd/boot/boot.go
pkg/cmd/controller/controller_backup.go
pkg/cmd/create/create_addon_istio.go
pkg/cmd/create/create_codeship.go
pkg/cmd/create/create_docs.go
pkg/cmd/create/create_quickstart.go
pkg/cmd/create/create_terraform.go
pkg/cmd/create/create_terraform_gke.go
pkg/cmd/create/create_terraform_integration_test.go
pkg/cmd/deletecmd/delete_branch.go
pkg/cmd/importcmd/import.go
pkg/cmd/importcmd/import_integration_test.go
pkg/cmd/opts/buildpacks.go
pkg/cmd/promote/promote.go
pkg/cmd/step/helm/step_helm.go
pkg/cmd/step/post/step_post_build.go
pkg/cmd/step/step_release.go
pkg/cmd/step/step_split_monorepo.go
pkg/cmd/step/step_split_monorepo_test.go
pkg/cmd/upgrade/upgrade_apps_test.go
pkg/helm/helm_helpers.go
pkg/helm/helm_template.go
pkg/tests/files.go
pkg/util/files.go
pkg/util/files_test.go

- updating ccode and tests to the new behavior
fixes #6758

fix: FileExists returns now false for directories

---

pkg/cmd/boot/boot.go
pkg/cmd/boot/boot_integration_test.go
pkg/cmd/boot/boot_test.go

fix: making sure boot repo exists before loading requirements

---

pkg/apis/jenkins.io/v1/types_pipeline.go
pkg/cmd/controller/controller_build.go
pkg/gits/provider.go

This ideally should have tests, but...yeah. Hard to write good ones here, and I intend to split the status reporting off anyway.
fixes #6832

fix: Change the commit status description when running stage changes

---

pkg/cmd/controller/controller_build.go

...this just annoys me whenever I'm tailing build controller logs, so
hey, let's fix it.
n/a

chore: Fix typo of "PipelineActicity" in build controller logs

---

pkg/cmd/step/verify/step_verify_preinstall.go
pkg/helm/helm_cli.go
pkg/helm/helm_cli_test.go
pkg/helm/helm_template.go

fixes #6818
following up on pull request #6803

fix: do not run helm init when using helm version > v2

---

pkg/cmd/controller/controller_build.go
pkg/kube/constants.go

Should improve performance in build controller + Lighthouse a bit.
I'm running this on prod and it looks to make a real difference in performance thanks to getting rid of getting creds from vault and making a GitHub API call for every completed step.
n/a

chore: Use an annotation to see if running stages have already been reported

---

pkg/kustomize/interface.go
pkg/kustomize/kustomize_cli.go
pkg/kustomize/kustomize_cli_test.go

finds out if there is any existing kustomize resource within the cwd and sub-directories
FindKustomize returns the kustomize resources path found in cwd and sub-directories

fix: FindKustomize

---

.secrets.baseline
pkg/config/install_requirements.go

chore: allow versions-git-ref to be overridden

---

.test-whitesource-scanning

chore: temporary file to test that whitesource scanning trigger on merge to master

---

.test-whitesource-scanning

chore: remove test file used for whtiesource scanning check

---

jenkins-x-whitesource.yml

chore: use latest docker image for whitesource agent

---

.gitignore

Added configuration to ignore ide generated files for eclipse and vscode

chore(config): add .gitignore rules

---

pkg/cmd/upgrade/upgrade_boot.go

Allow labels to be added to generated PRs created usinig `jx upgrade boot`

feat: allow labels to be added to boot upgrade PRs

---

pkg/gits/operations/pull_request_op.go

fix: wrap dependency asset retrieval with exp backoff strategy

---

pkg/cmd/step/create/test_data/step_create_task/override-steps/jenkins-x.yml
pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
pkg/jenkinsfile/pipeline.go

using env for specific task wasn't working (at least for overridden tasks), no the anv variables are added correctly
fixes #6845

fix: add env variables specified per step

---

pkg/cmd/cmd.go

This message should show up in the following situations:
* Running locally, connected to a cluster using static master.
* Running locally, calling `jx create cluster` without `--skip-installation` and without flags for installing with Tekton.
* Running locally, calling `jx install` without flags for installing with Tekton.
It should never show up in pipelines, in controllers, or in any case where you're connected to a Tekton cluster.
fixes #6887

chore: Add warning for upcoming removal of static masters

---

pkg/helm/helm_cli.go

Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
fixes #

fix: remove namespace switch used for helm3 alpha

---

pkg/cmd/create/create_devpod.go

feat: add option request memory to devpod

---

pkg/gits/operations/pull_request_op.go

fix: increase asset retrieval timeout

---

pkg/config/install_requirements.go
pkg/config/install_requirements_test.go
pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml

fix: ignore load jx-requirements.yml validation errors

---

go.mod
go.sum
pkg/gits/bitbucket_server.go
pkg/gits/bitbucket_server_test.go

Updating github.com/gfleury/go-bitbucket-v1 and fix #2682
Cherrypicking 40be834a789b2a44a3159350cc31a7e917f71184 into master allows you to reproduce the error with the test. The second commit updates the broken lib and some changes on structures. 
fixes #2682

fix: Updating github.com/gfleury/go-bitbucket-v1 

---

pkg/cmd/deletecmd/delete_application.go
pkg/cmd/promote/promote.go

This should help with problems with rotating GitHub App tokens.
fixes #6954

fix: Fresh authentication for each PR status polling check

---

pkg/gits/helpers.go

Whilst this won't fix the issue, it should help us debug problems like #6160

chore: display git status/diff on git stash pop error

---

pkg/util/system/version_linux.go
pkg/util/system/version_linux_test.go

fix: add extract PRETTY_NAME from /etc/os-release to as the current OS

---

pkg/util/http_utils.go

whoopsie. It's still going to fail in cases of new repos, but that fix lives elsewhere.
fixes #6976

fix: GHA install check needed an "or", not an "and"

---

.secrets.baseline
pkg/gits/github.go

feat: correctly determine if a user is an org when creating a repo

---

pkg/cmd/step/verify/step_verify.go
pkg/cmd/step/verify/step_verify_dns.go

feat: add a command to verify dns resolution of ingress rules

---

pkg/cmd/importcmd/import.go
pkg/cmd/importcmd/import_reporter.go

Adds more reporting to importcmd.ImportReporter
fixes #7017

feat: add more reporting to ImportReporter

---

pkg/cmd/controller/controller_build.go

This is preparatory for https://github.com/jenkins-x/lighthouse/pull/603, which, among other things, introduces a new deployment, `lighthouse-foghorn`, which will handle SCM provider status reporting. While we'll update `jenkins-x-boot-config` to not configure the build controller to do status reporting when that Lighthouse PR merges, I'd like to also add a check to see if the `lighthouse-foghorn` deployment is present and skip reporting if it is. This will prevent potential issues with anyone using master of the version stream picking up the new Lighthouse but not the change to `jenkins-x-boot-config`.
n/a

chore: Disable PR status reporting if new enough Lighthouse present

---

pkg/cloud/gke/gcloud.go

Potential error like bucket not found or anything was not catched as we were only streaming command stdOut. It was hard to debug when something is going wrong.
As we don't really want to stream logs as they are stored in a bucket, I'm wondering if we could just use cmd.Run() or wait for the command to finish and just return the output.
I would make the error handling better.
fixes https://github.com/jenkins-x/jx/issues/7027

fix: catch errors when retrieving logs from gs bucket

---

go.mod

github.com/antham/chyle v1.4.0 has a lousy dependency on spf13/cobra that we need to replace.
n/a

fix: go.mod replace for spf13/cobra

---

pkg/cmd/controller/controller_build.go

It was treating not found as found. Whoops.
n/a

fix: Foghorn check logic was wrong

---

jx/bdd/boot-vault/ci.sh
jx/bdd/boot-vault/jx-requirements.yml

Thanks to https://github.blog/2020-04-14-github-is-now-free-for-teams/ =)
fixes #7049

chore: Switch to using org rather than user for boot test repo owner

---

jenkins-x-whitesource.yml

chore: set whitesource image to version 20.3.1

---

pkg/cmd/gc/gc_gke.go

We recently added this suffix in Terraform stuff, as best as I can tell, so we need to be GCing it.
fixes #7053

fix: GC SAs ending in `-bc`

---

pkg/kube/env.go

fixes #7056
Signed-off-by: David Conde

fix: Do not create a PR against a remote environment

---

pkg/cmd/update/update_webhooks.go
pkg/cmd/update/update_webhooks_test.go
pkg/kube/sourcerepositories.go

fixes #7084
Signed-off-by: David Conde

fix: Do not register a register a webhook on the dev environment

---

.github/issue_template.md

Remove installation type section from the issue template
fixes #7109

chore: Remove installation type from the issue template

---

pkg/gits/bitbucket_cloud.go
pkg/gits/bitbucket_server.go
pkg/gits/gitlab.go

The only direct reason for this is the Lighthouse BDD tests, but it's still something we should have in there anyway.
fixes #7113

fix: Add context to GitLab and BitBucket commit status functions

---

pkg/gits/gitlab.go

fix: Add labels to GitLab MRs

---

pkg/builds/jenkinsfiles.go
pkg/cmd/controller/controller_enviornmentcontroller.go
pkg/cmd/create/create_cluster_iks.go
pkg/cmd/get/get_apps.go
pkg/cmd/get/get_build_logs.go
pkg/cmd/get/get_issues.go
pkg/cmd/initcmd/init.go
pkg/cmd/step/boot/step_boot_vault.go
pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/git/step_git.go
pkg/cmd/step/helm/step_helm.go
pkg/cmd/step/report/step_report_image_version.go
pkg/cmd/step/step_next_version.go
pkg/cmd/step/verify/common.go
pkg/cmd/step/verify/step_verify_environments.go
pkg/cmd/sync/sync.go
pkg/github/github_app.go
pkg/gits/git_fake.go
pkg/helm/helm_cli.go
pkg/helm/helm_template.go
pkg/tekton/syntax/pipeline.go

remove unused code to pass `golangci-lint -E unused`
fixes #7080

chore: remove unused code

---

pkg/gits/gitlab.go
pkg/gits/gitlab_test.go
pkg/gits/test_data/gitlab/add-project-member.json
pkg/gits/test_data/gitlab/list-users.json

Various little fixes discovered in getting Lighthouse BDD tests to run against GitLab properly.
n/a

fix: Various small GitLab fixes

---

pkg/health/health.go

There are times when Kuberhealthy is not ready to determine the health of a cluster, especially after a being recently installed. This wraps the check to ensure the check retries until a valid error is returned that matches the returned status.

feat: wrap kuberhealthy check in exponential backoff

---

pkg/cmd/step/verify/step_verify_preinstall.go
pkg/config/install_requirements.go

Add Openshift specific configuration. Let users decide if their cluster will be run with normal permissions or strict ones.
fixes https://github.com/jenkins-x/jx/issues/7141

feat: add strict permissions flag

---

pkg/cmd/step/create/step_create_task.go
pkg/tekton/syntax/pipeline.go
pkg/util/shell.go

Due to Windows file struct, We cannot found `/bin/sh` in Windows.
Same way in #7096.  
fixes #7035, #7156

fix: add compatibility sh

---

pkg/cmd/update/update_webhooks.go
pkg/cmd/update/update_webhooks_test.go

Sometimes, but weirdly not always, when switching from Prow to Lighthouse, the `hmac-token` secret gets deleted. Currently, Prow and Lighthouse use the same name for that secret, so I believe that Lighthouse installs and then Prow gets removed, resulting in Lighthouse not needing to create the secret, since it's identical to the Prow one, but then the removal of Prow deleting the secret (and possibly the `hook` service - still trying to verify that).
As I said, this doesn't happen consistently - I've now switched a cluster from Prow to Lighthouse, back to Prow, and back to Lighthouse, and the first time, Prow didn't get deleted at all, then the secret stuck around after the installation of Prow and removal of Lighthouse, and stuck around again after the installation of Lighthouse and …

fix: Handle Lighthouse-specific HMAC secret in update_webhooks

---

pkg/cmd/opts/install.go
pkg/cmd/update/update_webhooks.go
pkg/cmd/update/update_webhooks_test.go

I missed this before and things continued to fail as a result.
n/a

fix: Fix hmac token reference in CreateWebhookProw too

---

pkg/cmd/step/create/step_create_task_test.go
pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/tasks.yml
pkg/cmd/step/syntax/step_syntax_effective_test.go
pkg/tekton/syntax/constants.go

fix: Upgrade Kaniko to 0.22.0

---

pkg/cmd/controller/controller_build.go
pkg/cmd/step/step_stash.go
pkg/collector/git_collector.go
pkg/collector/helpers.go

fix: Support build log URLs on GitLab and BitBucket Server

---

pkg/cmd/controller/controller_build.go

fix: Don't determine git URL for log storage with bucket storage

---

pkg/cmd/ui/ui.go

feat: Make `jx ui` accept 401 JXUI response.

---

pkg/cmd/get/get_applications.go
pkg/cmd/step/report/step_report_chart.go
pkg/kube/daemonsets.go
pkg/kube/deployments.go

In some places in the code base, we were querying the wrong apiVersions, this PR removes those.
fixes #7251 
/assign @hferentschik

fix: remove usage of deprecated apiVersions

---

CONTRIBUTING.MD

[This PR](https://github.com/j…enkins-x/jx/pull/7025) has been merged but CONTRIBUTING.MD is still mentioning 1.12 as the upper supported version. The documentation repository has been updated, here is a PR to update it here too.
Relates to/fixes https://github.com/jenkins-x/jx-docs/issues/2813

fix: update Go supported versions in CONTRIBUTING.MD

---

pkg/cmd/deprecation/deprecated.go

chore: removing commands not longer in codebase from deprecation list

---

README.md

Updated a few broken links
fixes #7250

chore: fixed broken links on main readme

---

OWNERS

chore: Add Adam to OWNERS

---

hack/vault-auth-setup.sh
pkg/cmd/opts/docker.go
pkg/cmd/step/boot/step_boot_vault.go
pkg/cmd/step/boot/step_boot_vault_test.go
pkg/cmd/step/verify/step_verify_preinstall.go

feat: adding interactive config of external vs internal Vault

---

README.md

This PR removes the jx console description in the readme to open static jenkins ui. The code still exists, but will be taken care of by #7232 
fixes #7303

docs: remove docs about opening static jenkins console

---

pkg/cmd/edit/edit_buildpack.go

This command edits the team settings which then get overidden by the boot pipeline. Therefore on boot based clusters we've default the command to do nothing and instead present an error message to users.
fixes  #7126

fix: disable edit buildpack cmd for boot clusters

---

cmd/codegen/generator/client_set.go
cmd/codegen/generator/open_api.go

fix: install openapigen and clientset depedencies w/o -u option in 'go get'

---

pkg/cmd/boot/boot.go

Just a minor refactor to improve error handling
Another observation is we use `BootOptions`, since the package name is boot, it can be simplified to Options instead to avoid stutter. Thoughts? 
fixes #7333

refactor: minor refactoring of cluster connection function

---

pkg/cmd/importcmd/import.go

feat: add bot as repo collaborator during import

---

pkg/cmd/controller/pipeline/pipelinerunner_cmd.go
pkg/cmd/create/create_devpod.go
pkg/cmd/start/start_pipeline.go
pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/create/step_create_task_test.go
pkg/cmd/step/report/step_report_image_version.go
pkg/cmd/step/syntax/step_syntax_effective.go
pkg/cmd/step/syntax/step_syntax_effective_test.go
pkg/cmd/step/verify/step_verify_behavior.go
pkg/tekton/constants.go
pkg/tekton/metapipeline/clientfactory_test.go
pkg/tekton/metapipeline/metapipeline_test.go
pkg/tekton/pipelines.go

Also make it a constant so that we don't have "tekton-bot" scattered randomly through the codebase.
fixes #7355

fix: Fall back on default SA for PipelineRuns

---

pkg/cmd/ui/ui.go
pkg/cmd/ui/ui_test.go

Make `jx ui` open the Ingress URL in the browser if an Ingress exist. (Otherwise still proxy jxui)
jxui issue linked below

feat: jx ui opens Ingress in browser

---

pkg/cmd/get/vault/config/get_vault_config.go
pkg/vault/vault.go
pkg/vault/vault_test.go

fixes https://github.com/jenkins-x/jx/issues/7315

fix: attempt to make get vault-config backwardly compatible

---

pkg/vault/vault.go

chore: minor typo in vault comments

---

pkg/packages/packages.go

chore: update kubectl binary to 1.16.5

---

go.mod
go.sum

chore(deps): bump cobra from 0.0.5 to 1.0.0

---

pkg/config/install_requirements.go
pkg/config/install_requirements_test.go

- setting envconfig LeaveNil option to ensure nil structs are not initialised
- switching more override parameters to envconfig
fixes #7331

fix: making sure envconfig is not initialising nil structs

---

pkg/cmd/step/step_next_version.go
pkg/semrel/semrel.go

chore: added debugging and default values for 'jx step next-version --semantic-release'

---

jx/bdd/tf-boot/ci.sh

fix: explicitly empty buckets before 'terraform destroy'

---

pkg/cmd/uninstall/uninstall.go

When uninstalling `jx`, the PVC would hang in a terminating state. When we set the PVC, finalizer volume to `null`, the uninstall process completes as normal.
There is an open issue in [Kubernetes](https://github.com/kubernetes/kubernetes/issues/77258) that has not yet been fixed.
This PR sets the PVC finalizer to `null`, which fixes our issue and allows users to uninstall `jx`.
fixes #7165

fix: uninstall jenkins-x

---

go.mod
go.sum
pkg/gits/bitbucket_cloud.go
pkg/gits/bitbucket_server.go
pkg/gits/gerrit.go
pkg/gits/gitea.go
pkg/gits/github.go
pkg/gits/github_test.go
pkg/gits/gitlab.go
pkg/gits/interface.go
pkg/gits/mocks/git_provider.go
pkg/gits/mocks/matchers/ptr_to_github_response.go
pkg/gits/mocks/matchers/slice_of_ptr_to_github_repositoryinvitation.go
pkg/gits/provider_fake.go
pkg/util/downloads.go

Just in case there are any API changes we hadn't picked up.
n/a

chore: Upgrade go-github to v32.0.0

---

pkg/packages/packages.go

There is an issue with jx UI that needs to be fixed before this can be merged. See #7437 
fixes #7456

chore: upgrade helm2 to 2.16.9

---

pkg/cmd/step/create/step_create_task.go

so that its easier to reuse the create task step in other places

fix: add a few more options

---

pkg/environments/gitops.go
pkg/pipelinescheduler/scheduler_builder.go

fix: fix unreachable code after generating readme

---

pkg/environments/gitops.go

fix: skip dir when loop Helm templates

---

OWNERS

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

chore: add MarckK to Owners

---

pkg/apps/install.go
pkg/cmd/add/add_app.go
pkg/helm/helm_helpers.go
pkg/helm/helm_helpers_test.go

The feature supports add an app from git respository.
example:
```
jx add app https://github.com/jenkins-x-apps/jx-app-kubeless.git
```

fix: support add an app from git repository

---

pkg/cmd/create/create_branch_pattern.go

Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com> 
fixes https://github.com/jenkins-x/jx-docs/issues/2974

fix: remove broken link from command description

---

pkg/cmd/opts/commands_test.go
pkg/kube/env_test.go

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

fix: terms in test comments

---

pkg/cmd/get/get_stream.go
pkg/cmd/upgrade/upgrade_cli.go
pkg/versionstream/resolver.go
pkg/versionstream/version_data.go

Just a URL fix. The current URL 404s.
None that I saw

docs: update docs to use correct Version Stream URL

---

pkg/apps/helmops.go
pkg/helm/helm_template.go

fix: add InstallOnly to InstallChartOptions and add checks before fetchChat

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
README.md

docs: refactor issue template and add discourse link to readme

---

.github/ISSUE_TEMPLATE/bug_report.md

fix: add metadata to fix bug template

---

pkg/cmd/step/create/step_create_task.go
pkg/cmd/step/step_next_version.go

such as the `VERSION` or `jenkins-x-effective.yml`

fix: avoid errors if other files need to be added to git

---

pkg/cmd/step/create/step_create_task.go

fix: Don't error out step create task if no docker registry configmap

---

pkg/cmd/step/boot/step_boot_vault.go
pkg/config/install_requirements.go
pkg/kube/vault/vault.go
pkg/vault/create/create.go

Added in Azure Vault configuration to requirements to allow `jx boot` to install Vault correctly for Azure backed with Azure Storage and Azure Key Vault Seal
Goes hand in hand with jenkins-x/terraform-azurerm-jx#14

feat: Vault - Added in Azure Key Vault support

---

pkg/cmd/preview/preview.go

This adds a new flag to the `jx preview` command: `--single-comment`. With this flag, the Pull Request comment will only be sent once - the first time.
I added a new annotation on the Environment resource to store the last date a comment has been sent.
fixes #7562

feat: jx preview --single-comment

---

go.mod
go.sum
pkg/gits/gitea.go

chore: migrate code.gitea.io/sdk/gitea to v0.13.0

---

pkg/cmd/controller/controller_enviornmentcontroller.go

Signed-off-by: Justo Alonso <justo.alonso@gmail.com>
Add support to Gitlab hook events to support multicluster installations based on gitlab repositories.
fixes #

feat: add support to gitlab to the environment controller

---

pkg/helm/helm_template.go

fix: hack helm hooks on upgrade helm chart

---

go.mod
pkg/cloud/aks/storage/bucket_provider.go
pkg/cloud/factory/factory.go

To allow upload of build logs on AKS, I've added a basic implementation of bucket provider to upload streams to azure storage

feat: Added in Azure storage bucket provider Upload only

---

go.mod
go.sum
pkg/gits/gitea.go

chore: update code.gitea.io/sdk/gitea to v0.13.2

---

go.sum
pkg/cmd/root.go
pkg/cmd/upgrade/upgrade_plugins.go
pkg/plugins/versions.go

fix: avoid downloading newer plugin versions

---

Dockerfile-boot

fix: Add git-lfs support

---

pkg/cmd/root.go
pkg/cmd/upgrade/upgrade_plugins.go
pkg/plugins/helpers.go

Only contact Github and potentially install plugin if it isn't installed or when calling jx upgrade plugins
Fixes #7922

fix: Don't contact github to use plugin

---

.golangci.yml
.lighthouse/jenkins-x/pullrequest.yaml
cmd/app/main.go
hack/linter.sh
pkg/cmd/namespace/namespace.go
pkg/cmd/root.go
pkg/cmd/ui/ui.go
pkg/cmd/upgrade/upgrade_plugins.go
pkg/plugins/helpers.go

refactor: add lint step and fix linting issues

---

.jx/updatebot.yaml

ci: update gc deployment images for new jx releases

---

run.sh

fix: use tf chdir flag to set working dir

---

OWNERS
run.sh

fix: position of chdir in run script

---

OWNERS
go.mod
go.sum
pkg/cmd/dashboard/dashboard.go

docs: minor typo in jx dash

---

pkg/plugins/versions.go

https://github.com/jenkins-x/jx-jenkins -> it's archived.

refactor: remove deprecated jx jenkins plugin

---

.github/workflows/jenkins-x-pr.yaml
.github/workflows/jenkins-x-release.yaml
.github/workflows/jenkins-x/upload-binaries.sh
.github/workflows/plugins-pr.yaml
Dockerfile-go
go.mod
go.sum

refactor: upgrade go version to 1.17

---

.github/workflows/jenkins-x/release-chart.sh
.github/workflows/jenkins-x/upload-binaries.sh

fix: unsafe repository error in actions

---

.lighthouse/jenkins-x/pullrequest.yaml
pkg/plugins/versions.go

fix: remove resource request from step template

---

Dockerfile-boot

fix: update alpine linux to 3.15

---

OWNERS
OWNERS_ALIASES

Use maintainers alias from jx-community

Use maintainers from jx-community

---

pkg/plugins/versions.go

fix: downgrade gitops version to 0.7.8 to fix versionstream tests

---

README.md

chore: add codecov status badge

---

pkg/cmd/dashboard/dashboard_test.go

test: comment dashboard test to unblock other PRs

---

go.mod
go.sum
pkg/cmd/dashboard/dashboard_test.go

test: set namespace to fix tests in GH actions

---

.jx/updatebot.yaml
.lighthouse/jenkins-x/pullrequest.yaml
pkg/cmd/upgrade/upgrade_cli.go

chore: switch from jxr to jx3

---

pkg/cmd/root.go
pkg/plugins/helpers.go
pkg/plugins/versions.go

- fix linting issues after linter upgrade
- upgrade jx-preview to 0.0.220
- upgrade jx-gitops to 0.7.24
Upgrades are also done in this PR as the auto bumped PR are failing with lint issues

fix: linting issues after linter upgrade

---

.github/workflows/jenkins-x/changelog.sh

fix: make commit sha from main

---

.github/workflows/jenkins-x-release.yaml
.goreleaser.yml

feat: add sbom generation

---

.github/workflows/jenkins-x-release.yaml

fix: use custom step instead of action to install syft

---

.github/workflows/jenkins-x-release.yaml

fix: action syntax to download syft

---

.github/workflows/jenkins-x-release.yaml
.github/workflows/jenkins-x/upload-binaries.sh

fix: issues with syft as executable

---

.lighthouse/jenkins-x/pullrequest.yaml
Dockerfile-tfo-gcp

fix: set user to root in gcp tfo dockerfile

---

run.sh

I am not sure where INSTANCE_NAME is being set, but seems like TFO_RESOURCE is set in the pods which run the tf jobs, so using that instead to see if jx3 version pipeline gets fixed.
https://github.com/isaaguilar/terraform-operator/issues/109
For example, inside pod `tf-jx3-versions-pr3246-gsm-14-275oumxk-v2-init-pw5cd`
`TFO_RESOURCE=tf-jx3-versions-pr3246-gsm-14`

fix: use TFO_RESOURCE instead of INSTANCE_NAME

---

.github/workflows/jenkins-x-release.yaml
.jx/updatebot.yaml

fix: comment out changes related to custom tf-operator changes

---

.goreleaser.yml

fix: test goreleaser source for generating sboms

---

.github/workflows/jenkins-x/upload-binaries.sh

chore: update syft to 0.54.0

---

.github/workflows/jenkins-x-release.yaml
.github/workflows/jenkins-x/sbom-container.sh
.gitignore

feat: use oras to push sbom to ghcr

---

.github/workflows/jenkins-x/sbom-container.sh
.github/workflows/jenkins-x/upload-binaries.sh

fix: install syft

---

Dockerfile-go-maven

fix: install bash in go-maven image

---

pkg/cmd/upgrade/upgrade_cli.go
pkg/cmd/version/version.go

fix: dont download latest version if on latest version

---

Dockerfile-go-maven
pkg/cmd/upgrade/upgrade_cli_test.go

fix: modify test cases for failing tests

---

.goreleaser.yml

feat: use go 1.18.6

---

.goreleaser.yml

@osamamagdy to add it back after things are fixed.

revert: remove gobinary version from goreleaser

---

.github/workflows/jenkins-x-release.yaml
.github/workflows/jenkins-x/upload-binaries.sh
Makefile
go.mod

ci: switch to custom goreleaser image

---

Dockerfile-go-maven

fix: replace bad digest sha for alpine image

---

.github/workflows/jenkins-x-release.yaml
.goreleaser.yml
jx.pub

feat: sign goreleaser artifacts with cosign

---

hack/changelog-header.md

docs: add instructions to verify archive using cosign

---

.github/workflows/jenkins-x-release.yaml

feat: sign pushed images with cosign

---

.github/workflows/jenkins-x-release.yaml

fix: use @ instead of : to fix incorrect image reference

---

.github/workflows/jenkins-x-release.yaml

fix: add version and cosign variables to sbom generation step

---

.github/workflows/jenkins-x-release.yaml

fix: remove sbom.json from cosign sign command

---

.github/workflows/jenkins-x-release.yaml
.github/workflows/plugins-pr.yaml

ci: switch to GITHUB_TOKEN for release pipeline

---

.github/workflows/codeql-analysis.yml
.github/workflows/jenkins-x-release.yaml

ci: add package write permission at job level

---

.github/workflows/jenkins-x-release.yaml

ci: keyless signing for images using cosign

---

pkg/cmd/upgrade/upgrade_plugins.go
pkg/plugins/versions.go

Part of fix for #8466
Signed-off-by: Mårten Svantesson <Marten.Svantesson@ticket.se>

chore: add changelog to boot image

---

CONTRIBUTING.MD

Signed-off-by: Mårten Svantesson <Marten.Svantesson@ticket.se>

chore: Updating CONTRIBUTING.MD

---

hack/changelog-header.md

docs: add instructions to verify archive using cosign with keyless signing

---

hack/changelog-header.md

fix: download instructions
