jenkins-x/jx

- pkg/cmd/boot/boot.go
Verify user is connected to a cluster before attempting to `jx boot`
> feat: Verify boot cluster connection

- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/tasks.yml
- pkg/cmd/step/syntax/step_syntax_effective.go
- pkg/jenkinsfile/pipeline.go
- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/pipeline_test.go
- pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
- pkg/tekton/syntax/test_data/validation_failures/volume_missing_name/jenkins-x.yml
- pkg/tekton/syntax/test_data/volumes/jenkins-x.yml
- pkg/tekton/syntax/zz_generated.deepcopy.go
This will allow pipeline authors to add existing volumes to the pods created for their stages, which can then be mounted via `containerOptions`. Note that this will result in errors for volumes that don't exist, and could cause problems, depending on the volume's configuration, with parallel stages using the same volume.
Docs PR: https://github.com/jenkins-x/jx-docs/pull/1776
cc @tdcox 
fixes #4665
> feat(tekton): Add support for specifying volumes to add to stage pods

- pkg/cmd/importcmd/import.go
- pkg/gits/git_url.go
- pkg/tekton/pipelines.go
for creating SourceRepository and meta pipeline - as bitbucket server can use `/scm` after the host for clone URLs
fixes #
> fix: use better URLs for BitBucket Server

- pkg/cmd/step_bdd.go
This will create both staging and production environments while running bdd tests. We can remove the repositories when tests end successfully instead of skipping the production environment. We have too many repositories created for bdd tests that we should remove anyway.
> feat: create production environment while running bdd tests

- jx/bdd/tekton/ci.sh
- pkg/cmd/get/get_build_logs_test.go
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/pipelinerun.yml
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_legacy_label/pipelinerun.yml
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_pending/activity.yml
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_pending/pipelinerun.yml
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_pending/pod.yml
- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
- pkg/tekton/pipelines.go
- pkg/tekton/pipelines_test.go
This fixes issues around `jx get build log` thinking a `PipelineRun` is valid before it's actually started, tricking it into thinking that the `PipelineRun`'s pods have already been GCed.
n/a
> fix(tekton): Make sure PipelineRuns exist and are running before logging.

- pkg/cmd/create/install.go
- pkg/cmd/opts/install.go
fix: Deferred execution of adding dummy app for prow if gitOps mode is enabled to after gitOps config has been applied to environment. resolves #4801
Currently when installing both prow and enabling gitOps the absence of the ingress ConfigMap prevents addition of the dummy prow app as it assumes the presence of it on the cluster already. This PR defers execution of this dummy app addition in the case of gitOps mode until after the gitOps changes have been applied to the environment. 
fixes #4801
> fix: Deferred execution of add dummy app for gitOps mode, resolves #4801

- jx/scripts/update-website.sh
This does mean we could lose changes if there's an error in one of the steps and it never gets to the push, but I don't think that's a real problem compared to the disruption that results from `unadvertised object` errors in `pipelinerunner` when `master` changes this rapidly and three release builds get kicked off.
fixes #4840
> fix: Just push to jx-docs once in update-website.sh

- Dockerfile.builder-go-maven
- jenkins-x-images.yml
Pushes the builder-go-maven image from the images context
> chore: Push the go-maven builder during image generation

- pkg/cmd/gc/gc_gke.go
If a resource was already deleted by something else (another cronjob instance, etc), the whole GC script fails. So let's throw `|| true` after the `gcloud ... delete ...` calls so that we don't fail out on those and continue through everything else to delete.
n/a
> fix: Don't fail the whole GKE GC for a resource that's already deleted

- pkg/cloud/aks/aks.go
- pkg/cloud/aks/aks_test.go
- pkg/cmd/create/install.go
Added Azure command line flag to allow specifying an Azure subscription id for the Azure container registry as existing implementation assumed a shared subscription by both Azure Kubernetes Service and Azure Container Registry
It's not an uncommon occurrence for Azure container registry to be housed in a separate subscription from the Azure Kubernetes Service. Currently the existing code assumes they both live under whatever subscription the `az` cli is currently set to i.e. `az account show`. In order to allow installation to proceed with ACR (Azure Container Registry) housed under a different subscription to AKS I've introduced a new CLI install flag to specify the ACR subscription id. This is used in several places to 
- Specify which subscription to query the existing ACR from
- …
> fix: Added Azure command line flag to allow specifying an Azure subscription id

- Makefile
- pkg/cloud/gke/gcloud.go
- pkg/cloud/gke/gcloud_test.go
Return region if `zone` argument is a region instead of a zone.
The new test case is self descriptive
fixes #4836
> fix: jx boot fails to create storage

- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/overrides-with-buildpack-using-jenkins-x-syntax/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/packs/jx-syntax-in-buildpack/pipeline.yaml
- pkg/cmd/step/syntax/step_syntax_effective.go
- pkg/cmd/step/syntax/step_syntax_effective_test.go
- pkg/jenkinsfile/pipeline.go
- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/pipeline_test.go
Applying the overrides as we had been twice for build packs worked fine for `jenkins-x.yml`-defined pipelines or build packs that use the traditional build pack syntax. But for build packs using `jenkins-x.yml` syntax, it resulted in duplicate steps being added. So instead, let's split the step override from the non-step override.
n/a
> fix(tekton): Properly handle non-step overrides for packs using jx syntax

- pkg/auth/auth_config.go
- pkg/cmd/importcmd/import.go
Run command line below and found --git-username and --git-api-token doesn't work:
"jx import --git-username='sonyafenge' --git-api-token='**************************'"
- updated 'pkg/cmd/importcmd/import.go':
if options.GitRepositoryOptions.Username existing,  use this name to get userAuth; if not, then ask user to input.
if options.GitRepositoryOptions.ApiToken existing, grant this ApiToken to userAuth;
- updated 'pkg/auth/auth_config.go':
only request user input when userAuth.ApiToken == ""
fixes #4752
> fix: jx import does not respect --git-username and --git-api-token

- pkg/cmd/importcmd/import.go
- pkg/cmd/opts/pullrequest.go
- pkg/cmd/step/get/step_get_version_changeset_test.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/collector/git_collector.go
- pkg/gits/git_cli.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/helpers.go
- pkg/gits/helpers_test.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
- pkg/kube/env.go
Previously the code would use the push url as the remote url. This is fine when run in a pipeline but less than ideal when run locally (as in `jx boot`.
With this change we set the remote to the clone URL and use the push URL directly when we do pushes.
No tests yet - will add shortly
contributes to #4789
> fix: don’t set push urls as remotes

- pkg/cmd/create/create_addon_prow.go
- pkg/cmd/create/install.go
- pkg/cmd/opts/helm.go
- pkg/cmd/opts/install.go
- pkg/cmd/upgrade/upgrade_addon_prow.go
- pkg/helm/helm_helpers.go
When running jx upgrade add on prow on a gitops enabled cluster, upgrade prow and tekton via a PR to the dev repository
fixes #4870
> fix: Upgrade Prow in GitOps cluster

- pkg/apps/gitops.go
We will ignore charts without an `app.yaml` file when executing `jx get apps` instead of failing. 
In the non boot way to install the platform, we were creating an `app.yaml` file for Prow and Tekton charts as we were adding them individually. Ideally these should have their own `app.yaml` file instead of creating a fake one. 
fixes #4910
> feat: let's ignore the charts that have no  file when getting apps instead of forcing them

- pkg/gits/bitbucket_server.go
not doing so breaks the creation of the promotion PullRequests
> fix: bitbucket server should populate Project + Org on GetRepository

- pkg/cmd/step/verify/step_verify_preinstall.go
if the JX_REQUIREMENTS_* env vars are empty, then do not use them
> feat: check if env var exists before overridding

- pkg/cloud/gke/storage/bucket_provider.go
- pkg/cloud/gke/storage/bucket_provider_test.go
- pkg/cloud/gke/storage/long_term_storage.go
- pkg/cloud/gke/storage/long_term_storage_test.go
Added a control for an edge case that was making boot install to fail when creating a long term storage bucket
fixes #4895
> fix: fixed a bug that made boot fail when a generated bucket name ends with '-'

- pkg/cmd/step/create/step_create_meta_pipeline.go
- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipelinerun.yml
- pkg/tekton/metapipeline/metapipeline.go
- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/pipeline_test.go
While we do want unique `Pipeline`s, `PipelineRun`s, etc for each build on a given org/repo/branch, we want to use the same `PipelineResource` for all those builds. There's no reason not to reuse the `PipelineResource`s, so let's avoid CRD bloat.
fixes #4913
> fix(tekton): PipelineResource should be reused for all builds on branch

- pkg/cmd/step/git/step_git_merge_test.go
- pkg/cmd/step/step_changelog.go
- pkg/cmd/step/step_next_version.go
- pkg/gits/git_cli.go
- pkg/gits/git_cli_test.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
- pkg/gits/testhelpers/testhelpers.go
- pkg/jenkinsfile/gitresolver/buildpack_test.go
This at least restores the broken release notes as covered in #4867. @hferentschik when you are back you should pick this up and see how you think it should be fixed properly. 
We should also think about how we actually test this - it was certainly returning a nonexistent SHA.
> fix: fix the jx changelog for now

- pkg/tekton/pipelines.go
- pkg/tekton/pipelines_test.go
A bit ago, we started ignoring pipeline runs that didn't have a running step yet - so that we don't get confused by pods that are in `Pending` and think they're actually done. This meant that we ended up waiting until there was a non-init container step running, because `PipelineRun`'s status doesn't include the init containers. D'oh! So let's look for either not waiting at all or waiting but the reason is `PodInitializing` - which basically means the init containers are running or have completed and other images are being pulled.
n/a
> fix(tekton): Include logs for builds with just init containers running

- pkg/cmd/step/helm/step_helm.go
- pkg/cmd/step/helm/step_helm_apply.go
- pkg/cmd/step/helm/step_helm_build.go
After the need to get versions from the version resolver was identified for `jx step helm build`, the existing code performing this functionality was present in `step_helm_apply`. 
I moved the code to `step_helm.go` as it serves as the common dependency of all helm commands, which means it should be easier to reuse this code in the future. 
`jx step helm build` should now properly resolve all versions and be able to form a values yaml file that will be needed to perform the linting of the chart.
fixes #4940, #4909
> feat: moved the boot configuration to step helm to be used by helm build too

- pkg/tekton/metapipeline/metapipeline.go
It should be the same in the `PipelineRun` as in the `Pipeline`, generated in the same way as in the generated pipeline. This means we should be passing the resource name to `GenerateSourceRepoResource` here as we do in `generateTektonCRDs`.
/assign @wbrefvem 
Replaces #4989 
n/a
> fix(tekton): Metapipeline resource name should be consistent.

- pkg/cmd/boot/boot.go
The existing check for connected cluster would pass if a context was set in the kube config, even if it wasn't actually connected to the cluster. This extra check attempts to connect to the cluster (by retrieving namespaces).
> fix: check boot cluster exists

- pkg/cmd/step/git/step_git_validate.go
Uses the env variables GIT_COMMITER_NAME / GIT_COMMITER_EMAIL
> feat: allow gitconfig to be configured from the environment

- pkg/cmd/preview/preview.go
- pkg/kube/naming/names.go
- pkg/kube/naming/names_valid_test.go
The `jx delete preview` cmd is returning the error `error: no environment with name 'x' found` since this PR https://github.com/jenkins-x/jx/pull/4382.
> fix: jx delete preview returns error

- pkg/gits/helpers.go
~~For whatever reason, GitHub seems to get goofy when you take an existing PR, update its title and body, and _then_ immediately push a new commit to the PR. That ordering results in GitHub sending two `synchronize` events for the exact same commit, triggering two builds in Prow, etc. Which isn't ideal.~~
~~But if we flip the ordering to push first and _then_ update the title and body, only one `synchronize` is sent. So let's do that thing.~~
UPDATE: @pmuir pointed out that we actually had two pushes, which is probably the root cause here. So let's get rid of the redundant extra one instead of just moving things around.
I've tested this manually by messing around with https://github.com/jenkins-x/jenkins-x-platform/pull/5835, calling the exact same `jx step create pr chart ...` that the …
> fix: Push an updated PR before updating its title and body

- pkg/collector/git_collector.go
A few things were just completely borked in using gh-pages for log storage for a while now. If the repo didn't already have a gh-pages branch, we tried to reclone without deleting the existing attempted clone, which was bad, and then when there was a gh-pages, we tried to push `HEAD` without specifying that we actually want to push it to `gh-pages`. This fixes both of those things.
n/a
> fix: Fix gh-pages for log storage in a couple ways

- pkg/cmd/get/get_build_logs.go
- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
Added support for downloading stored logs from a HTTP(S) endpoint back. This will allow us to get logs back from GitHub pages as a fallback.
> feat: added a way to read logs from HTTP/HTTPS URLs back

- pkg/kube/crds.go
so that `kubectl get sr` shows useful clickable URLs
> fix: polish SourceRepository CRD display

- pkg/cmd/opts/docker.go
Signed-off-by: Joost van der Griendt <joostvdg@gmail.com>
- [?] Change is covered by existing or new tests.
Context; a docker image FQN* = `${Docker Registry}`/`${Docker Registry Organization}`/`${Application}`
If you want to override the Docker Registry or the Docker Registry Organization (owner) for a pipeline, you can use the `jenkins-x.yml` file. There are two fields in this file which can be used to override the Docker Registry information, `DockerRegistryHost` and `DockerRegistryOwner`.
Currently both configuration options - Docker Registry and Docker Registry Organization - are being read from `DockerRegistryOwner`. This does not allow you to only override the Docker Registry Organization, as it will automatically override the Docker Registry as well.
I believe the `dockerRegistry` …
> fix: docker registry is the host, owner is the org

- pkg/quickstarts/model.go
When more than one does in batch mode
Since https://github.com/jenkins-x-quickstarts/golang-http-from-jenkins-x-yml was created now this command used in many examples fail
```
jx create quickstart \
--language go \
--project-name xxx \
--batch-mode
error: More than one quickstart matches the current filter options. Try filtering based on other criteria (eg. Owner or Text)
```
With the patch it prints
```
error: More than one quickstart matches the current filter options. Try filtering based on other criteria (eg. Owner or Text): [golang-http golang-http-from-jenkins-x-yml]
```
/cc @vfarcic 
fixes #
> fix: print the quickstarts that match

- pkg/cmd/step/git/step_git_validate.go
Using GIT_AUTHOR env varibles, default to jx values if not available
Contributes towards fixing #4943 #4965
> fix: do not fail if git config is not available

- pkg/cmd/step/create/pr/step_create_pr.go
- pkg/cmd/step/create/pr/step_create_pr_versions.go
- pkg/gits/operations/pull_request_op.go
I had mistakenly skipped the commit for all of
`jx step create pr` which broke updatebot
fixes #
> fix: only skip the commit for the versions pr

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
- pkg/cmd/step/verify/test_data/preinstall/no_tls/jx-requirements.yml
Warn the user that continuing without TLS is not
recommended if they are using vault or web hooks.
Note that right now you can’t not use web hooks.
We present a confirmation dialog to continue, with
`N` being the default after logging warnings.
fixes #5044 fixes #5048
> fix: warn the user if TLS is not enabled

- pkg/cmd/create/create_terraform_gke.go
using a more human readable timestamp
> fix: update create-timestamp for terraform clusters

- pkg/cmd/step_bdd.go
for terraform based clusters use the name %s-dev for the cluster name
> fix: cleanup for terraform clusters

- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipelinerun.yml
- pkg/tekton/syntax/pipeline.go
See https://github.com/jenkins-x/jenkins-x-builders/pull/659 for me trying to use the new `distributeParallelAcrossNodes: true` option and discovering that I was missing something rather important. Whoops.
n/a
> fix(tekton): topologyKey needs to be specified in affinity policy

- Makefile
- jenkins-x-integration.yml
- jenkins-x-tekton.yml
- jenkins-x.yml
The test caching seems to be disable by default in all test without any option to
turn it on when test are executed locally. This option will allow to keep the
test caching on and disable it explicitly only when required.
This will speed up the test execution at least when run locally.
fixes #
> test: add an option in the makefile to disable the test caching only when is set

- pkg/tekton/metapipeline/metapipeline_test.go
Since map orders aren't guaranteed, we can't be sure that the order in which the custom env vars show up in the command line will be consistent. So stop assuming they will be in the test, and just check for each of them individually.
Saw this in the integration test run for #5051, so hey, a fix.
n/a
> fix: Don't require ordering of env vars on command in metapipeline test

- pkg/cmd/step_bdd.go
Should fix failures like `there was a problem creating a version resolver from versions stream repository and ref dff43bbff485edcf7d49a21f8916bcb62a17e011` in BDD tests using boot.
n/a
> fix: Include versions stream URL in BDD requirements

- pkg/cmd/create/create_terraform.go
- pkg/cmd/create/create_terraform_gke.go
--skip-jx-install can be used to stop the jx install into the dev cluster.  The generated cluster can then be used with jx boot
> feat: added a flag to skip the jx install for terraform clusters

- pkg/tekton/metapipeline/clientfactory.go
- pkg/tekton/metapipeline/clientfactory_test.go
> fix(tekton): allow clientFactory to clone a version stream with a SHA ref

- jenkins-x.yml
While watching a release build, I saw it spiking to its cpu limit of 3 a few times, so let's bump it to 4 and speed things up ever so slightly.
n/a
> chore: Increase cpu limit for release builds to 4

- pkg/cmd/version.go
The namespace for jx version is empty and it cannot be set.  In addition and if you have multiple teams installed on a cluster, then it reports the incorrect version because it processes releases in the whole cluster instead of the team namespace.
> fix(version): set namespace for jx version command

- pkg/tekton/metapipeline/metapipeline.go
`JX_LOG_FORMAT=json` breaks BDD tests parsing `jx get build logs`, and, frankly, makes the log output rather unappealing in the first place. So let's turn this off until @hferentschik has a more holistic approach that turns off the JSON unless a flag like `-o json` is passed to `jx get build logs`.
fixes #5208
> fix: Turn off JSON logging for metapipeline-triggered pipelines

- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
Fixed the ordering of pipeline runs so we always get the metapipeline stage(s) first.
Also reversed the ordering of pods in a certain pipeline so we show the logs of stages in order.
fixes #5207
> feat: fix ordering of metapipeline logs

- pkg/cmd/initcmd/init.go
When using kops or EKS, NLB appears to now support handling both HTTP and HTTPS traffic.  Also, if you look at the example NLB, it has both ports: https://github.com/kubernetes/ingress-nginx/blob/master/deploy/static/provider/aws/service-nlb.yaml
The way I tested this was by creating a YAML file with:
```yaml
rbac:
create: true
controller:
service:
annotations:
service.beta.kubernetes.io/aws-load-balancer-type: nlb
enableHttp: true
enableHttps: true
```
And then running:
```bash
helm repo update
helm upgrade jxing stable/nginx-ingress --values jxing-values.yaml
```
And that setup `443` on the existing NLB.  This did install `nginx-ingress` version `1.17.0` which I think is ahead of what is distributed with JX.
fixes #3079 but existing installs need to do the workaround still, this only …
> fix(init): enable both http and https for NLB ingress

- pkg/cmd/opts/helm.go
This warning message is misleading when vault is not configured as a secret
engine. It shouldn't be a warning since there is falling back on local secrets in that case.
fixes #
> chore: remove misleading warning message

- pkg/cmd/step/e2e/step_e2e_gc.go
Right now, it's checking if an existing cluster's type contains another cluster's type, but that leads to situations like `boot-lh` getting deleted because `boot-lh-ghe` is running with a higher build number. Let's change that to an equality check instead.
fixes #5238
> fix: e2e gc should check equality of cluster type between clusters

- pkg/cmd/opts/helm.go
- pkg/cmd/step/create/step_create_values.go
- pkg/cmd/step/helm/step_helm_apply.go
- pkg/cmd/step/helm/step_helm_build.go
- pkg/io/secrets/secret_locations.go
- pkg/kube/vault/vault_factory.go
In the current implementation the `step create values` is falling silently back on local secrets URL client when the vault
is not ready. This could happen during the boot sequence when vault is starting off. This results in secrets being locally stored,
but in the following steps vault becomes ready and `step helm apply` tries to fetch the secrets from vault. Unfortunately the secrets
aren't stored in vault but locally.
This is not what the user expects since he configured `secretsStorage: vault` in the `jx-requirements.yaml` file. It is better to fail
explicitly instead of mixing the secrets location in unexpected way.
I increased also some timeouts used during vault client creation. It seems that sometimes it takes longer with external DNS + TLS until
the vault becomes reachable.
fixes …
> fix: explicitly specify the secrets location when creating the vault URL client based on value specified in requirements file

- pkg/kube/services/services.go
This method is used by jx open/jx get urls to list the available URLs/ingress resource. It's
more appropriate to log a debug message when not ingress is found for a service instead of an error.
This will reduce the noise in case of services which are not exposed from the cluster.
fixes #5215
> fix: do not log an error when an ingress is not found for a service

- pkg/cmd/boot/boot.go
This should be a catch for `gitRef, err = resolver.ResolveGitVersion(gitURL)` returning blank, instead of checking if the flag `o.GitRef` was set
> fix: Use correct gitRef in boot version resolver

- pkg/cmd/step/verify/step_verify.go
- pkg/cmd/step/verify/step_verify_url.go
- pkg/cmd/step/verify/step_verify_url_test.go
This command waits with exponential backoff for a URL to return an expected status code. It will
fail when the timeout is exceeded.
Add a new command `step verify url` which waits with exponential backoff for a URL to return an expected HTTP status code. 
This is particularly useful to check when a URL configured by the external DNS is ready during the boot sequence.
fixes #
> feat: add a step command to verify if a URL returns an expected HTTP status code

- pkg/cmd/step/boot/step_boot_vault.go
- pkg/cmd/step/verify/step_verify_environments.go
There were a few issues with the master pipeline on a new GitOps cluster's dev environment repo.
We are now getting the cluster name from the `requirements.yaml` file instead of trying to get it from the cluster. We are also removing the git diff check on the dev environment repo before continuing with the master pipeline.
> feat: remove git diff check from environment repo and get vault name differently

- pkg/cmd/step/create/pr/step_create_pr_versions.go
- pkg/dependencymatrix/matrix.go
- pkg/gits/operations/pull_request_op.go
* Switch to a consistent order of `Mismatched Versions` field in dependency matrix Markdown.
* Update `machine-learning` and `machine-learning-gpu` builder images separately from `jenkins-x-builders` images.
fixes #5286 
fixes #5288
> fix: Ordering of dep matrix mismatched versions and handling of ML builders in create pr versions

- pkg/cmd/create/create_devpod.go
- pkg/cmd/opts/common.go
- pkg/cmd/opts/install.go
- pkg/cmd/opts/version.go
- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/syntax/step_syntax_effective.go
- pkg/cmd/step/verify/step_verify_packages.go
- pkg/cmd/upgrade/upgrade_cli.go
- pkg/cmd/version.go
- pkg/dependencymatrix/matrix.go
rather than using whatever is on github, lets use the version in the version stream dependency matrix.
This means that `jx version` and `jx upgrade cli` will now use the version stream instead
also added `o.GetVersionResolver()` as a helper method to lazily create and cache the creation of the version resolver to avoid multiple git clones + filling the log with duplicate clone text
fixes #5276
> fix: use the version stream to find the latest jx version

- pkg/cmd/gc/gc_activities.go
The argument assignment was flipped, so we were keeping pull requests for the release age, and vice versa.
fixes #5293
> fix: Pull request and release age limits in gc activities are flipped

- pkg/cmd/create/create_addon_environment_controller.go
- pkg/cmd/deletecmd/delete_addon_environment_controller.go
`jx create addon envctl -n jx` would ignore the namespace flag and install the environment-controller chart into the `default` namespace. Additional edits were made to the delete command in order to handle deletion of chart in namespace other than `default`.
fixes #4739
> fix: create/delete addon envctl functions to handle namespaces

- pkg/kube/ingress.go
Check that the TLS value in the ingress config is not an empty string before attempting to parse to a bool value
fixes #5319
> fix: create devpods - check for empty tls value

- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/no_pipeline_for_kind/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/remove-pipeline-from-jenkins-x-yml/jenkins-x.yml
- pkg/cmd/step/syntax/step_syntax_effective.go
- pkg/config/project_config.go
- pkg/config/project_config_test.go
- pkg/tekton/syntax/pipeline.go
Previously, we'd just end up with a nil pointer, and that's...never helpful. This will instead report an error for when there is no pipeline of a given kind in the effective config.
Also, I reworked how we check for expected errors in the test, and made `override.MatchesPipeline` case-insensitive, since we've got `pullrequest` in some places and `pullRequest` in others. Sigh.
fixes #5183
> fix: Report error for nil pipeline for expected kind

- pkg/gits/bitbucket_server.go
- pkg/gits/bitbucket_server_test.go
Signed-off-by: Mark Nielsen <mark.nielsen@blackboard.com>
When adding the webhook via API, it only seems to set the webhook under the repository's Webhooks setting. Under these settings, the server_url parameter is required as documented [here](https://support.cloudbees.com/hc/en-us/articles/115000053051-How-to-Trigger-Multibranch-Jobs-from-Bitbucket-Server-#configurationinbitbucketserver).
When I manually added this to the webhook, it started working again.
See also https://kubernetes.slack.com/archives/C9MBGQJRH/p1566807618281800
None that I could find.
> fix(gits): correct webhook URL for Bitbucket Server

- pkg/gits/bitbucket_server.go
- pkg/gits/gitlab.go
- pkg/gits/helpers.go
for bitbucket server / gitlab - they are not vital and usually we use them for updatebot type logic anyway
> fix: lets avoid failing to promote if we cannot add labels

- pkg/cmd/step/verify/step_verify_environments.go
This was failing during jx boot cli.
Unless I'm missing a change in design looks like some boolean logic was incorrectly refactored a couple days ago. `jx boot` now no longer creates a dev repo because of it.
fixes #5336
> fix: Fixed boolean logic around creating dev environment repo

- pkg/cloud/amazon/storage/bucket_provider.go
- pkg/cloud/amazon/storage/bucket_provider_test.go
- pkg/cloud/factory/factory.go
Adding AWS support for bucket provider.  This is only called during `jx step verify preinstall` command that I think it used with `jx boot` type projects.
We are not using `jx boot` yet, so didn't actually test this beyond the automated tests.  We are using AWS though, so wanted to try to get ahead of any problems.
Open questions:
1. Unsure if BDD tests or similar could be modified to include bucket creation for in AWS?
2. Wasn't sure how to get `pegomock` to work with 3rd party interface.  Maybe doesn't matter?
Didn't find any.
> feat(cloud): create buckets for AWS

- .secrets.baseline
- pkg/cmd/step/create/step_create_install_values.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/config/install_requirements.go
JX_REQUIREMENT_INGRESS_TLS_PRODUCTION can be used to toggle TLS providers
fixes #
> feat: can determine tls server from env variable

- pkg/cloud/gke/gcloud.go
During installation where google services have been enabled when the check to determine which google services are enabled executes it returns an error, the call has been updated to use an exponential backoff strategy so that it can help prevent a failure.
> fix: getEnabledServices api now uses exponential backup

- pkg/cmd/opts/releases_test.go
- pkg/dependencymatrix/commits.go
Regex didn't allow the .git suffix to be on the url
fixes #
> fix: allow .git to appear in dep update messages

- pkg/cmd/controller/controller_build.go
- pkg/kube/watcher/pods.go
- pkg/kube/watcher/watcher.go
fix up a simpler and nicer retry logic for watching resources like pods so
we can handle losing a watch; we try to rerun things if a watch fails
otherwise we restart the pod
fixes #5395
> fix: build controller should restart if it fails to list/watch pods

- myvalues.yaml.tekton.template
- pkg/cmd/controller/controller_build.go
- pkg/cmd/controller/controller_build_test.go
- pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/activity.yml
- pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/pipelineruns.yml
- pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/pipelines.yml
- pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/structures.yml
- pkg/cmd/controller/test_data/controller_build/completed_generated/expected/activity.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/cluster_state/activity.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/cluster_state/pipelineruns.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/cluster_state/pipelines.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/cluster_state/structures.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/expected/activity.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/activity.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pipelineruns.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pipelines.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/structures.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/expected/activity.yml
- pkg/tekton/metapipeline/metapipeline.go
- pkg/tekton/pipeline_info.go
This fixes a number of inconsistencies/shoddy logic/odd behavior around how metapipelines are handled in `controller_build`. First, we weren't properly detecting the `PipelineRun` type due to using the wrong prefix, which was dumb on my part. =) That on its own led to us assuming the `PipelineActivity` was complete as soon as the metapipeline finished, which led us down code paths that result in #5395. Additionally, we weren't consistent with our `PipelineRunInfo` names, which may not have been a functional bug, but was definitely a logging bug that made it hard for me to figure out what was going on.
Along the way, I realized that even with those things dealt with, we still ended up processing the metapipeline's pod, albeit after the completion of the generated pipeline, so it didn't …
> fix: Handling of completion of metapipeline in build controller was flawed

- pkg/cmd/create/create_cluster_eks.go
Neither `jx create cluster eks` nor `jx install` receive any arguments as part of its execution and every data needed is passed by flags.
Introducing a flag the wrong way: 
`--static-jenkins true` was causing the value to be passed as an argument instead of being the part of the flag like `--static-jenkins=true`.
This was being passed down the commands calls as an argument and ended up calling `jx create jenkins token "true"` which was causing errors when loging into the Jenkins server.
fixes #5000
> feat: avoid passing arguments down the chain with create cluster

- pkg/cmd/create/create_vault.go
- pkg/cmd/step/boot/step_boot_vault.go
PR allows clusterName & vaultServiceAccount name to be configured from the 
jx-requirements.yml when installing from `jx boot`
> feat: allow vault to be configured in cluster

- pkg/cloud/gke/gcloud.go
If a service account has recently been created then when the boot installation tries to lazy create the key for the service account it sometimes is unable to find it. Therefor we need to allow the function to retry when locating the service account to prevent it trying to create a duplicate.
fixes #
> fix: allow retry when searching for gcloud sa

- pkg/config/install_requirements.go
Reverses the switch that will turn on/off auto updates in `jx-requirements` to use `enabled` making it more consistent.
> chore: make autoupdate flag consistent

- pkg/gits/helpers.go
If an existing PR hadn't been merged it could be updated (by a cronJob) even though no file changes had occurred.
> fix: update PR only when files changed

- hack/linter.sh
Allow the ability to disable the linter check performed during the pre-commit phase by adding the following environment variable `DISABLE_LINTER="true"`
> feat: add ability to skip linter

- jx/bdd/tekton/ci.sh
- pkg/cmd/opts/cert_manager.go
- pkg/kube/pki/cert-manager.go
Something in `upgrade ingress` does not want to work with the newer cert-manager, so let's revert. Also adds the `upgrade ingress` BDD test to the Tekton context here so this can't happen again.
Reverts https://github.com/jenkins-x/jx/pull/5464 and #5508.
n/a
> fix: Revert update to latest cert-manager

- pkg/apis/jenkins.io/v1/types_pipeline.go
- pkg/cmd/deletecmd/delete_application.go
- pkg/kube/activity.go
- pkg/kube/activity_test.go
Since the label was a combination of repo owner and name there was a chance
it exceeded the 63 char limit of labels.
Where necessary the label were replaced with field selectors.
fixes #5515
> fix: removing sourcerepository label from PipelineActivity

- pkg/cmd/uninstall/uninstall.go
- pkg/cmd/uninstall/uninstall_test.go
Now when asked to enter the Kubernetes context to delete, we actually
display the current context.
Updated and refactored tests.
fixes #5479
> fix: making the uninstall confirmation clear by displaying context

- pkg/tekton/metapipeline/clientfactory.go
We're not passing the pull refs to the `PipelineActivity` for metapipelines, which causes things like batch reconciliation not to be performed. This was surfaced in the process of investigating #5539.
fixes #5552
> fix(pipeline): Pass pull refs for metapipeline to PipelineActivity

- pkg/cmd/step/step_override_requirements.go
- pkg/config/install_requirements.go
The storage enabled check for each storage was not being populated correctly during the override step, this should now populate the local field correctly so that it can determine whether it's enabled or not.
The backup storage enabled and url can now also be overridden using an environment variable.
> fix: correct and add storage overrides for boot override step

- pkg/kube/test_integration/activity_integration_test.go
- pkg/kube/test_integration/doc.go
> fix: move activity_integration_test.go into dedicated package

- pkg/cmd/step/verify/step_verify_environments.go
GIT_AUTHOR_NAME/GIT_AUTHOR_EMAIL should not be added if they already exist.
Fixes #5574
> fix: avoid duplicating env vars during verify env

- pkg/cloud/amazon/common.go
- pkg/cloud/amazon/common_test.go
- pkg/cmd/step/verify/step_verify_preinstall.go
chore: formatting and comment
Added code to gather boot requirements when using EKS and add the `Region` to the `jx-install-config` ConfigMap.
Also fixed an issue where we would panic when asking for feedback and the user answered no.
fixes #5441 
fixed #5370
> feat: correctly gather boot requirements for EKS

- pkg/cmd/step/verify/step_verify_preinstall_test.go
At the moment, `jx boot` launched in `batch mode` with a provider different than GKE, requires the user to input a confirmation to proceed. Since batch mode should run seamlessly, this PR implements a way to skip the user's input and log the same message instead.
fixes #5573
> fix: boot command should not ask for confirmation when provider is not GKE

- pkg/cmd/step/step_credential.go
this command allows a pipeline to download a secret and store it in
a file on the file system.  This is not a recommended approach, secrets 
should be mounted outside of the workDir
> chore: remove the --file flag from 'jx step credential'

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_test.go
- pkg/kube/constants.go
When using AWS, you need to provide the AWS_REGION variable in multiple parts of the code (among others).
I needed a way to reliably get this from the cluster configuration so we may as well save the current state of the requirements yaml in a config map so we can access it from everywhere in the code.
This allows for some utility code that can be used to return an implementation based on cloud provider. 
part of #5432
> feat: add the requirements file to a ConfigMap on every pipeline run so it can be obtained in other contexts

- pkg/logs/tekton_logging.go
- pkg/logs/test_data/metapipeline_failure/pipelineruns.yml
I'm not good with pointers, basically. If there are multiple runs for an owner/repo/branch, without this, the pointers returned by `getPipelineRunsForActivity` end up pointing to the last run we looked at, not the one that actually matched. Sigh. I modified an existing test to fail without this fix.
fixes #5652
> fix: Don't use pointers for getPipelineRunsForActivity return

- jx/scripts/update-bot.sh
Once https://github.com/jenkins-x/jenkins-x-builders/pull/823 is merged, it will handle updating the jx version in `jenkins-x-platform` and `prow`, keeping them more cleanly in sync.
fixes #5596
> fix: Stop updating jenkins-x-platform and prow charts from jx directly

- pkg/cmd/step/verify/step_verify_git.go
- pkg/gits/github.go
Add special handling for the Jenkins-x[bot] user. This is the Github app bot.
fixes #
> feat: adding Jenkins-x[bot] user

- pkg/cloud/gke/gcloud.go
Sometimes a check whether a bucket exists times out, this change enables a retry logic on the `gsutil` check.
> fix: allow bucket check to retry

- pkg/gits/git_url.go
- pkg/gits/git_url_test.go
allows import repos created inside subgroups in Gitlab
for example: https://gitlab.com/good-backend/subgroup/test-project
about subgroups: https://gitlab.com/help/user/group/subgroups/index
fixes #
> fix: import GitLab repos with subgroups

- charts/jx/templates/serviceaccount.yaml
For example, IAM permissions via service accounts require
eks.amazonaws.com/role-arn annotations for ServiceAccount.
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
Please note that I have not been able to test this on a live cluster - I've not been able to work out how to patch in the changes.
> feat: allow annotations on ServiceAccount

- pkg/cmd/gc/gc_gke.go
We're now using a service account for external DNS in `jenkins-x-boot-config`'s `boot-vault` tests but not cleaning it up.
n/a
> fix: Clean up "-dn" service accounts in e2e GC as well

- pkg/cmd/step/boot/step_boot_vault.go
The vault operator is currently always using the default version stream to lookup its image tag.  This can lead to the incorrect one being used (or a failure occurring as the ref of the incorrect version stream being doesn't exist)
> fix: specify version stream for vault operator

- pkg/cmd/step/create/pr/step_create_pr.go
- pkg/cmd/step/create/pr/step_create_pr_quickstarts.go
- pkg/cmd/step/create/pr/step_create_pr_versions.go
- pkg/gits/operations/pull_request_op.go
- pkg/gits/operations/pull_request_op_test.go
If we can get the git author name and email, add `Signed-off-by: NAME: <EMAIL>` to commit messages generated by `jx step create pr`.
fixes #5735
> fix: Add "Signed-off-by:" to `jx step create pr` commit messages

- jenkins-x-boot-vault.yml
- pkg/cmd/clients/factory.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_environments_test.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_test.go
- pkg/kube/env.go
We're now storing `jx-requirements.yaml` in `TeamSettings`, so let's check there for whether we should be discovering the Vault URL automatically or not, rather than using the env var override. Local `jx-requirements.yaml` still gets priority.
fixes #5746
> fix: Use requirements from TeamSettings instead of env var for vault URL check

- pkg/health/health.go
http client requires a protocol when sending request to kuberhealthy in cluster. Out of cluster a follow redirect with auth is required to cover both http and https possibilities.
> fix: kuberhealthy protocol and authed redirect

- pkg/cmd/controller/controller_build.go
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pipelineruns.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/expected/activity.yml
If a step in a pod fails, the steps after it will all end up terminated with a 0 exit code, making the build controller think they were actually successful. They weren't - they were never actually run. So let's mark them as not executed.
/assign @romainverduci 
fixes #5768
> fix: Mark steps after a failed step as not executed in PipelineActivity

- pkg/cloud/amazon/common.go
- pkg/cloud/amazon/ecr.go
- pkg/cmd/step/verify/step_verify_preinstall.go
… wrong regions due to misconfiguration
A quick fix to use the right region when adding the default ERC registry when booting. 
With that, and the build pod assuming a role through the `tekton-bot` `Service Account`, we are able to build and push Docker images using Kaniko in EKS.
fixes #5433
> feat: get the current region and cluster name differently so we avoid wrong regions due to misconfiguration

- OWNERS
- pkg/cmd/controller/controller_build.go
- pkg/cmd/controller/controller_build_test.go
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/activity.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pipelineruns.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pipelines.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/structures.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/expected/activity.yml
If a stage fails and there are one or more stages supposed to run after it, those stages are currently left in `Pending` forever, with the `PipelineActivity` as a whole staying as `Running`. Those stages should instead by marked as `NotExecuted` and the `PipelineActivity` should be marked as `Failed`.
Also adds @romainverduci as an `OWNER`. =)
fixes #5779
> fix(activity): Properly handle unrun stages after a failure

- pkg/cmd/controller/controller_workflow.go
- pkg/cmd/promote/promote.go
- pkg/kube/activity.go
- pkg/kube/activity_test.go
`PipelineActivity` status is only updated from `Running` with a manual promotion via `controller_workflow`, which we're not using with Tekton enabled. So let's make `OnPromoteUpdate` and `OnPromotePullRequest` update their `PipelineActivity` status when they're called for a terminal status.
/assign @romainverduci 
fixes #5755
> fix(activity): Set activity status for manual promotions with Tekton

- pkg/cmd/step.go
- pkg/cmd/step/github/step_github.go
- pkg/cmd/step/github/step_github_app.go
- pkg/cmd/step/github/step_github_app_token.go
- pkg/github/github_app.go
- pkg/tenant/tenant.go
- pkg/tenant/tenant_test.go
- pkg/util/http_utils.go
As part of the github app integration, we need the ability to query the github app for an installation token during `jx boot` and then refresh at regular intervals. Creating a step command to allow us to do this. The command will query the tenant service to get an installation id and then a github app to get an installation token. This token is then written to a k8 secret
Command:
`jx step github app token`
fixes #
> feat: github app integration

- pkg/cmd/step/verify/step_verify_environments.go
- pkg/gits/helpers.go
- pkg/gits/helpers_test.go
fixes #5819
* only call `handleDevEnvironmentRepository` is in `jx boot`. This effectively pulls up ` o.isJXBoot()` one level 
* Let helpers#DuplicateGitRepoFromCommitish return an error if the target repo exists which is more in line with one would expect from the function name
> fix: only create/update dev environment repo when within `jx boot`

- pkg/cmd/step/verify/step_verify_environments.go
- pkg/config/install_requirements.go
Also override the dev environment ingress config with the main ingress config. They should be identical.
In the near future, we should deprecated the main ingress config in favour of dev env ingress config.
fixes #
> fix: define the TLS secret name in each environment ingress config

- pkg/collector/git_collector.go
Why:
This change addresses the need by:
GitHub Enterprise Provider have different raw location for files
Signed-off-by: Jiang Yitao <jiangyt.cn@gmail.com>
```
$ jx get build log
? Which build do you want to view the logs of?:  sosops/devops-staging/master #23
error: there was a problem obtaining the log file from the github pages URL https://raw.githubusercontent.com/sosops/devops-staging/gh-pages/jenkins-x/logs/sosops/devops-staging/master/23.log: status 404 Not Found when performing GET on https://xxxx@raw.githubusercontent.com/sosops/devops-staging/gh-pages/jenkins-x/logs/sosops/devops-staging/master/23.log
```
fixes #
> fix(logs): Get correct location For completed builds in GHE

- pkg/cmd/boot/boot.go
- pkg/cmd/boot/boot_test.go
- pkg/cmd/boot/test_data/jenkins-x-versions/git/github.com/jenkins-x/jenkins-x-boot-config.yml
- pkg/cmd/boot/test_data/requirements/jx-requirements.yml
When `jx boot`ing if no gitRef is specified if should look it up from the version stream being used.  If it is not found in the version stream then `master` should be used.
> fix: default gitRef to master if not in default/specified version stream

- pkg/boot/constants.go
- pkg/cmd/boot/boot.go
- pkg/cmd/create/install.go
- pkg/cmd/opts/expose.go
- pkg/cmd/opts/helm.go
- pkg/cmd/opts/team_settings.go
- pkg/cmd/opts/upgrade/upgrade_ingress.go
- pkg/cmd/opts/version.go
- pkg/cmd/step/get/step_get_version_changeset.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_environments_test.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
- pkg/cmd/upgrade/upgrade_boot.go
- pkg/cmd/upgrade/upgrade_platform.go
- pkg/gits/git_cli.go
- pkg/gits/git_cli_test.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
- pkg/versionstream/versionstreamrepo/gitrepo.go
- pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
* De-reverts #5110, in the process reverting #5870.
* `gitter.Describe` should fall back on just returning the original ref if the commit-ish is untagged.
* The tests in `gitrepo_integration_test.go` weren't actually doing the right thing or testing the right thing.
/assign @wbrefvem 
fixes #5087
> fix: Bring back, and fix, locking version stream to tags

- pkg/cmd/upgrade/upgrade_boot.go
Adds support to run `jx upgrade boot --upgrade-version-stream-ref='branch_name'.
fixes #5885
> chore: support making the version stream upgrade ref configurable

- pkg/cmd/controller/pipeline/pipelinerunner_cmd.go
- pkg/cmd/start/start_pipeline.go
- pkg/tekton/metapipeline/clientfactory.go
- pkg/tekton/metapipeline/clientfactory_test.go
- pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
Now that the standard version stream cloning logic has merged, let's use that in metapipeline rather than its own logic.
fixes #5075
> fix(pipeline): Use standard version stream cloning logic in metapipeline

- .secrets.baseline
- pkg/cmd/create/create_addon_vault.go
- pkg/cmd/create/install.go
- pkg/cmd/step/boot/step_boot_vault.go
- pkg/cmd/step/helm/step_helm_apply.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_test.go
- Installation of the vault operator was not using version stream specified in the requirements for `jx boot`. It was not set in the helm InstallChartOptions and was ignoring what was set in teamsettings and then defaulted to the default version stream.  This fix passes the values through in InstallChartOptions.
- Similarly in `jx step helm apply` this PR now passes the version steam config from requirements through in helm InstallChartOptions. 
- `jx step verify preinstall` was updating the team settings prior to the above steps. This wasn't taken effect however, as the team settings is being ignored. Removing this functionality as the above means it's no longer required, and this also prevents team settings being updated in multiple places. It should reflect what is in the dev-env …
> fix: ensure helm is using requirements version stream

- pkg/cmd/upgrade/test_data/upgrade_boot_builders/jenkins-x-boot-config/values.tmpl.yaml
- pkg/cmd/upgrade/upgrade_boot.go
- pkg/cmd/upgrade/upgrade_boot_test.go
- pkg/gits/git_cli.go
As part of the `jx upgrade boot` process, builder images for kubernetes resources in templates needs to be upgraded inline with version update being performed in the pipeline files.
An example of this is the upgrade cronJob itself.
To implement in the dev environment repo, something like `builderImage: gcr.io/jenkinsxio/builder-go:0.1.791` needs to be included in `env/values.tmpl.yaml` and then `{{ .Values.builderImage }}` can replace any builder images specified in `env/templates/` files
> feat: upgrade template builder images

- jenkins-x-bdd.yml
- jenkins-x-boot-vault.yml
- jenkins-x-tekton.yml
- pkg/builds/build_info.go
- pkg/builds/build_number.go
- pkg/cmd/preview/preview.go
- pkg/cmd/start/start_pipeline.go
- pkg/cmd/step/bdd/step_bdd.go
- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/pr/step_pr_labels.go
- pkg/cmd/step/step_stash.go
- pkg/cmd/step/step_stash_integration_test.go
- pkg/tekton/metapipeline/metapipeline.go
- pkg/tekton/pipeline_info.go
- pkg/util/constants.go
So let's delete `~/.kube/config`, which just contains the test cluster in it, before we stash anything.
n/a
> fix: BDD test reports don't stash after using a test cluster

- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipelineresources.yml
- pkg/tekton/metapipeline/client.go
- pkg/tekton/metapipeline/clientfactory.go
- pkg/tekton/metapipeline/metapipeline.go
- pkg/tekton/pipelines.go
- pkg/tekton/pipelines_test.go
- pkg/tekton/test_data/next_build_number/no_activities/activities.yml
- pkg/tekton/test_data/next_build_number/unparseable_build_number/activities.yml
- pkg/tekton/test_data/next_build_number/valid/activities.yml
With the new `UseActivityForNextBuildNumber` and `UseBranchAsRevision` boolean parameters for `PipelineCreateParam`, you can force the metapipeline to:
* Determine the next build number by looking at the build numbers on `PipelineActivity`s for this org/repo/branch combination, rather than using (and if need be creating) the `SourceRepository`.
* Pass the new `--branch-as-revision` flag to `jx step create task`, which will override the default behavior of using the new version tag to checkout for release pipelines, instead just using the given branch.
fixes #5909
> feat(pipeline): Allow activity for next build number and branch as revision

- pkg/gits/git_cli.go
lets not fail if we try and add a git remote if one already exists
> fix: git remote add fix

- pkg/cmd/boot/boot.go
- pkg/cmd/create/install.go
- pkg/cmd/opts/domain.go
- pkg/cmd/opts/helm.go
- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/helm/step_helm.go
- pkg/cmd/step/helm/step_helm_apply.go
- pkg/cmd/step/helm/step_helm_version.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_git.go
- pkg/cmd/step/verify/step_verify_install.go
- pkg/cmd/step/verify/step_verify_packages.go
- pkg/cmd/step/verify/step_verify_pod_ready.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_requirements.go
- pkg/kube/secrets.go
- pkg/log/log.go
- pkg/versionstream/versionstreamrepo/gitrepo.go
fixes #5927
You get a more verbose output which contains most of the original output of `jx boot` via:
```
$ jx --verbose boot
$ JX_LOG_LEVEL=debug jx boot
```
Still room for improvement, but imo the default output is a bit saner.
Would love to separate default UI output (to stdout) from logging. It really is unfortunate that we use the logger for both.
> fix: Reducing and structuring the log output of `jx boot`

- pkg/versionstream/versionstreamrepo/gitrepo.go
- pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
This is a fix for one scenario where `~/.jx/jenkins-x-versions` can't get updated. I'm still trying to find more. =)
fixes #5945
> fix: Delete and reclone version stream in case of non-fast-forward

- pkg/kube/activity.go
- pkg/kube/activity_test.go
We don't use the `SourceRepository` in the `PipelineActivity` any more, so let's stop doing this.
n/a
> fix: Don't lazily create SourceRepository for PipelineActivity

- pkg/gits/github.go
This should hopefully get `jx promote` and `jx delete app` to stop getting confused by `tide` contexts, blocking merging due to the `tide` context being, obviously, `pending`, and also first in the list. So this will make sure that we check the latest non-`tide` context with a state instead.
n/a
> fix: Ignore tide context for last commit status on PRs

- pkg/cmd/boot/boot.go
- pkg/cmd/boot/boot_integration_test.go
- pkg/gits/helpers.go
This will check if the boot clone isn't using the ref the desired tag points to, after cloning the boot config if needed. If the clone is using a different ref, it will try to stash any local changes, update the clone to use the appropriate ref, and unstash those local changes. If there are errors in the unstash due to conflicts, it'll report the `git stash pop` error message and tell the user what they need to do to fix it.
/assign @macox 
fixes #5929
> fix(boot): Try to update local boot clone to config ref from versions

- pkg/cmd/controller/controller_build.go
Just warn if a `SourceRepository` or `PipelineActivity` that doesn't already have its label populated is not able to be updated due to one or more of the label values being an invalid value for a k8s label.
fixes #4049
> fix: Don't crash build controller for errors in labeling legacy resources

- pkg/cmd/get/get_activity.go
- pkg/cmd/get/get_activity_test.go
- pkg/cmd/testhelpers/cmd_test_helpers.go
- pkg/kube/activity_test.go
- pkg/kube/env.go
This PR introduces the flag `--sort` to the get activities command which will return a sorted version of the activities by timestamp.
fixes #2910
> feat: sort activities output

- Makefile
- pkg/cmd/upgrade/upgrade_boot.go
- pkg/cmd/upgrade/upgrade_boot_integration_test.go
Without doing that, the cherry-pick will fail due to the commit from the release tag not being present in the local boot repo, since it's not on master.
/assign @macox 
fixes #5974
> fix(boot): 'jx upgrade boot' needs to fetch upgrade boot config SHA before cherrypicking

- go.mod
- pkg/cloud/amazon/common.go
- pkg/cloud/amazon/common_test.go
The regex to determine the EKS cluster name and region does not support the EKS ARN which is the format of the context name generated by `aws eks update-kubeconfig` 
This issue appears when running `jx boot` and `jx install`
Added functionality where an attempt is made to retrieve the eks cluster name from AWS via the AWS eks sdk looping through all the eks clusters until one is found that has an endpoint matching the one in the current kubeconfig context.
Also includes a small typo fix
I was unable to run `make build` as i received the following errors:
```
make build
CGO_ENABLED=0 GO111MODULE=on go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=2.0.882-dev+66cb8bdc8 -X github.com/jenkins-x/jx/pkg/version.Revision='66cb8bdc8' -X …
```
> fix: Add support for eks arns as context names

- jx/bdd/boot-vault/ci.sh
This is needed due to #5949 causing `jx boot` to fail out if you clone a newer version of `jenkins-x-boot-config` than is in the version stream and then run `jx boot` from in that newer clone.
n/a
> test: Use boot config release from version stream in boot-vault test

- pkg/cmd/controller/controller_build.go
- pkg/cmd/get/get_build_logs.go
- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
- pkg/logs/test_data/metapipeline_and_pending_generated/pipelineruns.yml
- pkg/logs/test_data/metapipeline_and_pending_generated/pods.yml
- pkg/logs/test_data/metapipeline_and_pending_generated/structures.yml
- pkg/logs/test_data/pod_with_failure/pipelineruns.yml
Don't just log the metapipeline if it failed or is still running and there is no generated `PipelineRun` yet - also log it if the generated `PipelineRun` exists but it doesn't yet have running pods (which can be the case for a number of reasons).
This should fix a failure that shows up very sporadically in BDD tests, like in https://dashboard-jx.jenkins-x.live/teams/jx/projects/jenkins-x/jx/PR-6003/6.
fixes #6007
> fix(logs): Log metapipeline when generated pipeline is not yet running

- pkg/cmd/step/verify/step_verify_preinstall_test.go
- pkg/config/install_requirements.go
The helm charts in `jenkins-x-boot-config` need to check this value a bunch of times, so it'd be awkward to tweak them to always do a `hasKey` check first. So let's set this by default to `"nexus"` - can't go with `""` as the default because the field is `omitempty`.
Fixes version stream BDD failures like:
```
STEP: install-jenkins-x command: /bin/sh -c ** step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders in dir: /workspace/source/boot-source/env
Modified file /workspace/source/boot-source/env/Chart.yaml to set the chart to version 1
error: generating values.yaml for tree from /tmp/**-helm-apply-164375805/env: failed to execute Secrets template: /tmp/**-helm-apply-164375805/env/bucketrepo/values.tmpl.yaml: template: values.tmpl.yaml:1:23: executing …
```
> fix: Set `.Requirements.repository` by default to "nexus"

- pkg/cmd/opts/helm.go
- pkg/cmd/step/helm/step_helm_release.go
- pkg/cmd/step/step_override_requirements.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/config/install_requirements.go
- pkg/gits/github.go
- pkg/gits/provider.go
- pkg/kube/constants.go
if folks are running bucketrepo then there's not a huge point to using chartmuseum as well; we may as well use a single artifact repository for both
fixes: #6005
> fix: allow chartmusem to be replaced with bucketrepo

- pkg/cmd/importcmd/import.go
- pkg/cmd/importcmd/import_test.go
- pkg/kube/sourcerepositories.go
We need to add `TypeMeta` to the serialized form of `SourceRepository`s added by `jx import` in the dev env repo, so let's just add that `TypeMeta` whenever we're creating a `SourceRepository`. It's cleaner that way anyway.
fixes #6016
> fix: "jx import"-created source repositories in dev env should be valid

- pkg/cmd/opts/install.go
Homebrew Cask is now integrated into Homebrew itself and tapping `caskroom/cask` will now return an error.
Fixes #6014
> fix: do not `brew tap caskroom/cask` when installing `gcloud` on macOS.

- pkg/cmd/boot/boot.go
this changeset will allow us to pass in a PR sha into `jx boot` so that we 
can test changes to a boot-config repo before they are merged.
> feat: allow boot to correctly launch from a sha

- pkg/cmd/controller/controller_workflow.go
- pkg/cmd/controller/controller_workflow_integration_test.go
- pkg/cmd/opts/helm.go
- pkg/cmd/promote/promote.go
- pkg/cmd/step/bdd/step_bdd.go
- pkg/cmd/step/helm/step_helm_release.go
- pkg/cmd/step/step_release.go
- pkg/helm/helm_helpers.go
as before this PR we were hard coding to use the chart museum URL
> fix: use correct chart repo URL when promoting with bucketrepo

- pkg/cmd/get/get_activity_test.go
- pkg/cmd/get/get_preview_test.go
- pkg/cmd/testhelpers/cmd_test_helpers.go
- Move FakeOut to be a helper
- Switch usage of BeforeSuite to BeforeEach so setup is visible on every
test specifically and not just magically by the first test that
introduced it
> chore: refactor `cmd` ginkgo tests

- jx/bdd/boot-vault/ci.sh
- pkg/cmd/boot/boot.go
- pkg/cmd/boot/boot_integration_test.go
- pkg/gits/git_cli.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
This will let newer commits or tags in the boot config be used for the local boot clone.
fixes #6024
> fix(boot): Only update to version stream boot config if current is ancestor

- pkg/versionstream/resolver.go
- pkg/versionstream/version_data.go
Fix for faulty commands being output:
`jx step create version pr` -> jx step create pr versions`
fixes #5724
> fix: Correct command name in output

- pkg/cmd/opts/helm.go
- pkg/cmd/promote/promote.go
- pkg/cmd/promote/promote_test.go
This PR introduces the function `EnsureApplicationNameIsDefined()` which is used to make sure that the application name is set when running the `jx promote` command. This functionality was extracted from the `Run()` function and additionally added a check for the user to confirm whether the name of the app is correct when we guessed it.
Some things to consider:
- I decided to export it, to make it easier to test without having to do a lot of test preparation.
- Because the process to figure out the app name is tightly coupled to to other function in the promote and helm packages I decided to pass those functions as parameters so it's easier to provide fake functions in the tests. I think this should be ok because the functionality being tested is not the one from figuring out the …
> fix: ask user to validate discovered app name

- pkg/config/install_requirements.go
OpenShift can use `Route` to expose endpoints, the configmap for the exposer always set to the `Ingress` by `jx boot` before. With such parameter, we can configure exposer type.
fixes #
Support:
https://github.com/jenkins-x-charts/jxboot-resources/pull/9
> feat: add the capability to configure exposer

- pkg/gits/git_cli.go
Since jx is assuming the output of git is is in English it should tell git to output English.
As it is now commands can fail because jx doesn't recognise the output of git when locale isn't specifying English language. For example in the case of promote:
```
error: pulling environment repo https://github.com/foo/environment.git into /Users/bar/.jx/environments: fetching origin promote-fubar-0.0.9: git output: fatal: Kunde inte hitta fjärr-referensen promote-fubar-0.0.9: failed to run 'git fetch origin promote-fubar-0.0.9' command in directory '/Users/bar/.jx/environments/production', output: 'fatal: Kunde inte hitta fjärr-referensen promote-fubar-0.0.9'
```
jx looks for the string `couldn't find remote ref` in method IsCouldntFindRemoteRefError. In thes same file (pkg/gits/helpers.go) …
> fix: Output language of git

- pkg/cmd/create/create_addon_environment_controller.go
- pkg/cmd/create/create_vault.go
- pkg/cmd/get/get_stream.go
- pkg/cmd/scan_cluster.go
- pkg/cmd/step/get/step_get_version_changeset.go
We shouldn't have been doing this in the first place, but definitely not now that we've changed `config.DefaultVersionsURL` to be overridable, and we've got a standard API for cloning the version stream. So change places that were previously using `config.DefaultVersionsURL` to use an empty string instead, which will result in the team settings-provided version stream URL being used instead.
n/a
> fix: Don't use config.DefaultVersionsURL outside of version stream cloning logic

- pkg/cmd/boot/boot.go
We just hit a bug which resulted in `o.GitRef` being unset, and so everything failed to check out etc. We should be passing `gitRef` around, not `o.GitRef`, since `o.GitRef` has legitimate cases for being unset.
n/a
> fix: More consistent use of `gitRef` rather than `o.GitRef` in boot

- pkg/gits/github.go
- pkg/gits/github_test.go
This PR adds unexported function `extractRepositoryCommitAuthor()` which will extract the author information from a GitHub commit. It will give preference to the commit's author above the github user when available.
fixes #5726
> fix: extract author info from commit

- Dockerfile.builder-go-nodejs
- jenkins-x-boot-vault.yml
- jenkins-x-tekton.yml
- pkg/cmd/step/create/pr/step_create_pr_versions.go
This will enable us to use Cypress tests within BDD tests.
We also add support for updating the `jenkins-x*.yml`s in `jenkins-x-versions` to use the latest `builder-go-nodejs` image, since we'll be switching them to use that builder as well. Once this merges and gets through builders, I'll update the image used in the version stream update cronjob.
/assign @romainverduci 
n/a
> chore: Add builder-go-nodejs, switch BDD tests to use that image

- pkg/cmd/cmd.go
- pkg/cmd/deprecation/deprecated.go
This generates a message such this before the command execution:
```
$x upgrade ingress
Command "ingress" is deprecated, it will be removed on 01-02-2020. We now highly recommend you use boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details.
```
fixes #
> feat: implement a generic mechanism to deprecate commands and marked a few commands as deprecated

- pkg/builds/build_info.go
- pkg/builds/build_info_test.go
- pkg/cmd/get/get_build_logs.go
- pkg/cmd/get/get_build_pods.go
so its easier to view the logs of a repo or PR by copy/pasting the git URL
> fix: allow passing in of a git repo or PR URL for `jx get build log/pod`

- pkg/builds/build_info.go
Build logs support filtering by `build_id`
Fixes https://github.com/jenkins-x/jx/issues/5656
> fix(build logs): allow to filter by `build_id`

- pkg/cmd/step/get/step_get_dependency_version.go
Because I keep messing up regexs to remove the boilerplate, so let's
add an option to just output the version.
n/a
> chore: Add --short option to jx step get dependency-version

- pkg/cmd/step/verify/step_verify_pod_ready.go
- pkg/cmd/step/verify/step_verify_pod_ready_test.go
`jx start pipeline` doesn't seem to add the `created-by-prow` label, so let's check for the presence of `tekton.dev/pipelineRun` when we're excluding build pods instead.
fixes #6085
> fix(boot): Exclude all pipeline pods from pod ready check

- pkg/cmd/step/report/step_report_junit.go
- pkg/cmd/step/report/step_report_junit_test.go
- pkg/cmd/step/report/test_data/junit/multiple_reports/ui_smoke.junit.xml
- pkg/cmd/step/report/test_data/junit/testsuites_report/ui_smoke.junit.xml
`jx step report junit` is used to aggregate junit reports from different sources, it was only handling reports of this kind:
```
<testsuite>...</testsuite>
<testsuite>...</testsuite>
<testsuite>...</testsuite>
```
This change allows the step to handle as well:
```
<testsuites>
<testsuite>...</testsuite>
<testsuite>...</testsuite>
<testsuite>...</testsuite>
</testsuites>
```
> chore: jx step report junit can handle both []<testsuite> and <testsuites> junit kind of reports

- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
- pkg/logs/test_data/active_single_run/pipelineruns.yml
- pkg/logs/test_data/failed_and_rerun/pipelineruns.yml
- pkg/logs/test_data/only_waiting_step/pipelineruns.yml
The immediate impetus here is that BDD tests can fail in this scenario, because more than one pipeline is found for the filter - the one that failed, and the one that was retried. But this should just clean things up a bit anyway.
~~I'll come back and add tests for this later today.~~
EDIT: Test added.
fixes #6061
> fix: Don't include pipeline runs that failed/were retried by Prow in logs

- pkg/cmd/deprecation/deprecated.go
There are commands such as install which has children but still implements its own
functionality. We want to deprecate also in this case the command.
fixes #
> fix: check also the commands which have children for deprecation

- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/tolerations/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/tolerations/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/tolerations/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/tolerations/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/tolerations/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/tolerations/tasks.yml
- pkg/tekton/metapipeline/metapipeline.go
- pkg/tekton/pipelines.go
- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/pipeline_test.go
- pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
- pkg/tekton/syntax/test_data/tolerations/jenkins-x.yml
- pkg/tekton/syntax/zz_generated.deepcopy.go
If said arbitrary label(s) are specified and `distributeParallelAcrossNodes` is true, then those label(s) will be used for the anti-affinity rather than the default of the `tekton.dev/pipelineRun` label+value. This will allow multiple runs of one or more pipelines to be on unique nodes, not just multiple pods of a single pipeline run.
Also switched the `distributeParallelAcrossNodes` behavior from `PreferredDuringSchedulingIgnoredDuringExecution` to `RequiredDuringSchedulingIgnoredDuringExecution`.
n/a
> feat: Add support for specifying node tolerations in pipeline syntax and specifying arbitrary labels for pipeline pods

- pkg/expose/exposecontroller.go
fixes #5800
supersedes PR  #5816
this PR adds the quotes around the URL template as well (as did #5816), but only if the template is not empty. I think for non-empty URL templates the quotes are indeed needs.
That said, jx upgrade ingress seems to work with an empty URL template, but not with a custom one.
> fix: wrap Exposecontroller UrlTemplate config in quotes

- pkg/cmd/stop/stop_pipeline.go
Prior to this PR, when a user ran `jx stop pipeline`, we'd display
the pipelines that could be stopped without the build number. This
commit adds the build number so it's easy to see which build would be
stopped when a user stops a pipeline.
fixes #5626
> fix: Add build number when displaying pipelines to stop

- pkg/gits/helpers.go
- pkg/versionstream/versionstreamrepo/gitrepo.go
We need to be able to use a branch as a versions stream ref in order to get our automated release system to work, if the ref is a branch it will look for it in the remote branches and then checkout to it if it is.
fixes #
> feat: checkout to the ref instead of FETCH_HEAD if ref is a branch

- pkg/cmd/add/add_app_test.go
- pkg/gits/helpers.go
- pkg/gits/helpers_test.go
**Fixing the following issue:**
It's not possible to install an app with a version containing capital letters like SNAPSHOT which can be useful for development and test purposes.
eg: `jx add app your-app --version=0.0.1-SNAPSHOT ` would fail with the following error:
```
error: adding app your-app version 0.0.1-SNAPSHOT with alias  using gitops: creating pr for your-app: pulling environment repo https://github.com/xxxx/environment-xxx-dev.git into /Users/xxx/.jx/environments: fetching origin add-app-your-app-0.0.1-SNAPSHOT: git output: fatal: couldn't find remote ref add-app-your-app-0.0.1-SNAPSHOT: failed to run 'git fetch https://xxx:xxxx@github.com/xxxx/environment-xxx-dev.git add-app-your-app-0.0.1-SNAPSHOT:xxxxxxx' command in directory '/Users/xxxx/.jx/environments/dev', output: …
```
> fix: can't install an app with version containing letters like *SNAPSHOT*

- pkg/cmd/step/create/pr/step_create_pr.go
- pkg/gits/operations/pull_request_op.go
This PR adds a flag called `--skip-auto-merge` that stops the updatebot label being added to a PR created with `jx step create pr`
fixes: #6157
> chore: Add ability to skip auto merging during `step create pr`

- pkg/cmd/upgrade/upgrade_boot.go
We shouldn't be using a hardcoded `master` here, we should be using `config.DefaultVersionsRef`.
n/a
> fix: jx upgrade boot should use set-in-binary version stream ref as default

- pkg/cmd/boot/boot.go
- pkg/cmd/boot/boot_test.go
Adding a parameter to jx boot that allows you to boot from an existing dev repository
fixes #
> feat: boot - attempt restore from existing dev repository

- pkg/cmd/clients/factory.go
- pkg/kube/services/services.go
- pkg/kube/vault/vault.go
Stop looking up the vault service, it is always available even when the vault ingress is not created.
fixes #
> fix: lookup only the ingress when use ingress is setup

- boot-vault.prow.yaml.template
- myvalues.yaml.tekton.template
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
- pkg/tekton/syntax/pipeline.go
/bin/sh doesn't exist on Kaniko's `executor` or `warmer` images, which is why we've been special-casing them all along. But that ends up creating a number of other problems. There is a `debug-...` image for every `executor` image, with `/busybox/sh`, so let's try using the `debug-...` image with `/busybox/sh -c` as the command when we see `/kaniko/executor` as the step command.
This should also allow environment variables to be used in kaniko step arguments.
fixes #6197
fixes #6058
> fix: Use debug image and /busybox/sh for /kaniko/executor

- .github/pull_request_template.md
- docs/contributing/hacking.md
Signed-off-by: Yuki Nagai <ynagai@r.recruit.co.jp>
fix: update urls for contributor guidelines
Update url in [this page](https://github.com/jenkins-x/jx/blob/master/docs/contributing/hacking.md).
Also, urls in pull_request_template.md are also outdated, so I fixed them.
> fix: update urls for contributor guidelines

- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
- pkg/tekton/syntax/pipeline.go
if the debug image is already specified, don't prepend debug
> fix: only use /busybox/sh for the official kaniko image

- .secrets.baseline
- jx/bdd/boot-vault/ci.sh
- pkg/cmd/clients/factory.go
- pkg/cmd/clients/fake/fake_factory.go
- pkg/cmd/clients/interface.go
- pkg/cmd/clients/mocks/factory.go
- pkg/cmd/create/create_quickstart.go
- pkg/cmd/importcmd/import.go
- pkg/cmd/opts/auth.go
- pkg/cmd/opts/quickstarts.go
- pkg/gits/github.go
Main motivation for this is to support GitHub Apps and also ensure we only ever use users local git auth credentials when creating or importing applications.  We don't want to be using an in cluster git secret.
fixes #6209
> feat: fixes for GitHub Apps and also only use local gitAuth.yaml when importing and creating quickstarts

- pkg/cmd/upgrade/upgrade_boot.go
- pkg/gits/git_cli.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
This was trying to commit the requirements file even when there was no changes, and then failing.
fixes #6213
> fix: only commit requirement upgrade files if changed

- pkg/cmd/step/boot/step_boot_vault.go
- pkg/cmd/step/helm/step_helm_apply.go
Correct use of AWS credentials for vault when creating cloud resources outside of jx
Allow use of system vault in other namespace than jx
fixes #6218
> fix: Correct use of AWS credentials for vault

- pkg/environments/gitops.go
- pkg/gits/helpers.go
- pkg/gits/interface.go
rather than in 2 separate REST APIs so its faster and we avoid possible webhook complications in lighthouse; seems can we sometimes miss the PR open if we label a PR immediately after creating
fixes #6243
> fix: create promote PR with labels

- pkg/cloud/gke/gcloud.go
- pkg/cmd/controller/controller_build.go
Also tweak the debug logging in `gcloud.go`'s `UploadFileToBucket`, because we don't really want to be logging the entire content we're about to save to the bucket (and I wonder if doing that is why I'm not seeing that message show up even with debug logging enabled).
Relates to #6217 and #6246
n/a
> chore: Add more debug logging around log collection in build controller

- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
Changes the logic determining whether to include kaniko secrets on a step to check whether it's running `/kaniko/executor`, not whether it's named `build-container-build`.
fixes #6247
> fix: Add kaniko secrets to all steps running `/kaniko/executor`

- pkg/cmd/deletecmd/delete_branch.go
- pkg/gits/git_cli.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
Adds new `--merge` option to the `jx delete branch` command. Which will
delete all merged branches on a repository.
fixes #2917
> feat: add '--merge' option when deleting branch

- .secrets.baseline
- pkg/cloud/gke/gcloud.go
This change reduces the default TTL of the NS and SOA record, this will allow the zone to check and update its cache more frequently so that new records created automatically are available sooner.
> feat: reduced the default NS and SOA record ttl

- pkg/cmd/upgrade/upgrade_boot.go
- pkg/cmd/upgrade/upgrade_boot_integration_test.go
Better logic and tests for evaluating if we should upgrade to a SHA or tagged release version of the version stream when running `jx upgrade boot`
fixes #6272
> fix: boot upgrade of tagged version stream

- pkg/cmd/step/step_next_version.go
- pkg/cmd/step/step_next_version_integration_test.go
- pkg/cmd/step/test_data/next_version/charts/charts/bar/Chart.yaml
- pkg/cmd/step/test_data/next_version/charts/charts/bar/expected_Chart.yaml
- pkg/cmd/step/test_data/next_version/charts/charts/foo/Chart.yaml
- pkg/cmd/step/test_data/next_version/charts/charts/foo/expected_Chart.yaml
Allow the selection of a specific helm chart in `jx step next-version`
Added a parameter, `charts-dir`, to` jx step next-version` which allows
the user to specify which chart directory should be tagged with the
latest version
When invoked with the tag flag `jx step next-version` delegates 
to `jx step tag` without specifying `charts-dir`, resulting in a default
behaviour which attempts to search for the correct helm chart. In the
case where the repository contains multiple charts this can fail to
select the correct one
Fixes #6025
> feat: allow selection of chart in next-version

- pkg/gits/operations/pull_request_op.go
- pkg/gits/operations/pull_request_op_test.go
Analogous to #6244 - gets us away from the nil pointer issue and cuts down on API calls a bit.
fixes #6210
> fix: Apply labels as part of pull req creation, not just after

- .secrets.baseline
- pkg/cmd/controller/controller_build.go
- pkg/cmd/create/create_addon_prow.go
- pkg/cmd/create/install.go
- pkg/cmd/opts/git.go
- pkg/cmd/upgrade/upgrade_addon_prow.go
- pkg/cmd/upgrade/upgrade_boot.go
`jx upgrade boot` is failing to clone dev env repository when using GitHub apps. This change determines if GitHub App is enabled and configured so that the appropriate token can be used.
If no GitHub App owner is found then the auth flow continues as before.
fixes #6276
> fix: boot upgrade cloning using GitHub apps

- pkg/cmd/create/create_branch_pattern.go
- pkg/cmd/get/get_branchpattern.go
- pkg/cmd/importcmd/import.go
Fixing that documentation has moved on the website making following links in command line help and also reference on website give 404.
> fix: Correct link to import documentation

- pkg/gits/operations/pull_request_op.go
- pkg/gits/operations/pull_request_op_test.go
updatebot label isn't getting added to PR's, seemingly labels need to be added using the GitHub issues API after PR creation https://developer.github.com/v3/pulls/#labels-assignees-and-milestones.
Essentially a revert of #6211 with a nil pointer check on the PR creation before applying labels
> fix: labels need to be added after PR creation

- go.mod
- go.sum
fixes #3436
Signed-off-by: Tony Noble <tony.noble@gmail.com>
The version of go-gitlab only supports version 3 of the GitLab API, which was deprecated in v9 and removed completely in v11 (current is now v12). As a result, anyone with a vaguely up-to-date GitLab installation cannot use jenkins-x. This changes updates the module requirement to a version that supports v4 of the API
fixes #5842
> fix: Update go-gitlab to version 0.12.0 for v4 of the API

- pkg/applications/applications.go
- pkg/applications/applications_test.go
- pkg/cmd/get/get_applications.go
- pkg/kube/sourcerepositories.go
- Application command returns user applications and not K8s deployments
(fixes jenkins-x#6099)
- Extract business logic outside of the get command into its own package
- Passing the --preview flag will return a message telling the user to
use a different command in order to separate concerns (fixes jenkins-x#6271)
> chore: Refactor applications commands

- pkg/github/github_app.go
If a cluster is using github apps to provide auth for the bot user then it would be useful to display the name of the github app during the initial setup phase when creating a quickstart.
> feat: display the github app name during quickstarts

- pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/maven_build_pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/override_block_step/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/per_step_container_build_pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/remove-stage/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/tasks.yml
- pkg/cmd/step/syntax/step_syntax_effective.go
- pkg/cmd/step/syntax/step_syntax_effective_test.go
- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
if we pass in custom env vars when creating an effective pipeline we should override any inherited env vars of the same name from the build pack to avoid creating invalid combined env var definitions in the pods which tekton + k8s cannot instantiate
fixes #6313
> fix: override env vars from build pack if passed in

- go.mod
- go.sum
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/gits/gitlab.go
fix: Remove hard-coding of github as target for duplication in verify_environment step
Signed-off-by: Tony Noble <tony.noble@gmail.com>
Further fixes to allow jx boot to work cleanly with GitLab (on-prem or .com).  
* Updated to use the latest version of the go-gitlab module, as this includes updates for required fields in API calls to latest versions of GitLab.
* When creating environment config repos (or checking for their existence), the GitKind field was hard-coded to GitHub, meaning the wrong client and API was used.  Given that the the GitKind field is available in the jx-requirements config for the repo in use, it makes sense to use that but default to GitHub if not specified
fixes #
This should provide a partial fix for #6158 as well.
> fix: Update go-gitlab to latest version to resolve project creation

- pkg/cmd/step/create/pr/step_create_pr_repositories.go
According to usage information `--version` is optional for `jx step create pullrequest respositories`, but ValidateOptions croaks if it is missing. I don't see that version is needed at all and it should certainly not be mandatory.
> fix: Don't require --version for step create pr repositories

- pkg/tekton/syntax/pipeline.go
fixes #6313 for if we overwrite env vars via the metapipeline client but leave around inherited env vars we create bad Pipeline Tasks
> fix: avoid creating invalid pipelines

- pkg/cmd/opts/cert_manager.go
- pkg/cmd/opts/upgrade/upgrade_ingress.go
Using a newer version of cert-manager was making the `jx upgrade ingress` command to fail due to different APIs being used.
After trying to upgrade the cert-manager dependency version in Jenkins X I found a problem with our dependencies and the inability to add new ones due to very old versions used for k8s dependencies.
As `jx upgrade ingress` is being deprecated soon, we are locking the cert-manager version to `0.9.0` so new versions are only applied to boot clusters.
Part of #5521
> feat: lock cert-manager version for jx install based clusters and block the use of upgrade ingress for boot clusters

- pkg/cmd/upgrade/upgrade_boot.go
- pkg/cmd/upgrade/upgrade_boot_integration_test.go
When the UpgradeVersionStreamRef is set to a branch the upgradeRef was being set to a tagged release, rather than looking up the commit.
This PR removes some of the recently added code which was trying to determine whether we should upgrade to a tagged release or a SHA. 
The `LatestRelease` will now be required to upgrade to the latest tagged release
> fix: upgrades using branch ref

- pkg/cmd/get/get_build_logs.go
- pkg/cmd/step/step_unstash.go
- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
This was a bug we discovered when trying to reuse this code. I copied it and fixed it where I was using it for now but this fixes it here too
fixes #6337
> fix: don’t create default factory in tekton logging code

- pkg/cmd/step/pr/step_pr_comment.go
--code can be used to turn on escaping
fixes #
> chore: allow escaping for code comments on PRs

- pkg/cmd/gc/gc_gke.go
Signed-off-by: David Conde <dconde@cloudbees.com>
Deletes bindings that have deleted members starting with deleted:
> chore: correctly clean down bdd iam bindings with deleted members

- jenkins-x-bdd.yml
- jenkins-x-boot-vault.yml
- jenkins-x-images.yml
- jenkins-x-tekton.yml
Since our builder images are using golang 1.12.4, lets update the docker golang images  within our pipelines to 1.12.4 too
Contributes towards #6345
> chore: update golang image version to 1.12.4

- charts/jx/templates/cronjob.yaml
- charts/jx/templates/daemonset.yaml
- charts/jx/templates/deployment.yaml
- charts/jx/templates/job.yaml
- charts/jx/values.yaml
Adds support for setting podAnnotations in jx chart.
The reason I needed this was that gcactivities stopped working when I enabled istio for the namespace. With the annotation sidecar.istio.io/inject: "false" on the pod it would have worked. But now there is no way to add this annotation via the chart.
> feat: podAnnotations on jx pod

- pkg/users/git.go
- pkg/users/git_test.go
When creating a new name for the new Jenkins X User CRD we need to make sure
the name is a valid Kubernetes resource name.
This is the minimal change necessary to move forward. The current design of the code needs imo to be refactored. See also #6365. This would, however, also require to change the code in the Slack App. To move this forward let's do the minimal amount of work for now.
fixes #5727
> fix: making sure naming.ToValidName is called before creating a new CRD

- pkg/cmd/clients/factory.go
- pkg/cmd/clients/fake/fake_factory.go
- pkg/cmd/clients/interface.go
- pkg/cmd/clients/mocks/factory.go
- pkg/cmd/gc/gc_activities.go
- pkg/cmd/gc/gc_activities_test.go
- pkg/cmd/opts/common.go
We're already GCing `PipelineActivity` and `PipelineRun` directly,
which also results in the downstream CRDs
`Pipeline`/`Task`/`TaskRun`/`PipelineStructure` all getting GCed too,
but until now, we're not doing anything about `ProwJob`s, so they can
get out of control and cause performance and OOM issues on the various
Prow pods. So let's GC `ProwJob`s too.
The default is to keep a week of `ProwJob`s - even on prod, I haven't
seen issues caused by excesses of `ProwJob`s until it's been at least
two weeks of regular rates of creation, so a week seems fine.
fixes #6094
> fix: GC ProwJobs in gc_activities

- pkg/cmd/create/create_docs.go
- pkg/cmd/deprecation/deprecated.go
The `create docs` command will generate a file with all the deprecated commands in the `commands folder`. The file content looks like this:
```
---
date: 2020-01-02T15:22:41+01:00
title: "deprecated commands"
slug: deprecation
url: /commands/deprecation/
---
| Command        | Removal Date   | Replacement  |
|----------------|----------------|--------------|
| jx console | Mar 1 2020 | jx ui |
| jx controller workflow | Feb 1 2020 |  |
| jx create addon knative-build | Feb 1 2020 |  |
| jx create archetype | Feb 1 2020 | jx create quickstart |
| jx create camel | Feb 1 2020 | jx create quickstart |
| jx create cluster aws | Feb 1 2020 |  |
| jx create cluster minikube | Feb 1 2020 | minikube start |
| jx create cluster minishift | Feb 1 2020 |  |
| jx create cluster oke | Feb 1 2020 |  | …
```
> feat: extend the create docs command to generate a docs page for all deprecated commands

- pkg/cmd/opts/install.go
Not only is there now Helm3 (which isn't yet supported by jx) but the binary download locations have changed as per https://helm.sh/blog/get-helm-sh/#where-are-we-now.  
Included Tiller URL as well for consistency
https://github.com/jenkins-x/jx/issues/6110
> feat: Updated Helm install URLs

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_test.go
Prow is case-sensitive when it comes to matching events for an org/repo name combo to a configured org/repo name combo in its configuration. So if you're using an org with upper-case letters in its name as things stand before this change (let's say `SomeOrg`), your Prow config will end up having `someorg/environment-whatever-staging`, but the hooks sent from GitHub will be for `SomeOrg/environment-whatever-staging`, and Prow will not find any actions to take based on the `SomeOrg` event.
Depends on https://github.com/jenkins-x-charts/jxboot-resources/pull/22 being merged to really work right.
fixes #5914
> fix: Stop lowercasing environmentGitOwner value

- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/syntax/step_syntax_effective.go
- pkg/cmd/step/syntax/step_syntax_effective_test.go
- pkg/jenkinsfile/pipeline.go
- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/pipeline_test.go
- pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
- pkg/tekton/syntax/test_data/validation_failures/top_level_missing_volume/jenkins-x.yml
- pkg/tekton/syntax/test_data/validation_failures/volume_does_not_exist/jenkins-x.yml
- pkg/tekton/syntax/test_data/volumes/jenkins-x.yml
Validate that each `volumeMount` in a `containerOptions` has a corresponding `volume` in the `containerOptions` context (or in a parent context).
Validate that each `secret` or `persistentVolumeClaim` `volume` in the `options` for a pipeline or a stage actually exists, when actually generating the effective pipeline during `jx step create task`.
fixes #6424
fixes #6426
> fix: Validate that container option volume mounts use defined, existing volumes

- pkg/cmd/create/create_cluster_gke.go
fixes #6428
Adds support for `jx create cluster gke --service-account mysa`
Signed-off-by: David Conde <dconde@cloudbees.com>
> feat: Support passing a service account to jx create cluster gke

- pkg/cmd/deprecation/deprecated.go
The `jx edit deploy` command does not seem to be a maintenance burden while, at the same time, it is a useful way to define the deployment model (e.g., default, knative). Also, that command could be useful as we add more deployment processes (e.g., canary), even though it might need to be extended with a few additional arguments.
This PR proposes the removal of `jx edit deploy` from the list of deprecated commands.
fixes #
> fix: removed edit deploy from the list of deprecated commands

- pkg/cmd/add/add_app_test.go
- pkg/cmd/preview/preview.go
- pkg/cmd/promote/promote.go
- pkg/cmd/promote/promote_test.go
- pkg/cmd/step/helm/step_helm.go
- pkg/cmd/step/helm/step_helm_apply.go
- pkg/cmd/step/helm/step_helm_install.go
- pkg/environments/gitops.go
- pkg/helm/helm_cli.go
- pkg/helm/helm_cli_test.go
- pkg/helm/helm_helpers.go
- pkg/helm/helm_template.go
- pkg/helm/interface.go
- pkg/helm/mocks/helmer.go
This PR passes useful tags and global chart variables to helm when deploying an application.
Prior to this PR, the only way to check in which environment a chart was deployed was to read `.Release.Namespace`. It was impossible to use such conditions in chart requirements, and preview environment were hard to detect.
Tags can be used to condition chart requirements.
Global variables can be used in chart templates.
`jx promote` and `jx preview` now pass the following variables to helm:
- `tags.jx-ns-<namespace>=true` (ex: `tags.jx-ns-jx-production=true`)
- `tags.jx-<env-type>=true` (ex: `tags.jx-preview=true`)
- `tags.jx-env-<env>=true` (ex: `tags.jx-env-production=true`)
- `global.jx-ns-<namespace>=true` (ex: `tags.jx-ns-jx-production=true`)
- `global.jx-<env-type>=true` (ex: …
> feat: pass tags and global chart variables when deploying an application

- .secrets.baseline
- pkg/cmd/opts/auth.go
- pkg/cmd/opts/git.go
- pkg/cmd/step/git/step_git_credentials.go
When creating the git provider for git server url (in this case: github) it seems that it was only using the github owner to determine if in github app mode or not. We should ideally use the common options `isGitHubAppMode` function to correctly determine whether GitHubApps mode is enabled or not.
> fix: use common options github app mode check as well as the github owner for gitprovider

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_test.go
- pkg/config/install_requirements.go
- pkg/config/zz_generated.deepcopy.go
Prompt for dev env repo approvers during `jx step verify preinstall`, if not specified in `jx-requirements.yml` and not run non-interactively, and write the list of provided users to the `OWNERS` file in the dev env repo.
I did a hacked BDD test here to specify approvers in the `jx-requirements.yml` and it worked, but I'm removing that for obvious reasons. =)
fixes #6457
> fix: Optionally write OWNERS file for dev env repo during boot

- pkg/config/install_requirements.go
Removing omitempty from the tags of these velero config items so that a default can be specified in the template without occurring an error.
> chore: remove velero config omitempty tags

- pkg/cmd/create/create_devpod.go
- pkg/cmd/step/git/step_git_credentials.go
- pkg/cmd/step/verify/step_verify_behavior.go
- pkg/tekton/metapipeline/client.go
- pkg/tekton/metapipeline/clientfactory.go
- pkg/tekton/metapipeline/metapipeline.go
This is to attempt to fix https://github.com/cloudbees/arcalos/issues/567, in this configuration we run the bdd tests from inside the cluster, but the user that the tests should run as is a local user (configured via a secret) rather than the pipeline user (the default)
> feat: add the option to run the bdd tests directly without importing

- pkg/apps/gitops.go
- pkg/apps/install.go
- pkg/cmd/add/add_app.go
- pkg/cmd/add/add_app_test.go
- pkg/cmd/deletecmd/delete_app.go
- pkg/cmd/deletecmd/delete_app_test.go
- pkg/cmd/deletecmd/delete_application.go
- pkg/cmd/get/get_apps.go
- pkg/cmd/promote/promote.go
- pkg/cmd/step/scheduler/step_scheduler_config_apply.go
- pkg/cmd/step/scheduler/step_scheduler_config_apply_test.go
- pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
- pkg/cmd/step/scheduler/step_scheduler_config_migrate_test.go
- pkg/cmd/testhelpers/app_test_helpers.go
- pkg/cmd/upgrade/upgrade_addon_prow.go
- pkg/cmd/upgrade/upgrade_apps.go
- pkg/cmd/upgrade/upgrade_apps_test.go
- pkg/environments/gitops.go
- pkg/pipelinescheduler/generator.go
Until this, `jx delete app`, `jx add app`, and `jx get apps` all did weird things with/under `~/.jx/environments`. All of them used `ForkAndPullRepo` to clone under there - `jx get apps` directly into `~/.jx/environments`, and `jx add app` and `jx delete app` into `~/.jx/environments/dev`. Literally none of this made sense. =)
This reworks not just the app commands, but all commands that create PRs (i.e., gitops) against the dev/prod/staging environments to use temporary directories for the fork/clone/push, with the option, just used in tests, of specifying an existing directory to use instead, while `jx get apps` just clones to a temporary directory as well.
Switching all this to temporary directories also really helps users who manage/work with multiple JX clusters from a single …
> fix: Cloning for environments shouldn't leave strange state in JX_HOME

- pkg/cmd/step/verify/step_verify_preinstall.go
Change messaging displayed when running `jx boot` to include `EKS` as Kubernetes provider.
fixes #6361
> fix(boot message): Add EKS as supported kubernetes provider

- pkg/cmd/boot/boot.go
First impressions count - and with boot the first thing people see is a big ugly warning with an error, when really it is just falling back to defaults. 
@rawlingsj may override this with a rethink of the UX of the CLI  which is fine, but I thought this was a simple thing. 
fixes #6483
> fix: #6483 - boot should not show warning as first impression

- pkg/cloud/gke/vault/vault_backend.go
- pkg/cmd/boot/boot.go
- pkg/cmd/create/install.go
- pkg/cmd/deletecmd/delete_application.go
- pkg/cmd/deletecmd/delete_devpod.go
- pkg/cmd/deletecmd/delete_extension.go
- pkg/cmd/deletecmd/delete_preview.go
- pkg/cmd/edit/edit.go
- pkg/cmd/edit/edit_addon.go
- pkg/cmd/opts/cert_manager.go
- pkg/cmd/opts/domain.go
- pkg/cmd/opts/install.go
- pkg/cmd/opts/upgrade/upgrade_ingress.go
- pkg/cmd/step/report/step_report_image_version.go
- pkg/cmd/step/verify/step_verify_packages.go
- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/stop/stop_pipeline.go
- pkg/cmd/uninstall/uninstall.go
- pkg/cmd/upgrade/upgrade_addon_prow.go
- pkg/cmd/version.go
- pkg/github/github_app.go
- pkg/gits/features/disable_features.go
- pkg/kube/env.go
- pkg/util/pickers.go
Prior to this commit, while a confirmation was required, `ctrl+c` would confirm the default value instead of stopping the program.
This could have the unintended purpose of confirming that a pipeline should be stopped instead of cancelling the operation.
On issue #5627 the answer was that it wasn't due to `jx` but the the library it's using. But `jx` ignores the error from the library: https://github.com/jenkins-x/jx/blob/master/pkg/util/pickers.go#L170
fixes #5627, fixes #3291
> fix: handle correctly ctrl+c on confirmation

- boot-vault.platform.yaml.template
- jenkins-x-boot-lh-ghe.yml
- jx/bdd/boot-lh-ghe/README.md
- jx/bdd/boot-lh-ghe/ci.sh
- jx/bdd/boot-lh-ghe/cluster.yaml
- jx/bdd/boot-lh-ghe/jx-requirements.yml
- jx/bdd/boot-lh-ghe/parameters.yaml
- pkg/cmd/opts/quickstarts.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/config/install_requirements.go
- pkg/gits/github.go
- pkg/gits/helpers.go
- pkg/gits/helpers_test.go
- pkg/kube/quickstarts.go
There are a few places where we use an authenticated `GitProvider` to perform API calls against github.com repos or orgs we know are public - `DuplicateGitRepoFromCommitish` for cloning/squashing `jenkins-x-boot-config`, and `jx get quickstarts` getting the default quickstarts from the `jenkins-x-quickstarts` org currently. If a boot cluster with gitops enabled is not using github.com and is instead using GitHub Enterprise, Gitlab, etc, these calls end up failing due to trying to use an authenticated provider when there are no credentials available. In these cases, we should fall back to anonymous authentication for the API calls.
As a followup, once this has merged, released, and gotten into the version stream, I'm going to be updating the Lighthouse and `jenkins-x-versions` BDD tests …
> fix: Use anonymous github.com creds for API calls on certain repos when there are no github.com credentials available

- pkg/cmd/stop/stop_pipeline.go
Prior to this commit, `jx stop pipeline` would often have error:
> failed to cancel pipeline ...: the object has been modified; please apply your changes to the latest version and try again
It would happen a handful of time when trying to stop a starting pipeline. Worse, the longer the user took to choose, the more likely it was, forcing the user to choose fast, and potentially making errors.
This was due to the pipeline object not being refreshed after the user took some time choosing which pipeline to stop.
Another one from my "Grrr" list ...
> fix: prevent `jx stop pipeline` from having "failed to cancel pipeline" error

- pkg/cmd/create/create_devpod.go
- pkg/cmd/deletecmd/delete_devpod.go
- pkg/cmd/get/get_devpod.go
- pkg/kube/services/services.go
This contains the following changes:
- Make the `auto-expose` flag to behave consistently and set it by default to false. This results in not exposing any DevPod port by default.
- Check whether or not the TLS is enabled when the `auto-expose` flag is active, and ask for user confirmation in case it is disable in order to proceed with an insecure setup.
- Configure the basic authentication when the services are exposed.
- Configure the expose-controller to only recreate the ingress resources of the service created by the DevPod, before it was recreating all ingress resources from `jx` namespace. This will prevent that the other ingress resources are accidentally recreated.
- Augment the error messages with more context and also handle some errors which previously were ignored.
fixes #6475
> fix: secure the endpoints exposed by the DevPod

- jenkins-x.yml
Release build tests are failing with 
```
=== Failed
=== FAIL: pkg/cmd/importcmd TestImportProjectNextGenPipelineWithDeploy (3.20s)
=== PAUSE TestImportProjectNextGenPipelineWithDeploy
=== CONT  TestImportProjectNextGenPipelineWithDeploy
import_deploy_integration_test.go:195: 
Error Trace:	import_deploy_integration_test.go:195
import_deploy_integration_test.go:177
import_deploy_integration_test.go:60
import_deploy_integration_test.go:125
Error:      	Received unexpected error:
Failed to update maven deploy plugin: Command failed 'mvn io.jenkins.updatebot:updatebot-maven-plugin:RELEASE:plugin -Dartifact=maven-deploy-plugin -Dversion=2.8.2': Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC …
```
> fix: Use builder-go-maven for make release due to new tests needing maven/java

- jenkins-x-integration.yml
- jenkins-x.yml
- pkg/cmd/step/step_wait_for_artifact.go
- pkg/maven/cli.go
To make sure that we don't end up with tests passing in the integration context that fail in the release context due to image differences.
Followup to #6530
n/a
> fix: Use same image in integration test as make release

- pkg/cmd/opts/quickstarts.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/gits/helpers.go
- pkg/gits/helpers_test.go
As described in #6539, I forgot just how stingy the anonymous GitHub API rate limit is. So let's refactor both the `jx step verify environments` logic for getting the required info about the upstream `jenkins-x-boot-config` and `LoadQuickStartsModel`'s logic for loading quickstart information work to not use anonymous GitHub API calls after all. The required information should be available in both cases without needing to make those API calls, thanks to `https://github.com/jenkins-x/jenkins-x-boot-config.git` actually having everything that's needed in its own URL, and the default quickstarts being in the version stream.
Starting out on WIP to make sure the non-required `boot-lh-ghe` test...well, doesn't pass, since it'll run into https://github.com/jenkins-x/lighthouse/issues/462, but at …
> fix: Don't use anonymous GitHub API for dev env repo creation and get quickstarts

- pkg/gits/bitbucket_cloud.go
so that we can get further in the support of bitbucket cloud
see: https://kubernetes.slack.com/archives/C9LTHT2BB/p1579116333135100?thread_ts=1577810088.032800&cid=C9LTHT2BB
> fix: avoid returning errors for unimplemented capabilities on bitbucket cloud

- pkg/cmd/create/create_spring.go
Currently defaulting to 2.2.3.BUILD.SNAPSHOT (possibly an initializer project problem)
fixes #
> chore: default spring version to 2.2.3 in `jx create spring`

- pkg/cmd/step/verify/step_verify_environments.go
The specific issue prompting this was a GHE user with a custom boot config upstream forked in github.com. That slipped through, since we were specifically looking for cases where the destination wasn't github.com and the origin was the default boot config repository, but when I think about it more, it makes more sense to just fall back to the simpler non-provider-driven approach to the origin for all cases where the git host for the origin and destination repository URLs differ.
fixes #6551
> fix: Fall back to not using provider for dev env creation in more cases

- pkg/cmd/testhelpers/cmd_test_helpers.go
fix: cmd_test_helpers - CreateTestJxHomeDir() returns empty string if gitAuth.yaml is not present.
fixes #6577
> fix: cmd_test_helpers - CreateTestJxHomeDir()

- pkg/cmd/create/install.go
- pkg/cmd/opts/git.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_environments_test.go
- pkg/cmd/step/verify/test_data/verify_environments/default/jx-requirements.yml
- pkg/cmd/step/verify/test_data/verify_environments/ghe/jx-requirements.yml
`opts.AddGitRepoOptionsArguments` defaults `--git-provider-url` to `https://github.com`, no matter what the actual default should be for the cluster. This makes sense for some of the cases where it's used (i.e., `jx install`, `jx create cluster`, `jx create terraform`, etc), but not for others (`jx import` (and therefore `jx create quickstart`), `jx edit env`, and `jx create env`). In those cases, we should default it to the `gitServer` in the team settings.
Except we don't actually set that with `jx boot`! It just stays on `https://github.com`. So we also need to set that from the requirements.
fixes #6579
> fix: Use requirements gitServer as default for import, create env

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/config/install_requirements.go
* lets write the helmfile configuration file when modifying requirements
* lets default the environment repository names so that they are definitely
populated before trying to install the environment charts
(jxboot-requirements stuff) to make life easier for the helm configuration
injection
> fix: fixes for helmfile feature

- pkg/cmd/start/start_pipeline.go
- pkg/kube/sourcerepositories.go
- pkg/kube/sourcerepositories_test.go
If you add a `SourceRepository` to your dev env repo by hand, you can specify an arbitrary name, but then when the pipeline for that repository runs, it will try to look for the repo's `SourceRepository` based on its "standard" naming scheme of `organization-repo`. When it doesn't find a `SourceRepository` with that name, it will create a new one instead with that name, resulting in duplicate `SourceRepository`s for that provider/org/repo combination.
So let's first try to look up by name, and then by labels.
fixes #6545
> fix: Look up SourceRepositorys by labels, not just name.

- pkg/cmd/step/scheduler/step_scheduler_config_apply.go
also add extra validation check to ensure team settings are created
> fix: lets always use the dev namespace for applying schedules

- pkg/cmd/clients/factory.go
- pkg/cmd/clients/fake/fake_factory.go
- pkg/cmd/clients/interface.go
- pkg/cmd/clients/mocks/factory.go
- pkg/cmd/get/get.go
- pkg/cmd/get/get_crd_counts.go
- pkg/cmd/get/get_crd_counts_test.go
There are lots of custom resources that can be created by various applications and it can be hard to keep a handle of how many exist.  This can lead to them growing over time if not managed.  This command allows users to get the counts for each custom resource given their permissions.
Example:
```
➜  ~ jx get crd count
looking for cluster wide custom resource counts and namespaced custom resources in these namespaces:
cert-manager
default
jx
jx-production
jx-staging
kube-node-lease
kube-public
kube-system
this operation may take a while depending on how many custom resources exist
NAME                                         VERSION  COUNT NAMESPACE
apps.jenkins.io                              v1       0     cert-manager
apps.jenkins.io                              v1       0     default …
```
> feat: add a command to get the custom resource counts in a cluster

- pkg/cmd/opts/git.go
- pkg/kube/git_services.go
- pkg/kube/git_services_test.go
- pkg/kube/test_data/git_service_kind/configmap_vault_auth.yaml
We're looking for this in a simple set of patterns, secrets, and `GitServices`, but once the `jx-auth-config` configmap is present (i.e., via a combination of boot/vault/gitops), we won't be able to find the kind for something that doesn't match one of the patterns we check first, since the `jx-pipeline-git-` secrets won't exist any more. So if we're in a cluster with `jx-auth-config`, let's look up there too, before we check secrets or `GitServices`.
fixes #6589
> fix: Lookup git service URL kind from jx-auth-config as well

- pkg/cmd/boot/boot.go
if you are developing boot and working on a local set of changes for a boot config repo you don't want `jx boot` to suddenly change your `~/.git/config` and try auto-merge stuff and generally mess everything up.
So lets add a `-no-upgrade-git` to avoid boot deciding that your local clone is behind and messing up your local source code
> fix: add a CLI argument to disable boot messing with the local git clone

- pkg/vault/create/create.go
Signed-off-by: Rafal Korepta <rafal.korepta@gmail.com>
Issue #6555 shows that cloud provider AWS panic when a user wants to create a vault.
This PR remove panic from the jx program flow and handle gracefully the not valid parameters. The main issue isn't resolved yet.
fixes #
> fix: validate AWS parameters to prevent panics

- hack/jxDebug.sh
- pkg/cmd/step/git/credentials/step_git_credentials.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/gits/credentialhelper/git_credential.go
- pkg/gits/credentialhelper/git_credentialhelper.go
- pkg/gits/credentialhelper/git_credentialhelper_test.go
- pkg/gits/git_cli.go
- pkg/gits/git_cli_test.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/helpers.go
- pkg/gits/helpers_test.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
- pkg/gits/provider_fake.go
The key feature of this pull request is to make `jx` a git credential helper which allows for using our Kube based authentication for retrieving git push/pull/fetch credentials. This is a replacement for adding the password to the remote URL directly or the workaround of generating an authenticated git URL on the fly (which as side effect does not update the remote refs).
Some other changes deal with the fact to allow consecutive execution of `jx boot`, however, this is a temporary solution and does not address the core issues with `jx boot`.  
Note: Now it is possible to have multiple consecutive boot executions and regular commits made on master will be cherry-picked on local `jx boot` execution. This does not change the fact that we should not be using cherry-picking in the first place …
> feat: Handling git credentials via credential helper

- pkg/cmd/upgrade/upgrade_boot.go
- pkg/gits/git_cli.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
Realized this was an issue while thinking about #6465 - we don't commit changes to `OWNERS` from upstream when running `jx upgrade boot`, but we still will hit merge conflicts when cherry-picking if `OWNERS` has changed in both the dev env repo and upstream, so let's use a custom merge driver to ensure that all conflicts for `OWNERS` are automatically resolved in favor of the existing version in the dev env repo, as described in https://stackoverflow.com/a/930495
I still need to write a unit test for this.
fixes #6543
> fix: Resolve OWNERS merge conflicts in boot upgrade with existing version

- pkg/cmd/deprecation/deprecated.go
- [X ] Change is code complete and matches issue description.
Based on community feedback, `jx install` will remain a bit longer but without any further enhancements or fixes.  `jx create spring` functionality to remain but accessed via `create project`.
https://github.com/jenkins-x/jx/issues/6439
> feat: jx create spring accessed via create project.  Install deprecation date change.

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/config/install_requirements.go
- pkg/config/install_requirements_test.go
- pkg/features/features.go
lets switch from using an environment variable to enable the experimental helmfile mode to using an optional boolean on the requirements file as its hard to enforce environment variables being consistently set across pipelines/shells/CLI invocations/steps.
The new flag is only marshalled to YAML if its set to true so has no backwards compatibility issues. Its also clearly marked as experimental in the generated reference docs
See: #6442
> fix: switched from env var to requirements flag

- pkg/boot/constants.go
- pkg/cmd/boot/boot.go
- pkg/cmd/opts/team_settings.go
- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_preinstall.go
when testing out a possible PR on the git boot repository referenced in the `jx-requirements.yml` even using `--no-update-git` I was finding that boot would:
* lookup my local fork of the git repository and since its not in the version stream assume 'master' was the branch I wanted (despite being in a fork/branch already
* re-apply all changes from master to my local checkout causing merge hell
* then `jx step verify env` tries to push to master the local changes merged with upstream causing merge conflicts etc.
This PR fixes this by disabling the bit of `jx boot` which switches from the current gitRef -> `master` if the `--no-update-git` is provided. That flag also passes in an env var so that `jx step verify env` doesn't try to push local changes to master of the dev repo (which is only …
> fix: allow `jx boot --no-update-git` to not mess with git

- pkg/cmd/step/verify/step_verify_behavior.go
> chore: add a flag to enable the goproxy when running in cluster

- pkg/cmd/controller/controller_build.go
- pkg/logs/tekton_logging.go
- pkg/tekton/pipelines.go
- pkg/tekton/pipelines_test.go
If Lighthouse has rerun a `PipelineRun` due to our buddy the Tekton race condition, the new `PipelineRun` has a different name than the original. This means that there's no `PipelineStructure` with the same name, so logging and the build controller don't know what to do with it. So when we're looking up `PipelineStructure`s for a `PipelineRun`, first try to look by the `PipelineRun` name, and then by the `Pipeline` name associated with the `PipelineRun`. The `Pipeline` name will always be the same for the rerun `PipelineRun` as it was for the original, so this will work.
fixes #6646
> fix: Get structure for rerun PipelineRun properly

- pkg/tekton/metapipeline/metapipeline.go
We need to be mounting the `jenkins-maven-settings` secret into the metapipeline pod to deal with updating versions in POMs with parents only available from private repositories.
fixes #6637
> fix: Mount Maven settings.xml secret into metapipeline pod

- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/packs/maven-with-overridden-env-var/pipeline.yaml
- pkg/jenkinsfile/pipeline.go
I missed this and feel silly - if you declare `env` variables at the top level of a build pack, they won't get inherited properly either by build packs that extend it or by pipelines that use it. So when we extend build packs/pipelines, combine the `env` field as well as agent, directory, and container options from the top level.
fixes #6668
> fix: Inherit build pack environment into pipelines

- cmd/codegen/app/generate_openapi.go
https://github.com/googleapis/gnostic/commit/896953e6749863beec38e27029c804e88c3144b8 broke at least `k8s.io/apimachinery`'s dependency on `github.com/googleapis/gnostic/OpenAPIv2`, so we need to fetch at least `k8s.io/apimachinery` as modules to get it to pick up the right version of `github.com/googleapis/gnostic`, and just to be safe, I did the same for `k8s.io/api` as well.
I am not...happy with this, but it seems to work and doesn't seem to have side effects that I can see.
fixes #6679
> fix: Fetch k8s.io openapi dependencies as modules

- pkg/gits/git_url.go
- pkg/gits/git_url_test.go
The source URL can sometimes look like this in Jenkins:
/projects/ORG/repos/NAME/pull-requests/1/overview
The /overview causes the git URL parser to think that the project name is "overview" instead of "NAME".
Fixes #6419
> fix(git): parsing of Bitbucket Server URLs

- pkg/cmd/diagnose.go
This PR adds the option to show the list of configmaps as part of `jx diagnose` and `jx diagnose --show configmaps`
fixes #6415
> feat(cli): show ConfigMaps on jx diagnose output

- pkg/cmd/preview/preview.go
- pkg/cmd/promote/promote.go
- pkg/cmd/step/step_tag.go
- pkg/cmd/step/step_tag_test.go
- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
- pkg/logs/test_data/invalid_name/activity.yml
- pkg/logs/test_data/invalid_name/pipelineruns.yml
Prior to this commit, the following problems where happening when a repository had a name not made of [a-z-] characters
- `jx step tag` would write the wrong docker image name (`strings.ToLower` was used (via `ToValidImageName`) instead of `naming.ToValidName`)
- `jx get build logs` would fail to list the running pipelines. This is a weird error, due to the fact that the labels of the `PipelineRun` and the `PipelineActivity` are not formatted the same way.
- `jx preview` and `jx promote` would fail to recognize the service (no formatting was performed)
Hopefully, non conventional repo names should work fine now.
> fix: various problem due to non-conventional github repository name

- pkg/applications/applications.go
Complemetary to #6550
Fixes another problem for repository repositories with other characters than `[a-z-]`.
The application name was directly retrieved from the repository name and not formatted, thus it couldn't be displayed in `jx get applications`.
> fix: non-conventional github repository names don't appear in `jx get applications`

- pkg/cmd/opts/git.go
- pkg/cmd/upgrade/upgrade_boot.go
- pkg/cmd/upgrade/upgrade_boot_test.go
`jx upgrade boot` in non-dev namespace results in a panic, this is due to the lack of error handling in the upgrade boot functionality. This PR adds the necessary checks, and some tests to validate it.
fixes #6529
> fix(cli): handle errors when doing a jx upgrade boot in non dev namespace

- pkg/cmd/get/get_build_logs.go
jx get build log invokes the GetEnrichedDevEnvironment function which creates a dev environment. Instead it to use GetDevEnvironment which does not have this sideeffect. Creating a dev environment in any namespace will lead to unexpected results (for instance creating dev env in certmanager/kubesystem ns), and seems unnecessary
This PR fixes the side-effect of creating a dev environment in any namespace when executing `jx get build log`
fixes #6482
> fix(cli): avoid creating dev environment in arbitrary namespace

- pkg/cmd/opts/helm_test.go
- pkg/cmd/opts/test_data/lint/Chart.yaml
- pkg/cmd/opts/test_data/lint/templates/test.yaml
- pkg/helm/helm_cli.go
- pkg/helm/helm_cli_test.go
Complementary to #6427 and #6682 all calls to `helm lint` (including `jx step helm release`) also pass some variables
- `tags.jx-lint=true`
- `global.jxLint=true`
- `global.jxTypeEnv=lint`
This avoids having `helm lint` errors when the templates are looking for variables like `.Values.global.jxPreview` due to `global` being `nil`
> feat: `helm lint` calls pass variables too

- pkg/gits/git_url.go
Internal function UrlWithoutUser fails with urls that start with "@git"
fixes #6767
> fix: UrlWithoutUser return correct URL when using ssh URL starting with git@

- pkg/gits/bitbucket_cloud.go
PRs used fail when using organisation since it wasn't populated from bitbucketCloud API answer
fixes #6688
> fix: fill organisation and other fields for bitbucketcloud

- pkg/prow/prow.go
- pkg/prow/prow_test.go
the `master` branch should be set as `^master$` in prow's postsubmit job, to avoid matching every branch with "master" in it.
this avoids triggering the release branch on non-master branches.
I haven't check if there is the same issue with lighthouse
fixes #6710
> fix(prow): postsubmit jobs branches should be regexp

- pkg/cmd/controller/controller_build.go
- pkg/cmd/controller/controller_build_test.go
This isn't the end state - #6793 needs to be dealt with. But this will allow for making changes in `env/jenkins-x-platform/values.tmpl.yaml` to specify a `--job-url-base=https://whatever.whatever` and then that'll be used with a default template for creating the logs URL. Also, we'll actually use the logs URL now. And the "pending" message will now tell you what stage(s) are currently running because I wanted more information there. =)
fixes #6791
fixes #6792
fixes #6794
> fix: LH reporting: fix target URL, specify UI URL, better running description

- pkg/kube/version.go
lets patch the code so that we can still detect the actual app name if we use the app name as the helm release name (and don't use a namespace prefix on the release).
this helps the code work with helm 2 and helm 3
> fix: jx get applications when helm release == app name

- pkg/cmd/step/helm/step_helm_apply.go
This will definitely pass the test contexts, but that's in part because of #6811. However, I verified that the fix actually, y'know, fixes things in #6813.
fixes #6812
> fix: jx step helm apply should always use default reqs for non-boot

- jx/bdd/boot-lh-ghe/ci.sh
- pkg/cmd/controller/controller_build.go
Otherwise you get an error because the target URL has to be an http/https URL. Sigh. So if the resulting target URL from the template doesn't start with `http://` or `https://`, don't pass a target URL at all.
And yes, this all really needs to be redone. Still in the land of tactical fixes here. I just wanna unblock the version stream right now. =)
n/a
> fix: Don't pass target URL to GH status if not an http/https URL

- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/pipeline.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/pipelineresources.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/pipelinerun.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/structure.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
- pkg/tekton/syntax/pipeline.go
Prior to this commit, we'd use the kubernetes compliant crd name to create the docker registry destination. But then later on in our code, we'd use the Git repository name to look up the docker registry image and it would fail in some cases. 
For example if the Git repo name contained `.`, the kubernetes compliant crd would replace all the dots with hyphens. So if we a customer had a repo called `example.company.repo` would be converted to `example-company-repo`. but then we'd use the wrong name to do the look up.
fixes #5322
> fix: Use kube crd name to look up the docker registry image

- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/create/step_create_task_test.go
> fix: skip the version tagging in the create task when the noReleasePrepare flag is configured in the project

- pkg/cmd/alpha/alpha.go
- pkg/cmd/cmd.go
- pkg/extensions/plugins.go
so folks can try out the new helm 3 / helmfile work from the `jx` command line via a separate binary
see the enhancement process: https://github.com/jenkins-x/enhancements/pull/15
also https://github.com/jenkins-x/enhancements/tree/master/proposals/2
> fix: add a `jx alpha boot` command

- pkg/cmd/controller/controller_build.go
- pkg/cmd/controller/test_data/controller_build/completed_generated/expected/activity.yml
- pkg/cmd/controller/test_data/controller_build/completed_metapipeline/expected/activity.yml
- pkg/cmd/controller/test_data/controller_build/failed_metapipeline/expected/activity.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/expected/activity.yml
- pkg/cmd/controller/test_data/controller_build/running_generated/expected/activity.yml
- pkg/tekton/pipeline_info.go
- pkg/tekton/test_data/pipeline_info/pr-yaml/pods.yml
First, make sure we set it even if we're not doing status reporting, because that's just cleaner.
But more importantly, the preexisting logic would only set the `BaseSHA` on the run info (and from there the activity) if the last commit SHA wasn't already set by the presence of 
`PULL_PULL_REF` or `PULL_BASE_REF` environment variables. Which...are actually present
now in Lighthouse, via https://github.com/jenkins-x/lighthouse/issues/542. So let's handle that correctly, and consistently with when we're on Prow.
fixes https://github.com/jenkins-x/lighthouse/issues/547
> fix: Properly set BaseSHA on activities

- pkg/helm/helm_cli.go
if we have configured helm 3 on the helmer then lets use that version to validate helm, rather than barfing that helm 2 is required
> fix: better validation of helm

- pkg/cmd/alpha/alpha.go
- pkg/cmd/cmd.go
this can happen if github is having issues or there are firewall problems accessing github
this avoids failing on all jx commands which is pretty fatal
> fix: lets just log a warning if the alpha commands can't be found

- pkg/cmd/step/create/step_create_values.go
I did not refactor the code because I think it should be another PR. I can write tests once I have refactored it. For instance:
```
type AzureRunner struct {
Runner util.Commander
}
```
can be made an empty struct and we can just use the snippet below to make the codebase a bit more consistent:
```
cmd := util.Command{
Name: "az",
Args: args,
}
output, err := cmd.RunWithoutRetry()
```
The code can be decoupled from external dependencies to make it more testable. 
/cc @hferentschik 
fixes #6394
> fix(aks): check for missing azure config when registry is empty

- pkg/cmd/step/create/pr/step_create_pr.go
- pkg/gits/helpers.go
- pkg/gits/operations/pull_request_op.go
- pkg/gits/operations/pull_request_op_test.go
- pkg/gits/provider_fake.go
Allows additional labels to be added to PR's when using `jx step create pr`.
The purpose of this functionality is to avoid unrelated `bump` PRs to be combined in to one PR, which can potential cause a failure in one change blocking the progress of another unrelated change.
fixes #
> feat: allow extra labels to be added to generated PRs

- pkg/secreturl/fakevault/client.go
- pkg/secreturl/helpers_test.go
- pkg/secreturl/localvault/client.go
- pkg/vault/fake/client.go
- pkg/vault/vault_client.go
If a cluster name has dots in it (EG: `test.kops.k8s.local`) then `jx boot` fails to convert secrets:
```
failed to convert secret URLs in parameters file /path/jx-boot/environment-test.kops.k8s.local-dev/env/parameters.yaml: replacing vault paths in
adminUser:
password: local:test.kops.k8s.local/adminUser:password
username: admin
enableDocker: false
pipelineUser:
email: jx-bot-test@example.com
token: local:test.kops.k8s.local/pipelineUser:token
username: test-user
prow:
hmacToken: local:test.kops.k8s.local/prow:hmacToken
: cannot parse "test" as path:key
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create values --name parameters' command in directory 'env', output: ''
``` 
None
fixes #5848
> fix(secreturl): Cluster names can have dots in them

- pkg/cmd/gc/gc_gke.go
so that we can properly GC more service accounts in the BDD tests
> fix: add more service account suffixes

- pkg/cmd/create/install.go
- pkg/kube/naming/names.go
- pkg/kube/naming/names_valid_test.go
when a gke cluster name length is 3 characters or less, fixes failed service account creation during jx/jxl boot create
```
Validating Kaniko secret in namespace jx
attempting to lazily create the deploy namespace jx
Configuring Kaniko service account cd-ko for project devtools-2341
Unable to find service account cd-ko, checking if we have enough permission to create
Creating service account cd-ko
error: failed to verify requirements in dir /var/folders/bp/4mgw9f094872yc6v7gyzqqt1frkjzj/T/helmboot-736612290: failed to lazily create the kaniko secret in: jx: creating the service account: failed to run 'gcloud iam service-accounts create cd-ko --project devtools-1234 --display-name cd-ko' command in directory '', output: 'ERROR: (gcloud.iam.service-accounts.create) argument NAME: Bad value …
```
> fix: enforce GCP service account minimum name length Closes #6334 fixes #6334

- pkg/gits/operations/pull_request_op.go
If for some reason a dependency asset is unavailable then the update fails completely, this change enables the update to continue and outputs a warning if a release asset is not available.
fixes #6923
> fix: lets not fail an update if a depedency asset cannot be found

- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_environments_test.go
- pkg/config/install_requirements.go
Define the desired URLTemplate for a given environment in `jx-requirements.yml` so it's configured when creating the environment's git repository.
This way when running the master pipeline it won't wipe the real value from the `exposecontroller` configmap.
fixes #6648
> feat: get environment urlTemplate from requirements when running JX Boot for the first time

- pkg/versionstream/version_data.go
- pkg/versionstream/version_data_test.go
As Git for Windows doesn't follow semver (as seen for example [here](https://github.com/git-for-windows/git/releases/tag/v2.25.1.windows.1)), the `jx diagnose` command fails, as issued [here](https://github.com/jenkins-x/jx/issues/6825)
This fix trim suffixes from semver-ish version text to avoid errors.
fixes #6825
> fix: trim suffix from semver-ish version text to avoid OS dependant errors

- pkg/versionstream/version_data.go
- pkg/versionstream/version_data_test.go
- uses now single regexp to extract semantic version if any
fixes #5580
> fix: simplify convertToVersion implementation

- pkg/helm/helm_cli.go
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
This problem just appeared today be cause of jx-labs updating helm binary (helm) to version 3, and we should check for version instead of binary name
fixes #
> fix: check helm version instead of binary for timeout

- pkg/cmd/upgrade/upgrade_boot.go
- pkg/gits/git_cli.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
`jx upgrade boot` fails with the following error if there are duplicate commit's 
```
error: failed to update boot configuration: failed to cherry pick upgrade commits: cherry-picking <commit_id>: git output: The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:
git commit --allow-empty
Otherwise, please use 'git reset'
On branch <branch_name>
You are currently cherry-picking commit <commit_id>.
```
fixes #6970
> fix: jx upgrade boot failure when duplicate commits

- pkg/cmd/step/syntax/step_syntax_effective_test.go
- pkg/tekton/syntax/pipeline.go
We lower-case the app name etc when generating directories (like `charts/(app name)`) in `jx import`, but had not been doing so when replacing `REPLACE_ME_APP_NAME` etc placeholders in directories configured in build packs. We should be using the same case there that we use in generating the directories in the first place.
fixes #6983
> fix: Lower-case dir placeholder replacements from build pack

- pkg/cmd/cmd.go
This is purely a helper command, so there's no reason to have the warning here, and it results in breaking tab completion.
fixes #6975
> fix: Don't warn about static master removal in "jx completion ..."

- .secrets.baseline
- pkg/cloud/gke/gcloud.go
- pkg/cmd/deletecmd/delete_vault.go
fixes failed service account creation during `jx create vault` when a gke cluster name length is 3 characters or less
```
jx create vault 
? Vault name: vault-inf
Unable to find service account cd-vt, checking if we have enough permission to create
Creating service account cd-vt
error: unable to create/update Vault: unable to set cloud provider specific Vault configuration: unable to apply cloud provider config: creating GCP service account: creating the Vault GCP Service Account: creating the service account: failed to run 'gcloud iam service-accounts create cd-vt --project xx-1 --display-name cd-vt' command in directory '', output: 'ERROR: (gcloud.iam.service-accounts.create) argument NAME: Bad value [cd-vt]: Service account name must be between 6 and 30 characters (inclusive), must …
```
> fix: enforce vault GCP service account minimum name length

- pkg/cmd/step/helm/step_helm_apply.go
- pkg/kube/build_lock.go
- pkg/kube/build_lock_test.go
This PR prevents builds to edit the same namespace at the same time. Such a behavior could lead to a namespace to be accidentally wiped out.
Only `jx step helm apply` is locked.
A ConfigMap `jx-lock-{namespace}` is used as a lock. No other build can run while this configmap exists. Waiting builds can edit the data of the ConfigMap in order to be the next one to run. If a build sees that the locking or waiting build is "higher", it will fail. When the build finished, the ConfigMap is removed. A waiting build can also remove the ConfigMap if the lokcing pod has finished.
The algorithm is approximately:
```
Label: CREATE
try to create the ConfigMap
if it succeeds:
return
Label: READ
get the ConfigMap and the locking Pod
if the locking Pod has finished
remove the ConfigMap
goto CREATE
if the …
```
> fix: prevent concurrent build to edit the same namespace

- pkg/builds/test_data/get_pipelinerun_pods/pods.yml
- pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pods.yml
- pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pods.yml
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/pod.yml
- pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_legacy_label/pod.yml
- pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pods.yml
- pkg/cmd/get/test_data/get_build_logs/with-metapipeline/tasks.yml
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/tasks.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
- pkg/cmd/step/syntax/step_syntax_effective_test.go
- pkg/logs/test_data/legacy_pipeline_run/pods.yml
- pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/pods.yml
- pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pods.yml
- pkg/logs/test_data/pod_with_failure/pods.yml
- pkg/logs/test_data/pods.yml
- pkg/tekton/syntax/constants.go
- pkg/tekton/test_data/pipeline_info/batch-yaml/pods.yml
- pkg/tekton/test_data/pipeline_info/batch-yaml/tasks.yml
- pkg/tekton/test_data/pipeline_info/pr-yaml/pods.yml
- pkg/tekton/test_data/pipeline_info/pr-yaml/tasks.yml
Signed-off-by: Gazal K <mohamed.gazal@target.com.au>
fixes #7012
> fix: use newer kaniko image

- pkg/cloud/amazon/storage/bucket_provider.go
Use `util.ContentTypeForFileName` to detect the MIME type of the file being uploaded to S3. When not set, `Content-Type` defaults to `binary/octet-stream` which makes it difficult to build report viewers.
fixes #7032
> fix: set ContentType when uploading files to s3

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/cmd/step/verify/step_verify_preinstall_test.go
- Even free Github organisations can now create private repositories
fixes #7059
> fix: removing GitHub check verifyPrivateRepos during boot

- jenkins-x.yml
This gets around the problem of `v2.0.1285` not resolving to a pseudoversion with go 1.13, which the version of Athens we're now running is using behind the scenes. The underlying problem is #7069, and the long-term fix for that is to go to a proper semver usage, but this should unbork things in the meantime.
n/a
> fix: Turn off Athens proxy when running "jx step create pr go"

- pkg/cmd/boot/boot.go
Listing namespaces requires a `clusterrole`. It will fail for clusters with tight permission restrictions, so we should list a resource that is local to a namespace.
fixes #7060
> feat: list pods instead of namespaces to avoid needing a cluster-wide permission

- pkg/cmd/controller/controller.go
- pkg/cmd/controller/controller_build.go
- pkg/cmd/controller/controller_role.go
It doesn't make sense to register CRDs again when we are running the controllers in a boot cluster as there's already a step that updates the CRDs in the Boot Pipeline.
This is making the controller fail when running in Openshift because the `ServiceAccounts` don't and shouldn't have any cluster wide permissions.
fixes #7058
> feat: don't register the CRDs on controllers the installations take care of that already

- pkg/cmd/gc/gc_gke.go
The `displayName` in our boot-created SAs is like `pr-206-5-boot-gke-vt`, but the ones created via Terraform end up as `Velero service account for cluster pr-7065-46-tf-boot`. Which is fine! Except that our GC keys on `displayName` having a known suffix, and these...don't. So let's fall back on parsing the name from the email when there are spaces in the `displayName`.
n/a
> fix: Handle Terraform SA display name format in gc_gke

- pkg/helm/helm_template.go
- pkg/kube/permissions.go
When adding a Helm chart, we have two "hooks" that will clean any old resources.
One of them attempt to clean cluster wide resources too, for which we may have no permissions to delete.
I'm modifying this to warn on failure instead of erring.
fixes #7061
> feat: create a function to check the current permissions and split the deletion of old resources between cluster and non cluster resources

- pkg/cmd/step/verify/step_verify_environments.go
- pkg/cmd/step/verify/step_verify_environments_test.go
- pkg/cmd/step/verify/test_data/verify_ingress/exposer/jx-requirements.yml
Make it possible to configure expose controller with a different exposer for all environments via `jx-requirements.yml`.
fixes #7095
> feat: make it possible to configure a different exposer from requirements.yml

- pkg/cmd/step/create/step_create_task.go
Due to windows file struct, We cannot found `/bin/sh` in Windows. 
fixes https://github.com/jenkins-x/jx/issues/7035
> fix: use sh instead of /bin/sh in Windows

- pkg/cmd/sync/sync.go
- pkg/ksync/cli.go
- pkg/ksync/interface.go
- pkg/ksync/ksync_integration_test.go
- pkg/packages/install.go
- pkg/util/downloads.go
- pkg/vault/cli.go
* use git commit as tags for ksync docker image
* refactor InstallSync to add tests
* improve error handling
/cc @hferentschik @abayer 
* If ksync is installed, jx will try to parse the git commit from the output of the command `ksync version`. 
* If ksync is not installed, then jx will get the commit sha for the latest tag/release for ksync.
It will use this commit sha (short sha of the first 7 characters) to pull the right ksync docker image 
fixes #6262 and #6123
> fix(sync): use commit sha instead of tag for ksync image

- pkg/cmd/controller/controller_enviornmentcontroller.go
- pkg/cmd/step/helm/step_helm_apply.go
- pkg/kube/build_lock.go
fixes: #7106 Introduces a new environmental variable JX_DISABLE_BUILD_LOCK that can be set to disable the locking in `jx step helm apply`
> fix: Disable the build lock when running via the env controller

- pkg/gits/github.go
This should prevent errors caused by GitHub not yet actually having the git repo proper ready and exposed.
fixes #7129
> fix: Sleep five seconds after GitHub repo creation

- pkg/cmd/create/create_devpod.go
- pkg/kube/naming/names.go
If you have a large git host name and a large repo name then maybe you get error creating devpod because the label of the kubernetes resources is very large.
With this patch we try to reduce the label name & value getting only the first part of the git host name if the label name reach the 63 characters limit.
> feat: split repo label into 4 labels (scheme, host, org and name parts)

- jx/bdd/boot-vault/jx-requirements.yml
Since we're now Lighthouse-by-default in `jenkins-x-boot-config`.
n/a
> chore: Switch `boot-vault` context to Lighthouse

- pkg/gits/gitlab.go
This will let the Lighthouse BDD test for assigning actually work with GitLab.
n/a
> fix: GitLab PR info should include assignees

- pkg/cmd/preview/preview.go
Priori to this commit, `jx preview` would systematically check for availability of the service, even if the latter wasn't designed to reply to HTTP requests, and consequently would fail.
This commits adds a `--skip-availability-check` flag to prevent this behavior.
This is a first step toward #7112
> feat: Allow to disable availability check in preview

- pkg/cmd/opts/common.go
> fix: adding JX_LOG_LEVEL documentation to the global verbose flag

- pkg/cmd/create/create_cluster_eks.go
Wrong cloud constant is passed to CreateClusterOptions. 
fixes #7164
> fix(eks): wrong cloud constant for eks

- pkg/cmd/step/verify/step_verify_preinstall.go
- pkg/util/commands.go
- pkg/util/commands_test.go
fixes #7169 
This PR installs helm and kubectl in to ~/.jx/bin as part of `jx step verify preinstall` it also forces ~/.jx/bin to the start of the path.
Signed-off-by: David Conde
> fix: Verify pre install fails with incorrect kubectl or helm version on the path

- pkg/cmd/boot/boot.go
- pkg/gits/git_cli.go
- pkg/gits/git_cli_test.go
- pkg/gits/git_fake.go
- pkg/gits/git_local.go
- pkg/gits/helpers.go
- pkg/gits/interface.go
- pkg/gits/mocks/gitter.go
- pkg/util/commands.go
Avoiding confusing WARNING message in helper.go when trying to determine
upstream URL for non git managed directory
fixes #7174
> chore: adding explicit IsVersionControlled to Gitter interface

- pkg/gits/gitlab.go
There appears to be a typo and `GitRepository` should be using `path` instead of `Name`. Creating PRs with [Gitlab user kind namespaces](https://docs.gitlab.com/ee/api/namespaces.html) `404` fails for me otherwise:
```
error: failed to create Pull Request on the development environment git repository `https://***git`: unable to create pull request: failed to create PR for base master and head branch bump-resource-version-75be7a50-9467-11ea-8f26-a44cc83868d9 from temp dir /tmp/create-pr135132813: finding existing PRs using filter updatebot on repo Steffan, Andreas/***: listing open pull requests on Steffan, Andreas/*: GET https://***/api/v4/users/Steffan, Andreas/projects: 404 {message: 404 User Not Found}
```
In my case, `Name` resolves to my full name `Steffan, Andreas`. 
fixes #7181
> fix: Gitlab (12?) namespace should use path in GitRepository

- pkg/cmd/create/create_devpod.go
- pkg/cmd/importcmd/import.go
- pkg/cmd/preview/preview.go
- pkg/cmd/step/create/step_create_task.go
- pkg/cmd/step/step_changelog.go
- pkg/cmd/step/step_custom_pipeline.go
- pkg/gits/bitbucket_server.go
- pkg/gits/bitbucket_server_test.go
- pkg/gits/git_url.go
- pkg/gits/git_url_test.go
- pkg/tekton/metapipeline/clientfactory.go
- pkg/tekton/pipelines.go
* Makes sure that whenever we call `*GitRepository.HttpCloneURL`, we pass the git kind to it so that we can determine if the clone URL needs `/scm` added to it for BitBucket Server.
* Include the PR title in the returned `GitPullRequest` from various BitBucket Server functions.
* Make use of owner/org/project in BitBucket Server provider consistent with GitHub and GitLab providers.
* Populate PR data properly.
fixes #6828 
fixes #7184 
fixes #7187 
fixes #7188
> fix: Various BitBucket Server fixes

- pkg/gits/bitbucket_server.go
- pkg/gits/bitbucket_server_test.go
- pkg/gits/test_data/bitbucket_server/app-props.json
`pr:from_ref_updated` was added in BitBucket Server 7.0.0. Without it, we're never notified when a new commit is pushed to an existing PR, so it's obviously something we really want enabled, but it doesn't exist prior to 7.0.0. If we try to enable it on older versions, the whole API call will fail. So let's only enable it if the target server is new enough.
fixes #7204
> fix: Don't use pr:from_ref_updated webhook on older BitBucket Servers

- charts/jx/templates/role.yaml
- charts/jx/templates/rolebinding.yaml
- pkg/cmd/step/step_changelog.go
We should not register any CRDs on any controller as they are being registered and updated by Boot. This makes the steps / controllers to fail on a cluster without cluster-wide permissions.
Also, allow the creation of `roles` and `rolebindings` for the `jx` Helm chart on different namespaces when configured.
fixes #7209 
fixes #7210
> feat: remove the CRD creation from the changelog step and allow the creation of the controller's role and rolebindings on other namespaces

- pkg/cloud/buckets/buckets.go
- pkg/cmd/step/step_unstash.go
- pkg/cmd/step/step_unstash_test.go
- pkg/cmd/step/test_data/step_unstash/bitbucketserver.yaml
- pkg/cmd/step/test_data/step_unstash/ghe.yaml
- pkg/cmd/step/test_data/step_unstash/github.yaml
- pkg/cmd/step/test_data/step_unstash/gitlab.yaml
- pkg/collector/git_collector.go
GitHub allows fetching raw file content with a url like `https://TOKEN@...`, but BitBucket Server requires `https://USER:TOKEN@...`. We need to fetch GitLab raw files via the REST API, regrettably. See https://gitlab.com/gitlab-org/gitlab/-/issues/36191 for more details. So let's change the generated logs URL to the REST API url, and change the unstashing behavior to support the idea of adding a header, not just manipulating the URL.
And finally, the logic for determining whether the provider is github.com or GitHub Enterprise here wasn't working right, so let's tweak that.
fixes #7216 
fixes #7217 
fixes #7219
> fix: Fix build log retrieval for BitBucket Server and GitLab

- CONTRIBUTING.MD
- Makefile
- docs/configdocs/config.json
Otherwise the version (and other compile-time values we set) don't get set, because the package is `github.com/jenkins-x/jx/v2/pkg/...`, not `github.com/jenkins-x/jx/pkg/...`.
n/a
> fix: Need to include v2 in compile values

- pkg/cloud/amazon/cli.go
- pkg/ksync/cli.go
- pkg/packages/packages.go
This PR fixes the eksctl version to 0.11.1 to keep it inline with other binaries that we install. The fix prevents `jx create cluster` from creating a 1.16 k8s cluster if the incorrect binary version is used.
fixes #7235
Also fixes a warning during ksync version checking.
Signed-off-by: David Conde
> fix: Lock eksctl version to 0.11.1

- pkg/cmd/create/create_docker_auth.go
If you specify a secret on the command line, it will be used.
If you don't, it prompts a value but it was not used.
fixes #7286 
Related to #7203
> fix: Docker auth use prompted secret

- pkg/cmd/clients/factory.go
- pkg/kube/vault/vault_factory.go
- the reason the Vault struct was created early was to call v.isExternal. As a side effect
it would fail in cases where CreateSystemVaultClient is called with a newer version of jx
with a Jenkins X install which has not been upgraded.
Technically the creation of the Vault struct can be deferred until the service account name
is determined in the old way further down in the call stack of CreateInternalVaultClient
fixes #7291
> fix: make sure Vault config struct is not created too early in CreateSystemVaultClient

- pkg/cmd/importcmd/import.go
- pkg/cmd/importcmd/import_test.go
- pkg/cmd/importcmd/test_data/application_with_preview/charts/preview/values.yaml
This will allow users define which namespace to use for previews while checking that they can't set a permanent environment's ns as a preview namespace.
This will then modify the `values.yaml` file within the `charts/preview/` folder so it can be read and used by the `jx preview`command within a builder.
fixes #7302
> feat: let users define a preview namespace when importing / creating quickstarts

- pkg/cmd/edit/edit_buildpack.go
Follows on for this [PR](https://github.com/jenkins-x/jx/pull/7311) and sets the docs link to correctly URL.
> fix: update the docs to point to correct URL

- Makefile.codegen
- hack/generate.sh
`generate-api-refdocs` was throwing an error because the wrong api-directory location was passed to it. This PR fixes that.
fixes #7350
> fix: add missing v1 to api directory

- pkg/cmd/create/create_env.go
When registering an environment (in `RegisterEnvironment` function in `create_env.go`), eventually a call to `kube.GetOrCreateSourceRepository` is made, which is expected to return the `sr` (but it might eventually fail). Immediately after this call, there was a line that tried to log the SourceRepository's name. However, if an error was produced and/or the `sr` value was nil, attempting to access fields was causing a nil pointer exception, as in the example included in the reported issue.
With this change, some new validations are introduced to make sure that the nil pointer exception doesn't occur and that an error or a log entry is produced instead.
fixes #7349
> fix: avoid nil pointer exception when creating sr

- pkg/cloud/factory/factory.go
This commit fixes the nil pointer dereference on LegacyBucketProvider() on-premises environments
N/A
fixes #7363
> fix(storage): Fixes LegacyBucketProvider() for non-cloud environments

- pkg/cmd/importcmd/import.go
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/Dockerfile
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/Makefile
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/OWNERS
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/OWNERS_ALIASES
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/README.md
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/.helmignore
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/Chart.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/Makefile
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/README.md
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/NOTES.txt
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/_helpers.tpl
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/canary.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/deployment.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/hpa.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/ingress.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/ksvc.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/service.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/values.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/Chart.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/Makefile
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/requirements.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/values.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/curlloop.sh
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/jenkins-x.yml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/main.go
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/skaffold.yaml
- pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/watch.sh
- pkg/util/files.go
Allows to reimport projects that have previously been
imported/created using Jenkins X by ignoring an already
existing chart directory.
Closes #7325
Skip copying chart dir from buildpack when the destination dir already exist and contains a `Chart.yaml`.
fixes #7325
> fix(import): Fix application reimport

- pkg/cmd/upgrade/upgrade_cli.go
- pkg/cmd/upgrade/upgrade_cli_test.go
so that running `jx upgrade cli` will eagerly install any binary plugins defined in the current cluster.
This lets you switch clusters and be able to reuse the same binary plugins in other clusters which may not have the Plugin CRDs
fixes #7176
> fix: eagerly download binary plugins

- pkg/cmd/cmd.go
- pkg/cmd/cmd_test.go
- pkg/cmd/test_data/binary_plugins_dir/jx-dummy-plugin-1.2.3
binary plugins can't be found if you are connected to a kubernetes cluster which has no `Plugin` CRD installed.
This PR makes binary plugins installed into the `~/.jx/plugins/bin` dir equivalent to adding `jx-foo` to your `$PATH`; it lets folks install binary plugins without having to add them to your `$PATH`
see #7176
> fix: support finding a plugin in the plugins dir

- go.mod
- go.sum
- pkg/cmd/step/scheduler/step_scheduler_config_apply_test.go
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_all/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_default_scheduler/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_repo_scheduler/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_repogroup_scheduler/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_all/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_default_scheduler/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repo_scheduler/plugins.yaml
- pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repogroup_scheduler/plugins.yaml
- pkg/pipelinescheduler/config_builder.go
- pkg/pipelinescheduler/generator.go
- pkg/pipelinescheduler/scheduler_builder.go
- pkg/pipelinescheduler/testhelpers/helpers.go
- pkg/prow/prow.go
- pkg/prow/prow_test.go
Followup to earlier when we did this for the config package, but now for the plugins package. Now the only `k8s.io/test-infra/prow` dependencies left are relating to `ProwJobs`, so once we eventually officially remove Prow, we can get rid of those too.
n/a
> chore: Switch to lighthouse-config for Lighthouse plugins too

- pkg/cloud/amazon/storage/bucket_provider.go
- pkg/cloud/amazon/storage/bucket_provider_test.go
- pkg/cloud/buckets/buckets.go
- pkg/cloud/buckets/default_provider.go
- pkg/cloud/buckets/interface.go
- pkg/cloud/buckets/mocks/buckets_interface.go
- pkg/cloud/gke/gcloud.go
- pkg/cloud/gke/storage/bucket_provider.go
- pkg/cmd/controller/controller_build.go
- pkg/cmd/get/get_build_logs.go
- pkg/cmd/get/get_build_logs_test.go
- pkg/cmd/step/step_unstash.go
- pkg/collector/bucket_collector.go
- pkg/collector/bucket_collector_test.go
- pkg/collector/git_collector.go
- pkg/collector/interface.go
- pkg/logs/tekton_logging.go
- pkg/logs/tekton_logging_test.go
Improvements:
* let build log methods return channel to let the caller
handle streamed log lines within its own goroutine.
* stream build log to long-term storage.
* change storage provider interface to stream data.
Closes #7422
improve build log stream
fixes #7422
> refactor: improve build log stream

- pkg/cmd/step/create/step_create_task.go
allow a build pack to opt out of using the google kaniko secret for when folks use workload identity
> fix: kaniko env vars

- jenkins-x-bdd.yml
- jenkins-x-boot-lh-ghe.yml
- jenkins-x-boot-vault.yml
- jenkins-x-images.yml
- jenkins-x-tekton.yml
- jenkins-x-tf-boot.yml
- jenkins-x.yml
Because Tekton 0.11 only supports $(). We work around this behind the scenes in steps, but not in image tags, so might as well just update it across the board to be safe.
> fix: Use $() instead of ${} for pipeline parameters

- pkg/cmd/step/step_changelog.go
- pkg/users/git.go
see https://github.com/jenkins-x/jx/issues/6879
lets try do a better job of defaulting the user login name if there's no login but there is a name + lets treat resolve errors as warnings; as not having the user in a CRD isn't the end of the world; we still want the commits in the release notes + to not fail generating the changelog
> fix: fix changelog errors

- jenkins-x.yml
`/builder/home` is now `/tekton/home` since we've upgraded to Tekton 0.11.3, so the old path is breaking release builds.
> fix: Set HELM_HOME to /tekton/home/.helm

- pkg/cloud/buckets/buckets.go
For some reason, `io.Copy` was resulting in a "short write" error in the build controller, and the best suspicion I've got at this point is that it's a problem with the bucket writer closing early or something along those lines. So let's instead go back to earlier behavior and read the reader contents and write that directly rather than relying on `io.Copy`.
fixes #7461 (hopefully!)
> fix: Read the entire reader before writing to bucket

- jenkins-x.yml
- pkg/cmd/gc/gc_activities.go
- pkg/cmd/gc/gc_activities_test.go
In practice, this results in builds that take longer than the max age sometimes (though not always) failing to get their status actually recorded properly. So let's increase that age, and also add a check to make sure the `PipelineRun` is in a terminal state before we even consider deleting it.
fixes #7444
> fix: Increase max age of PipelineRuns for GCing

- jenkins-x.yml
- pkg/cmd/preview/preview_test.go
- pkg/cmd/step/create/step_create_task_test.go
- pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
- pkg/cmd/step/syntax/step_syntax_effective_test.go
If `DOCKER_REGISTRY_ORG` is set in the environment the test is being run in, it'll end up overriding what's expected in the test results, so let's override the env var to be safe.
n/a
> fix: Hardcode DOCKER_REGISTRY_ORG for certain tests

- pkg/cmd/deprecation/deprecated.go
jx-app-kubeless has been released, so I add `create addon kubeless` to deprecatedCommands.
> fix: deprecate create addon kubeless

- pkg/tekton/syntax/pipeline.go
- pkg/tekton/syntax/pipeline_test.go
- pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
- pkg/tekton/syntax/test_data/sidecars/jenkins-x.yml
Adding support for [Tekton Sidecars](https://github.com/tektoncd/pipeline/blob/v0.11.3/docs/taskruns.md#sidecars) at the pipeline and/or stage level - in the options:
```
pipelineConfig:
pipelines:
release:
pipeline:
options:
sidecars:
- name: top-level-sidecar
image: top-level/sidecar:tag
stages:
- name: my-stage
options:
sidecars:
- name: stage-level-sidecar
image: stage-level/sidecar:latest
```
- Note that as of Tekton 0.11.3 (current version of Tekton used by jx), sidecars have a few known bugs: https://github.com/tektoncd/pipeline/blob/v0.11.3/docs/taskruns.md#sidecars
- PR to update the docs: https://github.com/jenkins-x/jx-docs/pull/3001
fixes #7488
> feat(pipelines): add support for Tekton Sidecar containers

- pkg/dependencymatrix/matrix.go
so that code using this can easily modify it to something else (e.g. `.jx/dependency-matrix` for use in environments in Jenkins X 3.x)
> fix: lets switch to using a var for the dependency matrix dir

- .secrets.baseline
- pkg/cmd/add/add_app.go
- pkg/cmd/boot/boot.go
- pkg/cmd/deletecmd/delete_app.go
- pkg/cmd/get/get_apps.go
- pkg/cmd/helper/error.go
- pkg/cmd/opts/environments.go
- pkg/cmd/step/create/step_create_values.go
- pkg/cmd/step/scheduler/step_scheduler_config_apply.go
- pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
- pkg/cmd/upgrade/upgrade_addon_prow.go
- pkg/cmd/upgrade/upgrade_apps.go
During boot, new installs were returning that the config was stale. Looking into it, it appears the function checking for this "staleness" assumed the returned environment could be `nil`. However, looking at the function that was called, it would never be `nil`. This PR just changes that check to make sure the returned environment has a name.
Closes #7432
> fix: check name of devEnv since devEnv never nil

- pkg/cmd/step/verify/step_verify_ingress.go
so that we can disable waiting for the load balancer IP
> fix: support ingress.ignoreLoadBalancer flag

- pkg/packages/packages.go
This is required to support newer regions like cn-north-1 (we could have used anything greater than 0.15.0 to support that region, but subsequent versions add support for other regions as well as newer K8s versions)
fixes #7528
> fix: update eksctl binary to the latest stable version

- pkg/cmd/step/step_tag.go
- pkg/cmd/step/step_tag_test.go
- pkg/cmd/step/test_data/step_tag_find_chart/aaa/my-project/Chart.yaml
- pkg/cmd/step/test_data/step_tag_find_chart/charts/aaa/Chart.yaml
- pkg/cmd/step/test_data/step_tag_find_chart/charts/my-project/Chart.yaml
Priori to this commit, `jx step tag` would edit the first `*/*/Chart.yaml` file found. This commit gives priority to the more likely `charts/<appName>/Chart.yaml` file.
fixes #7417
> fix: jx step tag can edit the wrong chart file

- Makefile.codegen
This got moved to jx-api, but won't actually _work_ there, so we need to bring it back into jx.git or the docs site will never get automatically updated.
> fix: Bring back config refdocs generation

- pkg/config/install_requirements.go
so we can use it in helm charts if specified
this aligns with changes in the jx-api repo - we should just switch that  at some point!
Signed-off-by: jstrachan <james.strachan@gmail.com>
> fix: add optional pipeline username + email

- pkg/cmd/uninstall/uninstall.go
- pkg/cmd/uninstall/uninstall_test.go
Added a flag `keep-namespaces` to uninstall (by default, it deletes all the namespaces). This will ensure that namespaces are not deleted. The namespaces are created in terraform, so I think we should not delete them. However, I dont want to add a breaking change to the jx2 codebase. So this is a way to maintain compatibility.
fixes #7523
> fix: add a flag to keep namespaces when uninstalling jx

- pkg/cmd/step/step_next_version.go
- pkg/cmd/step/step_next_version_integration_test.go
- pkg/cmd/step/test_data/next_version/helm3/Chart.yaml
- pkg/cmd/step/test_data/next_version/helm3/expected_Chart.yaml
This makes the `jx step next-version` command compatible with Helm 3 when it reads/writes `Chart.yaml` files.
When the `jx step next-version` command reads the version from a Chart.yaml file, it looks for the `version` string, reads the value and stops there.
But when it writes a version in a Chart.yaml file, it replaces all the values following the `version` string.
This was not an issue with Helm 2, because there used to be a single `version` field in the Chart.yaml file.
But in Helm 3, the dependencies have been moved inside the Chart.yaml file, which means that each dependency now has a `version` field.
As a result, when the `jx step next-version` updates a version, it replaces all versions (including the dependencies) with the new value - which is incorrect.
This commit fixes this …
> fix: step next-version and helm 3

- pkg/cmd/step/step_split_monorepo.go
relates to issue #7535 
fixes #
> fix: split command creates a new repo as public

- pkg/cmd/step/step_tag.go
- pkg/cmd/step/step_tag_test.go
- pkg/cmd/step/test_data/step_tag_find_best_fit_chart/charts-v1/my-project/Chart.yaml
- pkg/cmd/step/test_data/step_tag_find_best_fit_chart/charts/my-project/Chart.yaml
findChartsDir() logic is messed up by an or checking if the file path is greater than the other. Which completely voids the use of the rank() method.
fixes https://github.com/jenkins-x/jx/issues/7591
> fix: corrected funky find charts logic

- pkg/packages/packages.go
Helm v2 was adding the deprecated stable repository by default when helm init was run prior to 2.17.0. Since the deprecated repository is no longer work, all Helm previews that rely on Helm2 are broken. 
Starting in v2.17.0, Helm is adding https://charts.helm.sh/stable repository instead of old one.
https://helm.sh/blog/new-location-stable-incubator-charts/
fixes https://github.com/jenkins-x/jenkins-x-builders/pull/1415
> fix(version): update Helm2Version to 2.17.0

- pkg/cmd/step/step_tag.go
When there is a relase, its commit message doesn't follow conventional commit convention, which is visible in release changelogs.
> fix: use conventional commit message for 'jx step tag'

- pkg/helm/helm_template.go
Adding "all" to the kinds of resources to delete that doesn't match the current release in helm template mode. This let's resources like deployments and services be deleted.
This fixes a regression introduced by #7073. (I find it worrying that no test caught that regression.)
In the earliest versions of jx "all" was the only kind to be deleted, the other ones where added later.
Fixes: #7486
> fix: Add "all" to list of kinds to clean after deploy in helm template mode

- pkg/tekton/metapipeline/metapipeline.go
the previous default value (512M) was not enough to run `git fetch` on big repositories
fixes #7577
> fix: set a bigger memory limit for the meta-pipeline

- Dockerfile-boot
If use vault as secretstorage. need to install vault plugin every time when run jx-boot in jx-git-operator
> fix: Install vault in image by default

- Dockerfile-tfo-aws
https://github.com/hypnoglow/helm-s3/blob/master/hack/install.sh#L49 -> the script requires which to find out if curl or wget packages exist.
```
#10 8.558 tar: Error is not recoverable: exiting now
#10 8.558 helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
#10 8.558 Error: plugin install hook for "s3" exited with error
#10 8.558 error: failed to install helm plugin s3: failed to run '/root/.jx3/plugins/bin/helm-3.6.2 plugin install https://github.com/hypnoglow/helm-s3' command in directory '', output: 'Downloading and installing helm-s3 v0.10.0 ...
#10 8.558 ERROR: no curl or wget found to download files.
```
> ci: add missing which command to unblock release pipeline

- Dockerfile-boot
Fixes that helm plugins are not found when container is run as non-root user with the jx-boot image.
In particular in the pull request pipeline of the cluster repo, where the the container is run with tekton as the user.
```
Adding repo local s3://somebucket/jx3
in ./helmfile.yaml: in .helmfiles[3]: in helmfiles/jx/helmfile.yaml: command "/usr/bin/helm" exited with non-zero status:
PATH:
/usr/bin/helm
ARGS:
0: helm (4 bytes)
1: repo (4 bytes)
2: add (3 bytes)
3: local (5 bytes)
4: s3://somebucket/jx3 (30 bytes)
5: --force-update (14 bytes)
ERROR:
exit status 1
EXIT STATUS
1
STDERR:
Error: could not find protocol handler for: s3
COMBINED OUTPUT:
Error: could not find protocol handler for: s3
make[1]: *** [versionStream/src/Makefile.mk:117: fetch] Error 1
make[1]: Leaving directory …
```
> fix: Find helm plugin as non-root user in jx-boot

- .github/workflows/jenkins-x-pr.yaml
- .github/workflows/jenkins-x-release.yaml
- .github/workflows/plugins-pr.yaml
Everytime I open a PR in the jx repo, I see github actions running on my fork and failing.
This PR runs the jobs only on the main jx repo.
> ci: stop github actions on forks

- .github/workflows/jenkins-x-release.yaml
- .goreleaser.yml
We are running an ancient version of goreleaser, it's time to upgrade.
Checked that the config does not have any deprecated flags:
```
goreleaser check
• loading config file       file=.goreleaser.yml
• checking config: 
• config is valid
```
We will see if it works properly, once this is merged. The release pipeline is anyways broken atm.
> refactor: upgrade goreleaser to the latest version

- pkg/plugins/versions.go
Seems like jx3-version PRs are breaking since 3.2.288 which bumped jx-verify to 0.2.3. Reverting that change for now.
> chore: revert jx verify to 0.2.2

- .gitignore
Since the switch to jenkins-x 3 the releases lack the install instructions and changelog. I think I have tracked down the cause of that.
It seems like goreleaser do git clean. So to use changelog.md generated by jx changelog it needs to be committed. This also makes the changelog.md checked in in the release tag, which is good idea as well.
> fix: Enable changelog in GitHub release

- pkg/cmd/namespace/namespace.go
- pkg/cmd/root.go
This makes ctx work like in jenkins-x 2
> fix: Make command ctx an alias for plugin jx-context

- .github/workflows/jenkins-x/changelog.sh
- .github/workflows/jenkins-x/upload-binaries.sh
This is an attempt to fix release notes
I don't really know why it doesn't work when using this GitHub Action when it works fine in the tekton pipelines. My hypothesis for this attempt is that the file name is case sensitive here and not in the tekton pipeline.
> fix: Upload release notes

- pkg/plugins/versions.go
Reverts jenkins-x/jx#8252
Back to the drawing board. 
BDD tests failed due to:
```
jx gitops helmfile move --output-dir config-root --dir /tmp/generate --dir-includes-release-name
error: failed to : failed to modify namespace to jx for release jxboot-helmfile-resources in dir /tmp/generate/jx/jxboot-helmfile-resources/jxboot-helmfile-resources: the server doesn't have resource of kind Environment 
```
CustomResourceDefinitions need to be installed before `jx gitops helmfile move` would work properly.
> Revert "chore(deps): upgrade jenkins-x/jx to version 0.7.13"

- .github/workflows/jenkins-x/upload-binaries.sh
- .github/workflows/plugins-pr.yaml
- Makefile
fixes #8297 
Here we are making the go version in the pipeline inherited from the image running gorealeaser.
In the makefile we ensure that GO_VERSION == CATALOG_GO_VERSION and error the make file if not.
To Do: How to get the CATALOG_GO_VERSION value?
> fix: inherit go version from catalog

- Dockerfile-go
```
golang                                                  1.18.6                                     f81bafb819d5   2 weeks ago     965MB
golang                                                  1.18.6-alpine3.16                          b68eed002951   3 weeks ago     328MB
```
I am using at my work, and the jx update bot image is 2.2 GB which is massive!
> feat: use alpine base image for jx-go

- Dockerfile-go
alpine does not have curl by default, this was breaking all release pipelines.
> fix: add missing curl to jx-go alpine image

- Dockerfile-go-maven
Also upgrading to go1.18 (Previously it was go 1.15, which is most likely breaking release pipeline)
Size decreased by 600 MB
```
(base) ➜  jx git:(maven-go-1.18) ✗ docker images | grep maven
jx-go-maven                                             alpine                                     6efd322ce121   About a minute ago   1.62GB
ghcr.io/jenkins-x/jx-go-maven                           latest                                     74f40a9e9983   3 hours ago          2.13GB
```
Also removing archived `ghcr.io/jenkins-x/jx-go-maven-base-image` image. 
https://github.com/jenkins-x/jx-go-maven-base-image (Public archive)
> fix: switch to alpine base image for jx-go-maven

- Dockerfile-go-maven
Ran into issues with alpine images, it cant find java binary even if it exists. Could be because of missing glibc (alpine uses musl), would be good to figure this out in the future. The image size is huge at 2.25 GB!
> fix: switch back go-maven image to non-alpine

- .github/workflows/jenkins-x-release.yaml
- Dockerfile-kubectl
Related to #8411.
Bitnami images don't support ARM yet, and I am not sure when that will land. We can build and maintain our own kubectl image for our usecase. The image is simple to build and smaller as it uses alpine.
https://github.com/jenkins-x/jx3-versions/blob/be23d4f583b765e832a0046e0ffd4f12be3cd21d/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl#L46 -> This is the current image.
Rancher also publishes it's own kubectl image, but we cant use it, as it's based on scratch, and we need base64 decode in the init script: https://github.com/rancher/kubectl/blob/ecb5988682864a252e55600fcca87b6d3d3d4312/Dockerfile#L12
> feat: create multiarch kubectl image for jx

- .github/workflows/jenkins-x-pr.yaml
- .github/workflows/jenkins-x-release.yaml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- Makefile
- pkg/cmd/root.go
Many plugins support using BINARY_NAME or TOP_LEVEL_COMMAND to form correct usage help.
This fixes makes use of this feature. It seems to me that it is an oversight that it has not been used previously.
> fix: Correct command in plugin help

- cmd/docs/man_docs.go
- cmd/docs/md_docs.go
- pkg/cmd/root.go
Better to use ReplaceALL 
https://github.com/nishantsikarwar/jx/blob/10d64c7e16be9f4ad6103ea258fcf52b679584ce/cmd/docs/man_docs.go#L68
instead of using replace 
https://github.com/jenkins-x/jx/blob/01894a7dd4f29bfa5817ce7230ad98d5962da8b4/cmd/docs/man_docs.go#L68
> Fix : Function call can be replaced with helper function

- .github/workflows/jenkins-x-release.yaml
dogfooding: use recent jx changelog by using latest jx boot
Also: no point in building the same kubectl image over and over again
Signed-off-by: Mårten Svantesson <Marten.Svantesson@ticket.se>
> fix: use changelogs from PRs

- Dockerfile-boot
Even though a lot of juggling with yaml files are possible with `jx gitops` I keep encountering situations when yq would be solve a problem in a simpler than for example adding the functionality to `jx gitops` and a less fragile way than writing an awk or shell script.
In a pipeline I can add a step using a dedicated yq image, but in the jx boot job that isn't really possible.
> feat: add yq to boot image

- cmd/docs/md_docs.go
- pkg/cmd/root.go
Some simple error-checking patterns can be reduced to just a single return statement returning a variable of type Error.
for ex :
https://github.com/nishantsikarwar/jx/blob/c88e4a5831f7c737423986c7e93e1bdfd8523f7f/pkg/cmd/root.go#L382
https://github.com/jenkins-x/jx/blob/36061629b2beadb7be407fa7d9a5e7a58b7a023f/pkg/cmd/root.go#L382
> fix: error checking

- .github/workflows/jenkins-x-release.yaml
The upgrade broke the release workflow
Reverts jenkins-x/jx#8524
> Revert "chore(deps): bump sigstore/cosign-installer from 2.8.1 to 3.0.1"

- .github/workflows/jenkins-x-release.yaml
jx doesn't build since the artefact signin by cosign fails
The cause seem to be described here https://blog.sigstore.dev/tuf-root-update/ and should be resolved by upgrading cosign
> fix: signing by goreleaser

- hack/changelog-header.md
The current instructions doesn't work with new versions of `cosign`. Also the current instructions makes for an unnecessary obstacle for new users. So I think simplifying the instructions makes most sense. I'm adding homebrew instructions while at it.
Possibly https://jenkins-x.io/v3/admin/setup/jx3/ should be complemented with cosign instructions.
> fix: simplify install instructions

- .golangci.yml
- pkg/cmd/dashboard/dashboard.go
- pkg/cmd/namespace/namespace.go
- pkg/cmd/root.go
- pkg/cmd/ui/ui.go
- pkg/cmd/upgrade/upgrade.go
- pkg/cmd/upgrade/upgrade_cli.go
- pkg/cmd/upgrade/upgrade_plugins.go
- pkg/cmd/upgrade/upgrade_plugins_test.go
- pkg/cmd/version/version.go
Linter pipeline has started failing as `service.golangci-lint-version` is no longer honoured so errors were being returned when trying to run deprecated linters. See linter failing here https://github.com/jenkins-x/jx/pull/8676
This PR removes these deprecations and updates each linters config to the latest versions (finding equivalents if possible). Unused args have also been removed as per `revive` linter.
> fix: update .golangci.yml for more recent version of linter

- .goreleaser.yml
This small PR updates the GoReleaser configuration to resolve the following warnings, which you can find in the [CI logs](https://github.com/jenkins-x/jx/actions/runs/16271693400/job/45940696513#step:11:25): 
```
DEPRECATED: archives.format_overrides.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat_overridesformat for more info
```
> chore: update GoReleaser configurations
